MegaMek/mekhq

- MekHQ/SubmitBug.html
Left in links to the old sf.net bug reporting pages, so people can look there for duplicate issues.  Might want to take them out to avoid potential confusion.
Removed the part specifying the save file be in XML format, as I don't see that option anywhere.  (The .cpnx file is basically just an XML file, but is a .cpnx file.)
> Point at github bug trackers, mention zipping the attached files.

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/gui/MekLabPanel.java
Related to https://github.com/MegaMek/megamek/pull/57.  The constructors for EntityVerifier and MapSettings are now private, however, there are new static methods to call to get an instance.
> fixed references to MapSettings and EntityVerifier

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/src/mekhq/resources/PersonViewPanel.properties
Allows the user easier access to who a selected persons spouse is over searching long logs or when a marriage log entry has already been deleted.
> UI Enhancement - Add Spouse to Person Panel

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
- MekHQ/src/mekhq/resources/HireBulkPersonnelDialog.properties
Along with a general cleanup, this PR adds a few options to the "Hire in bulk" dialogue:
* The ability to hire named Astechs
* The ability to set an age range (GM mode only)
If the age range is set, the person is still generated normally and only if the generation *doesn't* result in them having an age within the range will their age be rerolled. Thus, an age range of 10-99 years literally has no effect at all, one with 10-25 will have some half of the people assigned a new range, and one of 10-15 will generate only young teenagers and throw away all the original generated ages.
Since this option can easily create impossible results (super elite 5 year old BA warriors? Sure!), it doesn't appear if you're not running in GM mode.
Inspired by the discussion here: …
> Adding options to the "Hire in bulk" dialogue

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/PartInUse.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/DailyReportLogPanel.java
- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
- MekHQ/src/mekhq/gui/dialog/DailyReportLogDialog.java
- MekHQ/src/mekhq/gui/model/PartsInUseTableModel.java
- MekHQ/src/mekhq/gui/sorter/FormattedNumberSorter.java
- MekHQ/src/mekhq/gui/sorter/TwoNumbersSorter.java
- MekHQ/src/mekhq/resources/PartsInUseTableModel.properties
Fixing most of the issues with the buttons in "parts in use" tab:
* The buttons refreshhng themselves, blocking the UI
* General speedup of the parts lookup via caching
It's not a 100% fix yet. In particular, mech heads are cached as `Mech Head (XX tons, (100%, [Sensors, Cockpit]))` and similar and queried as `Mech Head (XX tons, (100%)`. That probably needs additional caching in the `PartStore` to work properly, but I'm out of time ATM.
Will update once I'll find some time, probably tomorrow. Feel free to comment and point to other obvious solutions I missed.
> Fixing most of the issues with the buttons in "parts in use" tab

- MekHQ/src/mekhq/gui/model/PersonnelEventLogModel.java
- MekHQ/src/mekhq/gui/model/PersonnelKillLogModel.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/src/mekhq/resources/PersonnelEventLogModel.properties
- MekHQ/src/mekhq/resources/PersonnelKillLogModel.properties
This replaces the personnel log entries (personal events/history and kills) with tables, to vastly improve its performance. I'm not 100% sure it works with all log entries until now (were there some with HTML code or interactive elements?), thus a PR and not a direct push, but for text-only entries, it works like a charm.
> Replacing personnel's kill and event log displays with tables

- MekHQ/src/mekhq/campaign/ExtraData.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This adds an "ExtraData" class which is like a type-safe "Properties" class with a build-in XML serialiser optimised for not wasting too much space (as much as that's possible with XML) while still being reasonably fast.
It has two a `set(key, value)` methods - one which accepts only values whose type matches that of the key's declared type, and one for String values, which are converted to the key's declared type if possible. The corresponding `get(key)` and `get(key, defaultValue)` method return the correct type according to the key's declared type (and `null` respective the supplied default value if the value doesn't exist).
Multiple keys with the same name but different declared types are considered to be different keys (which can be checked with `key.equals(otherKey)`).
Pre-defined …
> Extra data class for type-safe, small extra properties

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/handler/XPHandler.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
Turning admin XP gain into an event handler for NewDayEvent, and making it work all the time, as opposed to just when AtB is turned on.
Also added a delay to the XP gain to make it be given less often than once per week, as per RFE #43.
> Making admin XP gain into a generic event handler for NewDayEvent

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/model/PatientTableModel.java
Added protection against PatientTableModel being given a bad index when attempting to retrieve an index. In such an instance, the model will return a NULL value. Also added null handling to the calling methods.
> Issue #68: IndexOutOfBoundsException when advancing day

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
Previously it would whatever most closely matched the dragoon rating. This doesn't work for IO rating above 4/40 and was inaccurate for most other ratings.
This should normalize the payment multiplier when taking a units rating into account. Ratings above 4 would default to a multiplier of 1 while smaller ratings would end up less than what they should.
> AtB Uses Int Ops Reputation Factor when IO rating is used

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
Light Vehicles are not Light Vehicle Bays and docking collars don't matter if you don't have dropships to attach to them.
> Issue #221: CO Incorrect Campaign Ops Transport Rating with No Dropships

- MekHQ/src/mekhq/campaign/personnel/Ancestors.java
In this case a null ancestor was being passed that caused the NPE. Added a null check and return and everything seems to be working again.
> Fixes #257 Cannot open context menu on children

- MekHQ/src/mekhq/gui/PersonnelTab.java
Created a new list item for the personnel dropdown to display all prisoners to keep them from clogging up the other personnel lists.
Partially implements #337
> RFE #337 Separate list item for Prisoners on the personnel tab

- MekHQ/src/mekhq/campaign/Campaign.java
Merge with MegaMek/megamek#518
Keeps flawed cooling from being carried over to the next battle.
Per arlith (possible optional application)
>  I suppose the quirk doesn't specify how it's fixed.  The easiest thing to do would be to just clear the flag in MHQ's resetEntity method. We could also add like a 5 or 15 minute repair task too.
As it is a quirk I don't know how easy it might be or if its currently possible.
> Reset Flawed Cooling System after battle

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
Calculation for admin staff incorrectly used medics instead of doctors. This has been corrected.
> Bugfix: Medics counted as Admin instead of Doctors

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
#382: MR-Warehouse no longer works
- The addition of OmniPods broke the MR-W dialog and caused and NPE when
it tried to launch
#385: MRMS no longer fixes units with bad hip/shoulder
- getLocation() on missing locations no longer returned the proper
location index. Changed to ((MekLocation)partWork).getLoc()
> Fix MRMS-MW issues

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/gui/CampaignGUI.java
Fix #387 - Don't call the DeploymentChangedEvent if it has a null scenario
When calling undeployUnit(), the downstream call to undeployForce() results in a null scenario and thus an assertion failure.
> Fix assertion failure when undeploying a unit from a special operation

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/unit/Unit.java
#389: Remove all personnel tried to remove the tech only if it didn't have a tech instead of if it did have a tech
> Fixed remove all personnel

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
Autogenerate AtB contract name in Contract market with "Faction_short_name-yyyymm-mission_type-length" format.
Ex: "CC-306701-Recon Raid-3"
> Autogenerate AtB contract name in Contract market

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Some bullet proofing. Whenever we get ICE_STORM weather in a scenario, the PlanetaryConditions weather name resolver does not appreciate it, as it has an off by one error in it. 
Also, noticed that gales and tornadoes were resolving as downpour and light snow.
> Fix for incorrect treatment of tornadoes

- MekHQ/src/mekhq/campaign/personnel/Person.java
It appears that elite mechwarriors were not actually very highly valued. Maybe it's because they're so snobby.
> Fixed typo

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
Fixed a bug where transit amounts were not being added to the contract amount when loading a save which resulted in the montly payout getting smaller.
Made a change to the supply cost dialog so the cost amounts would display with a comma, making them easier to read.
> Support - Peacetime Costs cleanup

- MekHQ/build.xml
- MekHQ/packaging.xml
- MekHQ/packaging_local.xml
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
A while back, changes were made to calculations within CampaignOpsReputation but the unit tests for that class were not updated to match.  As a result, the unit tests fail.  This fixes that issue.  Also, I added code to ensure that unit tests are always run by the build and packaging scripts.
> Fix Unit Tests

- MekHQ/data/universe/factions.xml
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/universe/Faction.java
- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/gui/FactionComboBox.java
- MekHQ/src/mekhq/gui/dialog/BloodnameDialog.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/ChooseFactionsDialog.java
- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
- MekHQ/src/mekhq/gui/dialog/NewPlanetaryEventDialog.java
- MekHQ/src/mekhq/gui/view/AtBContractViewPanel.java
- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
This fixes the errors and problems caused by the recent Era.java change.
startingPlanet
altNamesByEra
eraMods
all moved away from depending on Era.java. First two now based on campaign year instead of Era. I updated the factions.xml data as well.
> Faction.java redesign to fix issue with Eras.

- MekHQ/src/mekhq/gui/model/PersonnelEventLogModel.java
- MekHQ/src/mekhq/gui/model/PersonnelKillLogModel.java
Calling setRowHeight in getTableCellRendererComponent triggers a re-render, which calls getTableCellRendererComponent again. Check the current row height, and only set the row height if we're making the row taller.
(Making the row shorter is a case I can't ever see coming up, and a case the old code wouldn't have handled correctly either.)
> Fix infinite loops in personnel view panel log renderers

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
1. The technicians count was never reset. updatePersonnelCounts()
adds to that variable, and is called when advancing the day and
(possibly) when making other changes, so the number of astechs
required would increase every day.
2. In getSupportDetails(), the code used getAstechPool() (which
only gets the number of temp astechs) instead of getNumberAstechs()
(which takes into account personnel with the role 'astech').
(Only the display was wrong; the calculation used to actually
determine the rating was correct.)
> Fix two tech team-related bugs in Campaign Ops reputation calculations

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
i.e., if you have someone with Tech/Mech and Tech/Aero skills, the CamOps reputation method will use their selected role to decide what kind of tech team they have. They still have to have some ranks in the skill to count as a tech of a given type.
> Issue #495: tech roles determine multi-skilled tech team type

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/BombsDialog.java
Was previously expecting Aero.bombChoices to keep total bombs loaded on
ASF, bombChoices is now set to 0, corrected bomb unmounting code for
that.
This is the fix for https://github.com/MegaMek/mekhq/issues/488
> Change Campaign.clearGameData(Entity) to fix Bomb unmounting

- MekHQ/src/mekhq/campaign/personnel/Person.java
Previously: only characters with common ancestors could marry.
Now: only characters without common ancestors can marry.
> Fix backwards conditional in common-ancestor marriage check (issue #503)

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CurrentLocation.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
- MekHQ/src/mekhq/gui/view/JumpPathViewPanel.java
This fixes a minor bug in the drop ship requirement calculations. Prior to this commit, the raw count of mechs, vehicles, and ASFs was used to determine DropShip requirements. This commit uses the count of untransported units, which is already calculated earlier in the method.
The attached saved game demonstrates the problem and verifies the solution. It contains a company of 12 mechs with a few attached ASFs, and has a Colossus and a JumpShip. The transport costs in the released dev snapshot are nonzero, despite the unit fitting entirely in its own transport assets. The transport costs in the version built with this commit are 0, as expected.
https://drive.google.com/file/d/0B4_Fe7AvNpDLTEdvSmpoelN5WTQ/view?usp=sharing
> Calculate DropShip rental costs based on untransported units only

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
These changes filter destination worlds for contracts based on
the search radius (in addition to the pre-existing filtering based
on employers with worlds in range). Some loosening of constraints
is included, adding 10% of the search radius per retry, in case
of difficult locations.
Tested by generating contracts in the near Periphery, Point Barrow in the middle of the Federated Suns, and near Terra. Doesn't seem to slow down contract generation.
> Issue #452: limit contract search by AtB search radius

- MekHQ/src/mekhq/campaign/unit/Unit.java
Fixes an issue where artillery gunners would show up in MegaMek with an Artillery Skill of 7 at best, even if their actual Artillery skill in MekHQ was better. 
TN modifier remains 7+ for indirect artillery fire, but should no longer be stuck at 14+ base TN when you have a gunner with rank 6 Artillery skill.
> Fix for Issue #507

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Adds a new GM context menu option to add/remove custom XP amounts to multiple selected personnel at once.
(previous "Add XP" option renamed to "Add 1 XP")
> Add/remove XP QoL option

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/resources/CampaignOptionsDialog.properties
When the new option is enabled in the Name and Portraits tab, any personnel with no current portrait whose primary role is changed to one that is selected for random portraits in the same options will automatically gain a random portrait. Discussed with scJazz and this solve #526.
> Implements #526: option to auto-randomize portrait on job change

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/handler/XPHandler.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
This goes over a few places where Campaign.getPersonnel() was used and the calling method implicitly assumed it was querying active personnel. I've added checks to make sure those places are only counting active persons.
> getPersonnel() usage cleanup pass

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
- MekHQ/src/mekhq/resources/CampaignGUI.properties
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
- MekHQ/unittests/mekhq/campaign/rating/FieldManualMercRevDragoonsRatingTest.java
Fix for #510, making Dragoons Rating medical support requirement count only active personnel. 
Also makes CamOps reputation admin support requirement count only active personnel.
Also renames the "Dragoons Rating" panel in the Overview tab to "Unit Rating" for consistency, as requested in #519.
> Unit rating fixup

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
As per #280, expanding on PR#481 this adds a layered fallback approach to random portraits: first look into a folder matching the person's primary role, then if no valid unused pictures exist check the "group" folder (Admin/, Tech/, etc.), then Combat/ or Support/, and then just the gendered folders.
> Expand discrete portraits feature

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
Also ignores changes to hits count when the slider is disabled (via KIA being checked.
> Fix for hitSlider error when hits > 5

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
Fixed out of memory bug due to adding endless cubicles when loading game with infantry transport capable dropship.
The actual error was a problem loading a faction whose name was specified in lower case for some reason.
> Fix for issue #592

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This affected options in the personnel tab that would keep the Time in Service option from showing up. The issue was caused by another PR being merged around the same time that also dealt with the numbering in the section fixed.
> Fixed issue with campaign options dialog numbering.

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Fixes a couple of extra support edge issues I noticed in playtesting - Elite techs were consuming edge on auto-success tasks like loading ammo and tasks with a smaller MoF than the set break part value.
> Fix issue misusing edge rerolls on automatic success tasks

- MekHQ/data/universe/customspa.xml
- MekHQ/data/universe/defaultspa.xml
- MekHQ/docs/custom_spa.txt
- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/personnel/CustomOption.java
- MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
Allows user to add spas/edge triggers/implants to the hard-coded ones through a data/universe/customspa.xml file that provides initialization data. The custom options use the existing PersonnelOption framework that is built on top of the MM PilotOption framework. Until such time as we have plugin modules, these have no game effect other than providing a way for users to manage XP expenditures and track which personnel have which ability.
> Custom spa

- MekHQ/data/universe/planets.xml
- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- Removed unnecessary 'toUpperCase' that was causing other issues
- Changed 'Merc' to 'MERC' in planets.xml
- Changed magic string comparison to "abandoned" tag comparison instead
> Faction-related campaign load issue fixes

- MekHQ/src/mekhq/campaign/universe/News.java
- MekHQ/src/mekhq/campaign/universe/NewsItem.java
This fixes an issue where news items that only list a year for the date would randomly generate the same date for each news item. It was doing this because the `NewsItem.finailizeDate(long)` method was creating a new `Random` object with the same seed every time it was called. I just replaced this with `megamek.common.Compute.randomInt(int)` instead.
> Fix for issue #626.

- MekHQ/data/universe/factions.xml
Was brought up on Slack.  The LC exists into the present (3145) so removed the <end> field causing the faction to disappear during the Dark Ages.
> Removed Lyran End Date

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Fixes #590 and an unreported bug where support edge triggers would show in the multi-select options even if that unofficial setting was disabled. 
Also always display all enabled edge triggers for single-select context menus, with triggers not "valid" for the person's current role grayed out. This part isn't a "fix" per-se but I found the behavior unintuitive and it _felt_ bugged when I'd go mouse over the "Set Edge Triggers" option and just not get any submenu pop up. 
This also allows me to set edge triggers even when a person isn't _currently_ on a role that can use it, which I find desirable too.
> Edge Trigger toggle tweaks

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/gui/dialog/LaunchGameDialog.java
When hitting 'load saved game' in the briefing screen, if the user clicks 'cancel', it brings up the file dialog anyway. 
Then, if the user hits cancel, it tries to start up megamek anyway, then used an exception for flow control. This set of changes optimizes the behavior somewhat.
> honor user's press of 'cancel' button during Load Save Game dialog

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/parts/Refit.java
Some changes that fix long-standing issues with ammo bins in refits
involve including AmmoStorage parts in the shopping list. Previously the
shopping list was only instances of MissingPart and acquireParts()
method had an unchecked cast based on that assumption.
Fixes #647: Exception Causing UI Issues while Unit is Being Refit
> Fix ClassCastException when acquiring refit parts.

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
Two sets of changes:
One spurred by issue #639, on line 171 in CampaignOpsReputation.java. This emulates the behavior of the dragoons rating code, which, if no anti-mek skill is present, assumes an anti-mek skill of "small arms + 1".
The rest is because the average skill level wasn't computing correctly due to always dividing the number of infantry by 28, even though infantry units may have man counts of not 28. That also led me to mess around with transport capacity-related code.
> Adjusted unit rating calculation and infantry counts

- MekHQ/src/mekhq/gui/MekLabTab.java
Pretty straighforward.
The call to refreshSummary() is supposed to refresh just the weight/slot
breakdown view on the structure tab, but it was calling refresh()
instead. This was causing a listener to get added a second time, so when
the listener was removed to refresh data without updating the Entity it
was updating anyway. This was causing any critical slots to assigned to
internal structure to be unallocated.
I double-checked the panels for the other unit types, and `MekPanel` was the only one with the typo.
> Fix for #688: Cannot slot Endo Steel crits.

- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/OmniPod.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
Pods were only being added in the general case scenario and not where they required special handling (heat sinks, jump jets, MASC/supercharger, variable weight).
In addition to adding the missing empty pods to the store I changed the filter in the dialog to match either the name or the details so you can actually find the pod you want. I also had the parts store exclude any equipment without the appropriate MiscType or WeaponType flag for mech, vee, or asf equipment.
> Fix for #668: Empty heat sink/double heat sink omnipods not available for Purchase Parts

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Fix for #531 
Basically, we collect "devastated" units and process them the same way as we do non-exploded units, except that we don't consider them valid for salvage.
> Process exploded units for prisoner capture

- MekHQ/src/mekhq/campaign/unit/Unit.java
isCommander() does not check the return value of getCommander() for null, which is possible when the unit has no assigned crew. Added a null check and also added javadoc comments to both methods.
If following the steps to recreate given in #715, you can find the infantry unit in question in Order of the Scale Combined Arms Regiment > 1st Combined Armored Battalion > 12th Combined Armored Battle Company > 12th Combined Armored Infantry Company.
> Fix for #715: Unit.isCommander Error

- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
- MekHQ/src/mekhq/resources/ContractMarketDialog.properties
Improved communication when the GM - Generate Contract button fails. Now, instead of throwing a NPE, it'll record a message to the daily log.
> improved communication regarding gm-generate contract failure

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This should fix #600 and #621 by adding faction handling (which only deals with the clan flag at the moment as far as I can tell).  ResolveScenarioTracker's processPrisonerCapture now determines the enemy's faction and passes that to genRandomCrewWithCombinedSkill.  Added faction handling to Person's constructor as well as Campaign's newPerson.  I left the original functions in place but have them call the new faction handling version with the player's faction as that was the previous behavior.
> Fixes issue #600 and #621 by adding faction handling to person/crew creation

- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
Dragoons rating counted unmanned units for the purposes of "average skill" calculations. getCrew() never returns null, but can return a 0-length list, so the code was adjusted to account for that.
> minor adjustment to dragoons rating

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/BriefingTab.java
Changed the "applyRetirement" method to return false only if a) there actually are payments to process and b) they were unabled to be processed.
Also, changed the MissionComplete event to fire only after all the retirement rigmarole is done and the mission is actually complete.
> Fix for issue #731

- MekHQ/src/mekhq/campaign/parts/Part.java
Fix for #733 
The maintenance mods were calculated using `Part.teamId`, which is the field that holds the id of the tech that is working on a repair that is carried over into the next day. In most cases the tech lookup returns null, which is handled the same way as a non-Clan tech. Instead it should be using `unit.getTech()`, which returns the tech assigned to the unit's maintenance.
> Use maintenance tech instead of repair tech for maintenance mods.

- MekHQ/src/mekhq/campaign/universe/AbstractUnitGenerator.java
Fix for #745 
If there are no turret RATs present or the campaign year is earlier than the earliest turret RAT, `generateTurrets` will throw a NullPointerException. Added checks for both exceptional cases. In the first case, return an empty list and in the second use the earliest available turret RAT. In both cases log a warning.
> Handle missing turret RATs without throwing exception.

- MekHQ/src/mekhq/campaign/Campaign.java
Fixes two issues:
1) Sometimes, a dead/retired guy's payout comes out as 0. Then, it never gets processed.
2) The nagging (and application of contract score penalty) for insufficient lance deployment on AtB contracts wasn't happening. Bet people will love this fix. 
For #1, I simply made it so that the applyRetirement function does its thing if the payout is more than 0 OR if there are any retirees.
For #2, the deployment deficit was coming back as less than 0, so I made the function output match its apparent semantic meaning.
> fix retirement and insufficient contract deployment nags

- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This was an amazing example of an endless loop that didn't eventually run out of memory.
Basically, the loop was:
a) Not actually replacing the missing parts.
b) Re-initializing the parts list from somewhere so that the missing part would pop back up even if it was replaced. 
Changed it to actually replace the missing part. Also fixed an issue where "restore unit" wouldn't actually reload ammo bins.
> Fix for endless loop causing issue #748

- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
While test the restore unit fix last week I discovered that attempting to salvage ammo on a dropship throws an NPE due to the inherited behavior that removes it and replace it with the corresponding MissingPart. Large Craft bays are not actually parts but rather ways to track capacity and have no corresponding MissingPart. I fixed it by overriding the replace method so that it simply unloads the ammo, and also ensured that ammo bins only show up in the task list for salvaging if they have ammo in them.
> Fix for salvaging dropship ammo

- MekHQ/data/universe/planets/0002_planetevents.xml
Was getting a message in `mekhqlog.txt`:
```
22:16:46,469 ERROR [mekhq.campaign.universe.Planets] {Planet Loader} 
Planet "Buckland" is missing coordinates
```
The id it was referencing Buckland instead of Bucklands.
> data: fix buckland missing coordinates message

- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
This allows editing of the "Payment Multiplier" spinnerbox in new AtB-style contracts being added in GM mode, in most situations. It was previously being recalculated in the event handler for _any_ changes to any of the controls in the dialog, including this one. 
It should now allow editing but get recalculated automatically if the planet, factions or contract type are changed. 
Fixes #308
> Fix GM "New Contract" payment modifier spinner

- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
Quick simple fix to #384 - now it searches for the person with the highest negotation skill, using admin as tie-break.
> Fix #384: Negotiation re-rolls now getting person by order of negotiation skill

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
- MekHQ/src/mekhq/resources/NewContractDialog.properties
Adds a simple spinner found in the "Edit Mission" dialog for the player to set a custom, arbitrary contract score modifier, mostly as a "crutch" to handle conditions not currently covered by MekHQ for now. 
Looks like this, in a new GM-created Contract that started at the usual contract score of 1:
> Added arbitrary contract score modifier

- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
- MekHQ/src/mekhq/campaign/universe/StarUtil.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Found via [static code analysis tool SpotBugs](https://spotbugs.readthedocs.io/).
> ES: Comparison of String objects using == or != (ES_COMPARING_STRINGS_WITH_EQ)
> 
> This code compares java.lang.String objects for reference equality using the == or != operators. Unless both strings are either constants in a source file, or have been interned using the String.intern() method, the same string value may be represented by two different String objects. Consider using the equals(Object) method instead.
This should have no visible impact to the user.
> string identity comparison to .equals()

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/Kill.java
- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/report/HangarReport.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/gui/dialog/PayCollateralDialog.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
- MekHQ/src/mekhq/service/MassRepairService.java
- MekHQ/src/mekhq/service/PartsAcquisitionService.java
This PR addresses a big TODO in Campaign.java to not double down on `ArrayList<>` and `Hashtable<>`:
```java
// TODO: do we really need to track this in an array and hashtable?
// It seems like we could track in a hashtable and then iterate through the
// keys of the hash
// to create an arraylist on demand
```
The general strategy was to replace true hash tables with `HashMap<>` and any hash table that needed insertion-order iteration with a `LinkedHashMap<>`. Each commit details the migration of one of the sets of data structures and is easiest to review when done individually.
Few performance gains can be expected given the small numbers of items in each collection, however, I paid some attention to over allocation (or re-allocation in a loop) with some of the more frequently used data …
> Refactor campaign data structures

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Addresses #549, allowing ransom if 'Capture enemies in scenario' is enabled but AtB's random capture is not. This still requires AtB rules to be enabled.
> Allow Ransom if 'Capture' is allowed but not AtB random capture #549

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/unittests/mekhq/campaign/personnel/PersonTest.java
Goes beyond a simple fix and pulls the logic for deciding whether a role is combat or support to a central location in Person.
> Fix for #796: LAM Pilot shows as Support in Personnel Breakdown

- MekHQ/src/mekhq/campaign/parts/MissingBayDoor.java
- MekHQ/src/mekhq/campaign/parts/MissingCubicle.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
Transport bays are a single structure in Entity but have multiple distinct parts in MekHQ. The TransportBayPart tracks doors and cubicles as child parts. When fixing a missing bay door or cubicle the new part was not getting added as a child part and the Entity was not getting updated with the new state.
> Fix for #819: Dropshop Baydoor unrepairable

- MekHQ/src/mekhq/MekHqXmlUtil.java
While investigating #814 I noticed odd XML entity escapes in the uploaded campaign file.
```xml
<entityStub>&amp;lt;html&amp;gt;Shi-ping Ts&amp;apos;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;ai (4/6), &amp;lt;i&amp;gt;LRM Carrier (Standard) #2&amp;lt;/i&amp;gt;&amp;lt;/html&amp;gt;</entityStub>
```
It appears that the string for unescaping `&apos;` was missing the trailing semi-colon. I noticed Apache Commons was available and instead switched to their XML encoding and decoding methods.
> Replace custom XML escaping with Apache Commons

- MekHQ/src/mekhq/campaign/parts/AeroHeatSink.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Reported in issue #819 
Restore unit calls fix() on every part whether or not it needs fixing, presumably for the side effects of resetting other values. AeroHeatSink#fix() adds a heat sink without checking whether it was damaged, so this was fixing the damaged ones and adding an extra of all the undamaged ones for each iteration of the loop.
I separated the side effects of fix() so they can be called independently. For extra safety I added a check to AeroHeatSink so it will only add a heat sink if was actually fixed, in case fix() gets called somewhere else without checking whether it needed fixing.
> Fix for adding phantom heat sinks when restoring aerospace unit

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Bloodname.java
Fixes #824 
Introduced by #726 
Added overloaded versions of checkBloodnameAdd so that newPerson can pass the factionCode. Without this it attempts to generate a Bloodname using the player's faction instead of the captured prisoner's faction. Also check the return value of randomBloodname for null before attempting to access it.
> Use factionCode passed to newPerson when checking for Bloodname.

- MekHQ/src/mekhq/gui/dialog/EditInjuryEntryDialog.java
- MekHQ/src/mekhq/gui/dialog/EditPersonnelInjuriesDialog.java
Fixes two bugs in the Edit Injuries dialog:
1. You could not delete injuries from the dialog.
2. The Injury Type combo box did not update w.r.t. the location being changed.
Whitespace in both files wrangled to project default of 4 spaces in a separate commit to keep review clean.
> Fix two bugs in Edit Injuries dialog

- MekHQ/build.xml
- MekHQ/src/mekhq/campaign/unit/actions/IUnitAction.java
- MekHQ/src/mekhq/campaign/unit/actions/StripUnitAction.java
- MekHQ/src/mekhq/campaign/unit/actions/UnitAction.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/unittests/mekhq/campaign/unit/TestUtilities.java
- MekHQ/unittests/mekhq/campaign/unit/actions/StripUnitActionTest.java
This implements #822 by adding a Strip Unit menu item under the per unit GM menu. Units are not removed, as this allows them to be restored by the same GM menu.
This also does two other things:
1. Introduces a UnitAction pattern, to help refactor and test the existing per-unit actions.
2. Copies `*.properties` files to the test classpath, allowing testing of items. These can be overridden by adding a file under `./unittests/mekhq/resources`.
> Feature: GM mode Strip Unit

- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/unit/MothballInfo.java
- MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java
Fixed a couple of issues:
- Mass Mothball interface became unusable when mothballing a large number of units. Now comes with a scrollbar.
- Reactivate would fail to set a mechwarrior or other single operator as both driver and gunner.
- Awards would fail to load if awards directory was missing, resulting in NPE and inability to use right click menu on personnel
> mass mothball and misc fix

- .gitignore
When packaging MekHQ the temporary work in `pkgdir` generates a lot of traffic in an IDE tracking possible git files. I've added it to `.gitignore`. I've also added `/.vscode` to compliment the IntelliJ project ignore.
> Adds pkgdir and .vscode to .gitignore

- MekHQ/build.xml
- MekHQ/packaging.xml
- MekHQ/packaging_local.xml
Fixes three problems in the build scripts:
1. Include data/images/awards in release packages.
2. Put the services folder into META-INF instead of META-INF/META-INF (fixes #842)
3. Put the resource files on the build path when running the unit tests, since there are tests that use tokenized strings.
> Packaging fixes

- MekHQ/src/mekhq/campaign/personnel/Person.java
Adds the tech's XP next to their name on the repair badge.
First commit implements feature, second switches to using `StringBuilder`.
> Feature: display a tech's XP on the repair tab and doctor's XP on the infirmary tab

- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/AtBConfiguration.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ExtraData.java
- MekHQ/src/mekhq/campaign/GamePreset.java
- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/personnel/Bloodname.java
- MekHQ/src/mekhq/campaign/personnel/CustomOption.java
- MekHQ/src/mekhq/campaign/personnel/Ranks.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/universe/Faction.java
- MekHQ/src/mekhq/campaign/universe/News.java
- MekHQ/src/mekhq/campaign/universe/Planets.java
- MekHQ/src/mekhq/campaign/universe/RATManager.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/view/Paperdoll.java
Addresses:
- DocumentBuilderFactory
- JAXB Unmarshaller
Custom SPA currently uses XML entities and an inline DOCTYPE parser. `newUnsafeDocumentBuilder` addressees this need, but isn't protected against entity expansion attacks. That would allow a DoS, but from a file unlikely to be shared and easily inspected for tainted code.
> Address XXE vulnerabilities in XML parsers

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/PopupValueChoiceDialog.java
Fixes a small logic error with the result of `PopupValueChoiceDialog` resolving #866, and implements #859 by using the default formatter's commit on valid value logic. At worst putting in an invalid value without causing the field to update will add 1 XP. This is more desirable than the odd behavior where you can't type because of the automatic validation.
> Bug: fix GM Mode Add XP subtracting one (1) XP if cancelled

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
Changeset
https://github.com/MegaMek/mekhq/pull/812/files?utf8=%E2%9C%93&diff=unified&w=1
inadvertently created an execution path in
AtBContract.calculatePaymentMultiplier() that would leave requiredLances
unitialized - this initializes requiredLances to #units/6, restoring the behaviour
prior to that changeset.
> Fixes generation of AtBContracts with 0 req. lances

- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/resources/PartsStoreDialog.properties
Use CTRL + CLICK to select multiple rows.
If someone could double-check the logic, especially all of those booleans that would be great.  I had to refactor a bit for the bulk case.  I believe it should all work for purchasing (single and bulk) as well as adding (GM mode).  I didn't test the bonus and left that as-is single selection since it has to decrement the bonus amount.  I also don't have a campaign to test that condition.
> allow purchasing and adding of parts en-masse, addresses issue: #121

- MekHQ/src/mekhq/campaign/Campaign.java
Invariant was incorrect to determine if a tech had enough time to perform maintenance; fixes #895.
> Bug: Fix invariant to check if tech time available for maintenance

- MekHQ/src/mekhq/campaign/Campaign.java
Found during campaign load benchmarks:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at mekhq.campaign.Campaign.getPartInUse(Campaign.java:1431)
at mekhq.campaign.Campaign.getPartsInUse(Campaign.java:1496)
at mekhq.gui.OverviewTab.refreshOverviewPartsInUse(OverviewTab.java:402)
at mekhq.gui.OverviewTab.lambda$refreshOverview$0(OverviewTab.java:386)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
at java.awt.EventQueue.access$500(EventQueue.java:97)
at java.awt.EventQueue$3.run(EventQueue.java:709)
at java.awt.EventQueue$3.run(EventQueue.java:703)
at java.security.AccessController.doPrivileged(Native Method)
at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPri …
```
> Fix NPE in getPartInUse if EquipmentType is null

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
When a rank name is missing for the profession the rank level is decremented until a rank name is found. This can drop the rank level below zero to RANK_BONDSMAN (-1). This is a misconfiguration of the custom ranks, but the way MekHQ handles it is confusing. By stopping at zero the rank is shown as - instead, which is easier for the user to figure out.
Fixes #917
> Handle missing E0 rank

- .mailmap
Began with MegaMek's `.mailmap` and extended it to cover the users and emails found via `git shortlog`.
> Add .mailmap to MekHQ for git shortlog

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/service/MassRepairService.java
This attempts to fix the root cause of #860 and #911. From what I can tell, a normal repair task (in RepairTab) will check to see if the unit is no longer repairable and no longer has salvageable parts and remove it if that condition matches. The other repair place missing this logic is in MassRepairService and when we advance the day and complete multi-day repairs. This PR adds that logic to those two places.
> Ensure after fixPart is called that unusable units are removed

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
This will allow units that are or are being mothballed to be given as reward in the retirement dialog
> Allow mothballed units in retirement dialog

- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
This feature adds in alternate coloration of the map based on socio-industrial level. This is selectable by the user from the map options panel. Here is an example using tech level:
Of course, a lot of systems are grey because of lack of information, but thats more incentive to get those values imputed. Here is a rough idea of what it would look like with no missing values by randomly imputing values:
Of course, the values make no sense because they are random. In actuality there should be a lot more dark color at the core and lighter colors at the periphery. 
The shading colors here come from the great [ColorBrewer website](http://colorbrewer2.org). All shades should be color-blind safe.  
All of the magic happens in `InterstellarMapPanel.getPlanetColors`, and it is extendable to other …
> Map Colors for Socio-Industrial Level

- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/universe/Planets.java
This simplifies the `MekHqXmlUtil` API so that it doesn't declare useless checked exceptions
(SAX already does that enough).
As an opportunity change, this also removes a static `SimpleDateFormat`
from AwardsFactory and normalises whitespace in `MekHqXmlUtil` from tabs to spaces.
**Note to reviewers**
There are two commits in this PR: you might want to only look at the first one to check out the actual code (the second commit changes whitespace, and so basically every line is modified)
**EDIT:**
I added a third commit to this PR, which removes some unnecessary complexity in how entities were parsed out of embedded mul-formatted tags and, in theme with the PR, also removes the need for a few other declared checked exceptions.
> Reduced declared checked exceptions in MekHqXmlUtil

- MekHQ/src/mekhq/campaign/personnel/Rank.java
Fixes #946 
If a rank name in the final column is left blank, the array for that level is too short. Changed the xml processing to include trailing empty strings in the array. Also removed extraneous code and added some more protection against custom rank names that include a colon that is not followed by an integer, which currently throws an exception.
> Custom rank fixes

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Fixes #905 
To check if some has spouse, use the new `Person.hasSpouse()` method, which checks if the actual spouse exists. Refrain from comparing `Person.getSpouse()` and `Person.getSpouseID()` with `null` as they are not safe. 
When a person is deleted and has a spouse, their spouse's spouseID will be set to null, just like in a divorce, to avoid this issue.
> NPE when spouse is simply removed

- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixes an issue with loading VTOLs from campaign files with damaged internal structure - they can't be repaired for because the "internal" locations don't get generated for them.
> Load VTOL locations when loading campaign

- MekHQ/resources/mekhq/resources/CampaignGUI.properties
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
This makes the personnel tab easier to review with large numbers of vehicles or infantry.
Not accomplished:
- Context menu does not apply any actions to the grouped persons.
- You cannot expand an individual (all or nothing).
> Allows grouping personnel by their unit on the Personnel tab

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/universe/FactionBorderTracker.java
The AtB contract generator was running before the faction borders had been calculated. This is due to a race condition resulting from an attempt to optimize the faction calculation by limiting the amount of synchronized code. Removing the premature optimization and synchronizing the entire method fixes the race condition.
Fixes #973: No contracts are offered at the start of an AtB campaign
> Removed race condition when calculating faction border data.

- MekHQ/src/mekhq/campaign/personnel/Person.java
Tangential issue to #979 
When checking whether a tech is tied up in mothballing, the tech's id is checked against getTechId() of every unit undergoing mothballing. For aerospace vessels this returns null, because the virtual engineer is used for all tech duties. Replacing getTechId() with getTech().getId() uses the engineer field instead if it's non-null.
> Fix npe when determining whether a tech is mothballing.

- MekHQ/src/mekhq/campaign/unit/Unit.java
Fix for #949 
Depends on MegaMek branch reset_crew_state
Added a method to `Crew` in MegaMek that resets the game state. Replaced separate calls to resetFatigueCount and setEjected with a single method call. Moved it to the beginning of resetPilotAndEntity before MekHQ sets missing and hit count values.
> Reset all crew state when resetting entity and crew.

- MekHQ/src/mekhq/campaign/parts/Refit.java
This PR addresses two bugs found exploring #981:
1. Armor was being charged at the full rate, presuming it was completely replaced, even if it could be reused.
2. Equipment move detection was somewhat off, in that excessive moves could be generated (e.g. WVR-6R to WVR-6M would move a CT Jump Jet when it should have stayed put).
This PR fixes those two issues like so:
1. Armor points that are detected to be recycled has its refit time refunded.
2. Move detection is split into two parts:
a. Find all of the parts that did not move.
b. Take the remaining parts and select a suitable location to move from or add it as a new part if none are found.
> Fixes bug where refits overcharged for armor or would perform excess moves #981

- MekHQ/src/mekhq/campaign/personnel/CustomOption.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This is something I just happened to run across by accident. When a new set of PersonnelOptions is created, the custom SPA file gets parsed each time rather than storing the results in memory the first time it happens. As this occurs every time a new instance of `Person` is created, this can be a rather expensive operation when loading a campaign file from xml.
> Don't parse customspa.xml every time a new Person is instantiated.

- MekHQ/resources/mekhq/resources/UnitTableMouseAdapter.properties
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This addresses #990 by adding a bulk confirm dialog if you remove more than one unit from the hangar.
Removing one unit:
Removing more than one unit:
Removing more than one unit, with one or more units deployed (deployed units are skipped):
> Feature: Add bulk confirm dialog if more than one unit is removed

- MekHQ/src/mekhq/campaign/log/LogEntryController.java
This PR does two things:
1. Fixes an exception raised when `Made Bondsman` or `Made Prisoner` did not include a name.
```
12:10:04,272 ERROR [mekhq.campaign.personnel.Person] {SwingWorker-pool-1-thread-1} 
No group 1
java.lang.IndexOutOfBoundsException: No group 1
at java.util.regex.Matcher.group(Matcher.java:538)
at mekhq.campaign.log.LogEntryController.updatePrisonerDescription(LogEntryController.java:195)
at mekhq.campaign.log.LogEntryController.updateOldDescription(LogEntryController.java:174)
at mekhq.campaign.log.LogEntryFactory.generateInstanceFromXML(LogEntryFactory.java:110)
at mekhq.campaign.personnel.Person.generateInstanceFromXML(Person.java:1721)
...
```
2. Caches regular expression patterns so they are not recreated each time this is used (important on large campaign files).
> Fix pattern matching in log entry updates and cache patterns

- MekHQ/src/mekhq/gui/dialog/DateChooser.java
On Mac OS X and Java 8 the DateChooser dialog becomes hidden behind the campaign loading splash screen when you create a new campaign. This makes it so that you no longer have to use Expose to find the date window.
> Ensure the DateChooser dialog isn't hidden when you create a new campaign

- MekHQ/resources/mekhq/resources/PersonViewPanel.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Refreshes the edge points available to support personnel each week. Combat personnel already get their edge points back at the start of each MM battle in which they are deployed. Available support edge points are displayed on the PersonViewPanel.
> Weekly Support Edge Refresh

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/universe/Planets.java
- Improve speed by ~4x using a Set instead of a List to track the open/closed lists
- Improve speed to ~5-7x by adding the visitor pattern to Planets (visitNearbyPlanets)
Random AtB campaign with 20 contracts:
- Old 37.356 seconds
- New 5.479 seconds
> Speed up calculation of jump paths

- MekHQ/resources/mekhq/resources/NewRecruitDialog.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
Adds a new "Add (GM)" button to the new recruit dialog.
I presume this was left out because Campaign did not have a means of doing so. I have added a function to unconditionally add a person.
> Adds a GM hire button to new recruit dialog

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Purely a convenience feature to make it easier to copy/paste the missing units from a campaign file.
> Adds the list of missing units on campaign load to the log

- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
It looks like the old code was incomplete or perhaps cut/pasted wrong. Fixes #1010
> Bug: Do not recurse into getStickerPrice for Battle Armor

- MekHQ/src/mekhq/campaign/finances/Loan.java
A loan's collateral value was written out instead as its total value, and thus on subsequent save/load cycles the loan's properties would become incorrect. Fixes #991
> Bug: loan total value written as collateral value

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
Corrects an inequality in Retirement/Defection dialog, fixes #986.
> Bug: Retirement/Defection dialog doesn't show first row details

- MekHQ/src/mekhq/campaign/Campaign.java
Commit d0c2b94 moved where acquisitions are tallied into a block of code that prevented failed acquisitions from applying #1022 . This moves it back to its original location and protects it with a `null` check to avoid the NRE mentioned in the original bug.
The second commit fixes whitespace problems I found in `goShopping` while debugging.
> Bug: failed acquisitions don't count against limit

- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
> Bug: Do not raise UnitChangedEvent if there is no unit in GM Acquire Instantly

- MekHQ/src/mekhq/gui/dialog/EditInjuryEntryDialog.java
- MekHQ/src/mekhq/gui/dialog/EditPersonnelInjuriesDialog.java
The Edit Injury dialog defaulted to the wrong type due to the order of operations when setting up the master-detail combo boxes and their options. This also marks the dialog as modal before it is called to ensure it stays over top of the injury manager on Mac OS X. Fixes #1009
> Bug: Default injury type wrong

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/Part.java
Addresses two bugs:
1. If a tech gets "stuck" on an overnight task when they have no minutes left after maintenance, remove them from the work and allow it to be reassigned (#976).
2. If `timeSpent` became greater than `actualTime` for a part, `getTimeLeft()` would underflow and give back time to techs.
This does not address the (currently unknown) root cause of why some techs can be assigned to overnight work when their maintenance tasks would prevent them from working on it.
> Bug: techs without any minutes left may get stuck on overnight tasks

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
This consolidates the multiple ways in which AtB is initialized in `Campaign`. It also (potentially) fixes a bug where the `AtBEventProcessor` is not hooked up for brand new AtB campaigns.
> Cleans up and (potentially) fixes AtB initialization

- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
This is a quick change to the GM Tools Add RAT Unit behavior to clear the last rolled unit after each add. Originally I had thought it best to have the user re-roll, but after using this in practice it wasn't that nice.
> Improved GM Tools Add RAT to clear the rolled unit each time

- MekHQ/src/mekhq/gui/RepairTab.java
Minor annoyance: whenever you changed the mode on a repair task (e.g. from normal to x4), the selected task moved to the next one.
> Fix bug where selected repair task moves when you change mode

- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/service/MassRepairService.java
The active mass repair options were computed but not passed to the actual routine which does the work. This fixes bugs like #1028.
> Fix bug where Mass Repair Options were not applied unless you clicked Save

- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
If less than a ton of ammo is needed a LargeCraftAmmoBin wasn't allowed to be reloaded. This fixes #1005.
> Allow fractional tons to be loaded in LargeCraftAmmoBins

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Fixes #970
Tested locally:
- Create new Campaign
- Recruit 4 mechwarriors.
- Imprison them. Set them to Prisioners (may defect)
- Recruit all of them.
> Allow multiple recruiting of prisoners

- MekHQ/resources/mekhq/resources/StartUpDialog.properties
- MekHQ/src/mekhq/gui/StartUpGUI.java
This "fixes" something I saw somebody note, which I never really noticed myself on my MacBook.
If the splash screen image will be less than 840 (buttons plus gutters) it switches to "small" buttons and text.
> Make startup GUI show all four buttons at lower res

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This fixes at CPNX load a few issues seen in a large CPNX:
1. A person techs a unit somebody else techs
2. A person techs a unit without a tech
3. A person techs a mothballed unit
4. A person techs a unit no longer in the campaign
This also cleans up setTech/removeTech usages.
This also fixes an NPE in RepairTab seen with the CPNX.
> Fix some unit/tech mismatches at CPNX load

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
Changing logic so Recruiting prisoners is enabled if at least one valid prisoner that can be recruited is selected. Only valid prisoners will be recruited.
Tested locally by creating a group of 4 prisoners, setting 2 to willing to defect and trying to recruit them all. Only 2 of them were actually recruited.
> Allow recruiting if a valid prisoner is selected

- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/gui/RepairTab.java
This resolves two NRE's seen in the warehouse tab in #1049. The first causes the tab to become unresponsive, and the second seems to occur when the tech list gets out of sync (unable to repro, but added a guard).
> Fix two NRE's seen in warehouse tab

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/unittests/mekhq/campaign/mission/ContractTest.java
We were stuffing long's into int's. This fixes that (found via: https://lgtm.com/projects/g/MegaMek/mekhq/snapshot/82b2780e05bf73dec210033fc277da6a6e2cecf9/files/MekHQ/src/mekhq/campaign/Campaign.java?sort=name&dir=ASC&mode=heatmap#x110f0bc0b025a7ab:1)
> Don't let peacetime costs overflow

- MekHQ/build.gradle
Fixes a problem where the releases were built using the (possibly-outdated) maven dependencies for the mm and mml jars rather than the jars newly built from the current code. Beside possibly being outdated they had different names that what is in the classpath in the MekHQ manifest.
> Bundle packages with newly built jar instead of maven dependency.

- MekHQ/src/mekhq/campaign/parts/Rotor.java
- MekHQ/src/mekhq/campaign/parts/TankLocation.java
This is a partial fix for #1057, keeps damages for rotors from rolling negative or using negative damages. Not 100% sure of the root cause, seems either `Rotor::fix` got called twice, or some calculation for the internals on the entity was incorrect in MM.
> Don't allow damage to go negative or use negative damages #1057

- MekHQ/src/mekhq/campaign/Campaign.java
This resolves (partially) #1085 by tallying the last part ID before spares are checked. Otherwise, if a part becomes a spare of a part with a lower ID, it may be skipped over on campaign load.
Still haven't located the source of the high part ID when a lower one would have done.
> Tally the last part ID before checking for spares #1085

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingEquipmentPart.java
Fixes #1125, #1127, and a few minor bugs introduced with the Joda money changeover (.equals is no longer the same as == for the Money data structure), which appears to fix #1121.
> Fix damaged ams/masc tracking on load

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/EnginePart.java
- MekHQ/src/mekhq/campaign/parts/MekActuator.java
- MekHQ/src/mekhq/campaign/parts/MekCockpit.java
- MekHQ/src/mekhq/campaign/parts/MekGyro.java
- MekHQ/src/mekhq/campaign/parts/MekLifeSupport.java
- MekHQ/src/mekhq/campaign/parts/MekSensor.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
This ~~isn't strictly~~ is required after #1129, ~~but~~ this fixes the upstream problem when evaluating equipment parts on campaign load. Basically these system level parts were chiming in for any matching equipment number, no matter the location. The combination of the prior pull request and this one should fix #1109.
> Ensure equipment parts don't chime in for parts not in their location #1109

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/Loot.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifier.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryTypes.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixes a few logical bugs found while playing with [Google's error-prone](https://github.com/google/error-prone).
The only one that I'm not 100% sure of is the last commit, where `tonnage` was not passed to the other EquipmentPart ctor. It looks like it is used as if tonnage means the part's tonnage in some cases, and the unit's tonnage in other cases (or `0`).
> Fix various logical bugs (found by error-prone)

- MekHQ/src/mekhq/campaign/finances/Finances.java
This fixes #713, and also slightly improves end-of-month performance, as we no longer recalculate salaries and such twice (the relevant properties in Campaign do a full calculation every time they are accessed). The amount of money *actually* being debited was correct, just that it was reporting the spare parts cost for fuel and munitions costs.
> Report correct amount of money for spare parts/etc in daily log

- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/dialog/CamoChoiceDialog.java
- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
On my MacBook, when I use the right click gesture with my trackpad (two finger tap) the various panels expand or contract every time. This makes the expand/contract logic only occur with the left mouse button double clicking.
> Don't expand/contract tab panels on right double click

- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
Using "targetWork" for shopping for parts means that the quantity field gets decremented as part of the shopping process. Since the same targetWork object is re-used every time the user clicks "order one", the next time it's called, the internal quantity is 0, so...
Thus, we just generate a new shopping order each time instead.
> Fix issue where "Order One" on repair tab acquisition UI was only allowing one part to be ordered

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/EnginePart.java
- MekHQ/src/mekhq/campaign/parts/MekActuator.java
- MekHQ/src/mekhq/campaign/parts/MekCockpit.java
- MekHQ/src/mekhq/campaign/parts/MekGyro.java
- MekHQ/src/mekhq/campaign/parts/MekLifeSupport.java
- MekHQ/src/mekhq/campaign/parts/MekSensor.java
This is a follow-up to #1130 that adds a check for the actual part types, since it appears that MekActuators end up with the same equipment numbers as actual equipment parts (different bug?).
> Only remove duplicate parts if they are the same type on CPNX load #1109

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
This fixes the behavior reported in #1149 , which causes a divide by zero error due to a Hetzer with a blown-out engine attempting to show up as reinforcements. 
Leaving aside the various questions raised by the idea of bringing an immobile unit as reinforcements to a battle, the simple solution is to prevent the divide by zero attempt.
> Immobile reinforcements no longer prevent scenario start

- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
It looks like after a refit there was an equipment number mismatch on an omnipodded ammobin. This avoids the NPE in this case.
> Do not throw if mounted is missing after refit #1138

- MekHQ/src/mekhq/campaign/mission/BotForce.java
This causes the force BV to be the actual BV * number of entities in the force.
> no need to loop through every entity #entity times

- MekHQ/src/mekhq/campaign/unit/Unit.java
Fixes a bug during calculation of peacetime costs, where protomechs (or potentially anything) were cast to `Infantry` inappropriately.
> Don't cast to Infantry unless you are one #1161

- MekHQ/resources/mekhq/resources/CampaignGUI.properties
- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/BaseDialog.java
- MekHQ/src/mekhq/gui/dialog/DialogResult.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
- MekHQ/src/mekhq/service/AutosaveService.java
- MekHQ/src/mekhq/service/IAutosaveService.java
This PR adds several things:
- AutosaveService: which will handle creating and managing autosaves (per #1171).
- MekHqOptions: so the user can configure autosave (per day, week, no autosave, save before missions, number of saves). This can be access from the File menu, like the Megamek and Campaign options.
- BaseDialog: a base dialog class to unify the look and feel and functionality of our dialogs. Used for MekHqOptions, should be adopted little by little in the rest of our dialogs.
Missing from this PR:
- Autosave before a mission starts. I have to find where is that code and make the call to AutosaveService.requestBeforeMissionAutosave().
I'm putting this PR up to gather feedback while I finish the mission saves.
> Adding autosave feature (#1171)

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This applies the changes recommended for #1198 
- view personnel buttons now use in-line handler instead of separate class
- view personnel buttons now disable when prisoner is dead
- made OK button the default for accessibility
> Applied recommended changes for view prisoner dialog

- MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
This fixes the issue in #1197 where personnel could not be assigned to Battle Armor. The armor had 0 internals after repair, it is now set to 1 and allows personnel to be assigned to them. Previously repaired suits can have their internals manually set to 1 to be functional again.
> Set Battle Armor internals to 1 after repair

- MekHQ/src/mekhq/campaign/finances/Money.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
This improves the purchase parts dialog's performance through a few improvements:
1. Introduce proxy objects to memoize expensive properties.
2. Ensure sorting is performed on native values and not by parsing strings.
3. Directly return values to the table rather than creating strings.
This is a partial fix for #1205.
This does not address part details sorting.
> Improve Purchase Parts performance #1205

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
Added functionality to the RetirementDefection tracker to clean up orphan person records when loading a save. Also made sure that the campaign removes orphan records when a person is gm-removed.
This fixes a behavior where, if you have an outstanding retirement/defection roll but then gm-remove that person, the player is unable to "advance day" due to an NPE in the retirement/defection UI.
> Retirement null fix

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
- MekHQ/src/mekhq/campaign/mission/ScenarioTemplate.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifier.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache2BuiltInScenario.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
- MekHQ/src/mekhq/campaign/universe/IUnitGenerator.java
- MekHQ/src/mekhq/campaign/universe/UnitGeneratorParameters.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
- MekHQ/src/mekhq/gui/dialog/ScenarioTemplateEditorDialog.java
Ported some of my work on AtB-StratCon back to legacy AtB just to give some of the mechanisms I've worked on a better workout.
Major changes for legacy AtB:
- APC type units will now come loaded with infantry
- Infantry may now be field gunners
- VTOLs are always on (the bot has gotten good enough at them that they're no longer useless)
- Aircraft may be loaded with bombs
- allied dropships aren't all just Leopards
Changes for Scenario Template system:
- can specify fixed modifiers for a scenario template
- capability for a scenario modifier to turn allied bot units against you. Surprise!
> Legacy atb goodies

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
This is an experimental change that may fix the tough to track down part ID changes affecting refits at CPNX load #1193 #1180 #1138 #1123 (to name a few).
*note: best compared with whitespace ignored*
> Track part ID moves during campaign loads that may affect refits

- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
This fixes an additional refit bug as seen in SilverSword's campaign posted under #1193 
If a refit changed the munition type of an ammo bin part (which happens a lot with updates that add ArtemisIV FCS and compatible missiles), UnscrambleEquipment was failing to update the equipment number of the AmmoBin part because it saw the munition mismatch as a complete part mismatch. This led to class cast exceptions when a refit was completed, the campaign saved, and then reloaded as ammo bin parts from the old entity were matched up with non-ammo bin Mounteds on the new entity.
I was also pointed to a piece of code that had never been updated to allow saving of NavalC3 networks in addition to C3/C3i networks.
+ Fix  NavalC3 networks can now be saved to MHQ campaign files
+ Fix Ammo bins that …
> Additional Fix for #1193

- MekHQ/src/mekhq/campaign/unit/Unit.java
There is a path through Unit#resetPilotAndEntity that dereferences the
value returned by getCommander() without checking for null, which
indicates no crew assigned.
Fixes #1230: Tripod mech breaking campaign save
> Check for crew before calculating special abilities.

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Fixed an issue where, if exporting a person into a campaign where their ID already exists, their kills would duplicate. 
Clear an exported unit's force ID to avoid phantom irreversible force assignments on export.
Optimization to the kills mechanism, where they are now stored in memory in a hashmap keyed by person ID, rather than re-scanning every kill in the campaign every time (this could probably lead to some hairy performance for longer campaigns).
> Campaign subset export update

- MekHQ/src/mekhq/campaign/parts/MekLocation.java
This fixes #1075 and updates 'Mech location repair/salvage times and difficulties based on StratOps p191. It also updates our logic for breached locations to include costs for any other repairs required per StratOps p177.
Best to review this with [whitespace off](https://github.com/MegaMek/mekhq/pull/1233/files?w=1).
> Update 'Mech location repair and salvage times to match StratOps #1075

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/MothballInfo.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/unit/actions/ActivateUnitAction.java
- MekHQ/src/mekhq/campaign/unit/actions/CancelMothballUnitAction.java
- MekHQ/src/mekhq/campaign/unit/actions/MothballUnitAction.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java
This adds GM Mothball and Activate to units in the hangar, contributing to #1238. This also splits out mothballing and activation to make it easier to do both as a GM action.
> Add feature to GM Mothball/Activate units

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
A couple of minor changes to the scenario resolution wizard:
- Let event handler handle setting enabled/disabled status for personnel MIA checkbox/hit slider
- When finishing up, make sure "dead" status is set last, as "set hits" overrides being dead if the # of hits < 6
- Removed unnecessary checkbox initialization
> fix immortality in certain cases

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
This PR fixes an observed behavior where, if a unit being upgraded is not eligible for any SPAs with a cost below the SPA cap, the spa upgrader code goes into an endless loop.
Also, check if the user has SPAs enabled before giving bot units SPAs.
> re-organize skill data structure

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
Current behavior is to disallow salvage unless the current % is less than the max. This prevents salvaging any units at 100% salvage rights if the current salvage level is at 100%.
Fixes #1240
> Allow salvage at 100% salvage terms

- MekHQ/src/mekhq/campaign/Campaign.java
Note that this is for merge into stable and not master.
This restores "[techname] attempts to [action] [partname]" in the daily report. It was left out while manually merging the mothball fix into the stable branch, which does not have the large craft parts feature. There is a conditional that changes the name to heat sink for large craft cooling system. I left out the entire if/else block, instead of including just the else block.
Fixes #1249: Tech Names Missing in Event Log
> Restore tech action description

- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
Relevant to both the stable and dev versions, this fixes the map size displayed in the briefing tab for standard AtB scenarios.
> fix map size display

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
This resolves bug (1) in #1257 where salaries are applied twice when peacetime costs are used. Salaries are excluded when reporting peacetime costs, but not showing them, on the first of the month. Effectively this means `payForSalaries` is the single source of truth for salary payments.
> Don't double up salaries in peacetime costs #1257

- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/MekHQAboutBox.java
If you call `setVisible(true)` on a non-modal dialog, it returns instantly. And if you then call `dispose`, well...you will definitely close that brand new window. This fixes the problem by explicitly calling `setModal(true)` before our calls to `setVisible` when we'd like to dispose of the dialog.
Fixes #1274
> Only call dispose if the dialog is modal #1274

- MekHQ/mmconf/mhqPresets/AgainstTheBot.xml
This addresses #1273 by making the preset edge cost 10 XP for AtB.
(apparently my editor also fixed some whitespace issues as well)
> Update edge cost for AtB preset to match current rules #1273

- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
- MekHQ/src/mekhq/gui/dialog/LargeCraftAmmoSwapDialog.java
+ BugFix  Allow the large craft ammo swap dialog to switch AR10, missile and artillery munitions properly
> Large Craft Ammo Swap Fix

- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/gui/dialog/LargeCraftAmmoSwapDialog.java
A couple of extra improvements after my last PR on the subject
+ Enhancement:  Properly removes ammo from large craft bins when ammo swap dialog reduces a bin to 0 shots
+ Enhancement: Refits return large craft ammo to the warehouse when the refit changes the count but not the type of ammo (AR10s, MMLs...)
> Large Craft Ammo Bin Improvements

- MekHQ/src/mekhq/MekHQ.java
For mac users, when using any of the other look and feel themes besides the standard Mac OSX look and feel, the standard key bindings for cut, copy, paste, and select all with the command key do not work, and users have to instead use the control keys which is not natural for many Mac users (including me). This PR re-introduces those key bindings so Mac users can utilize the more familiar command keys when using other themes like Nimbus or Metal. It still retains the control key bindings as well. 
The code for the PR comes from [this StackOverflow thread](https://stackoverflow.com/questions/9780028/mac-keyboard-shortcuts-with-nimbus-laf).
> Mac OSX key bindings on non-standard look and feel

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
Fixes behaviors reported in #1290:
- part counts properly export
- source campaign skill and ability settings don't get clobbered
- "techs" for crew-maintained units properly register upon export campaign load rather than having to wait a day
> Subset export fixes

- MekHQ/src/mekhq/campaign/Campaign.java
In the normal operation of MekHQ the currency manager is initialized before initializing a campaign. This is not the case in the unit tests. When unable to find a general default currency for the CurrencyManager tries to access the campaign location to set a currency appropriate to where the unit is located. This results in an NPE. Initializing the default location before initializing CampaignOptions allows unit tests to use a Campaign object without adding the overhead of loading the currencies.
> unit test fix

- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/gui/MapTab.java
- MekHQ/src/mekhq/gui/view/PlanetViewPanel.java
This is a small (yay!) PR to fix a couple of issues noticed about the recent system map PR.
First, the "Calculate Jump Path" button was failing to show the jump path information in the view when pressed ... because I removed that code. Its back in now and working as it should in this PR.
Second, when a planet only had small moons, they were not being reported in the planet view. This PR fixes that.
> a few map fixes

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjective.java
This fixes a long-standing complaint about MekHQ: if you give some of your units to a buddy, they show up as totaled during scenario resolution. Turns out, it's pretty easy to detect if a unit that you gave to an ally actually came from your campaign.
> detect units given to other players

- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/utilities/ImgLabel.java
- MekHQ/src/mekhq/gui/view/UnitViewPanel.java
On the twin premises that:
1. Battletech is first and foremost about mech porn
2. Players are so into mech images (see premise 1) that they are willing to commission [great works of art](https://bg.battletech.com/forums/index.php?topic=37902.0;topicseen) to see their personal units in action
I have therefore concluded that our UnitViewPanel could use some work to better show off fluff images when players have them. In order to do that I have moved things around a little bit when a fluff image exists and put an image which automatically adjusts to fit the space (up to its size) when it has the room. Here is an example of it in action;
In order to do this, I created a custom ImgLabel.java object that uses the paintComponent method to paint a properly sized image. This could be used in other …
> Rescalable images for unit view panel when fluff image exists

- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/MissingSVEngine.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/parts/SVArmor.java
- MekHQ/src/mekhq/campaign/parts/SVEnginePart.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/MekLabTab.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Adds support vehicle support to MekHQ, including two SV-specific part types and the ability to configure SVs in the MekLab tab. It also fixes errors in the MekLab tab introduced by API changes in MML.
The new parts are SVEnginePart (and MissingSVEngine) and SVArmor. Though support vehicles in MM use the Engine class, there are some additional characteristics of the engine that are contained in the Entity itself and need to be tracked separately in a MekHQ part. SVArmor likewise tracks the BAR and tech rating of the armor. Under advanced rules SVs with the armored chassis mod can use armor types used by other units or patchwork. The constant EquipmentType.T_ARMOR_STANDARD is used to indicate that the SV uses standard SV armor.
This branch depends on the sv_customize branches in MM and MML.
> SV parts and customization

- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/ProtomekArmor.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/MekLabTab.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
When I was adding SV customization support to the MekLab tab I noticed that I had never done it for protomechs or advanced aerospace units. So here it is. I also added the fluff tab, and a preview tab for combat and support vehicles. Protomechs required some adjustments to the armor part to distinguish between standard and EDP.
> Customize protomechs and advanced aero

- MekHQ/src/mekhq/campaign/parts/SVArmor.java
- MekHQ/src/mekhq/campaign/parts/SVEnginePart.java
1. The default constructor can't be private even though it's invoked through reflection.
2. SVArmor::loadFieldsFromXmlNode doesn't call its super method, so the location (among other fields) doesn't get set and an IndexOutOfBoundsException is thrown when trying to use -1 as an array index.
Partial fix for #1333
> SV part loading fix

- MekHQ/src/mekhq/campaign/Campaign.java
Calling either Entity.setTransportId(int) or Entity.setSwarmTargetId(int) with an argument of Entity.NONE has the side effect of setting both done and unloadedThisTurn to true. In Campaign::clearGameData, this is done after clearing the transportId but before clearing the swarmTargetId, resulting in all units being sent to MM with both done and unloadedThisTurn set to true. Though it evidently gets cleared later, at the time of PHASE_SET_ARTYAUTOHITHEXES they are still true and cause Entity::isSelectableThisTurn to return false.
Fixes #1337
> Change order of resetting game data.

- MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java
I changed how the objective scoring worked in a subsequent PR but forgot to update the AtB scenario objectives - need to specify how many points towards scenario victory/defeat an objective gives, as the default is 0.
This would result in scenarios being incorrectly declared draws.
> fix victory/defeat determination issues

- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes #1344 by ensuring techs return S_TECH_MECH for protomechs.
> Ensure techs show the right skill for Protomechs #1344

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
This adds functionality to MHQ to handle ejected ASF/CF/LAM fighter pilots and any damage they might have taken during ejection.
It also corrects a bug where ejected pilots were not ever processed as possible prisoners if the option "Ejected Pilots Flee" is turned on.
Per SO p45, the victor/battlefield controller is assumed to have collected all warriors on the battlefield unless using the advanced SAR rules.  I'll be adding that in at a later date.
> Ejected aero pilot import

- MekHQ/src/mekhq/campaign/parts/MissingProtomekLocation.java
Unlike other units, Protomech critical slots only point to crits on the location itself, never the equipment installed there (probably because Protomech damage resolution is a bit weird). This results in CriticalSlot#isRepairable returning true, and the part is falsely flagged as still containing equipment. I changed the check to loop through the components and find anything in the same location that is not a MissingPart or armor with any points.
I can't think of a situation that would involve equipment still installed in a missing location, but as MissingMekLocation also performs this check I thought it better to leave it as is since it works. I also tested removing an arm while salvaging, and it correctly switches from impossible to possible when the last component is removed.
Fixes …
> Fix protomech location replacement

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/MercRosterAccess.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
Adds a T_VEHICLE_CREW role for support vehicle crew other than the driver/pilot and gunner(s). This allows the unit to be fully crewed so that it can be deployed. To keep things simple there is no distinction made between different vehicle types. In order to have an experience level there needs to be a skill requirement, so I used mechanics as the most reasonable skill.
This does not enforce the officer requirement, but neither do aerospace vessels at this point. A possible future refinement is to allow crewing mobile hospital units with doctors/medics, but I leave that for another time.
> General support vehicle crew

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Fixes two issues I discovered when setting the force tech.
1. NPE when adding/removing a force tech and the force contains a phantom unit.
2. Adding/removing a force tech doesn't immediately reflect the change in the force display.
The first is addressed by cleaning up unit IDs for non-existent units when loading a campaign. The second is addressed by firing the appropriate event when a force tech is set/removed.
> fix undesirable behavior when setting force techs

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/NewPlanetaryEventDialog.java
*[This is best viewed with whitespace ignored.](https://github.com/MegaMek/mekhq/pull/1382/files?w=1)*
This speeds up Advance Day through the following profiling driven enhancements:
1. `Part::writeToXmlBegin` was a huge time sink and was sped up using a `StringBuilder` and memoizing indentation for XML. (15% -> 9%)
2. `Armor::writeToXml` was the second largest time sink and was sped up in a similar fashion. (3% -> 0.7%)
3. `Planet::getEventData` was the third largest time sink and was sped up with a cache based on the last event date requested. (7% -> too few samples to profile)
4. `PlanetarySystem::getFactionSet` was the fourth largest time sink and was sped up with a new cached entry on `PlanetaryEvent`. (1.9% -> 0.1%)
Other classes' `writeToXml` are likely ripe for performance …
> Speed up advance day based on profiling data

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
When we write customs in the MTF format we were not wrapping them in CDATA blocks. This caused certain issues with units, see #1390. This makes MTF formats written to the CPNX file XML safe, mirroring the code used for BLK files.
This also resolves a double encoding problem in BotForce, found during code review, as `MekHqXmlUtil.writeSimpleXmlTag` already XML escapes string arguments.
Test campaigns (broken and fixed):
[campaigns.zip](https://github.com/MegaMek/mekhq/files/4054958/campaigns.zip)
> Bug: fix XML parsing failure when putting customs in CPNX #1390

- MekHQ/src/mekhq/campaign/universe/FactionBorderTracker.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
When selecting a location for a generated contract, if the attacker or defender does not control any systems in the region under examination, the only possibility that is considered is that it is contained within another faction, such as Clan Nova Cat inside the Draconis Combine, and if not found as an internal faction, an empty list is returned as possible locations. The other possibility that is not considered is that the faction is a rebel or generic pirate faction, which has special handling to place it anywhere within the attacking faction (rebels) or on a border world (pirates) but this special handling is never reached.
Also did a little whitespace cleanup and javadoc fixes.
Fixes #1384
Fixes #1284
> Pirate rebel contracts

- MekHQ/src/mekhq/campaign/unit/Unit.java
While trying to debug an issue in a user's campaign file, it was difficult to pin down exactly which unit caused the exception. This adds the unit's ID (from the CPNX) to the message.
> Add the unit ID to the log when unable to parse a unit

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
While working on a contract generation feature, I noticed that the jump path was getting recalculated many times for the same contract. Introduced a caching mechanism to greatly reduce the number of jump path calculations for each individual contract.
> Contract market performance improvement

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/model/ProcurementTableModel.java
The ProcurementTableModel defaulted to loading without the campaign's current parts list, causing CPNX reloads to display an empty procurement table in the warehouse tab #1366.
> Bug: Use current shopping list in ProcurementTableModel and restrict acquisitions #1366 #1345

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/finances/CurrencyDataLookupWriter.java
- MekHQ/src/mekhq/campaign/finances/CurrencyManager.java
- MekHQ/src/mekhq/campaign/finances/FinancialReport.java
- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/BaArmor.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/PartInUse.java
- MekHQ/src/mekhq/campaign/parts/PodSpace.java
- MekHQ/src/mekhq/campaign/parts/ProtomekArmor.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/parts/SVArmor.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/work/IPartWork.java
While investigating an issue where ammo could not be bought, I noticed a number of huge performance slowdowns in the Purchase Parts screen. I also found a bug w.r.t. refit ID's.
1. Cache CurrencyManager::getDefaultCurrency. This was extremely expensive and called constantly 25bed25.
2. Remove text "sanitizing" from PartsInUse 21d2f0f.
3. Add Campaign::streamSpareParts and use it where allocating a huge ArrayList is unnecessary 51ffcd3.
4. Add Campaign::findSparePart to take a predicate to quickly find a matching part e8b0652.
5. Speed up AmmoStorage 43da701, Armor 72ce2f3, BaArmor b1c5751, ProtomekArmor c9fc5c5, and SVArmor a0ab221 bc100ad with findSparePart.
6. Speed up AmmoBin with findSparePart and streamSpareParts 18a608a. **This one could use some eyes**
7. Fix incorrect usage of …
> Improve performance of purchasing parts and fix refit bug

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
When we call PartInUse::getNewPart it would call AmmoStorage::getNewPart that simply returned a clone of this part, rather than returning an actual new part #1427. If the ammo in question had 0 shots remaining, when you GM added it from the Parts in Use tab, you just added a bunch of 0 shot ammo parts.
This should land after #1426.
> Fix bug where GM Add'ing ammo with 0 shots did not add new ammo #1427

- MekHQ/src/mekhq/campaign/unit/Unit.java
Ensures that transport bay space is properly initialized when loading ships from a campaign before attempting to set used capacity values for those bays.
> Initialize bay space on Campaign load before setting Used Capacity

- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
Corrects an issue where campaigns fail to load due to an invalid class cast to largecraftammobin
This happens infrequently with dropship refits.  Fix allows the campaign to load anyway and logs which ship and equipment number are bugged so the unit can be repaired.
> Fix and log invalid lc ammo bin

- MekHQ/src/mekhq/campaign/Campaign.java
Fixes PR #1440 which died during CI due to release day Maven issues, but once those cleared it actually dies due to the unresolved `OptionsConstants` symbol.
```
PS E:\Source\megamek\mekhq> .\gradlew jar
> Task :MekHQ:compileJava
E:\Source\megamek\mekhq\MekHQ\src\mekhq\campaign\Campaign.java:7890: error: cannot find symbol
if(u.getEntity().hasQuirk(OptionsConstants.QUIRK_POS_RUGGED_1)) {
^
symbol:   variable OptionsConstants
location: class Campaign
E:\Source\megamek\mekhq\MekHQ\src\mekhq\campaign\Campaign.java:7894: error: cannot find symbol
if(u.getEntity().hasQuirk(OptionsConstants.QUIRK_POS_RUGGED_2)) {
^
symbol:   variable OptionsConstants
location: class Campaign
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.      
Note: …
```
> Add missing import for OptionsConstants

- MekHQ/src/mekhq/campaign/Campaign.java
Fixes an infinite loop when performing planetary acquisitions that will never succeed, no matter how many logistics personnel you have #1447.
> Bug: Don't infinite loop in planetary acquisition #1447

- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Fixes a handful of reported bugs with unit to dropship assignment:
-Refreshes TOE tab on load/unload to fix some graphical errors
-Corrects issue where ships have no available space when loaded from legacy campaigns
-Removes menu option to assign large craft to a transport
-Properly checks that all selected units are assigned to a transport before displaying 'unassign from transport' menu option.
> Dropship Unit Assignment fixes

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Another fix for Unit > Ship assignment
- Properly calculates the Infantry Bay space available on a ship and that consumed by platoons of various types
- Adds UI tweak, separating available transport ships by type of unit transported.
> Infantry autoload tonnage fix

- MekHQ/src/mekhq/campaign/personnel/Person.java
Time in Service for dead Personnel now only states the amount of time between recruitment and death, instead of continuing to increase despite being dead. This fixes #925 , specifically the addition to that issue in the second comment.
> 925: Fixing Zombie Time in Service 

- MekHQ/src/mekhq/campaign/unit/Unit.java
Fixing the Thumper Artillery Vehicle by removing the turret that wasn't supposed to be there is causing MekHQ campaigns that contain one to fail to load because the turret location, armor, and stabilizer parts are still there but the arrays are sized by number of current locations. I added range checks where appropriate. I believe that it is safe just to remove the part, since this is not likely to happen except when the part shouldn't be there due to a change in the unit file.
Fixes #1470
> Add bounds check when initializing parts

- MekHQ/src/mekhq/campaign/CampaignOptions.java
This fixes #1476 , and during investigation revealed that StringUtils.join cannot be used for boolean arrays.
> 1476: Fixing portrait generation setting save issue

- MekHQ/src/mekhq/campaign/unit/Unit.java
Fix #1497
When computing construction costs, the final cost of many units is scaled by a multiplier.
Generally this is related to the unit's weight class or type (e.g. aerodyne dropships cost 36 times
the sum of their components costs).
This change causes getSellValue() to take this into consideration, generally resulting in higher
sell prices. Ideally the sell value of a perfect condition, undamaged Unit would match it's buy cost.
This change doesn't get all the way there (things like SI are still not accounted for), but this is
a step towards that goal that doesn't require a major redesign of the Entity cost calculation methods.
> Scale Unit sell values by their Entity's price multiplier

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/dialog/BombsDialog.java
This allows users in MekHQ to load whatever bombs they want onto their aerospace fighters, limited only by availability. Previously, there was a restriction on that based on ... uh... a setting that's no longer present in MegaMek. ::shrug::
> relax bomb selection restrictions

- MekHQ/src/mekhq/campaign/personnel/DefaultSpecialAbilityGenerator.java
- MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
This implements the SPA generation for newly generated veteran and elite personnel, and renames a confusingly named variable that I thought was another AtB issue.
> AtB: Adding SPA Generation for Generated Veteran and Elite Personnel

- MekHQ/src/mekhq/gui/ForceRenderer.java
This fixes the missing space for C3 slaves in the lobby, so they display properly.
> Fixing spacing for C3 Slaves in the TOE

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
We were using a getLogger call to return MekHQ.getLogger(), so I just replaced the calls with the proper MekHQ.getLogger()
> Removing useless logger method in Unit Rating

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This was caused by a missing division
> Campaign Options now loads properly if you change the Chance of Procreation 

- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
This fixes a bug I discovered while testing my personnel dialog changes.
> Adding a market table refresh to the PersonnelMarketDialog

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
- MekHQ/unittests/mekhq/campaign/rating/FieldManualMercRevDragoonsRatingTest.java
This fixes two related bugs in FMM(r) unit rating, namely that we were double counting medic pool personnel, which was being hidden by how we unit tested. That should no longer be the case.
> Fixing FMM(r) Unit Rating Medic Pool Hour Calculation and Unit Test

- MekHQ/src/mekhq/campaign/log/MedicalLogger.java
- MekHQ/src/mekhq/campaign/log/PersonalLogger.java
- MekHQ/src/mekhq/campaign/log/ServiceLogger.java
- MekHQ/src/mekhq/campaign/mod/am/HitLocationGen.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryTypes.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
- MekHQ/src/mekhq/campaign/personnel/Injury.java
- MekHQ/src/mekhq/campaign/personnel/InjuryType.java
- MekHQ/src/mekhq/campaign/personnel/Modifier.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/enums/BodyLocation.java
- MekHQ/src/mekhq/campaign/personnel/enums/GenderDescriptors.java
- MekHQ/src/mekhq/campaign/personnel/enums/InjuryHiding.java
- MekHQ/src/mekhq/campaign/personnel/enums/InjuryLevel.java
- MekHQ/src/mekhq/campaign/personnel/enums/ModifierValue.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/dialog/EditInjuryEntryDialog.java
- MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/view/Paperdoll.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This is the first of two organizational changes that I'm doing to make it easier to parse through the Personnel folder. 
To review this: whitespace differences off (automatic changes), and the changes are almost entirely due to locating enums. The one exception is that I've added comments to GenderDescriptors to explain what each one means
> Moving Personnel Enums to their own folder

- MekHQ/src/mekhq/MekHQ.java
This prevents the case where you end up with a huge log file because you never start MegaMek. I also removed the inline Strings and moved it to instead use the preference manager.
> MegaMek Log File is Reset on MekHQ load

- MekHQ/src/mekhq/campaign/CampaignOptions.java
The default should be 10, not 1. This fixes that issue, which was raised by Algebro on discord.
> Campaign Options: Fixing Default Edge Cost

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/utilities/JMenuHelpers.java
This moves the addMenuIfNonEmpty method to a new JMenuHelpers class, which allows it to be easily reused in the code (two implementation PRs will be opened soon after this is merged)
> Creating JMenuHelpers class

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes the behavior described in issue #1611 - for some reason the 'days since maintenance' count was being reset every day, rather than every maintenance check.
> #1611: just reset maintenance when we do maintenance

- MekHQ/src/mekhq/campaign/personnel/Person.java
This is a bug I found when asked about a workaround as part of #1612 . Prisoners were supposed to be able to marry whomever (specifically that a prisoner can marry anyone, but nobody else can marry a prisoner), however they are currently only able to marry other prisoners.
> Prisoners Marriage Logic Fix

- MekHQ/src/mekhq/campaign/personnel/Person.java
> 1632: Fixing ternary mistake that makes all random marriages same sex

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This fixes an issue where I flipped the sides of a ternary, which then displays the wrong values.
> Fixing Activate/Mothball Display Text

- MekHQ/src/mekhq/MekHqXmlUtil.java
This is a utility add for LocalDate methods for saving and parsing from file (this is originally sixlevelvariables' code). This will be used to properly implement LocalDate in MekHQ, starting with a PR to fix the implementation in Person and FormerSpouses.
> XML Utility: Adding LocalDate Save/Load Methods

- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
This fixes a few issues I noticed when working on #1636, notably that the display did not show the spaces as expected which forced words together.
> Fixing Popup Display Text Spacing Issues in DataLoadingDialog

- MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
This small change fixes a behavior where any forces assigned to most AtB scenarios (especially ones generated from templates) as reinforcements would default to ANY as a deployment zone, which makes very little sense.
> Fix undesirable deployment zone for reinforcements

- MekHQ/src/mekhq/campaign/personnel/Person.java
Sometimes a unit would be marked as mothballing but the tech would be cleared, leading to an NPE when checking if the IDs matched. This switches the logic to only search the units the person is tech'ing.
> Avoid NPE in Person::isMothballing

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/model/DocTableModel.java
- MekHQ/src/mekhq/gui/model/PatientTableModel.java
- MekHQ/src/mekhq/gui/model/TechTableModel.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
The cognitive burden of reading Person.java is getting Too Damn High. This PR simply moves five UI-only descriptor methods to their respective UI classes. A 2.3% win, but a win nonetheless.
> Remove UI-only code from Person

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/unittests/mekhq/campaign/personnel/PersonTest.java
This fixes a bug introduced in the refactoring commit d59fa1f85b3fb673cbb0b766be34a28409c24bc7. The old code set `originalUnitTech` to 0 before adding either 2 for clan tech or using postfix increment for IS2. The new code did not reset `originalUnitTech` to 0.
> Do not add TECH_CLAN to originalUnitTech

- MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
Map was "leaking" Person entities over time as it was never cleared.
> Remove unused map in PersonnelMarket

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes a recursion issue where Clanners with a single given name would NPE out on migration, ensures a person does not have a null given name, and simplifies and cleans up the code for name migration.
> Fixing Clan Name Migration

- MekHQ/src/mekhq/Utilities.java
Fixes an undocumented bug where the available refit dialog won't appear due to an index out of bounds exception. This happens when refitting squads that have models with different numbers of troopers, such as IS/WoB versions of the Phalanx.
> Change refit model weight calculation to work with BA

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This PR fixes an issue which prevents the personnel tab from displaying when one of the units involved has been assigned to a scenario but has somehow not been properly unassigned.
> fix phantom scenario assignment npe

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This fixes #1691, and implements fixes for a few missing roles in the sorting for the Personnel Tab.
> 1691: Personnel are now filtered by primary and secondary roles in the Personnel Tab

- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
The change to save the original part quality while items are cloned during a refit.
This fixes #1725
> 1725: Refit does not save original part quality when part is cloned

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
This is a little performance saver for calls to createScenariosForNewWeek, based on the new active contract tracing added in #1695
> Implement Quick Skip for createScenariosForNewWeek

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This fixes #1735, fixes #1736, and fixes #1737. The last was not the same as the middle, but were all directly related in terms of how to fix them.
It also fixes another bug with editing units, whereby the underlying entity would be damaged but the parts were not.
> 1735-1737: Fixing how units are edited in Scenario Resolution Wizard

- MekHQ/resources/mekhq/resources/ChooseMulFilesDialog.properties
- MekHQ/src/mekhq/gui/dialog/ChooseMulFilesDialog.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This adds mnemonics to these two files, and fixes #1733.
Whitespace differences off, especially for the MUL Files dialog. Everything was shifted off by a space, so I fixed it back to our regular spacing. I've also fixed a nasty ordering mistake for the close vs ok buttons, as that actually let to an issue while testing this, and cleaned up the latter dialog.
> 1733: Scenario Resolution Wizard and MUL Selection Dialog Mnemonics

- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/personnel/generator/SingleSpecialAbilityGenerator.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
A recent MegaMek PR changed the Sandblaster SPA so that it points to a particular weapon, but caused a bunch of issues in MekHQ with personnel generation, in multiple areas. This PR fixes those errors, and also limits randomly generated personnel with Sandblaster to just weapons that can potentially use cluster tables.
> fix sandblaster issues

- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/WarehouseTab.java
I noticed that the acquisition tables were not properly refreshing when you moved to a new day and were on the same tab for both the warehouse and hangar. They should be counting down the days until the next procurement check. The problem seemed to be that the refresh method in each tab for the acquisition table were not part of the refreshAll() method.
> acquisition tables are not refreshing on new day

- MekHQ/src/mekhq/IconPackage.java
This fixes the missing final, which enabled writing on the IconPackage constants for layered force icons.
> Fixing IconPackage Constants Access

- MekHQ/resources/mekhq/resources/AdvanceDaysDialog.properties
- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
These are two little changes, the first of which is advance to next year (just a nice thing to have), and the other is increasing the limit of days to advance at a time to 10 years. This latter change is mostly because it is useful during testing, although I can see a use case of waiting for the next generation in a 
dynastic mercenary company that has funds but does not have the dynasts.
> Advance Days: Increasing Day Count Limit and Adding Advance to Next Year

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelStatus.java
This cleans up how PersonnelStatus is loaded, and was something I noticed while merging stories today.
> Changing PersonnelStatus to use ParseFromString

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This fixes #1631.
I did a bunch of whitespace changes and some light refactoring in the area, so I'd recommend turning off whitespace differences. The actual fix is the last commit.
> 1631: Regenerating Forces for AtB Dynamic Scenarios now Resets Attached Bot Forces

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This removes a temporary method to get a standard display format and replaces it with a call to CampaignOptions::getDisplayDateFormat
> Removing inline display date from Person

- ISSUE_TEMPLATE.md
This is because a significant portion of the MekHQ bug reports require asking for this file given that the logger does not always redirect to the MekHQ file.
> Adding MegaMekLog.txt to standard list of files for MekHQ

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
This fixes a bug I made when implementing this, namely that it will be passed the date based on the display format but parse always using the ISO-8601 format.
> Fixing the date parsing when removing an award

- MekHQ/src/mekhq/gui/GuiTabType.java
This fixes a dumb mistake I made, namely a double space typo. That is an accessibility issue, so I'm fixing it here.
This PR is entirely whitespace changes.
> Fixing GuiTabType Accessibility Spacing Issue

- MekHQ/data/universe/defaultspa.xml
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java
This PR adds two new unofficial special abilities for techs:
* Engineer: subtract 2 from all refit rolls
* Mr/Ms Fix-It: ignore the first point of penalty for repairing or maintaining poor quality parts
In addition to the two new abilities, I also refactored a new method `getQualityMods` in Parts, because both `getAllMods` and `getAllModsforMaintenance` need to add those quality modifiers and it was being done slightly differently in each case.
I have not added the new abilities to any of our predefined game option sets because I am planning to be update all of those with our existing abilities in a separate PR.
> Two new unofficial special abilities for techs

- MekHQ/data/universe/defaultspa.xml
- MekHQ/mmconf/mhqPresets/CamOps.xml
- MekHQ/mmconf/mhqPresets/DefaultTotalWarfare.xml
- MekHQ/mmconf/mhqPresets/SimpleOptions.xml
- MekHQ/mmconf/mhqPresets/TaharqaMW2ish.xml
This PR updates all of the presets that ship with MHQ to include some SPAs that have not been included. This varied from preset to preset, but in all cases it included Zweihander and all of the options for tech special abilities except clan tech knowledge. I have also set default values for all of these special abilities in the defaultspa.xml file. I have tried to be consistent with the existing point ranges and weights for all presets.
> Updates to special abilities in all presets

- MekHQ/src/mekhq/gui/RepairTab.java
The "last repair check" Jlabel in the repair bay, added in PR #1776, is occasionally resizing rather than wrapping text, causing it to take up too much space. To fix this, I changed all three vertical panels in the repair bay to use a gridlayout rather than gridbaglayout so that they all take up the same amount of relative space and won't resize based on the changes to other components. In my tests, its working great now.
> use grid layout for repair tab main panels

- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
This PR fixes #1803. The dialog was trying to append `fetchAndClearNewReports()` from Campaign, but this only adds new reports added since the `campaign.newDay()`. There are none of these because the user is advancing through the days without doing anything. To get the reports at the start of the day, you use `getCurrentReportHTML()` in Campaign. This corrects for that.
> Fix advance multiple days reports not showing

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Fix for an annoying issue where 'customize in mek lab...' was going to the infirmary instead.
> customize in mek lab now goes to mek lab

- MekHQ/src/mekhq/campaign/parts/Part.java
This is to make it obvious the value is transient and not saved to file.
> Marking usedForRefitPlanning as transient

- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
The code attempting to log the error gracefully was throwing an NPE by attempting to access the short name property of a non-existent object.
The player still won't get any contracts generated, but that's a wider issue beyond the scope of a simple bug fix.
Addresses #1828
> fix NPE when generating contracts for suddenly extinct faction

- MekHQ/src/mekhq/gui/CampaignGUI.java
When picking techs to carry out refits, it's very annoying to have to search through a large list looking for the right type of tech. Now, it's ordered by tech type (mech/aero/ba/etc), then skill in descending order.
> order refit techs by role, then ascending skill

- MekHQ/src/mekhq/campaign/force/Force.java
> 1822: Making the default Force Icon into a transparent background

- MekHQ/src/mekhq/campaign/universe/Planet.java
This fixes MekHQ failing to load a campaign because of the transient property.
> Fixing Duplicate Transient Campaign Run Failure

- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
The "campaign subset export" wizard's personnel section is basically unusable for larger units because personnel are sorted more or less in the order in which they were loaded into memory.  This PR changes that behavior so that they're now sorted by role.
> order personnel for campaign subset export by role

- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes a return oddity for both of the Time in * functions, something I've found while tracing the Time in Rank errors I've been hearing about.
> Person Time in * as String Return Fix

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/enums/PrisonerStatus.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
This fixes #1847 by removing the same prisoner status check and moving it to the PersonnelTabMouseAdapter.
This ensures that both prisoner status and the personnel logging is done properly.
> 1847: Fixing Time in Service

- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/personnel/Award.java
- MekHQ/src/mekhq/campaign/personnel/FormerSpouse.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/universe/NewsItem.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/FileDialogs.java
- MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
- MekHQ/src/mekhq/gui/dialog/NewPlanetaryEventDialog.java
- MekHQ/src/mekhq/gui/dialog/ShipSearchDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/src/mekhq/service/AutosaveService.java
This switches Ship Search and Filenames to LocalDate, and moves the format for filenames into the Constants file. It also refactors the majority of LocalDate display formats back to Campaign Options to improve readability.
> LocalDate: Ship Search and Filename Date Switchover

- MekHQ/src/mekhq/IconPackage.java
- MekHQ/src/mekhq/gui/dialog/UnitSelectorDialog.java
- MekHQ/src/mekhq/gui/view/UnitViewPanel.java
A namespace in MegaMek was moved, and this causes MekHQ to be unable to compile. This PR addresses the compilation errors.
> fix compilation errors due to damage overlay PR

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes the Retirement Nag popup calculation due to a mistake in the modified logic. This was pointed out in the review but I misunderstood why, and didn't notice the functionality change until today.
> Fixing the Retirement Nag Popup Calculcation

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/Part.java
This implements the MekHqXmlUtil functions fully in writeToXML and implements indent based on a constant value instead of being specified numbers
The offsets have been annoying me for a while, so I've fixed them here.
Review with whitespace differences off, as I fixed what was left of the primary formatting issues.
> Campaign writeToXml: Fixing Output Spacing Issues

- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
Two changes in this one:
First, the campaign export wizard now tries to re-construct force structure for exported units. So, if a mech was in Alpha Company/Fire Lance in the source campaign, it'll either create that force structure in the destination or place the mech there if it exists already.
Second, the personnel selection list in the export wizard displays the call sign of a person in addition to the role.
> retain force structure in destination campaign

- build.gradle
This PR adds the jitpack maven repository for Megamek's SerialKiller library dependency in [#2132](https://github.com/MegaMek/megamek/pull/2132). After adding it, I was able to build with the `assembleDist` task and run the game, and dangerous Java object payloads were correctly blocked by SerialKiller.
> Add jitpack for serialkiller mm dependency

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
This fixes a NPE relating to fill transports if it is called with a null or empty list. This bug was raised on Discord.
> Fixing bug with fill transports

- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
This fixes #1829. Campaign::newDay triggers a DayEndingEvent that is then handled by CampaignGUI::handleDayEnding to force the overdue loans, Retirement Defections, Yearly Retirements, Short Maintenance, Short Deployments, and Outstanding Scenarios. Therefore the checks are not required, and this fixes issues where they can show up twice.
> 1829: Fixing Duplicated Nags in AdvanceDaysDialog

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
Took a while, but this fixes an observed and reported issue where units being customized would not begin refit once all parts had arrived. Turns out that the "is there enough of the right type of ammo present" check wasn't working (it would attempt to load an ammo bin, and the call would immediately fail because the bin wasn't attached to a unit yet).
> fix refits involving ammo-based weapons

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
This allows units given to other players' control to get credits for in-mission kills, by removing the "is the unit owned by the MekHQ player" check. Has a MegaMek companion PR.
Fixes #1962
> credit player units given to others with kills

- MekHQ/src/mekhq/campaign/personnel/familyTree/Genealogy.java
This fixes a bug reported on the bg.battletech forum whereby siblings are duplicated.
> Fixing Duplicated Siblings

- MekHQ/src/mekhq/campaign/CampaignOptions.java
This fixes #1982 by fixing the return for any unassigned lances.
> 1982: Fixing AtBBattleChance for unassigned lances

- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
This fixes a minor display oddity for an initial report in a new campaign that I noticed while testing #1997
> Fixing Incorrect Initial Report Date Format

- MekHQ/data/mechfiles/vehicles/TRO Vehicle Annex/Tracked/RRV.blk
- MekHQ/resources/mekhq/resources/SmallSVAmmoSwapDialog.properties
- MekHQ/src/mekhq/campaign/parts/InfantryAmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/equipment/InfantryAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingInfantryAmmoBin.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/SmallSVAmmoSwapDialog.java
Adds InfantryAmmoBin and InfantryAmmoStorage for handling small support vehicle ammo repairs and reloading. Each weapon has at least one ammo bin. If it can use inferno ammo it has two. There is also a dialog for redistributing space between standard and inferno ammo.
Depends on MegaMek/megamek#2219.
> Parts for small support vehicle ammo tracking

- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
This fixes a few exceptions I ran into while working on another project - sometimes, a unit without weapons rolls a "Weapon Specialization" SPA, and sometimes, a unit gets generated without a crew or the options data structure isn't initialized.
Now, instead of failing the whole process, we just don't generate an SPA and move on.
> crew skill upgrader bulletproofing

- MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
This fixes #2001 and two object comparison issues.
I moved Unassigned to the bottom of the list instead of the top, but missed the adjustment here.
> 2001: Fixing Lance Ordinal Comparison

- MekHQ/src/mekhq/campaign/parts/Refit.java
Fixes #1252 
https://github.com/MegaMek/mekhq/blob/8dc44e93b4d772cf54cb94263616810cc3b1f34c/MekHQ/src/mekhq/campaign/parts/Refit.java#L499-L502
Line 501 above causes the size of target computers (and possibly other variable equipment) to be recalculated based on the old unit's weapon config. This can cause a mismatch when checking the warehouse for a correctly-sized replacement. (It's corrected back later when the actual refit is done, so the only issue here is that new parts are ordered when spares are available.)
I can't see any reason why nPart would need to be assigned to oldUnit here, so I think the comment in line 500 is correct.
> On refit don't temporarily add new parts to old unit

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This fixes #2032 .
The issue is that I missed a line saving the new options object to the Campaign, which was required for overwrite prevention.
> 2032: Fixing Campaign Options Save following Preset Load

- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/LootDialog.java
- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
This fixes the MekHQUnitSelectorDialog displaying twice, and removes the setVisible from its constructor.
> Fixing duplicated MekHQUnitSelectorDialog

- MekHQ/src/mekhq/campaign/parts/Refit.java
First commit fixes the way untracked/integrated heat sinks are calculated for Aero Fighters - should be based on engine type (not engine size/rating)
Second commit make heat sink cleanup for Aero Fighters more careful not to strip valid heat sinks.
> Aero Fighter refit heat sink tracking improvements

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
This fixes a minor issue whereby Campaign::personUpdated method triggers a PersonChangedEvent then the code triggers a second one.
Also, I'm not a fan of how Campaign::personUpdated works nor where it is located... but that's for future development.
> Fixing Doubled PersonChangedEvents

- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Per the documentation, JTree::getSelectionPaths may return `null` if nothing is selected. Fixes:
```
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
at mekhq.gui.adapter.TOEMouseAdapter.maybeShowPopup(TOEMouseAdapter.java:626)
at mekhq.gui.adapter.TOEMouseAdapter.mouseReleased(TOEMouseAdapter.java:604)
at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
at java.desktop/java.awt.Component.processMouseEvent(Component.java:6631)
at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
...
```
> Fix NPE when getSelectionPaths is null in TOEMouseAdapter

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
This fixes #2059 by fixing the experience determination, and swaps the method used to calculate the Campaign Ops Unit Rating to the proper getAverageExperience.
> 2059: Fixing Incorrect Experience Calculation Method

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Null entities in the list are not handled and cause NPEs. This prevents that from occurring.
> Preventing null entities in AtBScenario

- MekHQ/resources/mekhq/resources/Campaign.properties
- MekHQ/src/mekhq/campaign/Campaign.java
This quick feature helps out with the new Command Center structured MekHQ. Now as AtB scenarios are added you receive daily log entries, along with daily log entries the day of a scenario (along with the force deployed if any).
> Add daily report entries for AtB scenarios

- MekHQ/src/mekhq/campaign/parts/StructuralIntegrity.java
- MekHQ/src/mekhq/campaign/parts/TankLocation.java
This PR fixes 4 issues when refitting:
1) when customizing an Aero, the Mek Lab shows that a Class A change has been made, before actually changing anything
2) customize/refitting an Aero unit causes "null missing part for Structural Integrity during refit calculations" repeatedly in the error log
3) when refitting an Aero, damage to internals is not preserved
4) when refitting a Tank, damage to internals is not preserved
The first commit fixes the first two issues, the second commit fixes the last two issues.
> Improved refit handling of internals for Aeros and Tanks

- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
Campaign Ops dropships operation costs due to training munition costs were in the millions - out of line with the examples in the published source book.  The calculations in the base class are correct, and have been used instead of the override that was multiplying for the size of the ammo bay twice.
Note: this fixes the issue, but unclear why there was a size multiplier given that getCurrentShots() / getShotsPerTon() was already giving a 2x cost for a 2 ton bay.
(Note, this is a small bug I've had fixed locally for a while, using as a sample for github contribution workflow before getting larger patches together.)
To verify, compare the patched and unpatched values for a Union-X in the hangar, by right clicking and choosing "Show Monthly Supply Cost Report".  Screenshot of fixed version …
> Dev vulpzor campaign ops dropship maintenance cost fix

- MekHQ/src/mekhq/gui/RepairTab.java
This fixes #2017 by remembering the focused unit when refreshing the serviceable units table.
> Issue #2017: Keep focus on unit during repairs

- MekHQ/src/mekhq/campaign/parts/Refit.java
If an ammo bin has zero shots per ton then the refit cost calculation code will throw a `NumberFormatException` due to `NaN` being passed to `Money.of`. This is a "fix" for the exception seen in #2066, but may not be a fix in the sense that the Refit calculation logic does not have any handling for `InfantryAmmoBin`s (and probably should, a la `LargeCraftAmmoBin`s).
> Issue #2066: Do not add zero or NaN costs for ammo during Refits

- MekHQ/src/mekhq/MekHQOptions.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
This PR ensures we have a non-null date in the MekHQ Options, as non-null date for a scenario, and that the new AtB scenario message only occurs on new AtB scenarios and not also on re-added AtB scenarios.
> Fixing Scenario Template Date NPEs

- MekHQ/src/mekhq/campaign/parts/Part.java
This fixes #1967 by saving a part's repair reservation to the campaign XML. I was unable to replicate the bug in a single sitting, but if you save and reload a campaign you'll see this occurs.
> Bug: Save part repair reservation if present #1967

- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/MekHqColors.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
- MekHQ/src/mekhq/gui/sorter/UnitStatusSorter.java
This fixes #1376 by standardizing the Hangar Tab Colours for Unmaintained and Uncrewed Units and adding them for Unmaintained Units.
Here's a sample of every state and their individual colours.
> 1376: Hangar Tab Line Colours For Unmaintained and Uncrewed Units

- MekHQ/src/mekhq/campaign/parts/MissingEnginePart.java
When we create a new `EnginePart` from a `MissingEnginePart` we were using heuristics to determine the appropriate engine flags for MegaMek. This is unnecessary as the `MissingEnginePart` has access to the actual flags for the missing engine (courtesy of `engine.getFlags()`. I can't figure out why we didn't just copy the flags in the first place, as the code commit history for that area does not do a good job of explaining those changes.
This fixes #2089.
> Issue #2089: fix procuring vehicle engines from the parts store

- MekHQ/src/mekhq/AtBGameThread.java
This swaps the order that the bot sends its information and the camo information, thereby removing the camo change refresh at the end of bot load.
This is something that has annoyed me for a while, where the bot loads using a separate camo before swapping over to the correct camo at the end of the load.
> AtB Bot Camo Load Swapover

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This fixes one of my annoyances with the Personnel Table popup menu, namely that this shows when it should not. This changes it so that it will only show if there are possible choices.
> Personnel Table: Hide Assign to Unit 

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/BayDoor.java
- MekHQ/src/mekhq/campaign/parts/Cubicle.java
- MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/MissingBayDoor.java
- MekHQ/src/mekhq/campaign/parts/MissingCubicle.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/TransportBayPart.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
I have never reliably reproduced the issues seen with child parts (such as bay doors, etc), but have always disliked our usage of IDs instead of strong references. MekHQ plays loose with IDs in order to aggregate spare parts and I'm not confident it isn't a cause of these problems.
I'm only confident this will resolve the class of errors where the part ID changed but the child part IDs were not updated.
> Switch to strong references instead of IDs for child parts

- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
This fixes something I missed while doing the initial Unit Selector PR, namely that MekHQ doesn't display the unit sprite
The code is not the best, but... that shall be improved in the near future as I continue my rework of portraits and camo.
> Fixing Missing Unit Selector Unit Sprite in MekHQ

- MekHQ/src/mekhq/campaign/parts/Part.java
While looking into some perf issues with large campaigns, I noticed that we serialize a boatload of details for Parts that are simply default values. This PR reduces the size of the `<parts>` section in a CPNX by about 30%. The overall size of a CPNX accounts for just about a quarter of the load time once you reach ~100mb.
> Reduce the size of a Part's XML by ~30%

- MekHQ/src/mekhq/campaign/parts/Refit.java
This is a fix for main issue reported in #1079, that hip and should damage were being cleared on a refit.
> Preserve hip and shoulder damage on a refit

- MekHQ/src/mekhq/gui/model/LootTableModel.java
This fixes a minor capitalization issue and adds some tooltips to the table at the same time.
To review: Whitespace differences off, and the first is a code cleanup plus spelling fix on the money column name, the second adds the tooltips I found as missing when fixing the capitalization.
> Loot Table: Fixing Money Capitalization and Adding Basic Unit/Part Tooltips

- MekHQ/mmconf/mhqPresets/AgainstTheBot.xml
- MekHQ/mmconf/mhqPresets/CamOps.xml
- MekHQ/mmconf/mhqPresets/DefaultTotalWarfare.xml
- MekHQ/mmconf/mhqPresets/SimpleOptions.xml
- MekHQ/mmconf/mhqPresets/TaharqaMW2ish.xml
This updates the presets following the removal of more than a few values. This is primarily to remove the automigration of what are now MekHQOptions values on preset load.
> Campaign Preset Update

- MekHQ/src/mekhq/campaign/parts/Refit.java
Fixes #1970 
As per discussion with @neoancient in the contributors channel on Slack, redoing this on the MM side to avoid adding the BA ECM part would be a lot of work. Instead, this PR implements a workaround by removing the BA ECM early in a refit to avoid overweight issues.
> Workaround for single hex ecm causing smallcraft to be overweight

- MekHQ/src/mekhq/campaign/parts/Refit.java
This is a fix for secondary issue reported in #1079, that during a refit moving a part between locations took no time.
> Add refit time for moving a part between locations

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
This PR is nasty and is not going to be fun to review...but at this point I am happy with just about all of the part ID issues I have been made aware of in the past. Basically: we're not going to reference parts by ID anywhere other than the CPNX file. Everywhere else should be using an actual reference to a Part object. That's about as close to avoiding part ID issues as you can get.
This is a draft because I'm not 100% on the refit code, but close.
> Avoid part ID references in Refits and elsewhere

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/gui/dialog/BombsDialog.java
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
In large campaigns the number of spare parts is typically overwhelming (I've seen it as high as 100k). In many areas we go ahead and make a huge copy of the array, plus the iteration costs. This PR adds forEachSparePart to improve cases where we're just walking the collection. This PR also switches to streamSpareParts where appropriate. In both cases the number of allocations and iterations is markedly reduced.
> Improve performance of searching for spare parts

- MekHQ/resources/mekhq/resources/MassRepair.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/service/MassRepairConfiguredOptions.java
- MekHQ/src/mekhq/service/MassRepairService.java
This fixes #442 and implements the basis of a refresh system.
As part of this I discovered we use type in two ways for MassRepairOptions, for two arrays that do not align. That will be my next fix.
> 442: Enable/Disable MRMS Repair and Salvage Portions

- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
This fixes #1723. The first four commits are code cleanup and refactoring, the fifth adds the force icon for the graphical hangar display, and the sixth is the bugfix.
> 1723: Fixing Missing Personnel and Hangar Tab Selection Highlights

- MekHQ/resources/mekhq/resources/Rating.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/rating/UnitRatingMethod.java
- MekHQ/src/mekhq/gui/CommandCenterTab.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This merges the useUnitRating into the UnitRatingMethod enum as a disabled case. The idea to do so was brought up based on the confusing method name of useDragoonsRating in a previous PR of mine.
I also fixed the command center hide/refresh for unit rating upon campaign options change.
> UnitRatingMethod: Add Disabled Case

- MekHQ/resources/mekhq/resources/GUIEnums.properties
- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/MekHQOptions.java
- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
- MekHQ/src/mekhq/gui/enums/PersonnelFilter.java
- MekHQ/src/mekhq/gui/enums/PersonnelFilterStyle.java
This fixes #2159 part 3 by implementing a PersonnelFilterStyle enum that has standard, individual role, and all options. I also added a bugfix for the filters being used ignoring the individual role option. Now, all pull from the selected PersonnelFilterStyle.
> 2159: Personnel Filter Style for All Options

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/unittests/mekhq/campaign/WarehouseTest.java
- MekHQ/unittests/mekhq/campaign/parts/PartTest.java
This cleans up various bits of Part logic that I noticed during my last few PRs. I targeted three areas:
1. Duplicative or erroneous events.
2. Correctness (e.g. removing the non-idempotent Part::checkArrival).
3. Ease of use / style (e.g. renaming arguments or refactoring method internals).
I added tests for most of the changes.
> Clean up various pieces of part logic and add tests

- .github/workflows/ci.yml
This should display our unit test results as part of the run rather than having to pull an artifact to see what failed.
> Add Unit Tests to CI results

- .github/workflows/ci.yml
Reverts MegaMek/mekhq#2178 due to GitHub Actions bug.
> Revert "Add Unit Tests to CI results"

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
When we read in a CPNX file, if the personnel salary array was ever smaller than what your current version of MekHQ expects, anyone with a role higher than your last salary in the CPNX is perpetually zero. This ensures we always have the correct *minimum* number of salary entries in the deserialized `CampaignOptions`, fixing #2188.
> Issue #2188: Cannot assign salary to LAM Pilots or Vehicle Crew loading older CPNX files

- MekHQ/src/mekhq/campaign/market/UnitMarket.java
This fixes #2193 and swaps to using the MekHQ XML Util.
> 2193: Unit Market: Units No Longer Reset to Open Market upon load 

- MekHQ/data/universe/ranks.xml
- MekHQ/src/mekhq/campaign/personnel/Ranks.java
Fixes #785. Adds 2nd Star League rank set, edits default Star League rank set to remove two lieutenants, add warrant, per FM: SLDF
> Issue #785 SLDF Ranks are Wrong

- MekHQ/src/mekhq/gui/BasicInfo.java
- MekHQ/src/mekhq/gui/model/CrewListModel.java
This fixes #564 by fixing the scaling size, namely changing it to be 54 instead of 58. Further, I swapped Basic Info to use AbstractIcon for portraits and cleaned up the Force icon code in this location as part of the continuing AbstractIcon changes.
The changes to CrewListModel are included in the first commit by accident. They were part of a version that I determined was not ready to be used. However, they do clean up the code and would be otherwise included in the near future, so I'm opening this with them.
> 564: AbstractIcon: Fixing Basic Info Portrait Scaling

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
This reverts the change in 0a593003cbefd4dc87de41013e6ea0b6c2e95e3f and adds a test to confirm the deserialization ctor for AmmoStorage works going forward.
Fixes #2213
> Issue #2213: Fix disasterous bug in AmmoStorage::ctor

- .github/workflows/ci.yml
- MekHQ/build.gradle
This adds a Code Coverage report to our test Gradle task. I'll try getting this roped in via the CodeCov app.
> Add JaCoCo code coverage plugin to test Gradle task

- MekHQ/src/mekhq/campaign/parts/Refit.java
Refactoring to use `getCampaign` introduced an error where two places should have been using `oldUnit.getCampaign`. This fixes #2217. This fixes #2219.
> Issue #2217 #2219: Cannot save Campaign with Refits and cannot start new Refits

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/InfantryAmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/InfantryAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingInfantryAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/BombsDialog.java
- MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
- MekHQ/unittests/mekhq/campaign/parts/InfantryAmmoStorageTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/AmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/BattleArmorAmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/InfantryAmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/LargeCraftAmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingAmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingInfantryAmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBinTest.java
This makes use of a Java feature whereby an override can use a more-derived type in a return value. In this case `AmmoBin` and `AmmoStorage` only support `AmmoType` as their `EquipmentType`, so we reflect that in their constructors and `getType` overloads.
This has two effects:
1. The code is more straightforward.
2. Errors caused by equipment mismatches are at the point of assignment rather than point of usage making tracing easier.
> Switch to AmmoType when more specific type is available

- MekHQ/src/mekhq/MHQStaticDirectoryManager.java
- MekHQ/src/mekhq/io/AwardFileFactory.java
This fixes #2220, but will need a revisit after the Java 11 migration as it may be one of the png features implemented in Java 11.
> 2220: Implementing AwardFileFactory to handle loading pngs that aren't handled by Toolkit

- MekHQ/src/mekhq/campaign/finances/Money.java
- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
We have seen more than a handful of null exceptions in `Money::plus`, most of the calling code however, has been fixed. There are a few places that may or may not have been fixed, but I couldn't find any issues with `Part::getStickerPrice` in my search today.
Instead, I've gone ahead and null protected `Money::plus` and `Money::minus`, and ensured that `BattleArmorSuit` does not return a `null` value for `alternateCost`. This fixes #2166, albeit in a defensive way we may not need anymore.
> Issue #2166: NRE in Money::plus/Money::minus

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/InfantryAmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
Adds basic AmmoStorage tests and protects against some basic problems found during testing.
TODO:
> Add basic AmmoStorage tests

- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/unittests/mekhq/campaign/parts/AmmoStorageTest.java
Certain BattleArmor ammos (e.g. Micro Bomb Ammo, Clan Torpedo/LRM5 Ammo) do not state how many kg per shot they are, which `PartsStore` required to calculate the number of shots per ton (and subsequent cost). This led to a situation where you couldn't afford to buy the ammo, but if you GM added it you'd have INT_MAX shots available for your BattleArmor. Sell it back and you can print money!
This "fixes" the bug on the MHQ side by only recalculating shots per ton if it is BattleArmor ammo and `AmmoType::getKgPerShot()` is greater than zero. A more appropriate fix would be to update the kg per shot on the MM side for these ammo types.
> Fix bug where PartsStore may list INT_MAX as cost and tons for BA ammo

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
The AtB Contract Market does not enjoy being at the bounds of playable data. This PR just adds a few checks to have it more gracefully fail instead of throwing exceptions and blocking the campaign's forward progress. This sort of fixes #2248 at a wishy-washy level.
> Issue #2248: Fix various ContractMarket exceptions when operating at the bounds of MekHQ data

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/gui/StartUpGUI.java
This fixes a bug raised on the BattleTech forums, namely that load last save only works for .cpnx files. Further, it only worked on the base campaign directory, not the preference campaign directory, which I've also fixed.
> Fixing Load Last Save for .cpnx.gz files

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/unittests/mekhq/campaign/parts/MissingPartTest.java
When we reserved a part for overnight work, we would give back an extra part in two possible situations:
1. The work was for a missing part.
2. The work on a missing part failed, destroying the part.
In both of the cases the cause is simple: we were not checking if the part had any quantity left before finding a spare and incrementing its quantity.
This fixes #2231 by doing two things:
1. Not manually finding spares when fixing/reserving and incrementing their quantities.
2. Only giving parts back to the Quartermaster if they have a non-zero quantity.
a. The Quartermaster class actually handles zero quantities, but this seemed like the more defensive solution.
I've also added tests for the reservation logic in MissingPart.
> Issue #2231: Don't give back free parts when fixing a missing part

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
This fixes #2254. The first commit improves the code, especially given getMission is not just a getter but actually has some underlying processing, while the second is the actual fix (just a missed call to Contract::addSalvageByUnit
> 2254: Ransomed Unit now properly adds to Total Value Salvaged

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/Warehouse.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/parts/BayDoor.java
- MekHQ/src/mekhq/campaign/parts/Cubicle.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/unittests/mekhq/campaign/WarehouseTest.java
This fixes _the result of_ an interesting bug, namely that some Part-Child trees are actually cyclic graphs. I don't know why, just that it seems to happen. We've seen it with `getStickerPrice` on `BattleArmorSuit` and added logic to avoid following the cycles.
This fixes the symptoms of #2255 by:
1. Only recursing to remove child parts if we removed the parent part.
2. Breaking the parent-child relationship before we remove the child part.
This also cleans up CampaignXmlParser by having it use the basic logic within Warehouse to consolidate parts. Basically, after we post-process the parts and reach a stable set of parts to keep, we just load them into a brand new warehouse, which will merge any spares. The campaign then uses this new cleaned up warehouse, and we keep one set of tested …
> Issues #2255 #2258: Fix Warehouse::removePart StackOverflowException with child parts

- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Removes usage of XPath/XQuery to improves performance of CPNX loads with transport linkages in AtB scenarios. A 15mb CPNX went from 13 secs to load transport linkages, to 4 secs to load the entire CPNX.
> Remove XPath/XQuery usage from AtBScenario CPNX load

- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
While research #1720 I noticed that _GM Acquire Instantly_ only found one of the part. This has it find the exact quantity that were missing.
> Bug: Ensure GM Acquire Instantly acquires the correct quantity

- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
This fixes issues where you get strange stack traces in the log that just report a failure in the DataLoadingDialog.
> When loading Campaigns, break out exception handling properly from SwingWorker

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
When we update the Random Skill Prefs there is logic to use any pre-existing options on a Campaign. However, once the Campaign is loaded the options are never saved back to the Campaign. Changes to the options made during the Campaign are persisted, but only because they are the same reference. This PR simply assigns the Campaign's `RandomSkillPreferences` property every time the options dialog updates the values, fixing #2278.
> Issue #2278: Ensure skill prefs are saved to the campaign on creation

- MekHQ/src/mekhq/campaign/unit/actions/RestoreUnitAction.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/unittests/mekhq/campaign/unit/actions/RestoreUnitActionTest.java
GM Restore was not making a copy of the parts list before iterating to restore the unit. When it encountered a missing part, the new part would be added and the missing part would be removed. Because the iteration was by index, whichever part was immediately after the missing part in the original list would assume the index of the missing part and it would be skipped. This fixes #2280 (found during investigation of #2266).
- The fix is in https://github.com/MegaMek/mekhq/commit/56659f62978edac307cf7ac0bf629de73a739e21
- The second commit just pulls this out of UnitTableMouseAdapter and puts it into its own file.
- The third commit tests for this bug
> Issue #2280: GM Restore skips parts

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
I noticed this while debugging this weekend, but basically we were reloading mech data even if nothing changed on disk during CPNX load. Now, this nearly always hits the hot cache and does not make a big impact for most users. However, when I moved MHQ over to a spinning disk on my machine, this shaved about 10 seconds off CPNX load times. Folks should not expect that amount of speedup in general, as most users do not have a few hundred customs (from all of the CPNXs shared on bug reports).
> Don't reload unit data if nothing changed on disk when reading Campaigns

- MekHQ/src/mekhq/gui/enums/PersonnelFilter.java
This fixes #2287: Prisoner Filter now properly includes bondsmen.
> 2287: Prisoner Filter Should Include Bondsmen

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
This is the MHQ-side of https://github.com/MegaMek/megamek/pull/2509 , and MUST be merged at the same time.
> AbstractIcon: Null Protection for ImageIcons and Separating Dialogs out from the Choosers beneath

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/unittests/mekhq/campaign/mission/AtBContractTest.java
AtBContract does not serialize its `parentContract` member, causing subcontracts to be made into full contracts after a save-load cycle. This resolves the issue by using a dummy reference type during deserialization and then restoring the reference after the missions are loaded from the campaign file, fixing #2141.
> Issue #2141: Subcontracts don't reference parent contract after campaign load

- MekHQ/src/mekhq/campaign/Kill.java
- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This removes all migration code older than the 0.4X series. Right now the remaining migrations are pretty generous and captures all of the relevant migrations in that series. Migrations from 0.2.X or 0.3.X would require using 0.46.1, then moving to 0.48+.
This is also pretty conservative, in that I did not remove any of the code in the XML parser that "upgraded" certain types of old parts to their newer variants. I wasn't quite sure what versions they came from so I erred on the side of safety. Once 0.48 lands I'll work to remove those as well.
Going forward, I believe the strategy offered by @neoancient should be adopted: _we support upgrading from the N-1 stable version._ That would capture all of the relevant upgrades without much of a burden for folks lagging behind (for whatever …
> Remove old migration code

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
When I fixed a bug with contract generation hanging due to retries not being respected, I introduced another bug in contract generation. Now, when retry handling is done outside the `generateAtBContract` method, rather than `0` being sent for retries we send `1`, fixing #2283.
I'm still evaluating how (if at all) the current code can be unit tested, so that all three legs of contract generation get tested.
> Issue #2283: Ensure contracts are generated with the correct number of retries

- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
When consolidating logic shared between ammo bins and other equipment parts, I missed that we renamed `size` to `capacity` in `LargeCraftAmmoBin`. This causes campaigns older than 0.47.15 to be loaded with zero ton ammo bins that you cannot refill with ammo. This adds back support for loading LargeCraftAmmoBin's older than 0.47.15.
Fixes #2296.
Fixes #2299.
> Issues #2296 #2299: Support older campaign dropship and jumpship ammo bin sizes in XML file

- MekHQ/src/mekhq/gui/model/PersonnelEventLogModel.java
- MekHQ/src/mekhq/gui/model/PersonnelKillLogModel.java
This fixes a minor display issue whereby the dates are sometimes cut off.
> Fixing Log Display Spacing

- MekHQ/resources/mekhq/resources/ScenarioTableModel.properties
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/ScenarioTableMouseAdapter.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
This fixes #2270.
The first commit cleans up the scenario table mouse adapter and some minor related things in the Personnel and Scenario Tables, the second fixes the bug.
> 2270: Scenarios Respect Sort Order

- MekHQ/src/mekhq/gui/CommandCenterTab.java
- MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java
- MekHQ/src/mekhq/gui/model/ProcurementTableModel.java
When clearing the procurement list, a race condition occurs when other areas of the GUI are updating as the underlying list gets out of sync. Attempts at synchronizing the list did not meet with success, however, moving to a model where failure is expected we can defensively avoid these exceptions.
- Use `Optional<>` to describe data in the table
- Use `Optional<>::ifPresent` to take conditional actions
- Refactor `ProcumentTableMouseAdapter` to be cleaner and more maintainable
- Improve the campaign report message when you actually procure an item
Fixes #2310.
> Issue #2310: Avoid procurement popup exceptions due to race condition

- MekHQ/src/mekhq/campaign/Campaign.java
This filters out armor which has an unknown type, as seen on some infantry units in the campaign. There may be a more elegant solution to this, but I'm not exactly sure how these units ended up this way in the first place (by design? error?). You can't buy this armor, nor sell it, so it might as well not show up.
Fixes #2298.
> Issue #2298: Do not display unknown armor types in the Parts In Use report

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorEquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/HeatSink.java
- MekHQ/src/mekhq/campaign/parts/equipment/InfantryWeaponPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/JumpJet.java
- MekHQ/src/mekhq/campaign/parts/equipment/MASC.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingBattleArmorEquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingEquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingHeatSink.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingJumpJet.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingMASC.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/EquipmentPartTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/EquipmentUtilities.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingEquipmentPartTest.java
This PR adds EquipmentPart unit tests and fixes five bugs found along the way:
1. Variable weight sizes were not saved in some circumstances.
2. Weapon Bays weren't checked for destruction in remove. Well, they weren't before due to a bug, then removed as a "dead code path". This restores it.
3. LAM bomb bays always reported 60 minutes to fix, even when not broken.
4. MissingEquipmentPart's did not apply variable sized sticker prices correctly
5. MissingEquipmentPart did not override MissingPart::clone
TODO:
> Add EquipmentPart unit tests

- MekHQ/src/mekhq/campaign/parts/MissingAvionics.java
- MekHQ/src/mekhq/campaign/parts/MissingLandingGear.java
- MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/unittests/mekhq/campaign/parts/MissingAvionicsTest.java
- MekHQ/unittests/mekhq/campaign/parts/MissingLandingGearTest.java
- MekHQ/unittests/mekhq/campaign/parts/MissingMekLocationTest.java
This adds checks for Landing Gear and Avionics on LAMs when trying to fix missing parts. This fixes #2266.
I handle the following situations in this PR:
- Missing HD, RT, or LT: ensure that Avionics and Landing Gear (RT/LT only) have been removed first before replacing.
- Missing Avionics: ensure that the HD, RT, and LT are all present before replacing.
- Missing Landing Gear: ensure that the RT and LT are present before replacing.
TODO:
Missing RT and working Landing Gear:
Missing RT, missing Landing Gear, missing Avionics:
Replaced RT:
> Issue #2266: For LAMs check Landing Gear and Avionics when considering repairable slots

- MekHQ/src/mekhq/campaign/personnel/Person.java
When serializing `Person::idleMonths`, as a performance tweak we do not save the value if it is zero. This performance tweak is only applicable if the default value for the field is used (`0`), however, in this case the existing code defaulted the value to `-1`. This meant if you saved the campaign when there were zero idle months for your crew and reloaded the campaign, they would instead be at `-1` idle months from the default ctor during deserialization. They'd end up having to work an extra month for the same XP gain.
This removes the default value for `idleMonths`, leaving it to be set by the JVM. Fixes #2317.
> Issue #2317: Ensure Person::idleMonths defaults to 0

- MekHQ/src/mekhq/campaign/parts/MekLocation.java
- MekHQ/unittests/mekhq/campaign/parts/MekLocationTest.java
This is the follow-up to #2290 and restricts removing, salvaging, and scrapping the head and side torsos on LAMs until their Avionics and Landing Gear have been removed/salvaged/scrapped.
> Restrict removing, salvaging, or scrapping certain locations on LAMs

- MekHQ/src/mekhq/Utilities.java
- MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
- MekHQ/unittests/mekhq/campaign/unit/UnitTestUtilities.java
The logic to unscramble equipment numbers did not always handle the case where less equipment was found that before, and therefore could throw an NPE when referencing the underlying `Mounted`. This adds an explicit null check for the `Mounted`, and if null the part ends up in the "remaining" bin.
The symptom in this case was a unit with an ammo bin for equipment number 4, when instead the equipments are 0 through 2. Resolving the NPE in a naive fashion led to an additional ammo bin being added for the missing equipment. This PR avoids that case as well (you will end up with _two_ pieces of equipment: the invalid missing part and the replacement part).
Fixes #2325.
> Issue #2325: Do not throw NPE on missing equipment when unscrambling equipment numbers

- MekHQ/src/mekhq/campaign/parts/Refit.java
When we begin a custom refit, we save the file to disk and then load it back into the cache. However, if we encounter a fatal error at this point and cannot read the file we simply alert the user. The file itself is never removed from disk. This causes an odd situation where you are allowed to make a mech with the same name, but it won't save it back to disk and each attempt at fixing or recreating the mech will fail unless you rename it.
This changes the behavior of Refit::saveCustomization slightly, in that if the refit file cannot be read back by MHQ the file itself is deleted and the cache is refreshed. The downside is that we won't have the files to look back at to see why it failed on load. The upside is that users do not have to take manual actions to restore their campaign.
Fixes …
> Issue #2332: Delete refit file if unable to read it back when saving

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
In certain cases (refits, entity updates) we get out of sync parts and equipment numbers. In most cases this is _missing_ underlying equipment, but in some cases there is a different type of equipment at the mount. In other cases, there is also a part for that equipment.
This fixes this situation by changing how we unscramble equipment, adding steps 2 and 4 below:
1. Detect exactly correct equipment.
2. Detect approximately correct equipment (AmmoBins with munition type changes not reflected on the entity yet).
3. Find matches on different equipment numbers.
4. Break linkages between equipment parts and mounts if they are incorrect and a part already exists for the mount.
A second issue was noted, which is that AmmoBins were not removed if they had a missing mount due to the boolean …
> Issue #2341: Equipment on incorrect mounts is not fixed

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Found this while debugging another campaign issue, but basically we were not escaping the name of the custom before writing it to disk. This brings the code over from Refit and unblocks this problem for customs that may not have valid file names for certain operating systems.
> Issue #2342: Customs in CPNX with invalid file name chars do not save to disk

- MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
I misunderstood the usage of the `INACTIVE` tag when I wrote the random origin code, and this fixes it such that ComStar can be selected as a random origin. This also adds the `SPECIAL` tag to the reject list, otherwise "All Clans" shows up.
I believe this passes the bar of being simple enough for Stable.
> Don't skip ComStar as an origin faction

- MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
This fixes a logic bug where the Clans had a hard time getting anyone but Mercs to fight for them.
- Ensures the clans can always generate clan origins
- Ensures the clans don't automatically give a 50:50 split to Mercs
- Ensures the clans are lopsided to favoring their own clan as an origin
Fixes #2348.
This is a nice to have for 0.48.0, but not required.
> Issue #2348: Allow Clanner origins

- MekHQ/src/mekhq/campaign/parts/equipment/MissingEquipmentPart.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingHeatSinkTest.java
In `MissingEquipmentPart::isAcceptableReplacement` a check was made against the `EquipmentType` of the part, which up until recently appeared to work. This check is not acceptable on its own in practice, and can lead to various equipment parts being swapped out for their incorrect Java type (even _non_-`EquipmentPart`s).
Now, a check is made against the actual implementation of `EquipmentPart` when searching parts in the warehouse.
Fixes #2365.
> Issue #2365: MissingEquipmentParts should only be replaced with parts of the correct Java type

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
I'm not sure of the root cause, but it appears that sometimes we do not correctly update the AtB lance list in Campaign. On load we now verify that the AtB lance list contains _at least_ the lances that should be there.
Fixes #2358.
Loading the Campaign in question:
```
17:42:55,458 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Command Star to AtB list
17:42:55,458 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Scout Star to AtB list
17:42:55,458 WARN [mekhq.campaign.io.CampaignXmlParser] {SwingWorker-pool-1-thread-1} 
parse(), line 373 : Added missing Lance Striker Star to AtB list
17:42:55,459 WARN [mekhq.campaign.io.CampaignXmlParser] …
```
> Issue #2358: Add missing lances on CPNX load

- MekHQ/src/mekhq/campaign/parts/InfantryMotiveType.java
- MekHQ/src/mekhq/campaign/parts/MissingInfantryMotiveType.java
This PR fixes the save format for the mode, namely that it should be saving as an enum. This also removes eight year old migration code that ends up causing issues during parsing. I found this issue while working on some modernization and simplifications relating to the EntityMovementMode enum, but thought this issue should be fixed for stable.
> Infantry Motive Type File I/O Fixes

- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
> 2389: Fixing graphical NPE when not purchasing units in the unit selector dialog

- MekHQ/src/mekhq/campaign/personnel/Person.java
The ternary was flipped, so it worked the exact opposite of how it was supposed to. This fixes that issue.
> Fixing Baby Prisoner Status Ternary

- MekHQ/src/mekhq/gui/dialog/EditSpecialAbilityDialog.java
This fixes #2397 by adding a fall back value if the SPA being edited isn't in the hash, adding getters and setters for the vectors (which are only partially implemented, I'll finalize that when I swap SPAs to no longer be static).
> 2397: Adding Fall Back SPA check for current SPAs being edited

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/BaArmor.java
- MekHQ/src/mekhq/campaign/parts/InfantryAmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/InfantryArmorPart.java
- MekHQ/src/mekhq/campaign/parts/ProtomekArmor.java
- MekHQ/src/mekhq/campaign/parts/SVArmor.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorEquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/src/mekhq/campaign/parts/equipment/InfantryAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBin.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
When we initialize a unit, there are certain assumptions about where a part came from. If a refit went "bad" and picked the wrong type of part, you can end up in a situation where the unit cannot be initialized. Two approaches are taken here to resolve this issue:
1. If the entity type for a BA part isn't BattleArmor, remove the part from the unit.
2. For all of the sub-classes and extendable parts, make `isSamePartType` use strict class equality rather than `instanceof`.
The first approach directly fixes #2396.
The second approach hopes to make this a non-issue going forward. We shot ourselves in the foot a bit where we have base classes that are not abstract. Ideally, EquipmentPart would be abstract (as would Armor and AmmoBin), and the various type or entity specific classes would …
> Issue #2396: Resolve Infantry part and other part type bugs

- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/EquipmentPartTest.java
Partial revert of #2308 to preserve MekHQ behavior. MekHQ automagically switches to salvage on a salvageable part, the previous fix did not apply in practice because of this. Fixes #2387.
> Issue #2387: Allow salvaging components on destroyed locations from repair bay

- MekHQ/src/mekhq/gui/dialog/BaseDialog.java
This should be using getClass, as we want the derived class not the base dialog class.
> Fixing BaseDialog Preferences

- MekHQ/src/mekhq/campaign/Campaign.java
I could not figure out _why_ the campaign with #2427 had a part with either a null campaign or campaignOptions, but we routinely run into failures during overnight maintenance. This PR adds error trapping and logging in order to keep the Advance Day button working. As a means to raise this issue to the user I've now included a report in the daily log that they should check the logs.
Fixes #2427 (the advance day being stuck part).
I think this is a good candidate for Stable in that it'll keep campaigns from getting "stuck" on Advance Day.
> Issue #2427: Exception during maintenance on a new day breaks MekHQ

- MekHQ/src/mekhq/Utilities.java
When exporting an arbitrary JTable to a CSV file we assumed that every value in every cell would be non-null, however, this appears to not be the case in practice. This PR uses an empty string if a null value is encountered. This PR also cleans up two possibilities for a file resource leak.
Fixes #2431.
> Issue #2431: Fix exception exporting personnel to CSV

- MekHQ/src/mekhq/campaign/parts/MekLocation.java
- MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
This adds more informative blockers for the Null Signature System, Void Signature System, and Chameleon Shield. I'm not sold on how this is done, but it does work properly.
> Repair Tab: Adding better information blockers for Null/Void Signature System and Chameleon Shield

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This:
1) Overwrites the Campaign Ranks object instead of making some internal changes to the Ranks object in Campaign (which... I'm surprised wasn't causing more issues) (fixes #2442)
2) Prevents rank system data overwrite when loading a non-custom rank system from Campaign XML.
3) Tears out a bunch of old (7+ years) migration code, some of which was causing naming issues.
4) Sets rank system name migration to happen for any campaign before stable, to fix the previous name issues.
5) Swaps the Campaign Options Dialog rank system spinner to instead track based on the Ranks, which... was just a quick flip (I also tore out some old graphical code there, because it will need to be completely rewritten)
> 2442: Fixing Multiple Ranks Issues

- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Part of cleaning up Campaign Options, this is a constant so it should be in the constant file not campaign options.
> Moving Maxmimum d6 to MekHQ Constants instead of CampaignOptions

- MekHQ/src/mekhq/gui/CampaignGUI.java
https://github.com/MegaMek/mekhq/issues/338
Resolution of above issue. Progress over perfection. This change will notify players if they are about to use a wrong tech, and it will put the right techs per the Tech class (is right (refit target)) at the top.
I think this is best because tbh, I don't assign techs based on their skills. Some repairs take more or less long and I will assign like that. But a new player will assign a tech and only at the end discover they made a mistake. This fixes that issue.
> Issue 338 sort technician

- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/CommandCenterTab.java
- MekHQ/src/mekhq/gui/FinancesTab.java
- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/TOETab.java
- MekHQ/src/mekhq/gui/WarehouseTab.java
- MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/JPopupMenuAdapter.java
- MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/ProcurementTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/ScenarioTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This adds a new abstract class `JPopupMenuAdapter` to help connect the keyboard chord SHIFT+F10 to all of our context menus on JTable's and JTree's. This fixes #2418.
Apparently SHIFT+F10 sometimes works, but not always. This removes all doubt.
> Issue #2418: Ensure context menu shortcut works on our tables

- MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/personnel/generator/SingleSpecialAbilityGenerator.java
This fixes #2415, in addition to swapping the code over to a weighted map, fixing comparison by incorrectly compared tech level magic int sets (which... we have more than a few of), and actually having certain weapons be rarer than others, with it now being quite a find to get a test pilot or one who uses very rare weaponry.
To review: Whitespace differences off. The first commit is code rework, the second is the actual meat of the PR.
> 2415: Implementing Unit Weapon SPA Generation and Fixing Tech Level Comparisons

- MekHQ/src/mekhq/gui/view/ScrollablePanel.java
MekHQ uses `ScrollablePanel` as a base class for panels that should be scrolled. Its implementation uses 16 pixels for both the unit and block scrolling increment, which breaks the basic UI assumption that block scrolling should be in "pages". This restores the intended behavior of block scrolling [by adopting what is effectively the JTable implementation](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/swing/JTable.html#getScrollableUnitIncrement(java.awt.Rectangle,int,int)):
> Returns visibleRect.height or visibleRect.width, depending on this table's orientation.
Fixes #2446
> Issue #2446: Calculate the scrollable block increment correctly

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/force/Lance.java
If the force assignment for a lance becomes out-of-sync, when AtB generates scenarios for the lance an NPE may be raised. `Lance::isEligible` presumes `Campaign::getForce` will be non-null for the assigned force. This resolves the NPE by instead marking the lance as ineligible if its force is no longer valid.
Ultimately, the entirety of Lance/Force/Scenario/Mission need to be converted to using object references to avoid these problems in the future.
Fixes #2452
> Issue #2452: Ensure a Lance's Force assignment is still valid

- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
Fixes an NPE seen when assigning a unit to a bad equipment part by protecting against a null EquipmentType.
Fixes #2459.
> Issue #2459: Only calculate weight if EquipmertPart has a type

- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/unit/actions/RestoreUnitAction.java
- MekHQ/unittests/mekhq/campaign/unit/actions/RestoreUnitActionTest.java
This PR allows for better unit restore logic, fixing a number of issues we've seen in the past. The new strategy undertaken is to create a copy of the underlying entity then remove and replace all of the parts on the unit, as if we were adding a brand new unit.
If it cannot create a copy of the entity, it instead falls back to the old logic.
Fixes #2347.
Fixes #2299.
Fixes #2266.
Fixes #944.
Fixes #943.
Fixes #774.
Fixes #748.
> Better unit restore

- MekHQ/src/mekhq/gui/ForceRenderer.java
Fixes a visual glitch that I'd seen before but did not previously understand the significance of:
After:
> Use the correct resource string for free C3i Nodes on TOE

- MekHQ/resources/mekhq/resources/AddOrEditPersonnelEntryDialog.properties
- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/campaign/log/AwardLogEntry.java
- MekHQ/src/mekhq/campaign/log/AwardLogger.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/control/EditPersonnelLogControl.java
- MekHQ/src/mekhq/gui/dialog/AddOrEditPersonnelEntryDialog.java
This fixes #2469. As part of that fix, I've also moved the dialog to extend AbstractMHQButtonDialog.
> 2469: Fixing Award Log Edit NPEs

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This switches to using MegaMek's new UnitNameTracker to avoid name collisions for a campaign.
Depends on https://github.com/MegaMek/megamek/pull/2632
> Use MM's new UnitNameTracker for name collisions

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/WarehouseTab.java
- MekHQ/src/mekhq/gui/model/TaskTableModel.java
- MekHQ/src/mekhq/service/MassRepairService.java
This fixes #338 while simplifying any calls to the three overloaded methods.
Elite first is only done for refits, so using Person::getDailyAvailableTechTime as the sort is perfectly okay here.
> 338: Base Free Time Sort

- MekHQ/src/mekhq/gui/baseComponents/JDisableablePanel.java
This creates a new base component that allows one to enable or disable all components within a JPanel with a single selection. This does NOT include their child items, which will be handled as is regular for their setEnabled method.
> Base Components: JDisableablePanel

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
This fixes an issue raised on Discord where the bay rating for ProtoMechs is not taken into account. I also reorganized the checks so they are in the same order as they are in on the dialog in commit 2.
> ProtoMech Bay Rating

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java
This fixes #2538 - basically, the scenario dates weren't resetting correctly and forces weren't undeploying properly for ignored scenarios.
> fix scenario date/force resets

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
Pretty simple: when a contract goes to rout morale then comes back, bring in a (probably) new opposing force. Now with potential for mercs!
Addresses #2487
> randomly swap enemy when contract returns from rout state

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
This swaps AtB Contract naming to use a nicer format than our current setup, and adds date sorting to missions.
These were raised in the chat for #2460, and I'd say this fixes #2460.
> 2460: Improving Default AtBContract Name and Briefing Tab Sort

- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixes an issue I noticed where, if an aerospace fighter with 10 heat sinks had taken heat sink hits, you couldn't ever fix it without restoring the unit. Adding the appropriate number of missing heat sink parts to the unit seems to solve the issue.
> add damaged heat sinks as missing parts when loading unit

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
I've backported individual dice to Compute, so we no longer need the utilities method or use.
> GM Tools Dialog: Removing Backported Method Use

- MekHQ/src/mekhq/gui/FactionComboBox.java
- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
This prevents an of error relating to NewAtBContractDialog, namely that the employer combo box may return null as the selected key, as there may not be a valid employer. Further, for the same reason you can't use the default setter to ensure it doesn't end up with a null code, so I removed that commented out code.
> 2553: Fixing FactionComboBox NPE with null input code

- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
This fixes #2553 by moving where the combo box is initialized. This does take a bit more memory at all times, but ensures the preferences are kept between times this can be used..
> 2553: Fixing preferences issue in the Personnel Market

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/force/Force.java
This requires the MegaMek lobby/force PR #2409!
Sends the force composition to MM when starting a scenario. Uses a String representation that is also used for loading/saving forces in MULs. Bot forces will receive a standard force based on the bot's name like "Rebels", see Screenshot (nvm the missing i18 entries, that's my Eclipse config).
Also replaces sending the entities individually with sending them as a block (which is required for the force setup to work in this way and, also, faster without the added thread sleep and if anything, safer, I guess).
I imagine that when forces need to transport more to MM than structure and name we'd send the forces as a MegaMek.Force object, but for now, this works and is simple.
> Transfer Force info to MM, requires MM#2409 Lobby/GUI changes

- MekHQ/data/universe/factions.xml
Typo, should be Granada not Granda.
> Fixing Escorpión Imperio starting planet

- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/MekHQOptions.java
- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
- MekHQ/src/mekhq/gui/model/DocTableModel.java
- MekHQ/src/mekhq/service/MassRepairService.java
This was a Discord request a few months ago
> MekHQ Options: New Day: Auto-hiring Pool Options

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This fixes a bug whereby if you had a different value for a value that you normally want to use its actionlistener for to disable other values, it wouldn't update properly when disabled.
> Campaign Options: Fixing doClick issue

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/personnel/enums/Marriage.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
This is the MekHQ-side of https://github.com/MegaMek/megamek/pull/2804
> Weighted Map: MekHQ-side Changes

- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Not sure how this wound up happening, but this basically prevented deployment of forces from TO&E in all cases.
> don't always disable deploy force menu item

- MekHQ/src/mekhq/AtBGameThread.java
This fixes an issue where AtB-generated passenger units weren't loading onto their transports.
> let AtBGameThread take a break after tossing over unit collection

- MekHQ/data/stratconfacilities/AlliedAirBase.xml
- MekHQ/data/stratconfacilities/AlliedArtilleryBase.xml
- MekHQ/data/stratconfacilities/AlliedBaseOfOperations.xml
- MekHQ/data/stratconfacilities/AlliedCommsCenter.xml
- MekHQ/data/stratconfacilities/AlliedDataCenter.xml
- MekHQ/data/stratconfacilities/AlliedEarlyWarningSystem.xml
- MekHQ/data/stratconfacilities/AlliedIndustrialFacility.xml
- MekHQ/data/stratconfacilities/AlliedMekBase.xml
- MekHQ/data/stratconfacilities/AlliedOrbitalDefense.xml
- MekHQ/data/stratconfacilities/AlliedSupplyDepot.xml
- MekHQ/data/stratconfacilities/AlliedTankBase.xml
- MekHQ/data/stratconfacilities/HostileAirBase.xml
- MekHQ/data/stratconfacilities/HostileArtilleryBase.xml
- MekHQ/data/stratconfacilities/HostileBaseOfOperations.xml
- MekHQ/data/stratconfacilities/HostileCommsCenter.xml
- MekHQ/data/stratconfacilities/HostileDataCenter.xml
- MekHQ/data/stratconfacilities/HostileEarlyWarningSystem.xml
- MekHQ/data/stratconfacilities/HostileIndustrialFacility.xml
- MekHQ/data/stratconfacilities/HostileMekBase.xml
- MekHQ/data/stratconfacilities/HostileOrbitalDefense.xml
- MekHQ/data/stratconfacilities/HostileSupplyDepot.xml
- MekHQ/data/stratconfacilities/HostileTankBase.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java
- MekHQ/src/mekhq/campaign/stratcon/StratconFacilityFactory.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
This pull request fixes an issue I noticed where, when captured, facilities would pretend to be captured but still supply scenario modifiers associated with hostile versions of themselves.
We explicitly define what a facility becomes when captured to avoid messing around with trying to guess the "opposite" definition file or modifiers.
> Stratcon - actually capture facilities

- MekHQ/resources/mekhq/resources/AtBStratCon.properties
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Make the message indicating reinforcement cost a little more clear when the player has no SP/VP.
> update reinforcement cost message for no SP/VP situation

- MekHQ/data/scenariomodifiers/groundBattleModifiers.xml
- MekHQ/data/scenariomodifiers/modifiermanifest.xml
- MekHQ/data/scenariotemplates/Defend Grounded Dropship.xml
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
Four changes:
- grounded dropships were unavailable as potential scenario modifiers even though they should have been
- customize scenario dialog would reset status to null if editing a non-resolved scenario
- invoke full "land" code to set all appropriate values when initializing a grounded aerospace unit
- don't deploy opfor directly underneath allied dropship in 'Defend Dropship' scenario
> fix multiple grounded dropship issues

- MekHQ/src/mekhq/gui/enums/PersonnelFilter.java
> 2588: Fixing unmarketable check value for personnel table filter support check

- MekHQ/data/scenariomodifiers/EnemyDropship.xml
- MekHQ/data/scenariomodifiers/GroundedEnemyDropship.xml
- MekHQ/data/scenariotemplates/Irregular Forces.xml
- MekHQ/data/scenariotemplates/Low Atmo - Escort.xml
- MekHQ/resources/mekhq/resources/AtBStratCon.properties
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/StratconPanel.java
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
- MekHQ/src/mekhq/gui/stratcon/TrackForceAssignmentUI.java
- Fixes a couple of modifier/scenario descriptions, objectives and force destinations.
- Fixes some text tokens
- Prevents map size rerolls from generating tiny maps
- Prevents stacking multiple forces on a single hex - it can still happen with reinforcements, but I a) want to prevent multiple scenarios from spawning in a single hex and b) want to prevent the player from stacking all their forces on top of an allied facility for "free" reinforcement.
> Stratcon fix batch #2

- MekHQ/resources/mekhq/resources/PersonnelTableMouseAdapter.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
- MekHQ/src/mekhq/campaign/report/PersonnelReport.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/enums/PersonnelFilter.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This fixes a handful of bugs and finishes the dependent flag swapover. The bugs are:
1. Missing migration for legacy personnel with the None primary role
2. Removing children leaving the force while dependents, dependents leaving their spouse (by checking if their genealogy is empty during the automated removal).
3. Fixing Personnel Breakdown Report display for dependents
> Dependent Swapover: Removing Parental and Spousal Abandonment, Fixing None Primary Role

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/StratconPanel.java
- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
This fixes #2603 and a nightmarish tangle of issues discovered while testing that fix.
- Introduces a mechanism to specify whether a StratCon scenario should be displayed in the briefing tab.
- Introduces a mechanism to prevent a scenario generation report from being displayed in the campaign log.
- Fixes a logic error which would result in fixed objective scenarios being generated but then getting eliminated immediately upon contract start.
- Fixes an error preventing "add a force" modifiers from being applied to fixed objective scenarios due to missing mission ID
- Updated right click menu logic to prevent information leakage about unrevealed fixed objective scenarios
> fix multiple issues generating fixed objective scenarios

- MekHQ/src/mekhq/AtBGameThread.java
StratCon will occasionally have a situation where you're deploying a unit to MegaMek without it being in the TO&E, this accounts for that possibility.
> fix exception thrown when deploying unit not in a force

- MekHQ/src/mekhq/gui/StratconPanel.java
The intended logic is explained in the updated comments. Basically, I want the "assign force to this track" menu item to show up if there aren't any forces currently assigned to that hex and there aren't any visible scenarios on it. If there *is* a visible scenario on the hex, then we should always be getting the "manage scenario" menu item.
> one more fix for the stratcon tab right click menu

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
When assigning a force to a scenario that's already had opposition generated, the scenario would occasionally mysteriously re-generate the opposition. This is undesirable, because, under house and better command clause, you're supposed to be able to assign lances after seeing the opposition.
Turns out, it would only happen when loading a save - the "finalized" flag wasn't being preserved. Note that it's not relevant once the scenario has been played out.
> fix bait and switch behavior for non-integrated scenarios

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes #2607 while making the calculation actually repay the whole overage instead of merely repaying based on the previous total, which doesn't pay back everything.
> 2607: Fixing Payment Overage Option Implementation

- MekHQ/data/stratconcontractdefinitions/DiversionaryRaid.xml
- MekHQ/data/stratconcontractdefinitions/GuerillaWarfare.xml
- MekHQ/data/stratconcontractdefinitions/PirateHunting.xml
- MekHQ/data/stratconcontractdefinitions/RiotDuty.xml
- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractDefinition.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/campaign/stratcon/StratconStrategicObjective.java
- MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java
- MekHQ/src/mekhq/gui/StratconPanel.java
- MekHQ/src/mekhq/gui/StratconTab.java
Multiple improvements to strategic objective tracking, as well as several bug fixes:
- Starting altitude for generated units is now preserved across saves
- Taking a break between adding a bot and trying to change its settings to avoid "can't connect client" errors and issues sending settings over
- Strategic objectives are now explicitly set at contract initialization, in the basic form of [Type] [At coordinates (optional)]. This enables explicit tracking of objectives and much more detailed display.
- Don't apply "global" scenario modifiers once per track to reduce "Allied Trainees" and "Overwhelming Enemy Reinforcements" spam; apply them only once instead.
> Strategic objective tracking improvements

- MekHQ/src/mekhq/campaign/CampaignOptions.java
This removes the repair system code from Campaign Options. If we implement a repair system in MekHQ outside of Campaign Operations, we can then add this into MekHQ as an option. However, for now this is useless.
> Campaign Options: Removing Unused Repair System Code

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes #2625 by moving full tech removal to Person and standardizing the cases between the two.
> 2625: Properly Clear Tech Units on Person removal/retirement

- MekHQ/data/scenariotemplates/Convoy Escort.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- MekHQ/src/mekhq/gui/StratconTab.java
- MekHQ/unittests/mekhq/campaign/market/ContractMarketIntegrationTest.java
Three changes:
- compilation fix
- convoy escort objective properly lists force
- ensure minimum objective count for small unit sizes (objective count rounds to 0 sometimes).
Addresses #2633
> Small unit contract init fix

- MekHQ/data/scenariomodifiers/BadIntelAir.xml
- MekHQ/data/scenariomodifiers/FacilityHostileExtract.xml
- MekHQ/data/scenariomodifiers/FacilityHostileRecon.xml
- MekHQ/data/scenariomodifiers/OverwhelmingEnemyAirReinforcements.xml
- MekHQ/data/scenariomodifiers/PiratesIncomingAir.xml
- MekHQ/data/scenariomodifiers/PiratesPresentAir.xml
- MekHQ/data/scenariotemplates/Destroy Grounded Dropship.xml
- MekHQ/data/scenariotemplates/Recon.xml
- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java
- MekHQ/src/mekhq/gui/StratconPanel.java
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
- MekHQ/src/mekhq/gui/stratcon/TrackForceAssignmentUI.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
- MekHQ/unittests/mekhq/campaign/market/ContractMarketIntegrationTest.java
- Updated arrival altitude for aerospace fighter reinforcement modifiers (they were showing up on the ground)
- Standardized "recon" type scenarios to have the same criteria as Tukayyid scenarios 
- Various briefing text clarifications
- Store artillery offboard status between campaign saves
- On Integrated command, don't immediately and incorrectly undeploy lances after generating scenarios
- Adjusted manual force deployment rules (unlimited stacking on allied facilities, one per hex otherwise, no manual deployment under integrated command)
- Tighten up reinforcement restrictions (can't deploy units that can't actually deploy; can't double deploy units; can now only deploy fight lances or have to use a support point/VP)
- VTOLs no longer start on the ground
> various StratCon fixes

- MekHQ/resources/mekhq/resources/CampaignGUI.properties
The removed lines were unused, and the dialog tags were the only ones to load dialogs without the ...
> Cleaning up a few erroneous Campaign GUI properties

- MekHQ/src/mekhq/campaign/parts/MekLocation.java
- MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java
This fixes #2534. I also fixed a visual oddity between the two MekLocations, namely the missing IS/Clan for Endo Steel when replacing them.
> 2534: Fixing Missing Clan Check For Endo Steel Location Repairs

- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
The NONE Role is supposed to be a secondary role only. This prevents you from hiring a person with NONE as a primary role.
The second commit refactors the personnel role methods into streams
> Preventing NONE Primary Role Hiring

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizeMissionDialog.java
- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
This fixes #2485 by adding a default subcontract name, adding an override of toString for Mission, and swapping the Briefing Tab to use the Mission objects instead of tracking using an id.
It also fixes a minor bug where the contract name would be dated using the wrong date, namely the current day instead of the start date.
> 2485: Default Subcontract Name, Briefing Tab Mission Tracking

- MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java
- MekHQ/src/mekhq/gui/StratconTab.java
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
A couple of changes:
- some descriptive text to indicate that a scenario will provide campaign VP
- expired contracts still show up in StratCon tab for now; updated text for expired contracts (partial fix for #2657)
- If a selected unit in the scenario wizard is selected in other unit lists, remove it from those. Fix for #2661
> Prevent expired contracts from disappearing outright; duplicate unit selection fix

- MekHQ/src/mekhq/gui/dialog/ChooseRefitDialog.java
This fixes #2529 and requires https://github.com/MegaMek/megamek/pull/2895
> 2529: Fixing refit display so it no longer includes the pilot's BV

- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
Implements the modifiers to maintenance, repair, and replacement for a mech with prototype TSM due to its unstable nature and tendency to burst into flames. See IO, p. 104.
1. All maintenance rolls for a mech equipped with P-TSM are made at +1.
2. All repair and replacement tasks take twice as long (I didn't apply this to reloading ammo bins, as this should not directly involve the myomer).
3. Any repair or replacement involving internal structure, location replacement, or actuators is made at +2.
Depends on MegaMek/megamek#2923
> Prototype TSM mods

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/MekHQOptions.java
- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQNagDialog.java
- MekHQ/src/mekhq/gui/dialog/InsufficientAstechTimeNagDialog.java
- MekHQ/src/mekhq/gui/dialog/InsufficientAstechsNagDialog.java
- MekHQ/src/mekhq/gui/dialog/InsufficientMedicsNagDialog.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/OutstandingScenariosNagDialog.java
- MekHQ/src/mekhq/gui/dialog/ShortDeploymentNagDialog.java
- MekHQ/src/mekhq/gui/dialog/UnmaintainedUnitsNagDialog.java
- MekHQ/src/mekhq/gui/dialog/UnresolvedStratConContactsNagDialog.java
This PR swaps our nag dialogs to the new AbstractMHQNagDialog, which is backed onto MekHQ Options to allow persistence in ignoring individual nags
It also fixes Campaign::getDeploymentDeficit.
> Ignorable Nag Dialogs

- MekHQ/data/scenariomodifiers/BadIntelAir.xml
- MekHQ/data/scenariomodifiers/BadIntelGround.xml
- MekHQ/data/stratconcontractdefinitions/CadreDuty.xml
- MekHQ/data/stratconcontractdefinitions/DiversionaryRaid.xml
- MekHQ/data/stratconcontractdefinitions/FileFormat.txt
- MekHQ/data/stratconcontractdefinitions/PirateHunting.xml
- MekHQ/data/stratconcontractdefinitions/RiotDuty.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractDefinition.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- MekHQ/src/mekhq/campaign/stratcon/StratconCoords.java
- MekHQ/src/mekhq/gui/StratconTab.java
Change to behavior for contract objective scenario modifiers - now, they can be explicitly applied to the scenarios associated with the objective only. The exception being AnyScenarioVictory, where they'll get applied to any scenario in the contract.
Also, fix incorrect coordinate display, and some data fixes for a few contract types. Riot duty is actually riot duty now. Also, some code cleanup for unused code.
> contract objective update

- MekHQ/src/mekhq/gui/model/UnitTableModel.java
This fixes a bug I noticed while testing.
> Hangar Tab: Maintenance Colour No Longer Shows with Maintenance Disabled

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Three changes:
- generated VTOLs no longer start at elevation 0
- only put 1 TAG on bombers, hook it up with other types of bombs for the rest of the space instead
- wait a little longer to load transports; this seems to be a thread timing issue
> vtols off the ground; bombs expansion

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Prevent situations where a force or a unit may theoretically be selected more than once on the StratCon scenario management UI. This would basically cause a freeze when starting a scenario.
Now, if a force has any of its sub-units or sub-elements deployed, it cannot be deployed itself.
> prevent double deployment of forces and units

- MekHQ/src/mekhq/campaign/parts/Refit.java
This is just a bit of defense-in-depth for a possible problem with parts not having a campaign after a refit (as in #2703). I could not reproduce the issue and honestly could not find a path in the Refit logic where a part would not have a campaign.
Also, do not try and using missing parts for Transport Bays.
Fixes #2687.
> Issue #2703: Defend against parts without campaigns after Refit

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This corrects the display and application of target rolls for multi-day jobs that may use overtime. The previous logic in `Person::isTaskOvertime` was more accurately called `canPersonCompleteTaskWithOvertimeRightNow`, which is not what was needed.
The new logic simply informs the caller whether or not overtime is needed and could be applied.
Fixes #2679.
> Issue #2679: Correctly show and apply overtime mod to multi-day rolls

- MekHQ/src/mekhq/campaign/parts/MekLocation.java
- MekHQ/src/mekhq/campaign/parts/MissingAvionics.java
- MekHQ/src/mekhq/campaign/parts/MissingLandingGear.java
- MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java
- MekHQ/unittests/mekhq/campaign/parts/MekLocationTest.java
- MekHQ/unittests/mekhq/campaign/parts/MissingMekLocationTest.java
This is a quick attempt at explaining why a part is blocked for repairs. The logic here is to aggregate all of the parts which are blocking the repair and listing them (and their location if applicable). This should hopefully improve situations like #2609 where it is not clear why exactly the part is being blocked.
Fixes #2609.
_NOTE: I'm evaluating the unit tests to see if any of them can be extended to test this._
> Issue #2609: Show which parts are blocking repairs

- MekHQ/src/mekhq/campaign/personnel/Person.java
> 2707: Preventing text wrap in the person title JTable usages

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This fixes the bulk refit code in the unit table mouse adapter, as noticed in #2717, and converts them into streams.
> 2717: Fixing Bulk Refit Complete/Cancel

- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
This fixes #2717 by removing the modality changes from the advance days dialog and instead tracking using a single variable.
> 2717: Advance Days Dialog no longer based on modality

- MekHQ/data/stratconcontractdefinitions/CadreDuty.xml
- MekHQ/data/stratconcontractdefinitions/GarrisonDuty.xml
- MekHQ/data/stratconcontractdefinitions/RiotDuty.xml
- MekHQ/data/stratconcontractdefinitions/SecurityDuty.xml
- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractDefinition.java
- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/gui/StratconTab.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
- MekHQ/src/mekhq/gui/view/MissionViewPanel.java
Three changes:
- Don't display "regenerate bot forces" button when editing completed scenarios
- Allow mission/contract completion when there are "cloaked" scenarios (useful for early contract completion on contracts with fixed objectives)
- For contracts that are defensive in nature, introduce an "allow early victory" flag. Currently, all that does is display a "hold until date on "hold this facility" objectives.
> Assorted UI improvements

- MekHQ/src/mekhq/campaign/market/UnitMarket.java
- MekHQ/src/mekhq/campaign/universe/AbstractUnitGenerator.java
- MekHQ/src/mekhq/campaign/universe/IUnitGenerator.java
- MekHQ/src/mekhq/campaign/universe/RATGeneratorConnector.java
- MekHQ/src/mekhq/campaign/universe/RATManager.java
- MekHQ/src/mekhq/module/atb/AtBEventProcessor.java
This fixes #251 and a common source of bug reports by adding a fallback system for force generator unit generation, with the goal of preventing empty OpFors. To do this I reserved two of the generation methods for OpFor generation and removed the two non-OpFor generation method uses.
To review: The second commit is the generation change, while the other three are a mixture of code cleanup and standardization.  (I was originally considering doing a full campaign options setup, but decided the bugfix should be merged in the nearer future.)
> 251: Force Generator Unit Generation Empty Unit Table Parent Faction Fallback

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/gui/StratconPanel.java
- MekHQ/src/mekhq/gui/StratconTab.java
Three changes:
- fix clicked hex detection on StratCon map when viewing anything other than top left corner when map doesn't fit on single screen
- added scroll pane in case info panel has more data than can be displayed
- do not un-deploy force from track if it's assigned to a scenario on the track until the scenario is resolved one way or another
> Mekhq potato cleanup

- MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java
This fixes a bug raised on Discord.
> Mass Mothball Dialog: Fixing IndexOutOfBoundsException with no techs for a unit type

- MekHQ/src/mekhq/campaign/market/UnitMarket.java
This fixes the generation order for the unit market after I misordered some values in https://github.com/MegaMek/mekhq/pull/2731
> Fixing Unit Market Generation

- MekHQ/data/scenariomodifiers/EnemyArty.xml
- MekHQ/data/scenariotemplates/Pursuit.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/campaign/stratcon/StratconStrategicObjective.java
- MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java
- MekHQ/src/mekhq/gui/StratconTab.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- Pursuit scenario had the opfor set to run for the opposite edge even though it's the player's goal to get to the opposite edge
- Objective scenarios can sometimes move, but the objective wouldn't go with them
- Now possible to completely fail a facility capture/control objective if the facility is destroyed
- Prevent being able to deploy to invisible objective scenarios from the TO&E
- To help with color-blind users:
o indicates an in-progress objective (not complete, not failed, colored orange)
x indicates a failed objective (no way to complete, red colored)
checkmark indicates a completed objective (green colored)
> fixes for multiple stratcon issues; objective display improvement

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes an IDE warning for a potential NPE (false positive, partWork.getUnit() is previously null checked, but better to clean up) and simplifies the code around the if statement.
> Fixing Campaign::getTargetForMaintenance IDE Potential NPE False Positive

- MekHQ/resources/mekhq/resources/Campaign.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
This fixes #2558 and a bug where the same dependent can be selected for removal twice.
Commit 1 swaps removePerson to use the object instead of the id, commits 2-3 adds the new custom messages.
> 2558: Adding Custom Messages for Dependant Joining/Departing the Force

- MekHQ/src/mekhq/campaign/finances/Money.java
This prevents regular IDE warnings for serialization differences.
> Making Money Serializable as it already has a read/write to XML setup

- MekHQ/src/mekhq/AtBGameThread.java
Turns out, when going to a generated map, getting a new instance of the settings also reset the map size. Who knew.
> fixed reset settings

- MekHQ/src/mekhq/campaign/personnel/Person.java
This removes the only place I found that could cause a null birthday, which fixes #2790
> 2790: Fixing Null Birthday

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/market/unitMarket/UnitMarketOffer.java
This ensures the unit market migrates on post-0.48 saves, as the code was originally written before 0.49.0.
> Fixing Unit Market Migration

- MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java
Noticed this while working on another enum.
> AtBContractType: Fixing Logging Typo

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
This (I believe... it works, but I'm not sure about unexpected behaviour) fixed #2807.
> 2807: Removing EquipmentParts whose EquipmentTypes fail to parse

- MekHQ/src/mekhq/gui/ReportHyperlinkListener.java
This PR fixes tab spacing, if formatting, and properly catches multiple parsing exceptions. This has come up when working on both #2811 and #2817
> ReportHyperlinkListener: Rework, Code Scanning Alert Fixes

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
For aerospace/space scenarios the terrain type is out of bounds of the array above the changed code. We don't actually want to change the terrain type, but we want to avoid array out of bounds exceptions. This would manifest in aerospace scenarios failing to appear on the stratcon map.
> prevent out of bounds array access

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
Did the full swapover because of a save issue with ally and enemy skills after the enum swapover, which were saving using the base toString instead of the proper name format and missed because of the old format not putting any errors out when used.
> AtBContract: MekHQXMLUtil Save Swapover and Skill Level Parsing Fix

- MekHQ/src/mekhq/gui/StratconTab.java
This fixes a NPE that occurs when showing the StratCon state management, found in the logs for #2858
> 2858: StratCon Tab NPE

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
This fixes another issue in #2858, where the shares sorter doesn't work nor is required.
> 2858: Removing Useless Shares Sorter

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Fixes #2846 by picking a random valid deployment zone as a default. This seems to be happening when a force template is configured to sync its deployment zone to another force template, but that template doesn't exist.
> bulletproof deployment zone generation

- MekHQ/src/mekhq/campaign/parts/Part.java
When saving the parts list for GM added units, the tag is only saved
when the 'brandNew' property is TRUE and leave the tag out if the
property is FALSE.  Because the default constructor sets the property to
TRUE, false values re never saved and loaded.
Fixes #2873
> Proposed fix for #2873 - saving the part new flag correctly

- MekHQ/src/mekhq/campaign/parts/MissingBayDoor.java
Fixes #2878 
Found and fixed an issue that occurs when a dropship bay door is scrapped and repaired.  The `MissingBayDoor::fix()` method was removing itself prior to adding the actual part.  The side-effect of the `remove()` function is that is renders `this.parentPart` null therefore unable to complete the critical next step of linking the child/parent relationship to the actual part.
I could have just moved the `remove` method below setting the actual part relationship, but thought this side effect needed to be documented here to make the reader of this code aware of the side effect.
The impact of the original code was that the bay door was being added, but the Transport Bay containing the door did not reference it nor did the new fixed bay door reference the transport bay.  As a …
> Fixed #2878 Missing Bay Door on reload.

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This fixes a copy-paste error I made when implementing the ransom options, which was raised on Discord.
> Ransom is no longer automatically selected at 100% salvage rights

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
This fixes training XP not being assigned in StratCon and it being assigned when GM generating scenarios. I also cleaned up a bit of the code to remove an unnecessary method and cast.
> Monday Training XP Assignment on New Day instead of AtB Scenario Generation

- MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java
> 2867: Making the default unit market type the Open market instead of the Employer Market

- MekHQ/src/mekhq/campaign/personnel/generator/AbstractSkillGenerator.java
- MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java
- MekHQ/src/mekhq/campaign/unit/actions/HirePersonnelUnitAction.java
- MekHQ/unittests/mekhq/campaign/unit/actions/HirePersonnelUnitActionTest.java
> 210: One Person will be Artillery Trained when hiring minimum complement for an artillery-armed unit

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/gui/BriefingTab.java
This has been raised on Discord a few times recently, so I've added it. I also cleaned up the code for the method and fixed any IDE warnings (protected makes no sense in a final class and unnecessary toString usages being the primary two).
To review: I put a comment over the actual functionality change, which was supposed to be in its own commit.
> Briefing Room: Print Sheets now prints sheets for all units in AtB

- MekHQ/src/mekhq/AtBGameThread.java
This addresses a scenario where supposedly grounded aerospace units that were swapped in from the player's force to replace bot-generated aerospace units would "float" at altitude 0, by "landing" the grounded aircraft. This was previously done for the bot controlled units, but not the swapped-in player units.
> prevent swapped-in player aerospace units from floating

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
This has been the cause of multiple misunderstandings, including by myself... so this should better state the situation when it comes to debugging.
> Improving Client Unknown Phase Logging During Initial Connection

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This renames the origin force node from "My Campaign" to whatever you set for your campaign name when you first create a campaign.
> Startup: Rename Origin Force Node With Campaign Name

- MekHQ/src/mekhq/campaign/unit/actions/RestoreUnitAction.java
This PR builds on the new Unit Restore behavior and ensures the C3 network settings are copied as well.
TODO:
> Make sure we copy over the C3 master on restore

- MekHQ/src/mekhq/campaign/parts/MissingRotor.java
Replacing a destroyed rotor needs to set the internal structure properly instead of just swallowing the replacement part and not doing anything. Fixes #2866
> actually replace VTOL rotor instead of eating the part

- MekHQ/src/mekhq/campaign/unit/Unit.java
This is a copy of the actual MekHQ options, and thus can be safely used in MegaMek without causing MekHQ issues. Eventually we'll want to separate combat SPAs, support SPAs, combat edge, and support edge into four separate modules to prevent any errors due to MekHQ support values being sent to MegaMek.
Fixes https://github.com/MegaMek/megamek/issues/3232 and fixes https://github.com/MegaMek/megamek/issues/3244
> PersonnelOptions/PilotOptions Fix

- build.gradle
This should fix the issues with the nightly build and some people's builds as raised in the comments at https://github.com/MegaMek/mekhq/pull/2967
> Adding temporary fallback for JCenter

- MekHQ/build.gradle
- MekHQ/testresources/mockito-extensions/org.mockito.plugins.MockMaker
- MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
- MekHQ/unittests/mekhq/campaign/universe/FactionBorderTrackerTest.java
- MekHQ/unittests/mekhq/campaign/universe/FactionBordersTest.java
This contains the MekHQ changes required to remove the IPlayer interface, and updates Mockito to 4.1.0 (required to fix a Mockito bug that came up in testing)
> MM 3289: Removing IPlayer Interface

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Sometimes, for some reason, a player force template ID maps to null, so we account for that possibility here. Fixes #2981
> prevent NPE when scaling stratcon objectives

- MekHQ/build.gradle
All tests work properly. We'll need to update to JUnit 5 at some point in the near future, but this is an easy update in the meantime.
> JUnit Update to 4.13.2 from 4.12

- MekHQ/src/mekhq/gui/MekLabTab.java
Adapts MHQ to MML's #978 rename & restructuring. I have unfortunately no working combined build so I have no way of testing this before the MML PR is merged, so there's certainly an error in here somewhere. My suggestion is merging MML's PR, then I'll correct any errors in here.
> Adapt to MML package/class rename/move

- MekHQ/build.gradle
Found this was missing for MekHQ's windows build after the Log4j2 changes. Will merge immediately if the fix works
> Fixing missing files in the Windows MHQ build

- MekHQ/src/mekhq/campaign/mission/Contract.java
getSystem() in contract returns null if it's entered from the add mission -> new contract workflow.
> prevent NPE when adding a new contract manually

- MekHQ/src/mekhq/Utilities.java
This fixes issue #3023 and probably many other similar errors for generating crews for units coming back to MekHQ for potential salvage. The previous approach was to use the monte carlo method, which breaks down when the skill is near the edge of the bell curve and leads to endless loops. Consolidated the logic instead to simply increment or decrement the skill level until it either matches the desired skill level or we can't change any more crew members' skills.
> Fix mul loading npe

- .gitignore
A very simple PR for the Mac people. The OSX operatin system puts a .DS_Store file in any directory visited through the finder, which git should ignore. The .DS_Store entry in the .gitignore file is only picking up .DS_Store in the top level directory and not in any sub-directories, meaning my `git status` checks are littered with .DS_Store entries. This just changes that to ignore .DS_Store in all sub-directories as well.
> Fix DS_Store entry in gitignore file

- MekHQ/src/mekhq/campaign/RandomOriginOptions.java
This fixes a nasty bug where planetary events get messed up when creating Random Origin Options after the initial load. We don't create this outside of loading currently, but it will be in the near future (#3033).
> Fixing Planetary Event Accidental Triggers

- MekHQ/build.gradle
This fixes #2974 and standardizes the naming of the startup scripts.
> 2974: Windows Build Unix Script MML Startup Script Missing

- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
This fixes #2928, and everything for the refit is cleared after the load fails.
> 2928: Return a Null Refit When The New Entity Can't Be Parsed

- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
This PR just adds shifting wind direction and strength conditions to Scenario. I already refactored most of the planetary conditions from AtBScenario to Scenario in a prior PR. However, there were never variables for allowing wind to shift direction and strength during a scenario. This allows for that and also has variables setting the min/max wind strength so players don't suddenly find themselves in a class 5 tornado.
> Add shifting wind direction and strength to Scenario

- MekHQ/data/universe/factions.xml
We are trying to line up faction codes as closely as possible with SUCS data. In looking through the existing list, it looks like we need to fix two things:
* Add Timbuktu Collective (new faction in 3151)
* Fix Escorpion Imperio entries. We have two codes for this, the old CGS codes and a new CEI code. However, we are not actually using the CEI codes. We already do something like this for the Ghost Bears where we switch all existing CGB codes to RD (Rassalhague Dominion) codes in 3103. So we just need to do that and then we need an alternate name of "Scorpion Empire" at some point.
> Fix faction codes

- MekHQ/data/universe/factionhints.xml
- MekHQ/data/universe/ratdata/House Arano.xml
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/universe/Faction.java
The faction no longer exists as of #3085, so this refactors out any remaining uses in our code and data.
> Removing remaining PIND uses

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignPreset.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/BotForceRandomizer.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/io/migration/FactionMigrator.java
We missed migrating the player data during the PIND removal, so this handles that bug. It also handles a bug in CampaignXmlParser, namely a duplicated call to Campaign::updateTechFactionCode, that I found while investigating our internals.
I specifically coded this to make it extremely easy to swap to the SUCS setup and migrate from there. FactionMigrator::migrateCodeToAlignWithSUCS is included at a completely unused state.
> Adding PIND Migration Post-Removal

- MekHQ/unittests/mekhq/campaign/CampaignTest.java
- MekHQ/unittests/mekhq/campaign/market/ContractMarketIntegrationTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingHeatSinkTest.java
- MekHQ/unittests/mekhq/campaign/unit/actions/StripUnitActionTest.java
This prevents issues with EquipmentType not loading fast enough by just forcing it to load before tests the require it.
> Blocker: Unit Testing EquipmentType NPE and ConMod Fixes

- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
Currently the `ScenarioObjectiveProcessor` has the following code to check whether the associated force name belongs to the player:
```java
for (Force force : tracker.getCampaign().getAllForces()) {
if (force.getName().equals(forceName)) {
for (UUID unitID : force.getUnits()) {
objectiveUnitIDs.add(tracker.getCampaign().getUnit(unitID).getEntity().getExternalIdAsString());
}
forceFound = true;
break;
}
}
```
This only works when using a scenario template because when the template is created, the associated force names are mapped to the player's forces. However, this will not work in cases where the scenario was not created through a template (as will be generally be the case for story arcs and other imaginable future enhancements) and there is no systematic way at present to tell the …
> Check for force named "Player" when processing objectives

- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
This fixes a bug in PR #3094. I used the getUnits method in Scenario to get units assigned to the scenario. However, that is apparently the wrong method that only gets units unaffiliated with larger forces which meant that the secenarioObjectiveProcessor would just ignore units that were part of a larger force. To get all units, I need to use the getAllUnits method. Duh, right? Anyway, this very small PR fixes that.
> Fix bug with missing Player units in ScenarioObjectiveProcessor

- MekHQ/data/scenariotemplates/Harass.xml
- MekHQ/data/scenariotemplates/Prevent Breakthrough.xml
- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
Ok, this is a very small PR intended to change the logic of the ScenarioObjectiveProcessor with regard to the preventing breakthrough objective. I am fairly certain that the existing logic makes no sense.
This came about because I was building a prevent breakthrough scenario for the demo story arc in PR #2997 and noticed that it was not assigning units correctly based on the outcome. Basically, the objectives was to prevent the breakthrough of 70% of the enemy forces (who were arriving in waves) for 12 turns before retreating. After running through the scenario and seemingly accomplishing the mission, the only enemy units that were shown as correct for the scenario objective were those units that I destroyed, even though I had prevented the breakthrough of most units. 
I tracked the issue …
> Remove bad logic from check on preventing breakthrough

- MekHQ/src/mekhq/campaign/personnel/Skill.java
This corrects issue #3108. The issue looks like a residual copy and paste artifact where an XML tag was not changed.
> Fix incorrect tag on xml output

- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
This is the first part of handling #3111. MekHQ has only been partially swapped to use SkillLevel, as it previously used two setups. This is thus the only place that needs to change for now.
Requires https://github.com/MegaMek/megamek/pull/3446
> Adding the Legendary SkillLevel

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDualBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
This fixes #3132.
Commit 1 cleans up some related code and improves the performance, Commit 2 adds the null protection, and Commit 3 fixes the class name.
> 3132: Adding Entity Generation Null Protection for Officer Duel Scenario

- MekHQ/src/mekhq/IconPackage.java
- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CampaignPresetSelectionDialog.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
DRAFT
Use shared methods across MM, MHQ and MML for display scaling and splash screens.  Also cleans up some startup screen code so new campaign dialogs appear in the center of the screen.
Depends on: https://github.com/MegaMek/megamek/pull/3473
Resolves https://github.com/MegaMek/mekhq/issues/3143
> Displayscaling

- MekHQ/src/mekhq/service/AutosaveService.java
Asserts can cause issues because they won't be properly hit in most runtime setups.
> AutosaveService: Fixing Two Assert Uses

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/log/ServiceLogger.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixed #3146 and fixes the annotation setup that led to that issue.
> 3146: Fixing NPEs in Campaign::getForceFor to handle NPE raised from unit assignment.

- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
- MekHQ/src/mekhq/gui/panes/RankSystemsPane.java
This was raised from tonight's Solaris battles.
> Campaign Options Dialog: Fixing Scrolling Issues

- MekHQ/src/mekhq/campaign/personnel/Person.java
Asserts don't work on all setups, while Objects.requireNonNull does... and was there too.
> Fixing person portrait assert

- MekHQ/src/mekhq/gui/CampaignGUI.java
This adds accelerators to menu items, and thus displays the mnemonics in the options themselves. We want to use both accelerators and mnemonics to prevent issues with layered menus, as just using an accelerator can cause different submenus to be selected instead of the proper menu item.
e.g. When selecting the Marketplace / Hire / MechWarrior dialog through mnemonics, with just an accelerator it would swap to the Marketplace / Medic Pool submenu instead of launching the correct dialog. It works properly using both.
For Review: Commit 1 is a general code cleanup, Commit 2 is the actual change.
> GUI Menu Bar: Adding Accelerators to Menu Items

- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
- MekHQ/src/mekhq/gui/menus/AssignTechToUnitMenu.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
This resolves #2696 I was looking for a good place to put the coloring, but didn't see a common place any better than in Unit.
> 2696: Added coloring to the Unit List on the Personnell assignment menus

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
- MekHQ/src/mekhq/gui/model/RetirementTableModel.java
This fixes #3252 and another pair of bugs I found in the misc mod column.
> 3252: Fixing Retirement Table Column Pay Bonus Sorters and Default Return Values

- MekHQ/src/mekhq/campaign/universe/FactionBorderTracker.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
This fixes #3270.
To Review:
Commits 1-2 are cleanups to simplify the code, Commit 3 is the bugfix.
> 3270: Preventing RandomFactionGenerator Rebel Faction Target NPE from Null Faction Borders

- MekHQ/data/universe/randomDeathCauses.xml
- MekHQ/src/mekhq/campaign/personnel/death/AbstractDeath.java
This fixes the cause generation and doesn't load causes when random death isn't enabled (no need to waste the memory)
> AbstractDeath: Fixing Cause Generation Typo

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Due to a misunderstanding of how compute.randomInt behaves, situations where the odds of a random scenario are 0 (e.g. rout) can still (with 1% odds) generate random scenarios. Fixed the logic and misunderstanding.
> prevent stratcon scenario generation during rout morale

- MekHQ/src/mekhq/gui/panes/UnitMarketPane.java
This fixes #3294. It was also missing for the entity null check error.
> 3294: Unit Is Properly Removed after Black Market Swindle

- MekHQ/data/scenariotemplates/Assassinate.xml
- MekHQ/data/scenariotemplates/Capture.xml
- MekHQ/data/scenariotemplates/Convoy Attack.xml
- MekHQ/data/scenariotemplates/Destroy Grounded Dropship.xml
- MekHQ/data/scenariotemplates/Low Atmo - Destroy Dropship.xml
- MekHQ/data/scenariotemplates/Space - Blockade Run.xml
- MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
Adds a flag to scenario force templates to make them not subject to random unit removal modifiers (at the moment, just "Good Intel").
Fixes #3160
> added do-not-remove flag to force templates

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Pretty straightforward - addresses #3289 
The SPA upgrade code for opfors was already present - I hate to add more configurable settings, but it seems like it wasn't generating enough SPAs for people to notice? So now they can crank the odds of getting SPAs up to the max and let every regular+ opponent get SPAs.
> configure SPA upgrade intensity

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
As part of adding the history note I noticed that the opener has been banned from our socials for many issues including ignoring repeated dev advice while asking them for advice on the same topic (with reverse compatibility being a constantly ignored topic). I'm pretty much certain this is just user error because of the opener's history and complete lack of other raises.
I had no idea how this could have happened originally, and this path shows why. I'm sorry for wasting your time with #2831 @NickAragua and @rjhancock.
> Revert "2766: Preventing an exception whereby the processing entity has a -1 external id"

- MekHQ/src/mekhq/campaign/personnel/SkillType.java
This one predates MHQ's historical tracking.
> Removing Ancient SkillType Migration

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/enums/MekHQTabType.java
StatCon tab isn't guaranteed to exist, so this puts the ones that are guaranteed before it.
> Fixing MekLab Tab NPE

- MekHQ/src/mekhq/campaign/unit/Unit.java
Updates the "isfunctional" method of Unit class to prevent "grounded" spheroid dropships from being classified as non-functional. They're perfectly fine, in fact. Fixes #3408 and also the sporadic inability to deploy spheroid dropships to multiple sequential scenarios without a MekHQ restart.
> update aero functionality logic

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java
- MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java
- MekHQ/src/mekhq/gui/StratconPanel.java
Adds a gm-remove scenario option to the stratcon track panel; updates the 'remove scenario' option in the briefing tab to perform the same sequence of actions, resolving #2791 and the root cause of #3225.
> add remove stratcon scenario option

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/unittests/mekhq/campaign/market/ContractMarketIntegrationTest.java
- MekHQ/unittests/mekhq/campaign/mission/AtBContractTest.java
- MekHQ/unittests/mekhq/campaign/mission/DynamicScenarioFactoryTest.java
This PR is disables random testing in MekHQ, as they do not properly test functionality. Testing based on static mocking is the proper way to test these, and they will need to be rewritten to do that.
> Disabling Randomization-based Tests

- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQScrollablePanel.java
- MekHQ/src/mekhq/gui/baseComponents/JScrollablePanel.java
- MekHQ/src/mekhq/gui/panels/CompanyGenerationOptionsPanel.java
- MekHQ/userdata/data/universe/ranks.xml
This adds the AbstractMHQScrollablePanel, expanding the JScrollablePanel functionality to a suite-wide base component. It also fixes a scrolling bug in the Company Generation Options Panel. This requires https://github.com/MegaMek/megamek/pull/3853
> Base Components: AbstractMHQScrollablePanel

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
This fixes the bug raised in #3424. This requires https://github.com/MegaMek/megamek/pull/3838, which fixes the version default value issue.
> 3424: Properly fail to load a Campaign when the version can't be parsed

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Addresses an issue noticed during a CasualJoker stream where individual units assigned to dynamic scenarios weren't contributing to opfor BV/unit count budget.
> individual units contribute to BV/unit count for opfor budget

- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
This PR will remove the restriction on confining generated/dynamic Scenarios to the current Campaign Week.
> Remove restriction limiting generated/dynamic Scenarios to the current Campaign Week

- MekHQ/src/mekhq/campaign/mission/Contract.java
This appears to be a really old bug that has largely gone unnoticed.
Basically players were getting additional income when **not** using the Pay for Transportation option. This corrects that issue. Now if pay for transport is false both income and expenses are correctly zeroed out.
> Fixes issue with missing pay for transport check

- MekHQ/src/mekhq/campaign/unit/Unit.java
This bug was caused by the PR adding code for Joda Money. I did find another bug when calculating the cost of SRM 6 ammo but I do not know the cause or reason. It uses getStickerPrice() as does other parts of the HQ code, but only in this instance (and when using the replaced function) SRM6 ammo costs 28,929 instead of the typical 27,000. It does not affect other SRM ammo and those show up correctly.
> Fixes issue where training ammo was affected by the parts cost multiplier

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
I have no ability to test this, but have known the first was technically possible. The second one is just a safety check, as that will cause problems in future if it is set to blank.
> Adding Faction Data Validation to Campaign Options Pane

- MekHQ/resources/mekhq/resources/AtBConfigDefaults.properties
- MekHQ/src/mekhq/campaign/againstTheBot/AtBConfiguration.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
The first commit fixes #3473, the second fixes a large number of null issues arising from missing nullable annotations, and the third fixes an erroneous " in a date in the AtB config defaults.
I also cleaned up some unused code along the way, including removing a useless null check.
> 3473: Load Default AtB Config When Custom Config Cannot Be Parsed

- MekHQ/src/mekhq/MekHQ.java
> 3492: Removing Cached ToolTip Portraits between MM Launches

- MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
- MekHQ/src/mekhq/campaign/universe/generators/partGenerators/AbstractPartGenerator.java
This fixes #3373, which I found to be a severe transient issue.
> 3373: Company Generator: Parts No Longer Go Missing After Unit Removal Before Reload

- MekHQ/src/mekhq/campaign/againstTheBot/AtBStaticWeightGenerator.java
- MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AllyRescueBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ConvoyAttackBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ConvoyRescueBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PirateFreeForAllBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
This moves weight generation code for AtB out of the unit market and into its own class, as it is called from multiple places not just the unit market.
> AtBStaticWeightGenerator: Separating Out Code From Unit Market

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes #3558. RATs are used outside of AtB now, so this clearing breaks stuff
> 3558: RATs Are Used Outside of AtB

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
Another small QOL feature for those who micro founder marriages to ensure the bloodlines expand beyond the main founding families (generational QOL).
> Adds founder information to the biographical information view

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
This fixes a few minor issues around calculating the admin personnel requirements for Campaign Operations Unit Rating.
> Campaign Ops Unit Rating: Properly Calculate Admin Personnel Numbers

- MekHQ/src/mekhq/campaign/CampaignPreset.java
This fixes a bug whereby you can open a preset in an older version, which has and will almost certainly cause issues.
> Campaign Preset: Prevent Preset From Loading in Older Versions

- MekHQ/src/mekhq/campaign/universe/companyGeneration/CompanyGenerationOptions.java
This fixes a bug whereby you can open a preset in an older version, which will almost certainly cause issues.
> Company Generator: Prevent Preset From Loading in Older Versions

- MekHQ/resources/mekhq/resources/GUI.properties
> 3569: Company Generation Dialog: Fixing Warning Option Names

- MekHQ/data/stratconfacilities/HostileOrbitalDefense.xml
I had the modifier xml name mixed up on this facility.  Fixed.
> Fixes Typo on Orbital Defense Facility

- MekHQ/data/universe/defaultspa.xml
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
This fixes #3607, as a stepping stone towards an isolated edge setup.
It also fixes a bunch of issues with the ProtoMech skill name, and thus this is a blocker.
> 3607: Properly Load Support Edge Option Text

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This amends #3547 to allow it outside of Mothballing states, as it is useful in assigning techs.
> 3547: Allow Specifying Maintenance Extra Time Outside of Mothballing, Activating, and Mothballed

- MekHQ/src/mekhq/gui/panes/UnitMarketPane.java
Found this one as it was breaking preferences.
> Unit Market Pane: Fixing Missing Table Name

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
I also used this to show the Contract Market Method as an unselectable option, as I'm going to start implementing the migration for it on the backend.
> Campaign Options: Properly Disable Contract Market Pane based on AtB Selection

- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
While working on this I found a few missing accessibility labels and updated some old hard fail action listeners to the silent fail method.
> Campaign Options: Properly Disable Retirement and Dependent Options On Preset Load

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
Addresses #2455 by using the companion MegaMek pull request's weather restriction mechanism to filter out invalid weather/atmo/temperature combinations.
Also displays and passes the scenario temperature (currently pegged to the planetary temperature) to megamek when planetary conditions are enabled.
> Enable weather restrictions/temperature passing to megamek

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Should allow for all weight classes of potential enemy forces to be loaded from the XML.
> Fix for IndexOutOfBoundsException in AtBScenario's loadFieldsFromXmlNode when loading a save with a special scenario

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
I started this with just the goal of updating the label for Max Acquisitions (Issue #3502) and adding a tooltip for it. I did that in the first commit.
I then decided to migrate most of the strings from the code to the properties file.
Lastly I reorganized the options in the Acquisition section to have a more logical flow.
Original:
Updated:
Feel free to suggest any changes or drop any commits.
> Campaign Options Cleanup

- MekHQ/src/mekhq/campaign/parts/Refit.java
While I haven't addressed every problem in #3515, I've updated many of the refit classes to bring MekHQ closer to current tabletop rules.
I've also tested it: assuming refit classes in the window for choosing a refit don't reflect the benefit of a refit kit, it is working as expected.
> Update refit classes based on CamOps

- MekHQ/data/scenariomodifiers/EnemyDropship.xml
SC Dropship modifier is supposed to be an active instead of grounded dropship.  It functions correctly, but the forceName said  Grounded and caused confusion.
This fixes forceName of Dropship in Stratcon Dropship Modifier.  Removes term "Grounded" and adds "Active" to force name and description, for clarity.  
Addresses #3632
> Stratcon Dropship Modifier Clarification

- MekHQ/src/mekhq/campaign/parts/Refit.java
Adding CASE is a Class D refit. Removing CASE is not, so simply changing it does not necessarily make a refit Class D.
In addition, the current designation of Class E is never applicable.
> Fix CASE refit classes

- MekHQ/data/mechfiles/dropships/TRO3085/Cutting Edge/Clan/Vanir Assault Dropship (Standard).blk
- MekHQ/data/mechfiles/warship/XTR/Republic III/Leviathan III Battleship.blk
Fix: MegaMek#4424 Spelling error in .blk files. Stringray->Stingray.
> Fix: MegaMek#4424 Spelling error in .blk files. Stringray->Stingray.

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
This PR changes one line of code to activate the Hidden Facility Modifiers so they are applied as intended.
Obviously, Stratcon is amazing and I defer to Nick on this.  This was just discussed in discord this morning and I had a little time.  
Discussing this with @PhoenixHeart512 this morning and he pointed out the bug.  Enemy Facility modifers do not apply until they are scouted. This is a long standing issue, although there is no bug report on it that we could find.  I had a little time today so poked around at it.
Per the code comments and @NickAragua, hidden SC facilities should apply their modifier on a %chance based on an "aggro rating."  However, it appears the %chance aggro variable was never triggered for some reason (or the chance was so low as to be imperceptable) and so …
> Stratcon Hidden Facility Modifier Fix

- MekHQ/build.gradle
Added explicit dependencies to the MekHQ gradle build file to resolve unspecified implicit or explicit dependency warning when building from the command line `./gradlew clean build`.
Example warning that were appearing in the gradle build execution:  
> Task :MekHQ:createStartScripts
Execution optimizations have been disabled for task ':MekHQ:createStartScripts' to ensure correctness due to the following reasons:
- Gradle detected a problem with the following location: 'C:\git\mekhq\MekHQ\build\scripts'. Reason: Task ':MekHQ:distTar' uses this output of task ':MekHQ:createStartScripts' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed. Please refer to …
> Gradle build fixes

- MekHQ/build.gradle
Reverting this fix that fixed 'Multiple dependency errors in Eclipse IDE' as this fix also breaks printing unit record sheets in MekHQ briefing tab in a similar way as megameklab#1263.  
0.49.13
Work-a-round for 0.49.13.
[mekhq_print_workaround.zip](https://github.com/MegaMek/mekhq/files/11571042/mekhq_print_workaround.zip)
> Revert Eclipse Multiple Dependecy Gradle fix.

- MekHQ/src/mekhq/campaign/Campaign.java
Fixes #3621 - this error occurs only when starting mekhq and the ship search runs before the unit generator is otherwise initialized.
> prevent npe when running ship search

- MekHQ/src/mekhq/gui/MekLabTab.java
Reverts MegaMek/mekhq#3689. I misread the initial PR, so this is broken.
> Revert "BV and MP adaptation to MM changes"

- MekHQ/build.gradle
Follow fix to MekHQ 'Multiple Module Dependency' errors when attempting to import MekHQ into Eclipse IDE.
This fix excludes the `xml-api` library from the Megameklab jar.  Additionally, it sets the `xml-api-ext` to be included in the runtime build as it is needed by Megameklab's xml graphics library and is not included in the Java Runtime library.
This gradle configuration allows MekHQ to be independently imported into the Eclipse IDE using Gradle integration while not breaking the scaled vector graphics functions provided by Megameklab.  (i.e. when printing record sheets while embarking on a scenario in the Briefing Room tab.
> Fix Eclipse IDE Multiple Module dependency error - take 2.

- .github/workflows/codeql-analysis.yml
Saw this while reviewing GitHub Action failures:
> [Analyze (ubuntu-latest, java, temurin, 17)](https://github.com/MegaMek/mekhq/actions/runs/5496359739/jobs/10016334339#step:5:42)
This version of the CodeQL Action was deprecated on January 18th, 2023, and is no longer updated or supported. For better performance, improved security, and new features, upgrade to v2. For more information, see https://github.blog/changelog/2023-01-18-code-scanning-codeql-action-v1-is-now-deprecated/
> [GitHub] Bump CodeQL action versions per warning

- MekHQ/src/mekhq/gui/model/UnitTableModel.java
Hangar -> Status -> Maintenance Cost now shown in whole c-bills, rather than CSB with lots of decimal places
> Maintenance Cost now shown in whole c-bills

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/Quartermaster.java
Pretty straightforward: if we're looking for a part, and we can't find it because of some inherent property of the part that doesn't depend on the planet being searched or the person doing the searching, switching planets won't make a difference - so we stop making search attempts right away.
For campaigns with large numbers of logistics people and with the search radius set high, this will improve part searching performance drastically.
Fixes #3725
> prevent unnecessary parts searching

- MekHQ/src/mekhq/campaign/parts/MissingAvionics.java
CamOps says that avionics repair takes 80 hours for Large Craft and 8 hours for other aerospace units: MekHQ was previously using 80 hours for everything.
Fixes #2854
> Fix fighter avionics repair time

- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
Use the variable tech level setting in unit selector filtering.
Requires https://github.com/MegaMek/megamek/pull/4751
> Unit selector filtering

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/gui/dialog/SmallSVAmmoSwapDialog.java
Replace equality tests for AmmoType.M_* with EnumSet<AmmoType.Munitions>.contains() tests.
Tested by building and running MekHQ with this (and the two other patches) applied.
Will need to be pulled *after* PR https://github.com/MegaMek/megamek/pull/4762
> Initial pass to update MekHQ for fix 1152 on MM

- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
I'd missed a few Munitions == tests; these should be .equals() checks when comparing two EnumSets.
Two related PRs for MM and MML are here:
https://github.com/MegaMek/megameklab/pull/1313
https://github.com/MegaMek/megamek/pull/4797
close #3761
> Fix #3761: update munitions equality tests

- MekHQ/src/mekhq/campaign/parts/MekLocation.java
What it says on the tin. Requires MegaMek PR #4818. Implements #3759.
> weight calculation for spare mech locations

- MekHQ/data/universe/factionhints.xml
This PR makes a lot of assumptions about some rough dates of when the battles might have taken place during the Aurigan Restoration campaign. I have also tweaked the war dates slightly to match the planetary control dates.
By putting joint control for planets between the ARC and ARD factions (and some Taurian control too) my hope is this should get MekHQ to trigger contracts during the war.
This should allow players to follow along the HBSTech storyline inside MHQ, and fight for either side. I have manually tested:
- Planet control flipping
- Contract generation (by GM spamming contract generation)
- That the universe doesn't break afterwards
Test evidence screenshots:
**Early War - March 3025 - some planets flipped, others with ongoing fighting**
**Contract Generation**
**The universe …
> Arano Restoration Campaign - Planetary Control

- MekHQ/src/mekhq/campaign/Campaign.java
This simply resets the underwater counter used for aquatic mounts. I started working on a part class to track mounts, but there's not simple way to have a part that is repaired by medics instead of techs. The only practical use I could see is to refit a unit, the way InfantryMotiveType is used, but in my opinion this is better handled by adding the unit and transferring the personnel.
Depends on  MegaMek/megamek#4883
> Beast mounted infantry

- MekHQ/docs/UserDirHelp.html
- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
This adds a setting to the misc MekHQ settings for the user directory of MegaMek/megamek#4961
Requires MegaMek/megamek#4961
As per requests, awards and rank systems are now read from the user directory.
> User files directory setting in MHQ

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/BombsDialog.java
- MekHQ/src/mekhq/utilities/MHQXMLUtility.java
- MekHQ/unittests/mekhq/campaign/unit/UnitTestUtilities.java
This PR must be taken into MHQ after MegaMek PR #4974 is pulled.
Changes: 
- fixes a unit test that fails once AeroSpaceFighter class is introduced.
- Makes clearGameData (called after MM games return to MHQ) aware of Internal and External bomb stores.
- Add handling for internal bombs in XML writer.
- Misc. commenting around bomb panel code explaining changes.
Testing:
- Added, changed, removed bombs from various Aerospace units with and without Internal Bomb Bay quirk.
- Ran all unit tests.
Note: tests for this PR will fail until MegaMek PR ~~#4974~~ #5003 is pulled.
> Implement #4397 Internal Bomb Bay (MHQ compatibility)

- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
Mek Mortars and IS BA Tube Artillery are excluded from the MekHQ "Spend XP" SPA menu because they have an AT2 Class of "NONE".  By rights this whole AT2 class thing should be torn out, but it seemed more sensible to massage the existing check and add classes to the missing weapons, rather than refactoring a lot of code across all three projects.
This patch restricts the range of AT classes that will be rejected to just the existing Naval / Large Ship weapons.
The full fix also relies on the MegaMek PR [here](https://github.com/MegaMek/megamek/pull/5027).
> MekHQ part of fix for #4648

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/nightly-maven-ci.yml
Applied the same fix as the nightly-ci git hub action to the remaining github actions to prevent Gradle JVM memory thrashing when building from a clean project.  This has been working with good performance with the Nightly-ci github action for the past few months.
See #3785
> Fix jvm thrashing in github actions.

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
- add max contract salvage percentage to campaign options
> add max contract salvage percentage to campaign options

- MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This fixes #3763. When setting the quality of a unit in the Hangar the quality names are properly reversed.
Code duplicated from [PartsTableMouseAdapter#actionPerformed](../blob/master/MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java#L107-L130)
> #3763 reversing quality names in unit set quality GM menu

- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
This fixes #3194. Allows selecting multiple personnel and awarding a non-stackable award, which will only be added to those who do not already have it. When a single person is selected, the awards list will still be filtered as normal.
> #3194 Awarding non-stackable medals to multiple people

- MekHQ/data/universe/eras.xml
MekHQ stopped being able to run, crashing whenever I tried to start a new campaign, or load an existing one. After some digging, I found that [eras.xml](../blob/master/MekHQ/data/universe/eras.xml) was missing the closing tag on the opening comment.
Adding that, I can now start and load campaigns.
Interestingly, it seems to have been missing for quite some time, so potentially the xml parser we use got an update, or got set more strict recently. Not sure.
> Closing opening comment in eras.xml

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/force/Lance.java
- MekHQ/src/mekhq/gui/TOETab.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Implements  #3540 by allowing the manual selection of a force commander from the TO&E menu if there's more than one "highest rank". Automatically updates the force commander if a unit/person is added/removed from the force/campaign.
> manually set TO&E force commander

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Fixes the MechSummaryCache lookup for meks with clan chassis names during scenario resolution. The MSC still uses the full names internally, e.g. Mad Cat (Timber Wolf) = entity.getFullChassis()
> Fix chassis lookup

- MekHQ/src/mekhq/io/migration/GameOptionsMigrator.java
- comment out unused code, did not delete so there is an example
fixes #3842
> fix issue_3842

- MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
This will let some of the refit unit tests pass; we've seen that more tests need the EquipmentTypes initialized in recent months.  Note that this does not fix the issues related to Machine Gun Ammo bins.
> Partial fix for failing refit tests

- MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
Includes a couple of fixes for non-standard Mek crew complements:
1. Non-SH Tripods can now be assigned to crews, or have crews assigned to them.
2. Pilots can be assigned to SH and Tripods in the Personnel tab (previously broken)
Testing:
- Ran all unit tests across 3 projects (several still failing in MekHQ, unrelated)
- Tested crew assignments in a campaign with both SuperHeavy and Medium Tripod meks.
Close #3775
> Fix 3775: unable to assign nonsuperheavy crew

- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/unittests/mekhq/campaign/parts/RefitTest.java
- MekHQ/unittests/mekhq/campaign/unit/UnitTransportTest.java
Add "AeroSpaceFighter" UnitType to the list of acceptable UnitTypes for ASFBay transport.
This is another place where the Aero -> AeroSpaceFighter transition was incomplete.
Testing:
- Ran all projects' unit tests (Some MekHQ tests failing due to other issues)
- Verified ability to load ASF onto transport in UI.
Close #3848
> Fix 3848: Unit bays not accepting Aeros for transport, with unit test

- MekHQ/mmconf/serialkiller.xml
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignSummary.java
- MekHQ/src/mekhq/campaign/force/Lance.java
- MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
- MekHQ/src/mekhq/campaign/market/PersonnelMarketDylan.java
- MekHQ/src/mekhq/campaign/parts/Avionics.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/report/TransportReport.java
- MekHQ/src/mekhq/campaign/unit/CargoStatistics.java
- MekHQ/src/mekhq/campaign/unit/HangarStatistics.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
This PR replaces most of the remaining instances of `Entity.ETYPE_AERO` checks (except those that don't actually check real entity values) with `Entity.ETYPE_AEROSPACEFIGHTER` checks.  The ETYPE flags should really go away as we're doing most tests with Entity methods anyhow.
The root cause of this issue was MHQ code doing equality checks on Entity ETYPE flags, when we should be using `entity.hasETypeFlag()` in case the entity uses more than one flag together.  Barring that, replacing ETYPE_AERO with ETYPE_AEROSPACEFIGHTER for most of these checks is the right move.
I collapsed the unit tabulation into a smaller function for A) ease of testing, and B) less copy-pasted boilerplate.  This should also allow us to more cleanly implement new unit and bay types, e.g. SuperHeavy Vehicles and …
> Fix 3856: aeros dont appear in basic unit information

- MekHQ/data/scenariomodifiers/BadEvent.xml
This PR fixes the BadEvent StratCon modifier to add a working bonus.  It did not appear to do anything before based on my observations and other bug report.  Its description states if you have a "Bad Event" then you should also have another negative modifier generated by it.  That didnt happen. 
I changed bad event to add +1 equipment quality and 1 hostile BV budget increase.  So it is now a combination of Good Equipment and Hostile BV budget increase.
Ill be honest - I cannot tell if the BV budget increase is working.  I copied the other modifier exactly, but I ran many test with spreadsheet tracking and changed the number to extremes and I could see no patter whatsoever.  Im not sure of exactly how to test it to see if its working, but even if it is, its effect is negligable.  But if it …
> BadEvent Modifier Fix

- MekHQ/data/universe/factions.xml
Fixed a faction name typo (From 'Alfrik' to 'Alfik').
Replaced indents with white spaces, as per Style Guide.
> [Refactoring] Fixed Typo and Removed Indents

- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
This PR doubles the size of the border on Hiring Halls and Changes the color from light grey to orange.
Before:
After:
This closes RFE #3802
> Interstellar Map Hiring Hall Highlight

- MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
- MekHQ/unittests/mekhq/gui/panels/StartupScreenPanelTest.java
Filter out `clientsettings.xml` when searching the user dir for the most recent MekHQ campaign save file.
Testing:
- Added unit tests for new FilenameFilter static member
- Tested with manually-created empty `clientsettings.xml` file alongside existing campaign saves.
Close #3839
> Fix 3839: load last save loads clientsettings.xml instead

- MekHQ/docs/Archive Stuff/stratcon-faq-original.txt
- MekHQ/docs/AtB Stuff/Stratcon_Tips.txt
- MekHQ/docs/AtB Stuff/stratcon-faq-2.5.txt
- MekHQ/src/mekhq/campaign/mission/ObjectiveEffect.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/gui/StratconTab.java
- MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
Adjusts the various uses of 'Victory Point' for added clarity.
- 'Scenario Victory Point' renamed to 'Operational Victory Point'
- StratCon 'Victory Point' renamed to 'Campaign Victory Point'
Any non-print references, such as variable names, have been left intact to ensure minimal risk of bugs.
Readme's have been updated to match the new terminology.
Minor grammatical changes have also been made, where relevant.
> [#3730] Victory Point Terminology Changes

- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
Reduced the base TN for retirement/defection rolls from 5 to 3.
Reduced retirement/death payouts from a value equal to roughly 62.5 months of employment, to a more sane 2 months of employment.
Reduced the multiplier applied to payouts for officers from *2 to *1.2 to match the monthly wage increase for officers assigned by the default AtB Campaign Preset.
Retirement/Defection rolls have been a point of contention for a while. While there has been a lot of discussion on Discord regarding this point, and a lot of really good ideas. This simple change attempts to act as a stop-gap until a more permanent solution can be found.
I have also adjusted the value of payouts made when employees depart (voluntarily or via death). This is predominately a sanity check as the original payout values were …
> [Balance] Adjusted Retirement TN and Payout Values

- MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java
Currently, when the players' base comes under attack (usually due to a difficult contract) they are presented with a special scenario. The failure of which results in a Contract Defeat.
Current objectives task players with keeping allied units alive, including their own. For each allied unit that is defeated the contract Victory Points (not Scenario) are reduced by 1. As allied losses are inevitable, contract loss is almost a given, even if the player plays well.
This patch removes the Victory Point loss from allied defeats, but leaves all other objectives untouched. These are as follows:
- Ensure that at least 3 base units (turrets/civilians) survive
- Destroy, cripple or force the withdrawal of at least 50% of opposing forces
- Ensure that at least 50% of friendly forces survive
This …
> [Balance] [AtB/StratCon] Base Attack (Defender) Objective Changes

- MekHQ/src/mekhq/service/mrms/MRMSService.java
This is a simple fix that changes 'part that _in_ not being worked on' to 'part that _is_ not being worked on in the Mass Repair print to Daily Activity Log.
> [Typo] Corrected Typo in Mass Repair Dialog

- MekHQ/src/mekhq/campaign/universe/companyGeneration/CompanyGenerationOptions.java
The tooltip for starting cash dice count states that the base value of 18 dice is enough for a company. However, the default dice count is 17, not 18.
This patch changes default starting cash dice count from 17 to 18.
I opted to change the default dice count, and not the tooltip, as 18 is easily divided by 3 for players who wish to base their starting funds on their initial lance count. i.e. 6 dice per lance.
> [Bug] [Company Generator] Correct Starting Cash Dice Count

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
This uses the new feature  in Megamek from PR Megamek/megamek#5277 to disconnect quietly from the GameThread and AtBGameThread in MekHQ. So when users complete a scenario, they will no longer get the "Disconnected!" popup window which just gets in the way.
> Disconnect quietly from GameThread for MekHQ

- MekHQ/src/mekhq/campaign/mission/Scenario.java
This is for a bug that was introduced by PR #3834. The XML has stored EMI and blowing sand as boolean conditions. Backwards compatability is respected in the `Scenario.generateInstancefromXML` method. However in the `writeToXML` functions, these conditions are being written as an ordinal numeric value rather than a boolean. The result is that once a campaign is saved again, the EMI and blowingSand conditions, if true, will be lost. This is currently affecting Story Arcs. See AaronGullickson/MekHQ#25 for further discussion.
The fix is easy. Just write the results back out as a boolean. I have tested the code and it works correctly.
> Correct writing to XML of EMI and Blowing Sand conditions

- MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
Currently `PersonnelTableModelColumnTest` features the unit test `testIsechBABA`
`testIsechBABA` is a typo and should read `testIsTechBA`.
Changed `testIsechBABA` to `testIsTechBA`.
> [Typo] Corrected Typo in testIsTechBA

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/PrisonersNagDialog.java
None
I am definitely not the only person who has done this: end the contract, enjoy the spoils of war, get halfway to Galatea only to remember you have a couple hundred prisoners of war still hanging about. You're not about to return to the contract planet so you just dump them out into space. Everyone is sad.
On a new day, if not on a contract, the system will check whether any of the users' active personnel are prisoners. If any prisoners are found the nag dialog is triggered.
</p>
I removed the check for Bondsmen, as these can still be assigned to roles they don't really have the same issue as Prisoners.
> Added Nag Dialog for Prisoners of War Outside of Contracts

- MekHQ/data/forcegenerator/factions.xml
- MekHQ/src/mekhq/campaign/universe/RATGeneratorConnector.java
Fix case error in Circinus Federation parent faction "WOB.pm" (should be "WOB.PM").
Safety part of the lookup which can cause NPE.
Testing:
- Ran MekHQ with campaign save and custom units from #3803 and confirmed proper operation.
Close #3803
> MekHQ fix for WOB.pm/.PM mismatch and missing parent faction check

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
Currently the Tech Skills view has the following tabs:
This makes it difficult to find those employees with the Tech/Vessel skill.
Added Tech/Vessel column
Also added appropriate Unit Test.
Closes #3890.
> Add Tech/Vessel Column to Tech Skills View

- MekHQ/data/scenariomodifiers/AlliedASFAce01.xml
- MekHQ/data/scenariomodifiers/EnemyASFAce01.xml
- MekHQ/data/scenariomodifiers/EnemyASFAce02.xml
- MekHQ/data/scenariomodifiers/EnemyFieldArtyCrack.xml
- MekHQ/data/scenariomodifiers/EnemyFieldArtyOffboard.xml
- MekHQ/data/scenariomodifiers/airBattleModifiers.xml
- MekHQ/data/scenariomodifiers/groundBattleModifiers.xml
- MekHQ/data/scenariomodifiers/modifiermanifest.xml
- MekHQ/data/scenariotemplates/fixedmuls/AlliedASFAceHvy.mul
- MekHQ/data/scenariotemplates/fixedmuls/EnemyASFAceHvy.mul
- MekHQ/data/scenariotemplates/fixedmuls/EnemyASFAceMed.mul
- MekHQ/data/scenariotemplates/fixedmuls/EnemyCrackFieldArty.mul
- MekHQ/data/scenariotemplates/fixedmuls/EnemyOffFieldArty.mul
This PR addresses a recent RFE to add infantry field guns.  Its also adds ASF aces to fill the last hole of the most commonly used units.  I dont plan on adding any more at this time unless the ability to sort them by date happens.
Regardless, later I plan on updating all of the current .mul modifiers to have one for each era.  Even without date sorting, they can be added to the repo to their own folder with instructions that users can copy over depending on the era they are playing, or I can just put them in the files forum for people that want to use them.
Closes #3894
> StratCon Air & Arty Modifiers

- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
These fixes will enable checking custom ScenarioObjectives to affect the victory conditions.
> Fix #3949: Custom ScenarioObjectives do not change ScenarioStatus in ResolveScenarioWizardDialog

- MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AceDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AlliedTraitorsBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AllyRescueBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AmbushBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ChaseBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/CivilianHelpBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/CivilianRiotBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ConvoyAttackBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ConvoyRescueBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ExtractionBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/HideAndSeekBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/HoldTheLineBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PirateFreeForAllBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PrisonBreakBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ProbeBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ReconRaidBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StandUpBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache2BuiltInScenario.java
`MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java` details the victory conditions (objectives) for the various built in AtB scenarios. All objectives have a fixed Operational Victory Point value of 1.
This means that it is not possible to edit the value of objectives when compared to each other. For example, in one scenario you might have three objectives: 1 primary, 2 secondary. All objectives are valued identically, meaning completing both secondary objectives but losing the primary is still considered a victory.
I added the integer `OperationalVP` to objective functions, where applicable. I updated all calls from the various objectives to include this variable. All instances default to 1, so nothing has been changed insofar as rewarding Operational VPs. This isn't an update …
> Variable OperationalVP Added to CommonObjectiveFactory.java

- MekHQ/resources/mekhq/resources/CampaignGUI.properties
- MekHQ/resources/mekhq/resources/CustomizeScenarioDialog.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
This PR addresses issue #3929. It will prevent advancing the day when a scenario is due (is pending and has a due date of today or earlier). This only affects vanilla scenarios not AtB scenarios. This will make story arcs where scenarios are created by the arc easier to manage because players will be alerted when there is a scenario that requires attention. 
This is ready to go ~~but I am going to leave it in a draft state because I do not want to add this code until we give players a way to edit the date of a pending scenario, which I plan to do as part of addressing issue #3927.~~
> Prevent advancing day with pending vanilla scenarios

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- add lances to the force string when sending data to megamek for bot forces
> add lances to the force string when sending data to megamek

- MekHQ/src/mekhq/campaign/parts/MekCockpit.java
- MekHQ/src/mekhq/campaign/parts/MissingMekCockpit.java
I noticed the costs and weights were incomplete when checking places the cockpit constants were being used.
Requires Megamek/megamek#5291.
> Add missing cockpit costs and weights

- MekHQ/src/mekhq/gui/dialog/nagDialogs/UnmaintainedUnitsNagDialog.java
When users trigger `Advance Day`, while there are unmaintained units in their hanger, they are presented with a nag dialog asking for confirmation.
This triggers even for units set to salvage.
The nag now only triggers if there are unmaintained units that are _not_ set to salvage.
Closes #646 (only 6 years old! :D)
> Unmaintained Unit Nag Dialog Suppressed for Units set to Salvage

- MekHQ/src/mekhq/campaign/Campaign.java
Currently, CamOps Unit Rating is uncapped. AtB relies on Unit Rating to generate TN modifiers to a number of different functions.
With CamOps being uncapped, there is no upper or lower boundary to the modifiers which can create undesirable effects. Such as...
- Only generating Relief missions
- Making Retirement checks impossible to pass/fail.
- Making Ship Search checks impossible to pass/fail.
- Influencing what large craft are found, through the Ship Search.
- Influencing the arrival/departure of Dependents.
- Influencing enemy Morale Checks, causing enemy morale to snowball towards Invincible/Rout.
- Influencing part availability, during contracts. Potentially making the availability of parts much easier/harder than intended.
- Influencing where units are placed, after scenarios …
> Clamped Unit Rating Mod for CamOps (redux)

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
When enabled, via Campaign Options, Toughness will always be visible on the personnel panel.
</p>
This does not follow the standard set out by other optional characteristics, such as 'Edge', which only display when having a non-zero value.
Expanded the existing conditional to check that Toughness is enabled _and_ above zero.
</p>
</p>
> Hide Toughness When 0

- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
The current zoom calculation, for the Interstellar Map Panel (IMP), is `1.5^(-1 * Mouse Wheel 'Clicks')`.
This leaves the IMP feeling a little over-sensitive. Frequently I've found myself going from planetary-level to Milky Way-level in a single mouse wheel roll, as illustrated below:
<p align=center>IMP After 10 Wheel Clicks (From default starting scale)
I adjusted the zoom calculation to `1.175^(-1 * Mouse Wheel 'Clicks')`. This improves the feel of zooming in & out on the IMP, without excessively slowing either down.
<p align=center>IMP After 10 Wheel Clicks (From default starting scale)
> Adjusted Zoom Speed on Interstellar Map Panel

- MekHQ/src/mekhq/GameThread.java
This is a correction of my own mistake when I was setting up the GameThread long ago to be able to use BotForces. I added the BotForces outside of the check for being in the chat lounge. The consequence is that you end up loading them multiple times, so that when you get to scenario resolution, you have a long list of duplicate entities. Just moving them inside the brackets for the check fixes the problem. 
I actually made this correction awhile back in my story arcs branch after noticing the problem. However, I am realizing that it would be better to make the correction as a separate PR since the bug is already present in master, both to keep the diff in story arcs as small as possible and for good record keeping.
> Load bot entities in the chat lounge

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
Currently, `BotForce` only tracks the starting edge with the variable `start` despite the fact that we now have several more variables that can be used to basically set up any deployment zone on a map. This PR brings in the additional deployment variables from `Player` in MegaMek to `BotForce` and assigns them in the `GameThread` and `AtBGameThread`. Given that the only place to currently set these parameters is story arcs, it doesn't have any practical use at the moment, but will be very useful to story arcs. Furthermore PR #3931 will be able to allow users to set these new variables in an updated `CustomizeScenarioDialog`.  So, this is preparatory work.
I did decide to change the name of the starting edge variable from `start` to `startingPos` to make it consistent with the variable …
> Add all deployment variables to BotForce

- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
Makes this lookup safer if `defaultspa.xml` contains an SPA that MM doesn't know about.
This appears to happen when AtB tries to generate a bot force during scouting, if the force will have pilots with SPAs.
About 27% of the options in `defaultspa.xml` will cause an NPE, so this change just forces a re-roll if the current SPA isn't found.
Testing:
- Ran previously-failing scouting missions from both posted issues.
- Ran all three projects' unit tests.
Close #3767 
Close #3884
> Fix #3767: NPE while scouting if AtB tries to generate enemy with SPAs not found in MM

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/gui/dialog/DateChooser.java
plus allow DateChooser resizing if theme does not fit right (as is the case with Flat Darcula LaF).
This sets the default MekHQ UI theme to the GUIPreferences default theme at initial startup, which will be Flat Darcula currently.
New startup theme:
Testing:
- Started MekHQ with and without `mhq.preferences` in /mmconf.
- Tested changing and saving preferences with default theme loaded from GUIPreferences (currently this is Flat Darcula) at startup.
- Ran all three projects' unit tests
> Implements RFE #3995: Set default theme to overall suite default at startup... 

- MekHQ/src/mekhq/campaign/Campaign.java
Currently, if 0 Astechs are assigned to a task 0 Astech minutes are used and an error message is popped into the log to confirm that this has happened:
`02:50:44,277 ERROR [mekhq.campaign.Campaign] {AWT-EventQueue-0} mekhq.campaign.Campaign.getAvailableAstechs(Campaign.java:5332) - Tried to getAvailableAstechs with 0 minutes. Returning 0 Astechs.`
Large Craft do not use Astechs, causing this error to fire for each Large Craft in the Hanger. Furthermore, this appears to be working as intended: if 0 Astechs are assigned to the task, then 0 Astech minutes should be used.
I removed the error message, in the event that 0 Astechs are assigned to a task 0 Astech minutes will be used silently.
closes... #3981
> Removed Unnecessary Error Log

- MekHQ/resources/mekhq/resources/AddOrEditKillEntryDialog.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/Kill.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/control/EditKillLogControl.java
- MekHQ/src/mekhq/gui/dialog/AddOrEditKillEntryDialog.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
Throughout this PR the term 'Mission' can be read as referring to both Missions and Contracts interchangeably. AutoMedals is the internal name for the in-dev project that will automatically prompt users to optionally assign medals to those employees that have earned them.
Three data points are recorded for Kills: Killer, Killed, and Date.
The in-dev AutoMedals project needs to be able to identify Kills that occurred over the course of a Mission, and those that occurred over the course of a single Scenario.
I added functions to allow for the Scenario ID and Mission ID numbers to be baked into the stored Kill data. This information is logged and stored, alongside the existing Kill data, in the users' save file.
</p>
These IDs are drawn from existing functionality, all I did …
> Added Scenario & Mission Tracking to Kills, Added Ability to Assign Kills to Scenario and/or Mission

- MekHQ/src/mekhq/campaign/againstTheBot/AtBConfiguration.java
AtB Ship Search currently uses a block of code to cycle through each logistics personnel, with a mind towards finding the best personnel skill rating among logistics personnel. It then uses this to apply a modifier to the Ship Search TN.
</p>
The code already checks for highest skilled personnel using the `findBestInRole()` function. The loop that follows is unnecessary.
Furthermore, the loop includes broken logic that results in Ultra-Green personnel being rated higher than any other personnel.
I simply removed the excess code.
I tested personnel with both primary and secondary Admin/Logistics roles of all ranks.
...closes #3989
> Fixed Ship Search Overvaluing Ultra-Green Personnel

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AceDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AlliedTraitorsBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AllyRescueBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AmbushBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ChaseBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/CivilianHelpBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/CivilianRiotBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ConvoyAttackBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ConvoyRescueBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ExtractionBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/HideAndSeekBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/HoldTheLineBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PirateFreeForAllBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PrisonBreakBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ProbeBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ReconRaidBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StandUpBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache2BuiltInScenario.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
I should have probably added this as part of PR #3991. That PR added all the new deployment variables to BotForce for use. However, the only deployment variable for players is still the starting edge. This now adds all of those same deployment variables to Scenario so that they can be applied to the player's forces. 
The changes are:
* Add the deployment variable to scenario along with getter/setter methods. I also refactored `Scenario.getStart `and `Scenario.setStart` to `Scenario.getStartingPos` and `Scenario.setStartingPos`, respectively, for greater consistency in naming. I put in a backwards compatibility check in the XML reader to still get cases where `start` was used.
* Changed `GameThread` and `AtBGameThread` to set the new deployment variables for the player's forces.
Several …
> Add new player deployment variables to Scenario

- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
- MekHQ/unittests/mekhq/campaign/mission/CrewSkillUpgraderTest.java
Note: this _may_ fix #4002, or may only fix something that may be contributing to it.
Prevent infinite loop by reducing choices each time we `continue` the while loop.
Also remove a check for more elements in some SPAs that, honestly, I don't remember writing - it actively prevents some SPAs from being applied even if they are valid.
Testing:
- Tested with failing save from #4002;
- Add unit tests for large number of consecutive calls to the previously-failing function;
- Ran all 3 projects' unit tests as well.
> Fix MHQ #4002: prevent infinite loop while assigning SPAs by removing unusable entries

- MekHQ/src/mekhq/gui/dialog/nagDialogs/UntreatedPersonnelNagDialog.java
The Untreated Personnel Nag Dialog triggers whenever users are attempting to Advance Day with untreated personnel 
This can get very spammy when there are large numbers of prisoners and insufficient doctors. This was an oversight in my original code.
The nag no longer triggers for injured Prisoners.
Closes #4001
> Fixed Untreated Personnel Nag Triggering for Prisoners.

- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
Currently it is not possible to purchase items, from the Parts Acquisition dialog, if that part has a TN >12.
This forces users to manually order the item from the Purchase Parts dialog. This can be a little awkward, if the part in question has multiple variants (based on weight, for example).
It is not possible to order Impossible TN missing parts from the Parts Acquisition dialog. In instances where the TN is impossible, this is clearly labeled.
</p>
…Closes #3359
> Added Ability to Order Impossible TN Parts from Acquisitions Dialog.

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/campaign/CampaignSummary.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/CargoCapacityNagDialog.java
None
Currently it is easy to exceed cargo capacity, unless you are watching your maximum cargo capacity like a hawk.
If the user has set a destination on the interstellar map, this nag will trigger in the event that current cargo tonnage exceeds cargo capacity. I opted to disable the check when no destination is set, as I figured while the user is on-planet there is no need to remain within cargo capacity.
</p>
This is definitely a nag I don't expect all users will appreciate, however the ease with which this nag can be suppressed seemed to warrant its inclusion for those users who _do_ try to keep cargo within capacity.
Ideally, this nag would start suppressed on a new campaign, however I couldn't figure out how to enable that functionality. If that functionality does …
> Added Nag Dialog for Exceeding Cargo Capacity While Destination is Set

- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
We now have `terrainType` in `Scenario` (I think as part of the work by @kuronekochomusuke on weather), which references the preset map generation parameters in `data/mapgen`. However, the code in `GameThread` will not properly apply these mapgen settings because it uses:
```java
File mapgenFile = new File("data/mapgen/" + scenario.getMap() + ".xml"); // TODO : remove inline file path
```
The problem is that `scenario.getMap()` does not access `terrainType` which is what needs to be accessed. I believe this is because somewhere in the innards of AtB code, terrain type gets translated into the `map` variable. However, this does not happen in vanilla `Scenario`.
This PR fixes the problem by just switching the code above to directly call `scenario.getTerrainType()` rather than …
> Move terrainType to AtBScenario

- MekHQ/build.gradle
- MekHQ/docs/history.txt
- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/gui/view/ScenarioViewPanel.java
- build.gradle
Includes the following fixes back-ported from 0.49.20:
#4023
#4052 (first part; does not include updates from #4050)
Plus an update to MM's Version.java to support a 4th field in the version number (without this, bug reports would be quite difficult to keep track of).
Version is reported as 0.49.19.1
Testing:
- Ran all unit tests
- Verified C3i fix working in OP's save from #4034 (can load, advance, save)
> MekHQ 0.49.19.1 dot release

- MekHQ/unittests/mekhq/campaign/parts/equipment/EquipmentPartTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/LargeCraftAmmoBinTest.java
It works! All green. I think some of this is correcting mistakes from my last PR plus a few other tests that were failing.
> Fix unit tests on Large Craft Bays

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/unittests/mekhq/campaign/CampaignTest.java
Issues for the reported campaign are twofold:
1. 3 Persons use a systemId that has changed in 0.49.19, causing the planetId lookup to fail.
2. At least one infantry unit has a quirk or ability that grants it BAP equivalent sensors, but no actual sensors; this causes a new-to-0.49.19 cleanup step to fail on loading the unit(s).
Fix is to add try/catch and better conditionals around the failing code blocks.
Testing:
- Ran all three projects' unit tests
- Added unit test for clearGameData() with affected Infantry unit instance.
- Loaded OP's previously-failing campaign save successfully.
Close #4061
> Fix 4061: Failure to load older Campaign save

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/unittests/mekhq/campaign/CampaignTest.java
Fix for #4061 , tested and proven in .20 code.
Testing done in 0.49.19.1:
- Ran all existing unit tests for all three projects,
- Added a unit test of clearGameData() on Infantry with quirks or abilities that add BAP functionality,
- Loaded OP's previously-failing campaign save successfully.
> Backport fix for MHQ #4061 to 0.49.19.1

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AceDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
Backports fix for #4062 into 0.49.19.1 from 0.49.20 code.
Testing:
- Ran all three projects' existing unit tests
- Loaded a known-good campaign, turned off Weather Conditions and Planetary Conditions but left Light Conditions enabled; confirmed only Light Conditions passed through to mission game in MM.
> Backport Fix for MHQ #4062 to 0.49.19.1

- MekHQ/src/mekhq/campaign/storyarc/StoryPoint.java
- MekHQ/src/mekhq/campaign/storyarc/storypoint/ChoiceStoryPoint.java
- MekHQ/src/mekhq/campaign/storyarc/storypoint/DialogStoryPoint.java
- MekHQ/src/mekhq/campaign/storyarc/storypoint/NarrativeStoryPoint.java
- MekHQ/src/mekhq/gui/dialog/StoryDialog.java
This is a slight tweak to the StoryPoint classes that create dialogs (ChoiceStoryPoint and NarrativeStoryPoint). I was previously tracking the image used for the dialog in StoryPoint itself, but I think it makes more sense to create an intermediate abstract `DialogStoryPoint` that tracks this and which ChoiceStoryPoint and NarrativeStoryPoint inherit.
> Refactor ChoiceStoryPoint and NarrativeStoryPoint with underlying abstract DialogStoryPoint class

- MekHQ/src/mekhq/campaign/Campaign.java
Currently we clamp CamOps unit rating within the bounds of the FM:F (F-A*) rating system.
While my earlier fix addressed the issue of CamOps unit rating modifiers breaking a bunch of things (see #3933), there is still the issue of the CamOps Unit Rating method resulting reaching the maximum/minimum modifier faster than expected - from a balancing point of view.
Dividing the CamOps unit rating by 3 produces closer results to the equivalent FM:M rating. It's not an ideal solution, but it resolves the biggest issues.
> Improved CamOps Unit Rating Handling Within Clamp

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
This PR modifies the 'Marriageable' and 'Trying to Conceive' flags to explicitly state that underage personnel will not be considered eligible for marriage or reproduction, even if these flags are enabled.
I also changed these tooltips to be multiline tooltips, as they're a little wordy.
closes #4080
> Updated Tooltips for the Marriageable & Trying to Conceive Flags

- MekHQ/src/mekhq/campaign/personnel/Person.java
At some point, I've no idea when, the 'rank multiplier' got snipped out of the salary calculation. This means that salary rank multipliers weren't applying.
This PR restores that functionality.
> Reintegrate Pay Multiplier into Salary Calculation

- MekHQ/userdata/data/universe/ranks.xml
Restored `ranks.xml` in the MekHQ/userdata/data/universe path. The file was accidentally deleted in a prior PR.
This prevents an error in mhq log when mhq is first run.
Turns out 'delete' in GitHub doesn't mean 'discard this change'. Now I know!
> Restored ranks.xml

- MekHQ/src/mekhq/GameThread.java
I created a problem with the "MegamekController" aka KeyDispatcher not being available from MHQ as MHQ did not create a MegaMekGUI. This corrects the problem. I was able to start a story arc mission without problems.
> MegaMek code adaptation

- MekHQ/resources/mekhq/resources/CustomizeScenarioDialog.properties
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioObjectiveDialog.java
The new CustomizeScenarioDialog was quite large which can cause problems on small monitors. So, I redid the layout using tabs to make the overall dialog smaller, as shown in the attached images.
I also fixed a small problem on CustomizeScenarioObjectivesDialog where I was using the wrong label.
> Use tabs in customize scenario dialog

- MekHQ/resources/mekhq/resources/LogEntries.properties
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/log/ServiceLogger.java
This commit introduces a new `ServiceLogger` method to post to the personnel log when a character is captured in a scenario, instead of logging to the scenario log. This ensures that prisoners do not receive scenario credit for the scenario in which they were captured. The change modifies the existing log behavior and includes a new log entry text in the relevant resources file.
Logging in the personnel log ensures there is still a record of the scenario and mission, this feature was requested on Discord when removing the scenario log was discussed.
This PR addresses an oversight reported by our QA team, where prisoners were incorrectly receiving award credit for the scenario in which they were captured.
> Updated Post-Scenario Logging for Prisoners

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/personnel/autoAwards/AutoAwardsController.java
This commit refactors the automatic awards tracking system to handle multiple personnel simultaneously, instead of one-by-one. This is achieved by changing the `person` parameter to a `HashMap` of UUIDs and injury counts in the `AutoAwardsController`'s `PostScenarioController`. Associated methods have been adjusted to handle the `HashMap` data, and the retrieval of kills has been consolidated within methods where necessary.
This resolves a bug discovered by our QA team, where faulty logic was causing auto-awards to trigger multiple times during post-scenario conditions.
> Fixed Post-Scenario Tracking System's Handling of Multiple Personnel in autoAwards

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This commit updates the calculation of `awardTierCount` in the `PersonViewPanel` class.
The new logic determines `awardTierCount` as the minimum between the number of medal files and the maximum of either 1 or the number of awards divided by the `AwardTierSize` specified in the campaign options.
These changes affect ribbons, medals, and miscellaneous awards.
This commit fixes a bug reported on Discord, where the award image getters were counting from 1 instead of 0. Additionally, extra binders have been added to ensure the index is always within bounds.
> Fixed Award Tier Count Calculations in PersonViewPanel

- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/unittests/mekhq/campaign/personnel/education/AcademyTests.java
Another case broken by the move to trim()
> Fix Piloting/Ground Vehicle Parsing in Education Module

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/src/mekhq/utilities/MHQXMLUtility.java
This PR introduces the ability to pass CamOps Fatigue to mm, which is a required functionality for #4101.
This PR depends on [#5516](https://github.com/MegaMek/megamek/pull/5516), which must be merged first. The test failures currently seen are due to this dependency.
- Integrates CamOps Fatigue handling with the mm module.
- Updates relevant parts of the code to pass fatigue information.
- Tests will pass once #5516 is merged.
> Added ability to Pass CamOps Fatigue to MegaMek

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Each graduateCaste method in the EducationController has been adjusted to include a return statement following the method call, thereby preventing the execution of multiple graduateCaste calls within a single instance.
The update eliminates the errors caused by unintended multiple gradations discovered by QA.
> Added Return Statements to Clan Warrior Caste Graduations in Education Module

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This is another quick fix to the display of award ribbons, medals, and miscs in the person view panel. My previous fix appeared to resolve the issue, but instead it failed whenever 'person' had more than one issuance of the award. This adds better bounds by using the `MathUtility.clamp()`.
> Fixed Award Image Display in Person View

- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This PR moves the awards campaign settings into their own panel within the Personnel tab, rather than sitting at the bottom of the expanded personnel information panel.
> Added Dedicated Awards Panel to Personnel Tab of Campaign Options

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/NoCommanderNagDialog.java
- Introduced new Nag dialog for when there's no overall assigned commander in the campaign
- Implemented checkbox option to ignore this reminder
- Updated GUI properties file with No Commander Nag related texts
- Optimized untreated injury check in UntreatedPersonnelNagDialog
Given how much of the turnover and retention module; and upcoming morale module; utilize the overall force commander, it seemed reasonable to have a nag that reminds users to set one.
> Added No Commander Nag Dialog

- MekHQ/docs/AtB Stuff/stratcon-faq-2.5.txt
- MekHQ/src/mekhq/campaign/mission/ObjectiveEffect.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
As per title, this PR renames 'operational victory points' to 'scenario victory points' to match terminology used elsewhere in mhq.
Closes #4043
> Changed "Operational Victory Points" to "Scenario Victory Points"

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Added the ability to reassign Original Unit to currently assigned unit via the personnel table mouse listener. If Person is not currently assigned to a Unit no change occurs.
- Added the ability to wipe Original Unit via the personnel table mouse listener.
Both of these allow users to reassign (or remove) original unit records en masse, rather than needing to do reassignments on an individual basis via the Edit Person dialog.
Closes #4022
> Added Ability to Change Original Unit Assignment via Personnel Table

- MekHQ/resources/mekhq/resources/HireBulkPersonnelDialog.properties
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
This PR adds a 'GM Hire' button to our bulk hire dialog that waives the cost of personnel hired through that dialog.
I also went ahead and added an option to generate personnel with specific skill levels. This way it's possible to hire all personnel at Elite, rather than random, skill rating.
Both of these options are only available if GM Mode is enabled.
I had wanted to extend the same functionality to 'hire minimum complement', but due to the way that menu tree is written I couldn't see an elegant way of achieving this.
> Added GM Hire & Fixed Skill Level Options to Bulk Hire Dialog

- MekHQ/resources/mekhq/resources/LogEntries.properties
- MekHQ/src/mekhq/campaign/log/ServiceLogger.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes an oversight where all four departure methods (retire, resign, desert, and defect) all used the same (retirement) log message.
> Fixed Missing Personal Log Messages for Resign, Desert, and Defect

- MekHQ/src/mekhq/campaign/personnel/Person.java
This should only really affect personnel from very old campaigns that pre-date our tracking of recruitment date.
When reading the xml entries for personnel (i.e., on campaign load) if personnel have `null` recruitment dates, we set their recruitment date at the campaign's current date.
This was causing problems when our pre-made campaigns interacted with the new Turnover and Retention Module; but this issue will affect any instance where we call `getRecruitment()` for personnel from very old campaigns.
For example, the premade campaigns were last updated in `0.47.15` and presumably the personnel contained within are much older.
> Fix NPE Resulting from Null Recruitment Date

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This PR adds a campaign option to optionally disable the salary increase from personnel having secondary roles.
Closes #149
> Added Campaign Option to Disable Salary Increases from Secondary Roles

- MekHQ/resources/mekhq/resources/Campaign.properties
- MekHQ/src/mekhq/campaign/Campaign.java
Following feedback from QA, I opted to change the logic that determines turnover check frequency from `x` days to every Monday; the 1st of every month; or the 1st of every year (campaign option dependent).
> Updated Turnover Frequency Logic in Turnover and Retention Module

- MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
This PR addresses a *really* weird issue where certain modifiers were persisting between instances of the turnover check dialog.
I'll be perfectly honest, I have no idea why this was a problem, nor what was causing it; but this PR fixes the issue by streamlining the modifier calculations for management skill. Which fixes the problem... somehow....
> Streamlined Management Modifier Calculations in Turnover and Retention Module

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This PR adds Campaign Start Date logging to the campaign class. Or, to put it another way, mhq now remembers what date the campaign started on.
I need this for the Turnover and Retention Module, but figured it would also be useful for Story Arcs and (if I ever do it) my RFE for campaign scoring. I also imagined there were other use-cases where knowing _when_ the campaign started might prove useful.
Existing campaigns with a `null` campaign start date have their start date set to whatever the current date is.
> Added Campaign Start Date Logging to Campaign

- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
This PR prevents an infinite loop caused by the new 'fixed skill level' parameter added to the Bulk Hire Personnel dialog.
Basically, when picking roles without skill levels (civilians, or assistants), the fixed skill level can never be reached so mhq gets into an infinite loop of generating persons and then throwing them away (because they don't meet the required skill level).
In addition to fixing this, I also added a new `isAssistant()` method to `PersonnelRole.java` which allows us to more efficiently check whether someone has the `Astech` or `Medic` roles.
> Prevented Infinite Loop from Bulk Hiring Civilian or Assistant Roles

- MekHQ/resources/mekhq/resources/CampaignGUI.properties
- MekHQ/src/mekhq/gui/CommandCenterTab.java
This PR updates the 'Basic Unit Information' panel to show the campaign name instead of 'Basic Unit Information'.
> Changed Title of Basic Unit Information to Use Campaign Name

- MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java
The recent role overhaul unintentionally filtered out all vehicles from the AtB Monthly Unit Market. This PR restores vehicles to the unit market.
~~However, due to code changes, the original functionality of the Unit Market is no longer possible, meaning artillery cannot spawn in the Unit Market without intervention. To address this, I added a handler that replaces 1 in 30 vehicles for sale with an artillery unit. This should produce results similar to how it previously worked.~~ Due to this causing conflicts with #4160 I opted to add this functionality to that PR, instead.
Closes #4203
> Fixed Monthly Unit Market Incorrectly Filtering Out Vehicles

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
This PR fixes a missed instance of XML parsing during campaign load, which prevented the campaign start date from being loaded.
Without this fix, MHQ thinks there's no campaign start date, so it helpfully saves the current date as the start date. This behavior was implemented to support campaigns predating 49.20, and hey, it works!
> Added Parsing for "campaignStartDate" on Campaign Load

- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
This PR addresses a situation where a couple of lines got intersected (probably during merge) in our code to customizing personnel (the edit person dialogue). This caused the setting of fatigue and the saving of any other changes to be reliant on  the `null == choiceOriginalUnit.getSelectedItem()` conditional being `true`.
> Fixed Intersected Conditions in CustomizePersonDialog.java

- MekHQ/src/mekhq/campaign/personnel/enums/education/EducationLevel.java
This PR adds a single new switch case to correctly handle the 'Early Childhood' education level when loading personnel. Failure to include this case resulted in personnel failing to load (though, thankfully, not being deleted from the save file).
Closes #4235
> Fixed Invalid Parsing of Early Childhood when Loading Personnel

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
Added...
- Galedon Military Academy
- Gershwin Academy of Combat
- Gogh-Bukowski University of New Avalon
- Gunslinger Program
- Gunslinger Program [3062]
- Hachiman Technical Institute
- Hero Training Institute [Cap Rouge]
- Hero Training Institute [Maxwell]
- Hero Training Institute [Payvand]
- Hero Training Institute [Sorunda]
- Hero Training Institute [Sterling]
- Hero Training Institute [Trinidad]
- Humphreys School of Warfare
- Humphreys Training Academy
- Humphreys Training Academy [3079]
- Illiushin Taurian Academy
- Imperial Institute of Technology
- Internal Security College
- Irian Academy of Combative Science
- James McKenna University
- Jarvis Military Proving and Training Grounds
- Jefferson University
Also adjusted `baseAcademicSkillLevel` across all prestigious academies. …
> Added Prestigious Academies G-J

- MekHQ/data/universe/academies/Prestigious Academies.xml
This resolved an NPE caused by a missing qualification for the Addicks University. This resulted from a regression.
> Fixed Missing Qualification from Addicks University ... again

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This PR adds a campaign option to restrict the AtB personnel market to Hiring Halls only. When enabled (disabled by default) personnel will only appear in the personnel market while the campaign is stationed at a hiring hall. Furthermore, leaving the hiring hall will remove all personnel from the market.
> Added Option to Restrict AtB Personnel Market to Hiring Halls Only

- MekHQ/data/stratconfacilities/AlliedAirBase.xml
- MekHQ/data/stratconfacilities/AlliedArtilleryBase.xml
- MekHQ/data/stratconfacilities/AlliedBaseOfOperations.xml
- MekHQ/data/stratconfacilities/AlliedCommsCenter.xml
- MekHQ/data/stratconfacilities/AlliedDataCenter.xml
- MekHQ/data/stratconfacilities/AlliedEarlyWarningSystem.xml
- MekHQ/data/stratconfacilities/AlliedMekBase.xml
- MekHQ/data/stratconfacilities/AlliedOrbitalDefense.xml
- MekHQ/data/stratconfacilities/AlliedSupplyDepot.xml
- MekHQ/data/stratconfacilities/AlliedTankBase.xml
- MekHQ/data/stratconfacilities/HostileAirBase.xml
- MekHQ/data/stratconfacilities/HostileArtilleryBase.xml
- MekHQ/data/stratconfacilities/HostileBaseOfOperations.xml
- MekHQ/data/stratconfacilities/HostileCommsCenter.xml
- MekHQ/data/stratconfacilities/HostileDataCenter.xml
- MekHQ/data/stratconfacilities/HostileEarlyWarningSystem.xml
- MekHQ/data/stratconfacilities/HostileIndustrialFacility.xml
- MekHQ/data/stratconfacilities/HostileMekBase.xml
- MekHQ/data/stratconfacilities/HostileOrbitalDefense.xml
- MekHQ/data/stratconfacilities/HostileSupplyDepot.xml
- MekHQ/data/stratconfacilities/HostileTankBase.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java
- MekHQ/src/mekhq/gui/StratconPanel.java
Fix #3974 - added a "user friendly description" field to the facility definition files and the capability to display it on the info tab.
Multi-line descriptions should be broken up by & l t ; br & g t ; ("< b r >", but without the spaces) due to the way that the xml files are read in ("<" and ">" must be escaped)
> Add facility description capability to StratCon

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
This PR adjusts local academy qualification start dates to match their prestigious academy counterparts.
Furthermore, based on QA feedback, officer and enlisted qualifications have been separated to allow more modular costs.
Lastly, incorrect uses of 'First Aid' have been replaced with 'Medtech'.
> Separated Officer and Enlisted Curriculums, Corrected Local Academy Data

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
This replaces instances of `◄` with `<<<` and instances of `►` with `>>>`, in the payout screen of the turnover dialog, as these were not displaying correctly on windows.
> Replaced Non-Universal ASCII Arrow with Braces in Turnover Dialog

- MekHQ/data/stratconcontractdefinitions/GuerillaWarfare.xml
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Corrects calculation in scenario modifier BV allowance. The calculation now correctly incorporates forceMultiplier and correctly converts scenario mod BV cap into a multiplier. Either I forgot to do this, or I left in a test value. Either way, fixed now.
Closes #4269
> Corrected Scenario BV Allowance Calculations for Scenario Modifiers

- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
The new invalid faction nag was incorrectly enabled or disabled by the cargo capacity nag. This PR switches it to correctly use the invalid faction nag option, instead.
> Corrected Dialog Option for Invalid Faction Nag

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
This PR fixes an unintended interaction where personnel would reduce their payout value based on the value of the unit they are given, when resigning or retiring, even if that unit was a unit _they_  owned.
Furthermore, I adjusted the value of mechs being given as part-payment so that they use the sell value of the unit and not the buy price. This ensures mhq isn't treating half an atlas as equal to an intact atlas.
> Fixed Original Unit Value Being Deducted from Payout Sum When Personnel Resign/Retire

- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
I'm not really a big fan of how the C3 network management was implemented in the code, but it is what it is. This adjust the "are all units not c3i networked" check to actually check for that condition - a unit is not c3I networked if it's "free c3i nodes" count is 5 (6 - the 1 unit). If it has fewer than 5 free c3i nodes then it is obviously networked with at least one other unit.
fix #4103
> enable new network creation for units not in a network

- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/src/mekhq/campaign/personnel/enums/education/AcademyType.java
- MekHQ/unittests/mekhq/campaign/personnel/education/AcademyTests.java
This bug was caused by two things:
- when I moved to enum from magic number I forgot to include integers-as-string when parsing from string, so autoAwards didn't know what academy type the award related to.
- the education module was failing to correctly unmarshel the 'type' field into a EducationType enum. I opted to just revert back to parsing a String into the EducationType enum as this was the easiest solution that required the least new code.
> Fixed Graduation Event Failing to Correctly Trigger autoAwards

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
To reduce unnecessary clutter, personnel with 0 Loyalty are intentionally not meant to display their Loyalty in the Person View panel.
However, Commanders have a dynamic modifier that reduces their Loyalty by 1, without changing their actual Loyalty. For instance, a Commander with +1 Loyalty would display as having 0 Loyalty in the Person View panel.
This PR addresses this issue by hiding the Loyalty display for individuals with 0 Loyalty or for Commanders with +1 Loyalty.
> Fixed Commanders Incorrectly Displaying 0 Loyalty

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
This PR adds a Clan Adoption (Abtakha) option to the right-click personnel menu. This option is only available to Bondsmen within a campaign whose faction has the `Clan` tag.
While the ability to set the prisoner status of Bondsmen to `Free` already existed, this was locked behind GM mode. This PR adds that functionality to campaigns whose players prefer not to use GM mode.
This functionality was requested in #4279
> Added Clan Adoption (Abtakha)

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
- Updated the Hiring Halls option text to "Hiring Halls & Capitals Only"
- Modified PersonnelMarket to include capital planets in personnel hiring process
When I initially introduced the option to limit hiring to hiring halls only, I didn't realize how few 'hiring halls' were actually defined in the AtB Config file. This PR expands the option to also allow personnel markets on capital planets.
> Extended 'Hiring Halls Only' Personnel Market Option to Capital Planets

- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/unittests/mekhq/campaign/personnel/education/AcademyTests.java
- Modified getTuitionAdjusted method to implement more precise calculation
- Revised getFactionDiscountAdjusted method for faction restricted cases
- Updated academy tooltip code to reflect the revised calculations
This PR addresses a bug where prestigious academies would not display a tuition cost if `factionDiscount` was 0. The issue stemmed from faulty logic that didn't account for academies with `isFactionRestricted` set to `true` having a faction discount of 0, resulting in the tuition fee incorrectly showing as 0, plus some modifiers.
Additionally, the tuition fee was being incorrectly multiplied by the education level instead of by the difference between the education level and the minimum education level.
While working on this part of the code, I also adjusted how education level …
> Revised Tuition and Faction discount Calculations

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/campaign/finances/Money.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This PR addresses and optimizes a calculation error in the profits method. Previously, profits were incorrectly failing to discount `Starting Capital` and `Financial Term End Carry Over`, resulting in higher-than-intended taxes and Shares payouts. While fixing this, I also optimized the calculation to better handle large volumes of financial transactions.
Additionally, following a conversation with Nick about Campaign Options (see #4281), I removed the two tax exemption campaign options. The reasoning is that users who want their campaign to be exempt from taxes can simply choose not to enable taxes.
> Fixed & Optimized Total Profits Calculation & Removed Exemptions

- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/src/mekhq/campaign/personnel/enums/education/EducationStage.java
This PR does five things:
- Fixes the faction discount multiplier applied to tuition costs if the person comes from the academy's faction. This was incorrectly applying a *0 multiplier, resulting in 0 c-bill tuitions.
- Fixes autoAwards triggering when personnel fail to graduate. This was caused by faulty logic: failing to graduate is a graduation event _technically_, and autoAwards didn't know that not all graduation events result in actual graduation.
- I optimized the ongoing education method to use booleans rather than enum checks.
- I corrected a typo in the `isJourneyToCampus` method
- I fixed a typo in the spelling of the word `Conservatory` in the prestigious academies xml
> Fixed Faction Discount to Tuition, Fixed autoAwards Triggering when Personnel Fail to Graduate

- MekHQ/src/mekhq/gui/CommandCenterTab.java
This fixes a visual bug that caused Administrative Capacity to still display if the Admin Cap option is enabled, but the global turnover option wasn't.
> Fixed Administrative Capacity Displaying while Turnover is Disabled

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Randomly generated units that are cleared to carry bombs currently do so in a somewhat blunt manner - pick a random bomb type, load up to maximum based on carrying capacity until it's just out of thrust.  This PR adds more randomness to the selection process, puts in a few guards to maintain a minimum thrust level, and produces more role-focused selections.  It's a bit chunkier than I would like but should be a good start.
The new process looks like this:
1. Randomly determine how many of the fighters will carry external ordnance, somewhere around half to all
2. For each fighter, calculate a maximum load using minimum thrust values as well as carrying capacity.  Some additional randomness is included.
3. Randomly select a loadout such as "Normal", "Anti-Mech", or "Anti-Conventional". …
> More detailed auto-selection of bombs

- MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
Removed the use of base modifier in the calculation of management skill in the RetirementDefectionTracker class. Now the management skill modifier is directly retrieved from the individual, which simplifies the code and eliminates the possibility of mistakes originating from manipulations with the base modifier.
Closes #4315
Closes #4341
> Refactored management skill calculation in RetirementDefectionTracker

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
The default campaign option for including negotiation in admin experience level was adjusted. The original setting incorrectly used negotiation as part of admin experience levels by default. This has now been disabled by default.
Closes #4326
Update:
I missed another bug report, while I was fixing this. It didn't make sense to put them into separate PRs, so I added to this: I adjusted how experience level is calculated when using the campaign options that incorporate Negotiation and/or Scrounge into the experience level calculation for Admins. This addition closes #4325.
> Corrected Admin Negotiation Experience Level Campaign Setting

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/BriefingTab.java
Changes MHQ autoconfig to use the same information in all places.
Rather than relying on the game instance or its map settings, draw location data about Ground and Space maps from the scenario in all cases.
This may not be necessary, but I'd rather be sure here.
Testing:
> Update autoconfig calls to explicitly set ground/space state from scenario data, not game or map info

- MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
- MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
When using the company generator, personnel will now be assigned a highest education based on their experience level and age. Children are given the 'Early Childhood' education level; ultra-green adults are assigned 'High School'; while all others are assumed to have graduated from college and have the 'college' education level.
This resolves the issue of children spawning with high school diplomas, when generated through the company generator.
Closes #4319
> Added Education Level to Company Generator

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Tooltips for "lblScenarioModMax", "lblScenarioModChance", and "lblScenarioModBV" have been updated in the CampaignOptionsDialog properties file.
'Fixed' modifiers have been renamed to StratCon facility modifiers for more clarity (this was causing confusion among some users).
Closes #4316
> Updated Scenario Modifier Tooltips in CampaignOptionsDialog Properties

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
CamOps excludes support staff from field kitchen capacity calculations, which just doesn't feel right to me. Surely Bill the Admin/HR deserves to eat too!
The option added by this PR is enabled by default and prohibits non-combatants from eating at the field kitchen. This allows us to simulate CamOps, but still leave the option open for non-combatants getting served for users who want that (read: me).
Closes #4329
Addendum: while I was fiddling around in `Campaign.java` I figured I'd also do some light refactoring, to clean things up.
> Added Option to Include Non-Combatants in Field Kitchen Capacity Calculations

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
This PR adds Education Level to the Biographical Filter of the Personnel Table, replacing the 'Founder' column in that filter. Since the Founder flag is also available in the Flags filter, it didn't seem necessary to have it featured in two filters.
Additionally, this implementation includes Education Level in the personnel CSV export.
Closes #4317
Refactoring: I refactored `PersonnelTableModelColumn.java` to use the new enhanced switches introduced in j17
> Added Education Level to Biographical Filter of Personnel Table

- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
Redundant checks in the process of determining faction restrictions were simplified in the Academy class. The code was refactored to clarify the if conditions checks for faction restriction while also bundling the checks for origin and campaign factions together.
This resolves a bug, reported on the forums, where faction restriction wasn't working correctly due to faulty logic.
> Refactored Faction Restriction Checks in Academy Class

- MekHQ/src/mekhq/campaign/personnel/autoAwards/AutoAwardsController.java
autoAwards will now check for scenario awards at the conclusion of a scenario and not just at the conclusion of a mission. I have no idea why I implemented it that way in the first place, but here we are.
> Added Scenario Awards to Post-Scenario autoAward Checks

- MekHQ/src/mekhq/campaign/personnel/autoAwards/AutoAwardsController.java
- MekHQ/src/mekhq/campaign/personnel/autoAwards/KillAwards.java
Updated the getIndividualKills method in KillAwards.java to use stream API for filtering mission kills. Improved the personnel filtering process in AutoAwardsController.java by combining all conditions into a single stream filter and removing the separate method for removing dependents and prisoners.
Closes #4408
> Refactored Kill Count and Personnel Filtering Methods

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
**All credit to SuperStucco. All I've done is duplicated their work to resolve git issues.**
This PR should not be merged until it has been approved by @SuperStucco as the chance of errors creeping in while I transcribed their work is non-zero.
> This is another chunky PR, touches lots of bits and pieces inside AtBDynamicScenarioFactory, some just for readability improvements (so I could follow along easily while testing).  There's a minor interaction with pending #4164 (improved bomb selection), in that the populateAeroBombs(...) method gets called towards the bottom of the generateForce(...) method, but the two are complete independent.
> 
> Side note: due to the fixed MUL loading issue from #4213 and using similar functionality, did additional checking specifically for fixed MUL …
> Added Basic Force Generator Role Functionality to Scenario Random Unit Generation

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
I initially thought that MekHQ didn't implement the damage-tracking system Campaign Operations uses for infantry and vehicle crew, only to realize upon opening the code that it does. The confusion lies in the fact that those settings are not marked as unofficial even though changing them violates official rules.
Since I doubt I'm the only person to assume those were optional official rules, I'm updating the label.
> Mark Medical settings as unofficial

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Awards would display incorrectly if award tier was set to 1, effectively skipping the first tier of award images. This PR addresses that.
> Refactored Award Tier Count Calculation in PersonViewPanel

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
The code for improving skills in the EducationController was refactored to simplify and clean up the existing implementation.
Redundant code was removed, such as the calculation of the education level which is now performed in a single line.
These changes also resolve an infinite loop that could occur if a student is attending a doctorate while also having a skill bonus to the skill improved _by_ that doctorate.
> Refactored Skill Improvement Logic in EducationController

- MekHQ/data/universe/awards/standard.xml
- MekHQ/src/mekhq/campaign/personnel/autoAwards/MiscAwards.java
Added checks for 'Prisoner of War' eligibility in 'MiscAwards.java'.
The 'Prisoner of War' award was relocated in the 'standard.xml' file for better organization. Additionally, changed group categorizations for 'Medal of Honor' and 'Ceremonial Duty' as these haven't been manual for a while and I must have just forgotten to move them.
> Expanded autoAwards Coverage to Include 'Prisoner of War'

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
- MekHQ/src/mekhq/module/atb/AtBEventProcessor.java
- MekHQ/unittests/mekhq/campaign/market/ContractMarketAtBGenerationTests.java
In order to facilitate custom mercenary factions, update the mission and contract generation to use the isMercenary() function.
While I was making the changes, I also changed the "PIR" and "REB" references with isPirate and isRebel so as to avoid having mixed call styles.
Also added required mock functions to the unit tests.
resolves MegaMek/mekhq#4318
> Update static faction references with appropriate isX() call

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Fixes #4429.
The 'fixed' scenarios like Base Defense, which are generated via code rather than using scenario template XMLs, call methods in AtBDynamicScenarioFactory so they do not have the same support for passing roles.  For now they pass null for the required roles parameter, which requires a bit of extra handling.
There should be some consideration to consolidating these scenario types to use the same template system as the standard scenarios, both for streamlining and to make it easier to customize them at the user/player level.
> Null protection when generating forces from fixed scenarios like Base Defense

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
The EducationController was updated to skip the processNewYearChecks functionality if the academy is homeschool-based.
Closes #4434
> Added processNewYearChecks Skip for Homeschool Academies

- MekHQ/src/mekhq/gui/dialog/ManageAssetsDialog.java
The asset removal event was being called after the asset had been removed, resulting in an out-of-index error. This PR just re-orders them so that the object still exists at the called index when the event occurs, it is then removed once processing has been completed.
Closes #4437
> Reordered Asset Removal and Event Trigger in ManageAssetsDialog

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
References to RibbonFiles were corrected to MedalFiles and MiscFiles allowing the correct file to be fetched.
Closes #4448
> Corrected Award File References

- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
The color options for paid retirement status in the MHQOptionsDialog were removed. This includes both the background and foreground options. These changes simplify the user interface and reduce clutter, as these options were vestigial their implementation having been removed in 49.20.
> Removed Paid Retirement Color Options

- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
A `WindowAdapter` was added to the `PersonnelMarketDialog` class, which triggers an update to paid recruitment when the window is closed.
This action, `closeOrCancelActionPerformed()`, was extracted from `btnCloseActionPerformed()` to be reusable. This method ensures that certain cleanup activities are performed whether the dialog is closed via the close button or by manually closing the window. Previously, they would only run when the window was closed via the close button.
Closes #4335
> Added Window Closing Event to PersonnelMarketDialog

- MekHQ/build.gradle
Added build all task to build all 3 repos and copy the distribution files into a single folder within MHQ's build directory `./MekHQ/build/distributions`
To run: `./gradlew buildAllPackages` and wait for it to finish.
> Added build all task

- MekHQ/src/mekhq/campaign/personnel/randomEvents/PersonalityController.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Modified the dimensions of the PersonnelMarketDialog and the tabUnit in the MekHQ application interface to be more compact and user-friendly. Improved handling of text in both the PersonalityController and PersonViewPanel by removing inline CSS and incorporating word wrap.
This PR requires https://github.com/MegaMek/megamek/pull/5780 and will fail while that PR remains unmerged.
Closes #4474
> Adjusted UI layout and Improved Text Handling for Personnel Market

- MekHQ/resources/mekhq/resources/Rating.properties
- MekHQ/src/mekhq/campaign/rating/UnitRatingMethod.java
The 'FM: Mercenaries (rev)' unit rating method was marked as deprecated for the purposes of user-facing campaign options. Additionally, the switch statement in the UnitRatingMethod.java file was simplified to a more modern syntax to enhance readability and maintainability.
This is the first step in us moving away from supporting FM:Mr with a mind to more broadly adopting CamOps systems.
> Marked 'FM: Mercenaries (rev)' Unit Rating Method as Deprecated

- MekHQ/src/mekhq/campaign/report/PersonnelReport.java
With this PR the personnel report will consider injured bondsmen as combat personnel if they have a combat primary role. Previously it always considered them Support personnel.
Similarly, the personnel report no longer considers injured prisoners as support personnel.
Closes #4386
> Updated Personnel Report to Better Handle Bondsmen & Prisoners

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/MapTab.java
Somehow I managed to accidentally all but wipe #4462 prior to it getting merged. It's definitely a case of error between keyboard and chair, but either way, this PR restores the code.
Furthermore, an oversight in the storing of turnover results across days caused it to never be forgotten so users would get spammed with their turnover results every day. On the bright side, this means it was currently storing the information across new day events! Not ideal though, so this PR also fixes that.
I also spotted that the leasing of DropShips was using a lossy implicit cast in a number of places, so I corrected that. DropShip need calculations should now be a little more accurate. Eventually we probably want to move this from `Campaign.java` and give it a full review to make sure everything is …
> Fixed Missing Site Location Change Code & Turnover Information Storage

- MekHQ/data/universe/academies/Unit Education.xml
Adjusted the start years for multiple apprenticeship and training programs in the Unit Education.xml file. These changes aim to align the timelines with established lore.
The benefit of this, is that unit education start dates are a little before the start dates for equivalent courses in established academies. This is due to there being a lag between a technology arriving and courses in it being offered at your local Tech College. Unit education bypasses this lag by having Sgt. Barry "Slaughterhouse" Wilson handle the education.
> Corrected Qualification Start Years

- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/campaign/personnel/autoAwards/AutoAwardsController.java
- MekHQ/src/mekhq/campaign/personnel/autoAwards/RankAwards.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/AutoAwardsDialog.java
This has been a feature much requested since I first started work on autoAwards. Via this PR I have added a new 'promotion' sub-category of Rank Awards. These awards are triggered whenever someone changes rank, but rather than being tied to specific thresholds, each award is assigned a specific rank. It will only be issued to personnel with that specific rank and, when issued, all other promotion type awards will be removed.
The use case here is for users who want to use autoAwards to distribute and manage rank insignia. To that end, I have also added functionality so that users can optionally limit promotion awards to only be valid for specific Rank Systems. For example, you might have one set of rank insignia for the SLDF and another for the MAF.
Documentation has not been updated for …
> Added Promotion-Based autoAwards Processing

- MekHQ/src/mekhq/campaign/personnel/Award.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
The tooltips for awards will now show what XP and Edge awards have been granted by those awards. This respects campaign options, so will not show Edge if Edge benefits from awards have been disabled.
> Improved Award Tooltips with XP & Edge Benefits

- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Updated the TO&E so that the origin node (the one that has the campaign name, by default) will always display the campaign commander if one has been set. Previously it would display the last person to be placed in the top level (usually some random character that got plonked there by accident).
In the event that there is no campaign commander, the field is left blank.
These changes are visual only.
Closes #4270
> Edited Commander Display in TO&E for Origin Node

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
Removed the 'uneventful' graduation event, as the relevant resource bundle had been removed at some past date and the reference was causing missing resource errors.
I also added a shuffle operation to randomize the order of graduation events in the `EducationController` because I'm fancy like that.
> Removed Vestigial 'Uneventful' Graduation Event

- MekHQ/src/mekhq/campaign/Kill.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/gui/dialog/AddOrEditKillEntryDialog.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
Added `forceId` and `unitType` attributes to the `Kill` class for better tracking of kill details and enhanced functionality.
Nothing is done with this information, in this PR, but this allows us to do some cool stuff, such as allowing users to filter out certain sources of kills - for example, I know some users don't count kills from infantry. It also opens the door for an entirely new type of Award based on `x` number of `y` units killed - something I know a number of users requested during the design stage of autoAwards.
Replaced `LogManager` with `MMLogger` for consistent logging across the application.
> Added Force and Unit Type to Kill Tracking

- MekHQ/data/universe/academies/Prestigious Academies.xml
Updated the descriptions of Capellan Warrior House Orders to remove placeholder descriptions. Adjusted location systems for Warrior House Ma-Tsu Kai and corrected details such as construction years and curriculum specifics. Removed references to the Star League for academies that existed before the Star League. Corrected one or two minor typos.
Closes #4518
> Education Module Data Fixes

- MekHQ/src/mekhq/campaign/Campaign.java
Support Score is used by autoAwards to track who is eligible to be awarded 'support person of the year' style awards. Unfortunately, it failed to include a handler for when an individual has an experience level score of 0 (Ultra-Green). As `Compute.d6()` cannot handle rolling `0d6` it throws an error. This PR fixes that oversight.
> Fixed Support Score Calculation

- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
This PR adds a "Buy in Bulk" button to the Parts Acquisition dialog in the Repair Bay, closing #2925.
I re-used the "Buy in Bulk" dialog from the CampaignGUI so very little new logic had to be implemented. The user clicks the "Buy in Bulk" button, a prompt opens up with a text box asking how many, and then the parts are added to the procurement list like normal:
View from the main Campaign GUI after ordering multiple parts:
Note that I also simplified/removed some redundant code when determining the text to display on the order button.
I did not touch the properties files in resources, although I think this is necessary for translations to work. Just let me know what I need to do there and I'll be happy to take care of it.
> Add "Buy in Bulk" Button to Parts Acquisition in Repair Bay

- MekHQ/data/universe/factions.xml
- MekHQ/src/mekhq/campaign/universe/Faction.java
I've updated the era modifiers for each faction to reflect the fourth printing of _Campaign Operations_, which extends to the Dark Age and ilClan eras as well.
> Update era modifiers to reflect CamOps

- MekHQ/src/mekhq/campaign/unit/Unit.java
Adjusted the sale value calculation for infantry (and BA) units by using their alternate cost method. This ensures that the sale of infantry is computed correctly and appropriately matches their purchase value.
Whether this final value is entirely correct is a matter for bigger brains than mine to debate. However, this at least matches the equipment value without factoring in personnel training. As you're selling the equipment, not the personnel.
This change will affect any instance where we use the sale value of an infantry or battle armor unit. Salvage immediately comes to mind, but likewise so does the campaign option to use unit sale value when calculating contract pay.
> Adjusted Sale Value for Infantry and Battle Armor Units

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
Added tracking of child dependents when a character attends an out-of-unit education.
Now, when characters attend an outside-unit academy they will take any child dependents with them. This is true even if there is another parent remaining with the unit. The logic there is that academies are perceived as safer than an active military unit.
Any children tagging along in this way will have their status set to `On Leave` for the duration of the academic education, even if they cease being considered a child during that time. Babies born while the mother is at an academy are automatically factored into this system.
When the education concludes and the parent successfully returns to the unit all 'tag alongs' have their status set to `Active`.
> Improved Handling of Child Dependents When Attending Academies

- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Previously, the re-enrollment eligibility counter was only incremented for existing skills with lower experience levels than those offered by the qualification. Now, it also increments when the skill is missing.
Furthermore, we were incorrectly parsing an `Optional` directly to `String` instead of using the `get()` which caused issues with re-enrollment, as well as any Education Module check that relied on `Faction`.
> Fixed Re-enrollment Checks

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
This PR addresses a small bug that caused errors when personnel were graduating from Education Level 0 (Early Education) academies, and when graduating from Post-Graduate and Doctorate academies.
I also fixed the color of the highlight text used when getting a Master's or Doctorate degree. MekHQ no longer thinks they are negative events.
> Corrected Errors in Post-Grad & Doctorate Graduation Handler

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/MapTab.java
- MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Standardized the names for various repair sites in the `getSiteMod` and `getSiteName` methods to match CamOps. I also added tooltips to the options when picking a repair site.
> Updated Repair Site Names to Match CamOps

- MekHQ/data/universe/awards/standard.xml
In what must be the smallest PR I've done to date: I've reclassified 'Prisoner of War' award grouping from 'Manual Awards' to 'Personal Awards'.
> Fixed Prisoner of War Award Categorization

- MekHQ/src/mekhq/campaign/universe/Faction.java
Adjusted the era mod loop to iterate based on the length of the `eraMods` array instead of the `values` array. This change prevents potential index out-of-bounds exceptions and ensures all elements in eraMods are correctly assigned.
> Fixed Index Out-of-Bounds Error During eraMods Parsing

- MekHQ/src/mekhq/campaign/unit/Unit.java
Revised the method for calculating the sell value of infantry units, incorporating unit quality multipliers. This fixes an oversight in #4572.
> Refactored Infantry Sell Value Calculation to Include Unit Quality Multipliers

- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Previously, the injury fatigue checkbox was incorrectly toggling visibility, instead of selection. Whoops!
> Fixed Injury Fatigue Checkbox
