- MekHQ/src/mekhq/Utilities.java
... and leaving the UUID generation to the campaign in generateRandomCrewWithCombinedSkill()
> Replacing addPersonWithoutId with recruitPerson

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/finances/Loan.java
- MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
- MekHQ/src/mekhq/campaign/market/UnitMarket.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
- MekHQ/src/mekhq/campaign/universe/UnitTableData.java
This PR doesn't change any functionality, just updates the `Utilities` class to be more useful for future development:
`combineString(collection, separator)` is changed so that it can deal with *any* `Collection` class, not just `Vector`. It's also speeded up considerably by using a `StringBuilder` explicitly instead of creating and destroying one implicitly once per loop.
`getRandomItem(collections)` returns a random (unweighted) item from a collection of them. It returns *null* if the collection itself is *null*, has no items, or the picked item is *null*. There is a special optimised version of the method for `List` classes. Where trivially possible, other classes needing it have been changed accordingly.
`lerp(fromValue, toValue, fraction)` is a simple linear interpolation method, in …
> Updates to the Utilities class

- MekHQ/src/mekhq/gui/CampaignGUI.java
Dependents can now be sorted like any other group. Makes them easier to
find and handle in large units
> UI Enhancement - Added Dependents group to Personnel Type menu

- MekHQ/src/mekhq/campaign/MercRosterAccess.java
- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/EnginePart.java
- MekHQ/src/mekhq/campaign/parts/MissingEnginePart.java
- MekHQ/src/mekhq/campaign/parts/SpacecraftEngine.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/MekLabPanel.java
- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
- MekHQ/src/mekhq/gui/view/UnitViewPanel.java
Required change to make MekHQ work with https://github.com/MegaMek/megamek/pull/154
> Updating tonnage/mass to use doubles

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/adapter/OrgTreeMouseAdapter.java
Fixes several minor bugs I have found (or missed).
> Bugfix for Issues #1 #55 #56 #57 and #59

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/src/mekhq/resources/PersonViewPanel.properties
An optional feature to refine the display of of immediate family (children) of a given person. Useful for tracking families. If there is enough interest I will do an enhancement that display parent information as well.
This would work extremely well if hyperlinks worked in the person panel as well but I believe they are only designed to work in the daily log.
> UI Enhancement - Show children in person panel

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/rating/InterstellarOpsReputation.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CustomizeMissionDialog.java
Will need to pull PR MegaMek/megamek#216 as well to complete #64
> Bug fix: IO Exp Rep Value, NPE when hiring via menu, Issue #64, Issue #63

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Added null protections to AtbScenario.setPlanetaryConditions.
> Issue 89 - Added null potections to AtBScenario.setPlanetaryConditions.

- MekHQ/src/mekhq/campaign/personnel/Person.java
At conception the mothers name is hyperlinked
At birth the childs name is hyperlinked
I created this as both messages in the daily log can be missed. Also, some childrens names... well, best to see it and rename the poor kid immediately.
> Conception and Birth now have names hyperlinked.

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
> Issue96 Fix

- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/campaign/universe/Planets.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
(PR, so I can consolidate all the individual pushes easier)
> Adding an ISW map overlay to the interstellar panel

- MekHQ/src/mekhq/campaign/parts/AeroHeatSink.java
- MekHQ/src/mekhq/campaign/work/WorkTime.java
Fixes issue #165 with swapped tech ratings in aeroheatsink.java
Fixes issue #164 reverts multiplier to original values of x3 and x4
> Bug fix for #165 and #164

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/src/mekhq/resources/PersonViewPanel.properties
Option created to log conception and birth to personnel log. No change to current notification via daily log
Added due date to person panel below persons current status.
Should satisfy feature request #144
> Feature: Log conception and birth in personnel log

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/gui/adapter/OrgTreeMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
> Bugfix for #182, #185, and #87

- MekHQ/build.xml
- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
Should fix the infantry and protomech tech issues with CO.
> Issue #215: CO Rating showing tech shortage due to infantry.

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/MekLabPanel.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/ChooseRefitDialog.java
Adds the ability to refurbish a unit as described in StratOps pg189
Up to date with current release. Follows current rules as written
> Feature: Refurbishment

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/resources/PersonnelTableMouseAdapter.properties
Adds a new menu item to manually add or remove a pregnancy. Implements part of request #263
> Feature add/remove pregnancy

- MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java
If you select multiple tasks/parts and change mode (Extra Time / Rush Job) / scrap, all of them should change. I am tired of setting it one by one...
> Allow setting repair modes/scrapping of multiple tasks/parts at once

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
This class is responsible for three of the five Codebeat quick fix suggestions.
> Newrecruitdialog cleanup

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/MekHQ.java
Make the log files reset between MHQ runs.
> Make the log files reset between MHQ runs.

- MekHQ/src/mekhq/AtBGameThread.java
Fix for https://github.com/MegaMek/mekhq/issues/431
> Run method did not set LocalPlayer colorIndex, add line of code to do so

- MekHQ/src/mekhq/campaign/mission/atb/scenario/AceDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AlliedTraitorsBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AmbushBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDualBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
Fix for https://github.com/MegaMek/mekhq/issues/437 & https://github.com/MegaMek/mekhq/issues/410
reinitialized enemyEntities in between loops
> Fix for issue #437 and #410

- MekHQ/src/mekhq/gui/BriefingTab.java
This is to fix https://github.com/MegaMek/mekhq/issues/458
> Changed to call for missionRefresh after a scenario is resolved

- MekHQ/data/universe/factions.xml
- MekHQ/src/mekhq/campaign/universe/Faction.java
Updated factions.xml from SUCS Data and changed altNames to
altNamesByEra to add altNames that are alternate names for factions, not
name changes.
> Update factions.xml and Faction.java

- MekHQ/src/mekhq/campaign/parts/equipment/MissingAmmoBin.java
Fix for https://github.com/MegaMek/mekhq/issues/455
> Check muntions type before replacing missing ammo bin

- MekHQ/src/mekhq/campaign/Campaign.java
https://github.com/MegaMek/mekhq/issues/280
MekHQ, when randomly assigning portraits, will first search for a gender/role directory.
ie
Female/Doctor
Female/Mechwarrior
Edit: This will now use one "Admin" directory for all four admin roles.
ie
Male/Admin
Female/Admin
> Implements FR #280 Discreet Portait Folders

- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
Fixes ever-increasing tech/support requirements. (Issue #557)
> Reset FM:Mercs calculated values on reInitialize()

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
> Fixes for scenario resolution

- MekHQ/src/mekhq/campaign/CampaignOptions.java
> Fix typo preventing load of useSupportEdge rule from cpnx

- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
Because sometimes you just get too lazy to math it out, y'know?
> Add "Advance to Next Month" option to Advance Multi Days Dialog

- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
Implementation of some of the most commonly replaced items for Issue #275, armor and ammo.
> Improved availability info. Crash fix.

- MekHQ/src/mekhq/gui/RepairTab.java
> Stabilize "Do Task" section proportions in repair tab.

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
Column index wasn't properly updating for some of the AtB options.
> Adjusted checkbox ordering

- MekHQ/data/universe/planets.xml
Addresses Issues #614 and #615 conforming the faction change data for Trondheim and Adherlwin to what is provided on Sarna.net
http://www.sarna.net/wiki/Trondheim_(FRR)
http://www.sarna.net/wiki/Adherlwin
> Faction Change Corrections

- MekHQ/packaging_utils/JavaApplicationStub
Removes excess white space and ensures correct line endings.
> Line Ending/White space cleanup

- MekHQ/src/mekhq/gui/MekLabTab.java
Which caused a compilation error.
> rolling back unnecessary compilation error fix

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
> Reset doomed and ejected flags between missions

- MekHQ/src/mekhq/Utilities.java
In most cases, this should allow SPAs to properly come in from a MUL file.
> Fix for #108 - implement SPA import from MUL

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
- MekHQ/src/mekhq/resources/Finances.properties
Should fix #698, and if it doesn't we'll have to dig deeper.
> New day cleanup

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizeMissionDialog.java
- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
- MekHQ/src/mekhq/gui/view/AtBContractViewPanel.java
- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
- MekHQ/src/mekhq/gui/view/ContractViewPanel.java
- MekHQ/src/mekhq/gui/view/MissionViewPanel.java
It was used as both name and ID, which is not correct as they're 2 different fields.
I chose to make it the ID since that is what it should always have been.
This is a dangerous merge and needs thorough testing prior to stable.
This is likely to delay stable by another month.
Fixes #328 If you accept a contract on Taussen, the game teleports you back to Terra once you arrive
> Update Mission.planetName to Mission.planetId for consistency.

- MekHQ/src/mekhq/campaign/CurrentLocation.java
Whups, @jayof9s pointed out that we missed the part in `CurrentLocation.java`
> Fix the campaign level planet pt. 2

- MekHQ/src/mekhq/campaign/parts/MissingOmniPod.java
The `OmniPod` class represents a part that does not have the equipment installed in it, which can only exist in the warehouse (an intact pod is indicated by a boolean field on the `EquipmentPart`). For the purposes of acquisition, it requires a corresponding `MissingPart`
> Added MissingOmniPod class needed for acquisition.

- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizeMissionDialog.java
Fix for problem uncovered by issue #734
> Allow non-canon planet names as contract locations

- MekHQ/docs/AtB Stuff/AtB documentation.19_8 (WIP).txt
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
Related to the issue #735 
I found a couple places with the presumably old domain name.
```
$ grep -Ril "megamek.info" .
./MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
./MekHQ/docs/AtB Stuff/AtB documentation.19_8 (WIP).txt
```
> megamek.info -> megamek.org

- ReadMe.md
add a basic markdown readme for the Github project page
> add a basic markdown readme for the Github project page

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
Should work the same as the KIA checkboxes added previously for the player's own pilots during scenario resolution.
> Add KIA checkbox and functionality to prisoners

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/resources/PersonnelTableMouseAdapter.properties
Per discussion with Paul Range Master will get the same errata treatment Sniper did.
Sniper errata here: https://bg.battletech.com/forums/index.php?topic=53442.msg1416053#msg1416053
> (Errata) Range Master does not affect LOS range

- MekHQ/src/mekhq/gui/dialog/MekHQAboutBox.java
> make link on the Help->About page a clickable URL link

- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
- MekHQ/src/mekhq/resources/AdvanceDaysDialog.properties
This just converts some hardcoded text to the resource map.
> convert the advance days text to resourceMap

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/WarehouseTab.java
- MekHQ/src/mekhq/gui/model/PartsTableModel.java
- MekHQ/src/mekhq/gui/model/ProcurementTableModel.java
* adds a column to the warehouse parts list and procurement list showing the total value of each part group
* fixes an issue in finance where the spare parts net worth was not accounting for the quantity
> adds total value for parts and fix issue with net worth calculation for parts

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/unit/UnitTechProgression.java
- MekHQ/src/mekhq/campaign/universe/NewsItem.java
These are not used (Eclipse throws warnings).
> remove unused imports

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
This has been missing from the CO rating for awhile.
> Admin now calculated correctly for government forces.

- MekHQ/src/mekhq/campaign/finances/Transaction.java
- MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/EditTransactionDialog.java
There were two issues:
* Upon editing a transaction and clicking cancel, it would still add a report to the daily log on the right.
* Upon making an edit, it would show the new entry for both transaction reports in the daily log.
> Two fixes to GM mode finances -> edit transaction

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/PartInventory.java
- MekHQ/src/mekhq/campaign/parts/PodSpace.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/LargeCraftAmmoBin.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/gui/model/TaskTableModel.java
- MekHQ/src/mekhq/service/PartsAcquisitionService.java
- Implements 2016 TODO from Cord Awtry (kipstafoo)
- Hoists out some common formatting of in transit and on order counts
(apologies if some of this is not idiomatic Java, I'm not active in Java development anymore)
> Refactors part inventories from a string array to a concrete class

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/model/RetirementTableModel.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
> fix text color of selected person/unit from black to white

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
> Adjust contract pay doesn't seem to work

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
Dragoon rating modifier wasn't negated. Second commit is whitespace only.
> Bug: AtB morale calculation didn't handle dragoon rating properly

- MekHQ/src/mekhq/campaign/Campaign.java
Addresses concurrent modification exception seen in #860.
> Bug: Don't remove units in same loop as the read #860

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Implements #475 
Also added scroll pane to award list.
> Sorts Choose Spouse (Mate) and Special Ability lists

- MekHQ/src/mekhq/campaign/personnel/Person.java
Implements #877, categorizing births and pregnancies as medical in the personnel log.
> Feature: Categorized births and pregnancy log entries as medical

- MekHQ/src/mekhq/campaign/AwardSet.java
- MekHQ/src/mekhq/campaign/personnel/Award.java
- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
As requested:
- Fixes the ribbon sorting.
- The order that awards appear in the .xml define their priority (top of the xml = highest priority)
> Awards fixes 1

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/service/PartsAcquisitionService.java
> Fixes #855 introduced by me in PartInventory cleanup

- MekHQ/data/universe/factionhints.xml
Fixes three dates not in ISO-8601 format.
> Fix date formatting in factionhints.xml

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorAmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
- MekHQ/src/mekhq/gui/model/RetirementTableModel.java
Should be no visible change from the point of view of the user.
> convert some system.out.println()s to standard logging format

- MekHQ/src/mekhq/campaign/Campaign.java
Fixes NPE seen in the logs for #853.
> Bug: On multi-day repairs do not report on the unit if not present

- MekHQ/src/mekhq/campaign/Campaign.java
This addresses #849 by:
1. Taking the maximum experience level among the commander's primary *and* secondary role.
2. Applying +1 XP to a person under their command if their primary *or* secondary role is Green (or Ultra-Green)
> Feature: Consider a person's secondary role during training XP calculations

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
This solves a NPE due to a field not being initialised.
> Bug: NPE in ResolveScenarioTracker

- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
> ContractMarketDialog table should not be editable

- MekHQ/src/mekhq/campaign/parts/AeroHeatSink.java
- MekHQ/src/mekhq/campaign/parts/AeroLifeSupport.java
- MekHQ/src/mekhq/campaign/parts/AeroSensor.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/Avionics.java
- MekHQ/src/mekhq/campaign/parts/LandingGear.java
- MekHQ/src/mekhq/campaign/parts/MissingAeroHeatSink.java
- MekHQ/src/mekhq/campaign/parts/MissingAeroLifeSupport.java
- MekHQ/src/mekhq/campaign/parts/MissingAeroSensor.java
- MekHQ/src/mekhq/campaign/parts/MissingAvionics.java
- MekHQ/src/mekhq/campaign/parts/MissingLandingGear.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/SpacecraftEngine.java
- MekHQ/src/mekhq/campaign/parts/StructuralIntegrity.java
- MekHQ/src/mekhq/campaign/parts/Thrusters.java
- MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java
- MekHQ/src/mekhq/campaign/parts/equipment/MissingAmmoBin.java
- MekHQ/src/mekhq/gui/RepairTab.java
Depends on the branch of the same name in MM. This removes a hack that's been in HQ for a couple years to get omnifighter pod space to work properly, and includes aerospace system parts in the fuselage or hull location as well.
> System wide equipment

- MekHQ/.gitignore
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignFactory.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParseException.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/FileDialogs.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/src/mekhq/io/FileType.java
- MekHQ/unittests/mekhq/io/FileTypeTest.java
This PR adds support for gzipped campaign save files.
1. Campaign XML parsing is moved to `CampaignXmlParser`.
2. Campaigns are loaded via a factory which detects the format of the file.
3. Saving the campaign checks to see if it was loaded from a `.cpnx.gz` and will try and honor that.
> Feature: Adds gzipped Campaign save file support

- MekHQ/data/universe/factions.xml
This is a work in progress. I'm updating faction data so that assigning a random faction to a person is reasonable enough for MekHQ's purposes.
> Update faction data for randomized assignment project

- MekHQ/src/mekhq/campaign/Campaign.java
Speeds up campaign loads some by:
1. Only doing spare parts matching on load for "spare" parts (no unit assigned).
2. Not recreating a massive `ArrayList` when it searches for these spare parts.
350 mb CPNX before:
```
mekhq.campaign.Campaign.checkForExistingSparePart() | 88.9211 | 1,504,879 ms (88.9%) | 1,504,879 ms | 1,506,272 ms | 1,506,272 ms
```
after:
```
mekhq.campaign.Campaign.checkForExistingSparePart() | 29.041937 | 43,270 ms (29%) | 43,270 ms | 43,379 ms | 43,379 ms
```
> A few minor tweaks to spare parts searches at CPNX load

- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
Fixes an NPE when you load the GM Tools dialog, missed this one during review.
> Fix NPE when you load the GM Tools dialog

- MekHQ/src/mekhq/gui/FileDialogs.java
Corrects string format statement in export personnel, fixes #985.
> Bug: Can't export personnel

- MekHQ/src/mekhq/Utilities.java
This adds some new information to help with debugging these issues (namely the list of equipment parts):
```
13:41:27,817 WARN [mekhq.Utilities] {SwingWorker-pool-1-thread-1} 
Could not unscramble equipment for Highlander HGN-732b (5f007720-ddf4-4846-9519-bba49439b09d)
- LRM 20 Ammo Bin equipmentNum: 11
Equipment Parts:
2: SRM 6 Left Arm SRM 6 
4: Gauss Rifle Right Arm Gauss Rifle 
5: Jump Jet Left Torso Jump Jet 
6: LRM 20 Left Torso LRM 20 
8: SRM 6 Ammo Bin Left Torso SRM 6 Ammo 
10: LRM 20 Ammo Bin Left Torso LRM 20 Ammo 
11: LRM 20 Ammo Bin Left Torso CASE  (Missing)
12: Jump Jet Right Torso Jump Jet 
14: Medium Laser Right Torso Medium Laser 
15: Medium Laser Right Torso Medium Laser 
16: Gauss Rifle Ammo [IS] Bin Right Torso Gauss Rifle Ammo [IS] 
17: Gauss Rifle Ammo [IS] Bin …
```
> Further improve unscramble equipment debug logging to help with CPNX load issues

- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
This enables a force in the TOE to have its camouflage changed en masse.
> Adds a Change Camouflage menu item to the TOE

- .gitignore
Updating .gitignore to work with Intellij IDEA
> gitignore for IDEA

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/RandomSkillPreferences.java
- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/parts/Turret.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/WarehouseTab.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
Cleaning most of the errors reported by lgtm (https://lgtm.com/projects/g/MegaMek/mekhq/alerts/?mode=list&severity=error)
Some seem real errors or possible bugs. The ones that are about type checking for subclasses could be argued if they make the code more or less clear.
> Static analysis cleanup

- Intellij-Java-Default.xml
- MekHQ/.editorconfig
Adding editorconfig and Intellij default settings following MegaMek Code Style Guide.
Read more about using this on Intellij here: https://www.jetbrains.com/help/idea/configuring-code-style.html
> Styling files

- MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
Apparently you need to initialize an array list before calling Collections.copy to put items into it.
> Fix bug preventing addition of new force templates

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/ScenarioTemplate.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifier.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
Cleans several errors and warnings reported from LGTM:
- Not closed files
- Unreachable casts
- Narrowing conversions (double to long/int)
- int math overflow
Still a lot of warnings pending, trying to break this into smaller PRs.
> Lgtm cleaning

- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
> Adds a Force column to the Hangar

- azure-pipelines.yml
This is just the YAML setup for Azure pipelines. It will need Marketplace integration.
(safe to squash)
> Add CI/CD support via Azure pipelines

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/market/ShoppingList.java
- MekHQ/src/mekhq/campaign/parts/PodSpace.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/unit/UnitOrder.java
- MekHQ/src/mekhq/gui/BasicInfo.java
- MekHQ/src/mekhq/gui/MekLabTab.java
- MekHQ/src/mekhq/gui/dialog/LargeCraftAmmoSwapDialog.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
- MekHQ/src/mekhq/gui/view/UnitViewPanel.java
Cleans up something I noticed in Unit.java in another PR.
> Do not expose Campaign as a public field in Unit

- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/gui/dialog/ShipSearchDialog.java
ShipSearchDialog was trying to format money as number instead of using the new Money formatting methods.
> joda-money bugs

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
Adds "Add Full Complement" to GM unit menu as well.
> Address bug in Personnel Market where GM Add still costs money #1076

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/personnel/Bloodname.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/universe/RATManager.java
- MekHQ/src/mekhq/campaign/universe/StarUtil.java
- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/WarehouseTab.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/service/MassRepairService.java
Adds missing null checks in a few places (lgtm static analysis).
> Adds null checks missing in a few places (lgtm)

- MekHQ/src/mekhq/gui/BriefingTab.java
> fix npe when deploying individual units rather than force

- MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
If the initial planet selection comes up as empty, avoid NPE. Fixes #1082
> minor bulletproofing

- MekHQ/src/mekhq/campaign/finances/Loan.java
Updating loan class to fix issues related to the field totalValue which is not used anywhere.
> Joda money issues

- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/gui/dialog/UnitSelectorDialog.java
Fixing NPE in refit.java as cost was not initialized.
Fixing int overflow in PartStoreDialog.
Standarized sorting for PartStoreDialog and UnitSelectorDialog.
> Money issues

- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
Fixes exception seen in MekHQ log in #1115. I missed this my first go around.
> Fix stack overflow in BattleArmorSuit::getTonnage #1115

- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
> Show Bloodname in Fluff Tab

- MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
Fixes a NPE in the retirement dialog preferences.
> Fix NPE by checking if the dialog is doing retirement or not

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Adds a dice roll to see if BA is actually salvageable or not, as per SO page 176.
> Fixes issue #70

- MekHQ/resources/mekhq/resources/EditTransactionDialog.properties
- MekHQ/src/mekhq/gui/dialog/EditTransactionDialog.java
Fixes several double/text/money conversions
Changes the .properties file for the EditTransactionDialog
This fixes #1174
> Fixes issues when editing a transaction

- MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
Fixes an NPE which causes the accessibility system to behave very strangely.
> Fix an NPE which Impacts ACcessibility

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This adds a dialog popup showing prisoner stats and info in the resolve scenario wizard that was requested in #1128
> Added dialog for viewing prisoner stats

- MekHQ/build.gradle
- MekHQ/src/mekhq/gui/dialog/LootDialog.java
Fix for missing directory in build script, which causes problems with the edit scenario dialog.
> Update gradle build script to include new directory

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
On occasion, scenario resolution would fail due to an array out of bounds error when setting up the kia buttons. This rearranges the relevant event handler to avoid array lookups and explicitly associate a kia checkbox with the relevant other controls.
> fix showstopper preventing scenario resolution

- MekHQ/src/mekhq/gui/CampaignGUI.java
Removes hard references to three dialogs that did not need them in CampaignGUI, implements #102.
> Implement #102 by removing unnecessary hard refs to dialogs

- MekHQ/src/mekhq/Utilities.java
+ Feature Allows artillery dropships to load alternate ammo added by MM #1409
> Allow DS to load with alt arty munitions

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/CrewSkillUpgrader.java
- MekHQ/src/mekhq/campaign/personnel/SkillPrereq.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Pretty simple: this lets generated units for AtB and Template scenarios have crews with SPAs, as per CamOps recommendations.
> Bot Unit SPAs

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
This fixes issue #1224, where, if you have vehicles turned off entirely but use the "Standard AtB Mix" unit type in a scenario force template, you wind up with no units. Now, we respect that setting and the relevant clan setting as well.
> respect 'no vehicles' and 'no clan vehicles' settings

- MekHQ/src/mekhq/gui/dialog/MaintenanceReportDialog.java
- MekHQ/src/mekhq/gui/dialog/TextAreaDialog.java
- MekHQ/src/mekhq/gui/dialog/UnitCostReportDialog.java
...don't forget to `pack` your dialogs.
> Fix zero sized dialogs #1275

- MekHQ/src/mekhq/campaign/unit/Unit.java
You can either price parts by quantity or quality, but you're certainly going to pay more for quality.
Original line:
https://github.com/MegaMek/mekhq/blame/089d23710eff787b3d834c959dc5328bfe8155c0/MekHQ/src/mekhq/campaign/unit/Unit.java#L1118
> Fix unit value explosions #1282

- MekHQ/src/mekhq/campaign/Campaign.java
self-explanatory, found this while testing other things
> fix npe when applying training XP

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/gui/StartUpGUI.java
- Addresses #1308
- Fixed a NPE trying to enumerate saves when the campaigns folder is not present.
- Clear all JIdea warnings from StartUpGUI.java
- Removes unused and probably wrong lerp utilities method.
> [#1308] Fixing NPE when the campaigns folder is not present

- MekHQ/src/mekhq/campaign/Campaign.java
Pretty straightforward, this fixes another NPE that I encountered when rolling over a week. Not really sure what the legitimate situation for a null unit in a force would be, but this prevents that NPE from occurring.
> Fix training xp npe

- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
When adding a unit to a force on the TO&E, support vehicles show up in the "Unsorted" catch-all category because the sorting by unit type and weight doesn't take support vehicle weight classes into account. This adds special handling for SVs so they will show up in the tank, VTOL, naval, or conventional fighter menus by their correct weight class.
Fixes #1333
> Sort SVs into unit type and weight class when adding to force on TOE.

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Fixes the NPE in PersonViewPanel by bringing all JPanel/JLabel creations local.
> Fix NPE when PersonViewPanel has a pregnant individual #1330

- MekHQ/build.gradle
Missed the scenario template folder that I added.
> update build file

- MekHQ/src/mekhq/campaign/CurrentLocation.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
This builds off of #1289 by @Skoraks, bringing the PR up to the current code base and extended the logic for when GM menu items are enabled on the Interstellar Map tab.
> Feature: GM Jumpship Recharge [rebases and updates #1289]

- MekHQ/resources/mekhq/resources/NewRecruitDialog.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/personnel/AbstractPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/personnel/AbstractSkillGenerator.java
- MekHQ/src/mekhq/campaign/personnel/AbstractSpecialAbilityGenerator.java
- MekHQ/src/mekhq/campaign/personnel/DefaultPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/personnel/DefaultSkillGenerator.java
- MekHQ/src/mekhq/campaign/personnel/DefaultSpecialAbilityGenerator.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java
- MekHQ/src/mekhq/campaign/personnel/SingleSpecialAbilityGenerator.java
- MekHQ/src/mekhq/campaign/personnel/Skill.java
- MekHQ/src/mekhq/campaign/personnel/SkillPrereq.java
- MekHQ/src/mekhq/campaign/personnel/Skills.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/universe/AbstractFactionSelector.java
- MekHQ/src/mekhq/campaign/universe/AbstractPlanetSelector.java
- MekHQ/src/mekhq/campaign/universe/DefaultFactionSelector.java
- MekHQ/src/mekhq/campaign/universe/DefaultPlanetSelector.java
- MekHQ/src/mekhq/campaign/universe/NoPlanetSelector.java
- MekHQ/src/mekhq/campaign/universe/Planet.java
- MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
- MekHQ/src/mekhq/campaign/universe/RangedPlanetSelector.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
- MekHQ/src/mekhq/module/atb/PersonnelMarketAtB.java
This abstracts personnel generation to support adding random factions/planets.
> Random personnel background generator

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
> 1306: Commander Bonus is now applied in Rating calculation

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
> 1370: Unit Rating FM:M(r): 0 dividends produce 0 results with non-zero divisors

- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
> 1374: Unit Rating: Excess Small Craft Bays can be used to store Fighters

- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- MekHQ/src/mekhq/gui/MapTab.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/PlanetarySystemMapPanel.java
- MekHQ/src/mekhq/gui/TOETab.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
[*Best viewed with whitespace differences ignored.*](https://github.com/MegaMek/mekhq/pull/1379/files?w=1)
This adds a hyperlink from the person view panel to:
- Jumps to the system in the big view if their origin planet is the primary planet for the system.
- Jumps into the system if their origin planet is within a system itself.
> Feature: Adds hyperlink from origin system to the map panel

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
- MekHQ/unittests/mekhq/campaign/rating/FieldManualMercRevDragoonsRatingTest.java
> Unit Rating: Varied Minor Fixes

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
- MekHQ/unittests/mekhq/campaign/rating/CampaignOpsReputationTest.java
- MekHQ/unittests/mekhq/campaign/rating/FieldManualMercRevDragoonsRatingTest.java
This implements #1383, and is a replacement PR for #1386
> 1383: Include Super Heavy Vehicle Bays in Unit Rating/Reputation

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This adds submenus by skill level to the Hangar tab's Assign Tech context menu #1363.
> Feature: added hangar tab sorting by skill type #1363

- MekHQ/src/mekhq/campaign/universe/RATGeneratorConnector.java
- MekHQ/src/mekhq/campaign/universe/RATManager.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
This originated in me looking for the issue for #1302, but is only a code cleanup. It does not fix the aforementioned issue, which is likely in MegeMek instead of MekHQ
> Cleaning up code in GMTools and RAT Management files

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
- MekHQ/src/mekhq/campaign/personnel/Bloodname.java
- MekHQ/src/mekhq/campaign/personnel/SkillPrereq.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/unit/UnitTechProgression.java
- MekHQ/src/mekhq/campaign/universe/FactionHints.java
- MekHQ/src/mekhq/campaign/universe/IUnitGenerator.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/ScenarioTemplateEditorDialog.java
- MekHQ/src/mekhq/gui/model/XTableColumnModel.java
I kept getting these warnings from my IDE, so I thought I might as well fix them. I also did some refactoring whenever I saw something that would make sense to change.
> Refactoring and Fixing lgtm Recommendations

- MekHQ/src/mekhq/campaign/report/HangarReport.java
- MekHQ/src/mekhq/gui/OverviewTab.java
This is a complete rework and refactor of the Hangar Report. As part of this, Space Stations and Support Vehicles have been added to the list, orderings have been standardized from heaviest to lightest, and the code performance has been significantly improved.
#219 is fixed as part of this PR.
> Overview Hangar Report: Completely reworked Hangar Report

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> Enabling RandomizePortraits for personnel with pre-existing portraits

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
My screen is too small to see all the settings under the Personnel tab, so I added a scrollbar to it.
> Adding Scrollbar to Personnel Settings

- MekHQ/src/mekhq/campaign/Campaign.java
Pretty simple, the 'rugged' quirk allows a mech to go 2x or 3x as long between maintenance cycles.
> implement 'rugged' quirk

- MekHQ/resources/mekhq/resources/NewPlanetaryEventDialog.properties
- MekHQ/src/mekhq/gui/view/PlanetViewPanel.java
Currently, the degree symbol does not show as a degree symbol but instead as a set of chars. This fixes it by using the unicode for the symbol instead of just the symbol.
> Fixing Temperature Display for Degree Symbol

- MekHQ/src/mekhq/campaign/Campaign.java
This is a further refinement to acquisitions (beyond #1448 to fix #1447 ) which removes the indefinite loops surrounding the current shopping list and logistical personnel. The next step will be to refactor out each shopping style into its own class (with tests to avoid these issues).
> Refine shopping to avoid indefinitely loops #1447

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/report/HangarReport.java
> 1413/1415: Adding (Mothballed) to units in the Hangar Report tab and Order Alphabetically

- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
> 1454: Adding scrollbar to NewContractDialog

- MekHQ/docs/AddingPortraits.txt
This should finally full implement and fix #280.
Note that the formatting is good when reading, just looks odd on GitHub
> 280: Adding Portrait folder documentation

- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
This fixes #1090, and a bunch of formatting issues in the PersonnelTableModel file.
> 1090: Adding Origin Faction and Origin Planet to Fluff Information Table

- MekHQ/src/mekhq/campaign/CampaignOptions.java
> 1488: Random Origin Search Radius now properly loads

- MekHQ/src/mekhq/MekHQ.java
This fixes the name of a method in the MekHQ.java file.
It needs to go in with MM PR 1634
> MM 1634: Fixing Shared Method Name

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/campaign/AtBConfiguration.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignFactory.java
- MekHQ/src/mekhq/campaign/JumpPath.java
- MekHQ/src/mekhq/campaign/MercRosterAccess.java
- MekHQ/src/mekhq/campaign/market/UnitMarket.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/personnel/CustomOption.java
- MekHQ/src/mekhq/campaign/personnel/Ranks.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
- MekHQ/src/mekhq/campaign/universe/FactionHints.java
- MekHQ/src/mekhq/campaign/universe/PlanetarySystem.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/GUI.java
- MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/utilities/PortraitFileFactory.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
- MekHQ/src/mekhq/module/ScriptPluginManager.java
- MekHQ/src/mekhq/module/atb/PersonnelMarketAtB.java
This PR is to fix a significant portion of our current LGTM issues in MekHQ, and I did some other quick IDE-recommended fixes along the way.
> Fixing LGTM Issues

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
> 1495: Export Campaign Subset to New Campaign Now Copies Options

- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixes #1508, specifically the new issue portion of it. That story can be closed, as the primary issue is another ticket.
> 1508: Injured personnel Keep Command of their Vehicles and Infantry units

- MekHQ/resources/mekhq/resources/PartsStoreDialog.properties
- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/OverviewTab.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/gui/dialog/PopupValueChoiceDialog.java
This fixes #1429. It also reorders the buttons to be consistent with them elsewhere in the program and hides GM buttons when not in GM mode.
> 1429: Adding Bulk Add to the Parts Marketplace

- MekHQ/build.gradle
See MegaMek/megameklab#490.
This makes the same necessary changes to get it to build the MekHQ packages correctly.
> Access values of string properties.

- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
> 1505: Fixing Personnel Tab Graphical Unit Images for Mixed Fighter and Tech Person

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes a TODO in the file, and has been split off my personnel changes.
> Adding proper bondsman formatting when Added to Campaign

- MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
This MUST be merged after MM PR 1712, as that PR adds the WeightedMap to MegaMek/Util
> Changing RandomFactionGenerator to use the MegaMek/Util WeightedMap

- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
- MekHQ/src/mekhq/service/AutosaveService.java
- MekHQ/src/mekhq/service/IAutosaveService.java
This adds monthly and yearly autosave options to MekHQ, in addition to some protection against bad directories and file names.
> Adding Monthly and Yearly Autosave Options

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
This fixes #1482, includes some refactoring, and implements some changes used in further personnel changes.
Anything deprecated here will be removed in future personnel changes that are currently undergoing testing.
> 1482: Hire Full Complement Now Records Time in Service

- MekHQ/data/universe/news.xml
This adds four new news items to MekHQ, three related to James McKenna and one for the first use of the HPG system.
> Adding Four New News Items

- MekHQ/src/mekhq/gui/BasicInfo.java
- MekHQ/src/mekhq/gui/model/CrewListModel.java
- MekHQ/src/mekhq/gui/model/DocTableModel.java
- MekHQ/src/mekhq/gui/model/PatientTableModel.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/model/RetirementTableModel.java
- MekHQ/src/mekhq/gui/model/TechTableModel.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
This is an easy fix for the buttons on the infirmary being unreadable in dark mode, fixes #1530.
> Fixes issue in infirmary where buttons unreadable in dark mode #1530

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignController.java
- MekHQ/src/mekhq/campaign/CurrentLocation.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This PR lands the groundwork for distributed MekHQ games:
1. Have a CampaignController that handles the timeline
2. Refactor some logic to ensure a centralized location or event manages the actions
> Groundwork for distributed MekHQ

- MekHQ/src/mekhq/campaign/personnel/Person.java
This is just a small improvements that adds ranks to the infirmary tab, so you can choose higher ranked personnel if you'd like (i.e. rp reasons)
> Adding ranks to Doctors in the Infirmary Tab

- MekHQ/src/mekhq/gui/WarehouseTab.java
Hi,
I added the existing 'FormattedNumberSorter' to the Total Cost column in the Warehouse tab to resolve the ordering issue where it is treated as a string.
> Added FormattedNumberSorter to Warehouse total cost column (Issue #1250)

- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
> 155: Adding Advance Day to Personnel Market

- MekHQ/src/mekhq/campaign/report/HangarReport.java
This should have had the <>, but they were missed. Fixed that, and switch the sort to use the natural order comparator instead. Also removed an old TODO that I missed when fixing the issue.
> Fixing Arraylist Declaration and Implementing Natural Order Sort in Hangar Report

- MekHQ/src/mekhq/gui/ForceRenderer.java
Reverts MegaMek/mekhq#1555
This is because I did not check to see if the same issue exists in MegaMek, which is does. I'm therefore going to instead fix this in a MegaMek PR.
> Revert "Fixing spacing for C3 Slaves in the TOE"

- MekHQ/data/names/bloodnames/bloodnames.xml
This adds the proper tab spacing to the bloodnames file, and is just a bulk tab. I would NOT recommend trying to review this whole file, as I am just trying to minimize the number of big changes in my next Personnel wave by placing the formatting switch here.
> Fixing Bloodname file formatting

- MekHQ/resources/mekhq/resources/PartsStoreDialog.properties
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
> 1564: Hide impossible parts in the Purchase Parts Windows

- MekHQ/src/mekhq/gui/PersonnelTab.java
> 1524: Sort P_NONE Personnel as Support Personnel

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This should hopefully fix #1540, although I was unable to test it on this branch.
Because of that, I changed to using the same format as we use for ClanPriceModifier, which I can test and confirm works properly with numbers whose decimals are done in either ',' or '.'. I'm pretty sure it should work properly, and will at the minimum maintain current functionality.
> 1540: Switching over to using JSpinner for base salaries

- MekHQ/src/mekhq/campaign/personnel/Person.java
Somehow this is missing in develop, yet is in my feature branch.
> Fixing expected due date read from file

- MekHQ/src/mekhq/campaign/ExtraData.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes an issue that I had thought I fixed, being something I was playing around with in my personnel changes. However, it appears that I did not revert my changes, and that can cause null pointer errors in a few locations (mostly relating to injuries)
I've also properly implemented the ExtraData isEmpty() checks, so that it only writes ExtraData to file if there are extraData objects to write.
Review with whitespace changes off.
> Fixing Person ExtraData Null Pointer Exceptions

- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes a missing migration value in personnel.
> Personnel: Fixing missing Due Date Migration

- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes a suite of surname related issues that I discovered while testing with migrating personnel without a last name.
> Fixing surname migration issues

- MekHQ/src/mekhq/campaign/Campaign.java
This is just a quick refactoring PR, before I add the new random death system to it.
> Minor refactoring in newDayPersonnel

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/MercRosterAccess.java
- MekHQ/src/mekhq/campaign/personnel/FormerSpouse.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
- MekHQ/src/mekhq/campaign/personnel/generator/AbstractPersonnelGenerator.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
- MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This PR switches the Person class to use java.time.LocalDate instead of the mixture of Joda, Gregorian Calendar, and Date.
LocalDate for campaign is currently just a conversion call, as we don't need to track the same thing three times.
This was stirred on to make it easier to implement parts of the RandomDeath code.
> Person LocalDate

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
To Review: This one my IDE played around with the formatting, so I'll add comments for the areas that are actually changed.
The changes are moving the GM-only pregnancy methods to be in the GM Menu, switching add pregnancy to use the standard requirements, and hiding the GM Menu for non-GMs.
> PersonnelTableModel: GM Menu Only Shows for GMs

- MekHQ/src/mekhq/gui/utilities/JMenuHelpers.java
This is a useful little piece of code that will permit the further code reduction and standardization of how JMenu and JPopupMenus are added together.
> Adding JPopupMenu functionality to the JMenuHelpers class

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> 1612: Adding Scrolling to Marriage Candidates

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/resources/mekhq/resources/CustomizePersonDialog.properties
- MekHQ/resources/mekhq/resources/PersonViewPanel.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This fixes #1626 , and implements it with a standard display in months before the addition of #1625
> 1626: Adding Time in Rank to MekHQ

- MekHQ/src/mekhq/campaign/ExtraData.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
This helps to prevent #1636, and adds more information when debugging Person xml load and save failures.
Only change in Person.writeToXml is the addition of a try-catch, but that change has blown up the change lines. Whitespace differences off turns this into an 18 line change
> 1636: Fixing ExtraData Export for Null Maps

- MekHQ/src/mekhq/campaign/Campaign.java
Minor bugfix for something I missed in initial testing.
> Fixing Time in Rank for Newly Hired Personnel

- MekHQ/src/mekhq/campaign/ExtraData.java
This will hopefully fix the current ExtraData saving issues we are having
> Fixing ExtraData Marshaller

- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
This fixes a missing +1 in the advance to next month functionality.
> Fixing advance days dialog

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
This fixes a bug raised on discord, and adds two more bug fixes to the same feature (actually handling missing spouses and missing fathers).
> Fixing load from psrx data for spouses

- MekHQ/src/mekhq/campaign/personnel/Person.java
This hits a few minor fixes that end up implementing prisoner random marriages.
> Random Marriages: Minor Prisoner Marriage Bugfix/Improvement

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/parts/MekLocation.java
- MekHQ/src/mekhq/campaign/parts/MissingPart.java
- MekHQ/src/mekhq/campaign/parts/Part.java
- MekHQ/src/mekhq/campaign/parts/ProtomekLocation.java
- MekHQ/src/mekhq/campaign/parts/SpacecraftCoolingSystem.java
- MekHQ/src/mekhq/campaign/parts/TankLocation.java
- MekHQ/src/mekhq/campaign/personnel/CustomOption.java
- MekHQ/src/mekhq/campaign/personnel/Ranks.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/universe/Faction.java
- MekHQ/src/mekhq/campaign/universe/FactionHints.java
- MekHQ/src/mekhq/campaign/universe/News.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/InfirmaryTab.java
- MekHQ/src/mekhq/gui/MekLabTab.java
- MekHQ/src/mekhq/gui/adapter/ScenarioTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/ServicedUnitsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/model/FilterableListModel.java
- MekHQ/src/mekhq/gui/model/RetirementTableModel.java
- MekHQ/src/mekhq/gui/model/TaskTableModel.java
- MekHQ/src/mekhq/gui/model/UnitAssignmentTableModel.java
- MekHQ/src/mekhq/gui/model/UnitMarketTableModel.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
I went through our active list of null check alerts on LGTM and fixed them in one of three ways:
1. Removed a useless null check.
2. Added a needed null check.
3. Reorganized the code to help the analyzer with null detection.
https://lgtm.com/projects/g/MegaMek/mekhq/alerts/?mode=list&severity=
One commit per file.
> Fix null checks per LGTM

- MekHQ/src/mekhq/gui/dialog/PrincessBehaviorDialog.java
Changes needed to prevent megamek PR #1861 from breaking mekhq compilation.
> companion changes

- MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
> 1285: Adding default value to prevent Personnel Market No-Role Personnel

- MekHQ/src/mekhq/campaign/personnel/Person.java
This should have been using ChronoUnit as we only care about the one field, so I've swapped it over.
> Improving Age Calculation in Person

- MekHQ/data/scenariomodifiers/AlliedReinforcements.xml
- MekHQ/data/scenariomodifiers/modifiermanifest.xml
This has been sitting in my local repo for some indeterminate amount of time and I've completely forgotten about it. 
Adds a scenario template modifier that generates a "lance" of allied reinforcements, which somehow was lacking in the scenario modifier set before.
> Allied reinforcements scenario mod

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This PR is just to clean up the code before I start tackling the big group of pre-existing and newly opened issues for this wizard. 
The changes are fixing spacing issues for for and if statements and casts, swapping ArrayList declarations to List, switching to imports for the few cases that didnt, and any IDE recommended changes that I agreed with.
Review with whitespace differences off.
> ResolveScenarioWizardDialog Code Cleanup Pre-Issue Fix

- MekHQ/src/mekhq/gui/CampaignGUI.java
> 1741: Adding Unit::isPresent check for Maintenance

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This fixes #1734, and removes two ArrayLists made useless by the fix.
> 1734: Scenario Resolution Dialog: View Unit is Always Enabled

- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
This fixes #1740.
I also removed a bunch of old finances code, as the calculations are now done in finances
> 1740: Adding Unit::isPresent check for FMMR Unit Rating

- MekHQ/src/mekhq/campaign/log/LogEntryController.java
This fixes a bug reported on the slack channel.
> Fixing LogEntryController Typo

- MekHQ/src/mekhq/campaign/Campaign.java
Fix an NPE that occurs on day advance when there's a weird current jump path with no nodes remaining. 
Fixes #1753
> fix day advance NPE

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/AmmoStorage.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/unit/UnitOrder.java
I noticed a few issues with planetary acquisitions that I wanted to clean up for the stable if possible, especially now that planetary acquisitions should work nicely with the new planetary system data. 
I also see that there was an issue with infinite loops in #1447  that was apparently fixed with #1451. Is that fully resolved or are there still issues with planetary acquisitions?
> Planet acquisition fixes

- MekHQ/resources/mekhq/resources/ImageChoiceDialog.properties
- MekHQ/src/mekhq/IconPackage.java
- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/force/ForceStub.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
- MekHQ/src/mekhq/gui/enums/LayeredForceIcon.java
This fixes #1662 and two of the three requests in #347 (copy/paste icons being left). The last one is possible, but would require significant refactoring outside of the scope of this.
There's a bunch of rework and refactoring to do this, and I'd recommend reviewing with whitespace differences off.
> 347/1662: Remember Layered Force Icon Setup

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes the elemental portrait folder and swaps the methods to use List instead of ArrayList
> Fixing elemental Portrait Folder

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/log/AwardLogEntry.java
- MekHQ/src/mekhq/campaign/log/AwardLogger.java
- MekHQ/src/mekhq/campaign/personnel/Award.java
- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/DateChooser.java
- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
I also cleaned up a bunch of the white spacing issues in the files while I was there, and clarified some TODOs to make it easier for me to search for them.
> Moving Awards to LocalDate

- MekHQ/src/mekhq/campaign/Campaign.java
> 1706: Techs now display as part of the force in the personnel tab

- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
> 1782: Moving listener to proper location

- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/campaign/mission/BotForceStub.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/CivilianHelpBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/HideAndSeekBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/HoldTheLineBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PrisonBreakBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache2BuiltInScenario.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
This fixes #1442 and fixes #1343.
I also did a bit of refactoring to swap to using Lists instead of ArrayList and fixing variable visibility.
> 1343/1442: AtB Scenario Objective Fixes

- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
This fixes a bug I missed when testing the layered force icons.
> Fixing the initial frame selection for layered force icons

- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
This fixes the image artifacting that can be seen in the Force and Portrait selection dialogs (as found while testing #1783).
> Force and Portrait Image Artifacting Fix

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
> 1766: Adding an option for attached units to use the faction camo

- MekHQ/src/mekhq/campaign/parts/Refit.java
Companion to MegaMek/megamek#2007. Calculates slot count of variable sized equipment correctly when determining refit class.
>  Variable equipment size, part 2

- MekHQ/data/universe/factionhints.xml
This fixes an impossible date, February 30th.
> Fixing Taurian-Canopian War end date

- MekHQ/resources/mekhq/resources/AdvanceDaysDialog.properties
- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
This implements a request along with some light refactoring in the code.
> Adding Advance to Next Monday to the AdvanceDaysDialog

- MekHQ/docs/Award Stuff/README/Award Guide.md
> 1827: Adding documentation comment for required Excel version for Awards Tracker

- MekHQ/src/mekhq/campaign/personnel/Person.java
> 1819: Fixing Time in Rank without Time in Service

- MekHQ/src/mekhq/gui/dialog/ImageChoiceDialog.java
> 1821: Can now reach all directories for images

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> 1816: Fixing Portrait Changing in the Same Category

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
When I first implemented this, I misunderstood what was being asked for rather airheadedly. This properly implemented #1766, as noticed in #1840
> Properly Implementing the Attached Camo Option

- MekHQ/src/mekhq/campaign/Campaign.java
Continuing to move systems to LocalDate, this does it for the isolated calculatePartTransitTime method
> Moving calculatePartTransitTime to LocalDate

- MekHQ/src/mekhq/campaign/personnel/Person.java
> 1861: tryingToMarry and tryingToConceive flags are now saved properly

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/resources/mekhq/resources/CustomizePersonDialog.properties
- MekHQ/resources/mekhq/resources/PersonViewPanel.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This implements Retirement Date tracking for Personnel in MekHQ and cleans up a few more minor things with Time in Service and Time in Rank (whose implementations were largely followed to implement this).
> Retirement Date Tracking

- MekHQ/docs/history.txt
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/force/Lance.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
- MekHQ/src/mekhq/gui/dialog/DateChooser.java
- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
- MekHQ/src/mekhq/gui/dialog/ShipSearchDialog.java
- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
- MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
- MekHQ/src/mekhq/gui/view/MissionViewPanel.java
- MekHQ/unittests/mekhq/campaign/mission/ContractTest.java
This PR swaps Contracts to LocalDate.
Review with whitespace differences off, as I fixed a bunch of weird formatting in the LanceAssignmentView.java file.
> Local Date: Contract Swapover

- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
> 1871: Implementing sorting fixes for the personnel tab

- MekHQ/src/mekhq/campaign/unit/Unit.java
Update method names due to MegaMek/megamek#2079
> Update infantry damage divisor setter and name

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/campaign/personnel/generator/AbstractPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
- MekHQ/src/mekhq/gui/model/DocTableModel.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/model/TechTableModel.java
- MekHQ/src/mekhq/service/MassRepairService.java
This PR standardizes how personnel experience is done, removing the need (if there even was one, cause I can't see a reason for it after going over the code) for a separate count for engineering xp. I also used this to make some more formatting changes to improve readability.
> Personnel XP Standardization

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
This fixes a bug raised on the Slack.
> Genealogy: Adding a contains map check

- MekHQ/src/mekhq/gui/dialog/DateChooser.java
> 1902: Fixing DateChooser NPEs

- MekHQ/docs/AddingPortraits.txt
> 1904: Updating Portrait documentation for role name changes

- MekHQ/src/mekhq/campaign/MercRosterAccess.java
This PR swaps one line of MercRoster over to LocalDate (line 129) and fixes a bunch of the formatting issues.
Whitespace differences off to review.
> MercRoster: LocalDate Swapover

- MekHQ/src/mekhq/gui/dialog/DateChooser.java
> 1915: Fixing Date Lineup

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
> 1920: Fixing xml load for bad data

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/force/Lance.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/TOETab.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
- MekHQ/src/mekhq/gui/dialog/ForceTemplateAssignmentDialog.java
- MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
> 790: Implementing Non-Combat TO&E Forces

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
> 1929: Scenario Resolution: Fixing Display Anchor Issues

- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This fixes a minor display issue I noticed while testing #1271.
> Fixing Prisoners Displaying Total Earnings

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This fixes #1941.
To Review: The first four commits are all just code cleanups, and can be viewed separately. The last commit has the actual change for this branch.
> 1941: Person View Panel Ability and Injury Description ToolTip

- MekHQ/src/mekhq/campaign/AtBConfiguration.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/universe/Faction.java
- MekHQ/src/mekhq/campaign/universe/NewsItem.java
- MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This fixes #1264.
To review: The first two commits are refactoring, only the third and fourth contain actual changes.
> 1264: Allow faction capitals to change on a specific date, not just year

- MekHQ/src/mekhq/campaign/force/Lance.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java
Apparently, you have to add the bot force to the scenario *after* adding units to it.
> base attack turret fix

- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/campaign/force/Lance.java
This fixes #1983 
(note: this has a MegaMek component too)
> 1983: Switching to new form of UUID save format

- MekHQ/src/mekhq/campaign/universe/RangedFactionSelector.java
> 1952: Personnel Market Updates No Longer Fail in Rare Cases During Person Creation

- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This fixes a minor bug I noticed while working on #1939
> Fixing Clan Vehicle Option

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/force/Lance.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This is a bugfix and refactor for the recent AtB Lance by Role changes. I swapped it over to using int, fixed saving issues, and simplified the math.
> AtB Lance By Role BugFix

- MekHQ/data/universe/factions.xml
This fixes #2003, round 2, and swaps to space spacing instead of tab.
To review: Whitespace differences off, or you're going to be very confused.
> 2003: implementing faction changes

- MekHQ/src/mekhq/campaign/GamePreset.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
> 1939: Fixing Preset Loading and Reworking Campaign Options Initial Value Load

- MekHQ/src/mekhq/campaign/parts/Refit.java
> Fix vehicle engine-free heat sink count

- MekHQ/src/mekhq/campaign/parts/Refit.java
> On refit don't add missing/destroyed parts from old unit to warehouse

- MekHQ/src/mekhq/Utilities.java
> AmmoBin from warehouse can rarely come with free ammo

- MekHQ/src/mekhq/campaign/parts/Refit.java
> OmniVehicle config changes require omnipod heat sinks

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
> 2039: Subcontract Check NPE

- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/dialog/CompleteMissionDialog.java
This fixes #2024
Review with whitespace differences off. The initial implementation changed parts of the CompleteMissionDialog, so that's why it is is included with only whitespace changes.
> 2024: Can Repeatedly Complete Missions by Cancelling Retirement Dialog

- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
I also swapped the file to use the new style of logger at the same time.
> Fixing Erroneous Newline after Unit Loading Failure

- MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java
If I had a nickel for every one of these in my mekhqlog.txt...
> Reduce the logging level of resolveVariableCost

- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
Fixed the issues, but forgot to remove the TODO.
> Clearing out two missed LocalDate swapover TODOs

- MekHQ/src/mekhq/campaign/rating/AbstractUnitRating.java
- MekHQ/src/mekhq/campaign/rating/CampaignOpsReputation.java
- MekHQ/src/mekhq/campaign/rating/FieldManualMercRevDragoonsRating.java
This fixes #1369 by adding hasUnits checks.
> 1369: Unit Rating FM:M(r): Default Quality Value is no longer Elite

- MekHQ/resources/mekhq/resources/GMToolsDialog.properties
- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
This is an enhancement to the GM Tools dialog that allows one to view each individual dice roll.
> Implementing individual dice roll display in the GMTools Dialog

- MekHQ/resources/mekhq/resources/MassRepair.properties
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/service/MassRepairMassSalvageMode.java
- MekHQ/src/mekhq/service/MassRepairService.java
This PR localizes the MRMS Dialog and simplifies a bunch of the graphical code in the file at the same time. Next up for MRMS is ensuring it properly follows the options it is run using.
> MRMS Dialog Localization

- MekHQ/src/mekhq/campaign/unit/actions/ShowUnitBvAction.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
While debugging https://github.com/MegaMek/megamek/issues/2273 I created this action for the Unit context menu to make my life easier. The code is taken straight from MegaMek and produces an identical popup to the one found in the unit selector.
> Add Show BV Calculation to Unit context menu

- MekHQ/resources/mekhq/resources/PersonnelTableMouseAdapter.properties
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> 2079: Implementing Bulk Free in Personnel Tab

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixes the first issue raised in #1953, namely techs don't restore properly when finishing activation.
> 1953: Fixing mothballing and activation tech restore

- MekHQ/resources/mekhq/resources/CampaignGUI.properties
- MekHQ/src/mekhq/gui/HangarTab.java
This fixes #1595 and fixes #1805 by adding Active, Mothballed, and Unmaintained filters in the Hangar Tab
> 1595/1805: Adding filters in Hangar Tab

- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
> 2091: Fixing missing requirement of addToCampaign

- MekHQ/resources/mekhq/resources/UnitTableMouseAdapter.properties
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This fixes #1525, as the majority of that issue was opened as #1526
> 1525: Swapping to Minimum Crew instead of Maximum Crew

- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
> 1875: Phenotype Bonus is properly added and reduced

- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Following on from #2101, I've added the same checks for Unit to further reduce XML size.
> Cleaning up unit XML Write

- MekHQ/src/mekhq/gui/dialog/BaseDialog.java
- MekHQ/src/mekhq/gui/dialog/LargeCraftAmmoSwapDialog.java
- MekHQ/src/mekhq/gui/dialog/ReportDialog.java
I also did some light other changes while looking at it.
> Fixing a pair of misnamed preferences

- MekHQ/src/mekhq/campaign/RandomSkillPreferences.java
This changes it to debug and reduces the lines from three to one.
> RandomSkillPreferences  Oververbose Load from XML

- MekHQ/data/universe/news.xml
- MekHQ/src/mekhq/campaign/universe/News.java
This adds validation to prevent empty headline and descriptions for news articles.
> News Validation Changes

- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
This fixes the report creation location.
> New Personnel Market Report

- MekHQ/.classpath
- MekHQ/.project
After updating to the latest Eclipse Tools (used under the hood by VS Code), these changes are suggested every time I open MekHQ.
> Add suggested changes to classpath and project

- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
> 2115: Fixing GM Tool Gender load

- MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java
This fixes a date compare issue.
> Fixing Scenario Date Compare

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/MekHQ.java
> 2118: Fixing MekHQ's use of MM password

- MekHQ/src/mekhq/campaign/unit/Unit.java
> 2138: Fixing GM Mothballing

- MekHQ/src/mekhq/gui/ForceRenderer.java
- MekHQ/src/mekhq/gui/TOETab.java
This fixes #2130. The first commit is a code cleanup, the second is the bugfix (we need to set it to be opaque in certain circumstances, but you need to set it to false in general or every cell will be opaque).
> 2130: Fixing TOE “Deployed” and “Undeployed” Background Colour Display

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/utilities/JMenuHelpers.java
This fixes the display error from which #1537 was noticed, but does not fix the underlying issue with the transition of bombs from MegaMek.
Commit 1 is a refactor/code cleanup, commit 2 prevents the NPE, and commit 3 rolls back one of my refactor changes.
> 1537: Fixing Null AmmoType NPE in Hangar Tab

- MekHQ/resources/mekhq/resources/Market.properties
- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/campaign/market/UnitMarket.java
- MekHQ/src/mekhq/campaign/market/enums/ContractMarketMethod.java
- MekHQ/src/mekhq/campaign/market/enums/UnitMarketMethod.java
- MekHQ/src/mekhq/campaign/market/enums/UnitMarketType.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/gui/dialog/UnitMarketDialog.java
- MekHQ/src/mekhq/gui/model/UnitMarketTableModel.java
This implements three market enums. Not the most useful of PRs, but another step towards moving aways from magic numbers.
> Implementing Market Type Enums

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This makes support edge reliant on edge being enabled as this is expected behaviour in the backend, cleans up a bunch of the code relating to edge, adds spacing to the TableMouseAdapter section.
> MekHQ Edge Cleanup

- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
This PR turns the MekHQ Options Dialog into a JTabbedPane, dividing it into tabbed categories. Most are currently rather bare, but this provides us the ability to expand upon the current setup.
> Tabbed MekHQ Options Dialog

- MekHQ/src/mekhq/Version.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/GamePreset.java
- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
> 2171: Implementing Campaign Option and Campaign Preset Versioning

- MekHQ/src/mekhq/campaign/Campaign.java
This (hopefully) fixes #572 by swapping random portrait generation to using file.
I say hopefully because the fix works on my system, but I rarely have this issue.
Next portrait PR will move this code to its own generator class.
> 572: Random Portrait Fails to Properly Compare File Paths

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/generator/RandomPortraitGenerator.java
This PR moves the portrait generation code out of campaign and into a random portrait generator.
> Random Portrait Generator

- MekHQ/src/mekhq/gui/model/UnitTableModel.java
> 2236: Making Unmaintained hangar color take priority over Damaged/Inoperable

- MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java
Fixes #1880. A little too much opposite edge retrieval.
> fix briefing destination

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/resources/mekhq/resources/LogEntries.properties
- MekHQ/resources/mekhq/resources/Personnel.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/log/MedicalLogger.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/enums/Divorce.java
- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelStatus.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This adds the pregnancy complication status as part of setting up Random Death. Further, I also removed the random death option, as both are part of simplifying the Random Death work I am doing.
> Random Death: Pregnancy Complications Status

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/gui/dialog/CamoChoiceDialog.java
This is the MekHQ-side of https://github.com/MegaMek/megamek/pull/2504
> Moving Color Names to PlayerColors

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
This fixes #2295 and cleans up some of the rank code in person.
> 2295: Expanding null protections for rank systems and adding defaults

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/generator/AbstractPersonnelGenerator.java
This ensures that newly generated personnel who have a preassigned gender will be generated properly instead of being generated as a male.
> Fixing Gender assignment on Generation

- MekHQ/src/mekhq/campaign/Quartermaster.java
- MekHQ/unittests/mekhq/campaign/QuartermasterTest.java
When converting compatible ammunition we should have been rounding UP for shots needed and DOWN for shots available. This adds a `Quartermaster::convertShotsNeeded` method used when removing compatible ammo; this fixes #2297.
> Issue #2297: Ensure shots needed is converted properly between ammo types

- MekHQ/campaigns/Fist and Falcon/Binary Bravo, 1st Falcon Strikers.cpnx
- MekHQ/campaigns/Fist and Falcon/Kewran Wolfhounds, C Company, 3rd Battalion, 25th Arcturan Guards RCT.cpnx
- MekHQ/campaigns/Sword and Dragon/Fox's Teeth, McKinnon's Company, Vausur's Battalion, Seventh Crucis Lancers RCT.cpnx
- MekHQ/campaigns/Sword and Dragon/Sorenson Sabres, Jisatsu Company, Otomo, formerly Third Company, Tarwater's Battalion, Fifth Sword of Light.cpnx
- MekHQ/campaigns/Wolf and Blake/Black Widow Company, Church's Independent Company, Wolf's Dragoons.cpnx
- MekHQ/campaigns/Wolf and Blake/Shadow Hunters, Opacus Venatori, Fifty-second Shadow Division.cpnx
- Fixes unit error in Sorenson Sabers (Grand Dragon DRG-1G Emory)
- Fixes unit error in Shadow Hunters (Grigori C-GCG-O Rufus)
> Upgrades built in campaigns to 0.47.15

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/view/ForceViewPanel.java
See https://github.com/MegaMek/megamek/pull/2567
> Colour Camouflage: Fixing Colour Camouflage Tint Application and Colour Setter

- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
This fixes two bugs in the acquisition dialog that were found investigating an issue on discord.
> Acquisition Dialog: Fixing NPE, GM Acquire for In-Transit or On Order parts, Adding GM Acquire Message

- MekHQ/src/mekhq/gui/MekLabTab.java
This is the MHQ companion to https://github.com/MegaMek/megameklab/pull/859
> Use MML's CConfig.load instead of new CConfig()

- MekHQ/resources/mekhq/resources/MassRepair.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/gui/model/DocTableModel.java
- MekHQ/src/mekhq/service/MassRepairService.java
This fixes #2458 by adding checks (including one that will fill the pool for you) into MRMS. As part of this I brought forwards some of the pool methods I was going to be adding in the near future.
> 2458: MRMS Astech Requirement Checks

- .classpath
- MekHQ/.classpath
Updates our .classpath files to point to Java 11.
> Update classpath for Java 11

- MekHQ/resources/mekhq/resources/GMToolsDialog.properties
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
This fixes #2388 by allowing multiple generation and manual editing for name and callsign generation in the GM Tools dialog.
> 3288: GM Tool Name Generation Expansion - Bulk Generation, Manual Editing

- MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java
- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
This fixes #2489 by improving the null handling for awards during load.
> 2489: Improving Award XML Load Null Proofing

- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
> 2501: Fixing Camouflage Button Icon Assignment Copy/Paste Error

- MekHQ/src/mekhq/MHQStaticDirectoryManager.java
- MekHQ/src/mekhq/io/AwardFileFactory.java
This fixes #2505, albeit in a band aid situation. I'll be working with Kailan on a full fix in the near future.
> 2505: Re-adding Awards PNG Load Band Aid

- MekHQ/src/mekhq/campaign/mission/ObjectiveEffect.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjective.java
This PR improves (somewhat) the human readability of the objectives section of the scenario resolution wizard, by specifying what each objective will accomplish when it succeeds/fails. Given the procedural nature of it, the language might be somewhat awkward but I tried to make it reasonable for the most common cases.
> Objective effect text update

- MekHQ/src/mekhq/gui/panes/RankSystemsPane.java
> 2561: Automatic export and refresh upon confirming the pane

- MekHQ/build.gradle
> 2569: Adding userdata to the build script

- MekHQ/src/mekhq/campaign/personnel/Person.java
This fixes a bug reported on Discord
> Fixing LAM Pilot Skill Level Calculation

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java
This fixes #2594 by adding a nullable compareTo version in our utilities.
> 2594: Allowing Scenario Date Nullable Comparison

- MekHQ/src/mekhq/campaign/force/Force.java
This removes some unused migration code from force
> Force: Removing Unused Migration Code 

- MekHQ/mmconf/mhqPresets/AgainstTheBot.xml
- MekHQ/mmconf/mhqPresets/CamOps.xml
- MekHQ/mmconf/mhqPresets/CampaignAnon_AtB.xml
- MekHQ/mmconf/mhqPresets/DefaultTotalWarfare.xml
- MekHQ/mmconf/mhqPresets/SimpleOptions.xml
- MekHQ/mmconf/mhqPresets/TaharqaMW2ish.xml
- MekHQ/userdata/data/universe/ranks.xml
This updates the presets, partially so they are now nicely versioned.
> Campaign Presets: Updating to modern version

- MekHQ/resources/mekhq/resources/PersonnelTableModel.properties
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
> 2620: Adding Missing Leadership Column in Personnel Tab

- MekHQ/src/mekhq/campaign/mission/BotForce.java
This fixes an issue raised in https://github.com/MegaMek/megamek/issues/2884
> Ensuring BotForce has a Valid Base Camouflage

- MekHQ/resources/mekhq/resources/Reports.properties
- MekHQ/src/mekhq/campaign/report/HangarReport.java
This fixes #2659 and adds a new section for IndustrialMechs, as they should really be shown separately from BattleMechs.
> 2659: Hangar Report: Adding IndustrialMech Section and Missing Combat Vehicle Super Heavy Nodes

- MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
This fixes #2642 by recreating the colour instead of using the direct colour (it's an odd swing bug that causes the issue)
The first commit is a few light changes when tracing down the problem, the second commit is the fix.
> 2642: StratCon Tab: Force Table Background Doesn't Work Properly in Nimbus

- MekHQ/src/mekhq/campaign/unit/Unit.java
> 2610: Adding Tech Officer migration from the reference class

- MekHQ/src/mekhq/campaign/unit/Unit.java
> 2382: Large Vessel Clan Repair and Maintenance modifier no longer applies to Clanners

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/gui/dialog/ScenarioTemplateEditorDialog.java
Since changing the CardinalEdge enum, I needed to make some updates to MekHQ.
> fix compilation errors resulting from MM pull request

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This fixes a build failure while implementing https://github.com/MegaMek/megamek/pull/2910
> Build Failure Fix: ResolveScenarioWizardDialog Uses Standardized EntityReadoutDialog

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/gui/dialog/OutstandingScenariosNagDialog.java
This fixes #2709, another advancement issue, and adds scenario date nullable annotations.
> 2709: Two Scenario Date NPEs

- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/gui/BriefingTab.java
This fixes #2685 by making units non-nullable.
> 2685: Preventing NPE when loading scenario save games

- MekHQ/src/mekhq/campaign/universe/RATManager.java
> 2736: Fixing Alternative Faction Code Generation by using correct ArrayList type

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
This is the MekHQ-facing side of changes for MegaMek PR #3006.
> Companion to MM PR #3006

- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/InfantryMotiveType.java
- MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
- MekHQ/src/mekhq/campaign/parts/MissingInfantryMotiveType.java
- MekHQ/src/mekhq/campaign/universe/RATManager.java
This is the MekHQ-side of https://github.com/MegaMek/megamek/pull/3008
> EntityMovementMode Enum Update

- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
This fixes two NPEs in the AtB scenario view panel. One of the two was found in https://github.com/MegaMek/megamek/issues/3005, the other was found by my IDE.
> Fixing Two AtB Scenario View Panel NPEs

- MekHQ/src/mekhq/MekHqConstants.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/work/IPartWork.java
This prevents a few divide by zero issues raised on the Discord while improving the code for Campaign::getTargetFor and Campaign::getAvailableAstechs and adding a constant for Astech team size.
> Astech Divide By Zero Errors

- MekHQ/src/mekhq/gui/RepairTab.java
This fixes #1098 by adding the filterTechs() line.
> 1098: Fixing Repair Tab Tech Order Options Fix

- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/CommandCenterTab.java
- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
This fixes https://github.com/MegaMek/mekhq/issues/2771 in my opinion, as the number of options would bulk out the code for limited benefit when this dialog handles it better. The colour nag will be handled elsewhere, and is already on my list.
> 2771: Fixing Missing Current Daily Log on AdvanceDaysDialog Creation

- MekHQ/src/mekhq/campaign/finances/Asset.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/gui/dialog/EditAssetDialog.java
- MekHQ/src/mekhq/gui/dialog/ManageAssetsDialog.java
First class handled as part of my finances refactor.
> Finances: Asset Refactoring/Standardization

- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/campaign/finances/Transaction.java
Finances file two refactor: Transaction
> Finances: Transaction Refactoring/Standardization

- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQPanel.java
This is required for my Force Icon and Personnel Module changes, as both will be utilizing this setup.
MekHQ-side of https://github.com/MegaMek/megamek/pull/3028
> Base Components: AbstractPanel

- MekHQ/data/universe/ranks.xml
This fixes a bunch of rank data issues based on HB:MPS.
> Rank fixes and improvements from HB: Major Periphery States

- MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
> 2779: Can now cancel a bulk part purchase

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Two changes:
- If removing a force, clear it off the StratCon board as well
- Can no longer deploy individual units to "hidden" scenarios to prevent both confusion and information leakage
> bulletproofing for a couple of actions with regard to StratCon

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
This fixes the last LGTM issue.
> Fixing Last LGTM Issue

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
I'd wager this was a copy/paste code issue, and was found in #2816 (this one fixes #2816)
> 2816: New Day: Fixing Two AtB Morale ArrayIndexOutOfBoundsExceptions

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
This fixes a NPE found in the log from #2816
> StratCon Scenario Generation New Day NPE Prevention

- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
> 2786: CustomizePersonDialog Phenotype and Gender ComboBox bugfixes

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes #2754 and requires https://github.com/MegaMek/megamek/pull/3097
> 2754: Properly clearing Hidden, Narc, and iNarc Flags during scenario resolution

- MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
This fixes a bug I discovered while testing out another story, and adds natural order sorting to the mission name.
> Fixing AtB Lance Role Sorting

- MekHQ/src/mekhq/MekHQ.java
This fixes #1042 and a newer bug with MegaMek preferences not saving
> 1042: Fixing Client Button Setting and MegaMek Preferences Not Saving from MekHQ

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/resources/mekhq/resources/PersonViewPanel.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/campaign/handler/XPHandler.java
- MekHQ/src/mekhq/campaign/mod/am/InjuryUtil.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/PersonAwardController.java
- MekHQ/src/mekhq/campaign/personnel/generator/AbstractPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
- MekHQ/src/mekhq/gui/dialog/CampaignOptionsDialog.java
- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- MekHQ/unittests/mekhq/campaign/personnel/PersonTest.java
This fixes #2798, pretty much copied the logic for Track Total Earnings when doing this.
> 2798: Adding Total XP Earnings Tracking

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
This fixes a NPE that I discovered while looking into some logs on Discord.
> Preventing Null Force Template Addition

- MekHQ/src/mekhq/campaign/force/Force.java
- MekHQ/src/mekhq/gui/panes/UnitMarketPane.java
This fixes Force Camouflage not layering and properly sends it to MegaMek. Requires https://github.com/MegaMek/megamek/pull/3114
> AbstractIcon: Force Camouflage: Layering and Properly Sending to MegaMek

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
This fixes the missing serialization for effectiveOpforSkill and effectiveOpforQuality and updates the writeToXML to use the new setup.
> Serializing StratCon OpFor Skill and Quality

- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
> 1420: Can No Longer Deploy a Person Multiple Times

- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/MekLocation.java
- MekHQ/src/mekhq/campaign/parts/MissingMekLocation.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
This fixes #1236 by adding full support for Tripod 'Mechs to MekHQ.
To review: whitespace differences off, as I fixed a bunch of spacing issues in Unit.
> 1236: Adding full support for Tripod 'Mechs

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/dialog/ChooseRefitDialog.java
- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/gui/model/ProcurementTableModel.java
- MekHQ/src/mekhq/service/PartsAcquisitionService.java
This fixes #2567 and a further contract date issue I discovered while investigating that.
The first commit is a bit of code cleanup, the second commit is the actual fix.
> 2567: AtB now follows the part acquisition skill option

- MekHQ/src/mekhq/MekHQOptions.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
I also fixed the constant save value, as using .name is more stable going forwards.
> Fixing an NPE in Personnel Filter Style

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
MekHQ-side of https://github.com/MegaMek/megamek/pull/3220
> IGame Interface Removal

- MekHQ/src/mekhq/gui/FinancesTab.java
Found this while working on localization issues with regards to dates.
> Fixing Inline Date Format

- MekHQ/src/mekhq/gui/CampaignGUI.java
Fixed a build failure due to changes in MegaMek's code
> Build Failure: GameOptionsDialog Update Fixes

- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
I can't believe I didn't notice these were missing during testing, but... this adds the filters.
> AssignUnitToPersonMenu: Adding Missing Personnel Filters

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
- MekHQ/unittests/mekhq/campaign/CampaignTest.java
The first four changes remove unused functionality and add returns to improve the performance, the fifth moves code into a method to handle the returns properly.
> Personnel Assignment Performance Improvements

- MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
Pretty straightforward. A gunner's a gunner, not a pilot. Fixes #2944.
> don't assign gunners as vehicle drivers

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
> 2962: AtB Campaigns Now Properly Load with Automatic or Tech Acquisition Skills

- MekHQ/src/mekhq/MekHqXmlUtil.java
This is the MekHQ implementation of https://github.com/MegaMek/megamek/pull/3282
> CommonConstants: MekHQ Removal

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
> Some cleanup in MHQ from the MM/MML updates including a Windows Bugfix

- MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
> 2983: Reordering spouse KIA logging so it is assigned to the correct person

- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
> 2993: Fixing Duplicated Small Craft and JumpShip Pilot Assignment

- MekHQ/src/mekhq/MekHQ.java
MekHQ side of https://github.com/MegaMek/megamek/pull/3346
> Logging: Default Global Exception Handler and Standardized Legacy Logging

- MekHQ/src/mekhq/campaign/icons/UnitIcon.java
> 3040: Fixing Unit Icon Filename Write Copy/paste Error

- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
This fixes #3038 and a few other missing comparators I noticed while investigating.
> 3038: Fixing missing Personnel Table Integer Comparators 

- MekHQ/src/mekhq/campaign/parts/Refit.java
> 2897: Prevent Loading of parts with invalid part ids

- MekHQ/src/mekhq/gui/adapter/TaskTableMouseAdapter.java
> 2947: Reset Skill Minimum upon scrap

- MekHQ/build.gradle
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/MekHQ.java
This is the MHQ implementation for https://github.com/MegaMek/megamek/pull/3412
> Improved Initial Log Message

- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
> 3102: Fixing Contract Completion Retirement ConMod

- MekHQ/src/mekhq/MekHQ.java
This is required for resolutions above 1080p, and is just code copied from https://github.com/MegaMek/megamek/pull/3427.
> BLOCKER: Read the font directory for MHQ instead of ignoring it.

- .github/codecov.yml
- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/nightly-ci.yml
- MekHQ/build.gradle
- MekHQ/src/mekhq/campaign/personnel/enums/FamilialRelationshipType.java
- build.gradle
This fixes the current maven issues and standardizes the internals with MM and MML build and integration changes.
> Build Script and Integration Issues: Standardization and Fixes

- MekHQ/src/mekhq/campaign/unit/UnitOrder.java
> 3130: Fixing Unit Order File I/O Copypaste Bug

- MekHQ/build.gradle
- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/campaign/personnel/enums/BabySurnameStyle.java
- MekHQ/src/mekhq/campaign/personnel/enums/FamilialRelationshipType.java
Useful links:
- https://github.com/MegaMek/mavenrepo
- https://github.com/MegaMek/megamek/wiki/Running-the-Packaging-Scripts
> Another few format changes for MML Maven testing

- MekHQ/resources/mekhq/resources/MekHqOptionsDialog.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/MHQOptions.java
- MekHQ/src/mekhq/gui/dialog/MedicalViewDialog.java
- MekHQ/src/mekhq/gui/dialog/MekHqOptionsDialog.java
> 3097: Adding Medical Dialog Handwriting Font Selection Option

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
This fixes #3185 by adding the none skill experience.
> 3185: Fixing Ransom With None Skill Experience

- MekHQ/src/mekhq/service/AutosaveService.java
To review:
Commit 1: Fixing resource leaks
Commit 2: Fixing missing null annotations
Commit 3: Code Cleanup, largely adding finals
> Autosave: Fixing resource leaks and nullability

- MekHQ/src/mekhq/MekHqXmlUtil.java
- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/force/UnitStub.java
- MekHQ/src/mekhq/campaign/log/PersonalLogger.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/BotForceRandomizer.java
- MekHQ/src/mekhq/campaign/personnel/Clan.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/enums/MergingSurnameStyle.java
- MekHQ/src/mekhq/campaign/universe/News.java
- MekHQ/src/mekhq/gui/DailyReportLogPanel.java
- MekHQ/src/mekhq/gui/dialog/AcquisitionsDialog.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- MekHQ/src/mekhq/gui/menus/AssignUnitToTechMenu.java
- MekHQ/src/mekhq/service/AutosaveService.java
This fixes a naming issue I caused during a legacy update.
> StringUtility: Renaming isNullOrEmpty to the proper isNullOrBlank

- MekHQ/src/mekhq/campaign/unit/Unit.java
This cleans up Unit::getSparePartsCost
> Unit: Cleaning Up Spare Parts Code

- MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
> Fixing VTOL Pilot Assignment

- MekHQ/resources/mekhq/resources/Unit.properties
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/unit/enums/CrewAssignmentState.java
- MekHQ/src/mekhq/gui/HangarTab.java
- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/dialog/MassRepairSalvageDialog.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
This fixes #3173.
To Review: Whitespace differences off. Commit 1 is a refactor to fix ordering issues and an option that wasn't set properly, Commit 2 adds the new values to the Hangar Table.
> 3173: Hangar Table: Adding Crew State and Condition columns

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
This removes a bit of unused code.
> Removing CampaignXmlParser Commented Out Info Code

- MekHQ/resources/mekhq/resources/NewContractDialog.properties
- MekHQ/src/mekhq/campaign/mission/Contract.java
- MekHQ/src/mekhq/gui/dialog/CustomizeAtBContractDialog.java
Pretty straight forward - allows the user to edit the base pay of an AtB contract.
> edit contract base pay

- MekHQ/src/mekhq/campaign/finances/Transaction.java
This makes it call the actual migration method...
> Fixing Transaction Type Migration

- MekHQ/src/mekhq/gui/view/MissionViewPanel.java
> Contract Score now shows properly in AtB

- MekHQ/src/mekhq/campaign/Campaign.java
> 3260: Clear Makeshift Clubs Upon Return To MekHQ

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/RetirementDefectionTracker.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
- MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java
I also renamed the civilian check to isCivilian
> Adding Missing Retirement Civilian Error Logging

- MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
- MekHQ/src/mekhq/gui/menus/AssignTechToUnitMenu.java
Commit 1 reorders so that the setName is done first, commit 2 adds the missing colour assignment
> Fixing Missing Navigator to Unit Colour Assignment

- MekHQ/src/mekhq/campaign/CampaignOptions.java
This is how it should have worked period, and is a blocker for 0.49.8.
> Personnel Modules: Migrate Retirement and Dependent Modules based on AtB Enable

- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
> 3281: Preventing Contract Market No Selected Contract NPE

- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- MekHQ/src/mekhq/gui/dialog/NewContractDialog.java
Two changes:
1 - "integrated" StratCon contracts won't have any objectives - the player has very little control over whether they get completed (addresses #2973)
2 - fixed a random NPE while typing stuff into the planet name textbox in the create contract interface
> remove strategic objectives for integrated contracts

- MekHQ/src/mekhq/campaign/personnel/Person.java
Found this while working on names
> Person XML: Fixing Copy Paste Error

- MekHQ/src/mekhq/campaign/finances/CurrencyManager.java
- MekHQ/src/mekhq/campaign/universe/StarUtil.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
Commit 1 moves personnel tab code outside of the file writing try catch and fixes missing null handling, Commit 2 fixes resource leaks where Closeable classes are improperly used in Try With Resources.
> Fixing Try With Resources Resource Leaks

- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
This fixes the leaks by swapping to try with resources, and expands the logging for the various file manipulation responses
> CampaignGUI: Fixing Campaign Save Resource Leaks

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
This has been raised a few times on Discord recently.
> Ignore End Date for Scenario Assignment to Active Contracts

- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
This fixes #3346 and fixes #3347
> 3346/3347: CustomizePersonDialog: Fixing Skills and Abilities Scroll Increments

- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
> 3362: CampaignOptionsPane: Personnel Tab: Allow Horizontal Scrolling

- MekHQ/resources/mekhq/resources/Finances.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
This fixes #3372 and a few more campaign report issues that I found while investigating it. I also added a new add report version to reduce simplify the code there.
> 3372: Fixing Campaign Loan Report Issues

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/BotForce.java
- MekHQ/src/mekhq/campaign/parts/Refit.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/campaign/unit/UnitOrder.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/FileDialogs.java
- MekHQ/src/mekhq/utilities/MHQXMLUtility.java
This fixes #3375 and a critical bug I found during it where loaded entities won't have their game set properly... which causes NPEs.
> 3375: Export MUL File Exports a MUL Per Player

- MekHQ/src/mekhq/utilities/MHQXMLUtility.java
Found this while testing #3398, you can't send null to Entity::setGame.
> Fixing Single Entity MUL NPE with Null Campaign

- MekHQ/src/mekhq/campaign/personnel/Bloodname.java
> 3291: Fixing No Exclusive Bloodnames Bloodname Generation Exception

- .gitignore
- MekHQ/data/universe/financialInstitutions.xml
- MekHQ/resources/mekhq/resources/CampaignGUI.properties
- MekHQ/resources/mekhq/resources/Finances.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/campaign/finances/Loan.java
- MekHQ/src/mekhq/campaign/finances/financialInstitutions/FinancialInstitution.java
- MekHQ/src/mekhq/campaign/finances/financialInstitutions/FinancialInstitutions.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/unittests/mekhq/campaign/finances/financialInstitutions/FinancialInstitutionTest.java
- MekHQ/unittests/mekhq/campaign/finances/financialInstitutions/FinancialInstitutionsTest.java
- MekHQ/unittests/mekhq/campaign/personnel/familyTree/FormerSpouseTest.java
- MekHQ/userdata/data/universe/financialInstitutions.xml
This handles a longterm TODO in the Loans code, with the addition of start and end dates. These additions are at 100% unit testing coverage.
> Moving Financial Institutions to Data

- MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
This improves the default handling to be my intended way.
> Company Generator: Improving Missing Force Icon Handling

- MekHQ/src/mekhq/campaign/personnel/death/AbstractDeath.java
- MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
- MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java
- MekHQ/unittests/mekhq/campaign/personnel/death/AbstractDeathTest.java
- MekHQ/unittests/mekhq/campaign/personnel/divorce/AbstractDivorceTest.java
- MekHQ/unittests/mekhq/campaign/personnel/marriage/AbstractMarriageTest.java
- MekHQ/unittests/mekhq/campaign/personnel/procreation/AbstractProcreationTest.java
Still a WIP, opening for CodeCov
> Personnel Modules: Expanding Unit Testing

- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQScrollablePanel.java
- MekHQ/src/mekhq/gui/baseComponents/DefaultMHQScrollablePanel.java
- MekHQ/src/mekhq/gui/baseComponents/JScrollablePanel.java
- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
- MekHQ/src/mekhq/gui/panes/CampaignPresetPane.java
- MekHQ/src/mekhq/gui/panes/RankSystemsPane.java
This creates a new base component that is for inline AbstractMHQScrollablePanel uses, and implements it.
> Base Components: DefaultMHQScrollablePanel

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/Utilities.java
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/ForceTemplateAssignmentDialog.java
- MekHQ/src/mekhq/gui/utilities/StaticChecks.java
- MekHQ/unittests/mekhq/campaign/unit/UnitTransportTest.java
> 3489: Adding Small Craft and DropShip Transport Support

- MekHQ/src/mekhq/gui/FinancesTab.java
- MekHQ/src/mekhq/gui/PlanetarySystemMapPanel.java
- MekHQ/src/mekhq/gui/dialog/reportDialogs/PersonnelReportDialog.java
- MekHQ/src/mekhq/gui/dialog/reportDialogs/TransportReportDialog.java
- MekHQ/src/mekhq/gui/dialog/reportDialogs/UnitRatingReportDialog.java
This requires https://github.com/MegaMek/megamek/pull/3998
> MHQConstants: Isolate Font Constants

- MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
This fixes #2467 and fixes #3483
> Issues #2467, #3483: Fix Battle Armour Tech Introduction and Clan Filtering

- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
The dialog's code needs a rewrite, so I just worked around it for now to add the functionality.
> Contract Market: Adding Transit Time and Estimated Profit Columns

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Sandblaster is now back on the menu and functional. Not sure if it was removed when the code changed in MM, but it did work once upon a time...
> Fixes #1858 Sandblaster issue in 0.47.7

- MekHQ/src/mekhq/gui/dialog/ScenarioTemplateEditorDialog.java
Found this while doing some testing
> Scenario Template Editor: Fixing Scrolling Intervals

- MekHQ/src/mekhq/campaign/universe/companyGeneration/CompanyGenerationOptions.java
> 3435: Company Generator: Fixing Preset System

- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Found this while working on #3533
> Data Loading: Don't Override the Selected Date

- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
> 3389: Personnel Table: Sort Age Using Birthdate

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- MekHQ/src/mekhq/io/migration/GameOptionsMigrator.java
> 3553: Migrate Turn Timer Game Option

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
> 3541: Maintenance Extra Time Doesn't Show For Unmaintained Units

- MekHQ/src/mekhq/campaign/personnel/Skill.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
> 3345: Rename Gunnery/Protomech to Gunnery/ProtoMech

- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/gui/dialog/AddFundsDialog.java
- MekHQ/src/mekhq/gui/dialog/ChooseFactionsDialog.java
- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/EditAssetDialog.java
- MekHQ/src/mekhq/gui/dialog/EditInjuryEntryDialog.java
- MekHQ/src/mekhq/gui/dialog/EditPersonnelHitsDialog.java
- MekHQ/src/mekhq/gui/dialog/EditPersonnelInjuriesDialog.java
- MekHQ/src/mekhq/gui/dialog/EditSkillPrereqDialog.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
- MekHQ/src/mekhq/gui/dialog/HistoricalDailyReportDialog.java
- MekHQ/src/mekhq/gui/dialog/LargeCraftAmmoSwapDialog.java
- MekHQ/src/mekhq/gui/dialog/ManageAssetsDialog.java
- MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java
- MekHQ/src/mekhq/gui/dialog/MercRosterDialog.java
- MekHQ/src/mekhq/gui/dialog/MissionTypeDialog.java
- MekHQ/src/mekhq/gui/dialog/NewLoanDialog.java
- MekHQ/src/mekhq/gui/dialog/NewPlanetaryEventDialog.java
- MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java
- MekHQ/src/mekhq/gui/dialog/PayCollateralDialog.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/PopupValueChoiceDialog.java
- MekHQ/src/mekhq/gui/dialog/RefitNameDialog.java
- MekHQ/src/mekhq/gui/dialog/SelectUnusedAbilityDialog.java
- MekHQ/src/mekhq/gui/dialog/SmallSVAmmoSwapDialog.java
This is a bug because Frame uses sometimes fail to call all of the accessibility methods that JFrame uses will catch.
> Swap Frame Uses to JFrame

- MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java
> 3573: Null Protect Adding Allied Entities to an Objective

- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AceDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AlliedTraitorsBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/AmbushBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/CivilianHelpBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/PrisonBreakBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache1BuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/StarLeagueCache2BuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java
> 3576: Prevent Ultra-Light and Superheavy Scenario Assignment OutOfBounds NPEs

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/MHQOptions.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- MekHQ/src/mekhq/gui/menus/ExportUnitSpriteMenu.java
Requires https://github.com/MegaMek/megamek/pull/4109
> MM4098: Adding Sprite Camouflage and Damage Export Options

- MekHQ/src/mekhq/gui/MekLabTab.java
> 3554: Null Protecting MechSummaryCache Return

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/gui/PersonnelTab.java
- MekHQ/src/mekhq/gui/enums/PersonnelTabView.java
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTabViewTest.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
This also fixes a bug when swapping off of the Graphical View by adding a Person column.
> Personnel Table: Adding Flag View

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignPreset.java
- MekHQ/src/mekhq/campaign/personnel/SkillType.java
- MekHQ/src/mekhq/campaign/personnel/SpecialAbility.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/CampaignExportWizard.java
- MekHQ/src/mekhq/gui/dialog/CreateCampaignPresetDialog.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- MekHQ/src/mekhq/gui/dialog/EditSpecialAbilityDialog.java
- MekHQ/src/mekhq/gui/dialog/SelectAbilitiesDialog.java
- MekHQ/src/mekhq/gui/dialog/SelectUnusedAbilityDialog.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
I actually fixed the SPA Campaign Options bug during this tear out, as the cause became obvious while finishing code cleanup.
> SPA: Tearing Out Unused Implant and Edge Code and Fixing New Campaign Options Reset

- MekHQ/src/mekhq/campaign/Campaign.java
This fixes a dumb mistake I made and adds fixmes for the missing localization.
> Yearly Retirement Nag Now Follows Campaign Options

- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
This organizes, inlines, and isolates Campaign GUI code.
> Campaign GUI Simplification

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechTimeNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechsNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientMedicsNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/OutstandingScenariosNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/ShortDeploymentNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/UnmaintainedUnitsNagDialog.java
- MekHQ/src/mekhq/gui/dialog/nagDialogs/UnresolvedStratConContactsNagDialog.java
This requires https://github.com/MegaMek/megamek/pull/4112.
> BaseComponents: Migrate Nag Dialog Baseline to MM

- MekHQ/src/mekhq/campaign/personnel/Person.java
> 3592: Handling Procration for Returning Pregnant Personnel

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/CommandCenterTab.java
- MekHQ/src/mekhq/gui/dialog/AdvanceDaysDialog.java
> 3605: News Properly Shows in Advance Days Dialog

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQNagDialog.java
> 3601: Fixing Nag Display and Specified Description Text

- MekHQ/src/mekhq/campaign/mission/atb/scenario/AceDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/OfficerDuelBuiltInScenario.java
- MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java
> 3599: Prevent Null Entity Generation Scenario Creation NPEs

- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Looks pretty straightforward :)
> Fix Bug Preventing Mass Mothball Dialog from Popping Up

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
> Fix for "Regenerate Forces" duplicating scenario description and objectives

- MekHQ/build.gradle
> Revert "Gradle build fixes"

- MekHQ/src/mekhq/campaign/parts/equipment/MASC.java
> simplify masc loading

- MekHQ/src/mekhq/gui/MekLabTab.java
This adapts MHQ to MegaMek/megamek#4474
> BV and MP adaptation to MM changes

- MekHQ/src/mekhq/Utilities.java
This adapts MHQ after https://github.com/MegaMek/megamek/pull/4510
> MM PR 4510: Weapon Specialist: Fix Option Display Format

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Required by MegaMek/megamek#4601. The campaign options are not available in loadBombs, so the value is set that continues the previous behavior.
Also sets GameOptions field based on campaign options setting.
> API update for ITechnology

- MekHQ/build.gradle
Build script update so that new dir can be included in distributions.
> build script update to pickup new image dir

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
Looking into Action failures and noticed a lot more actions are out of date (not the likely cause, but going to start from the beginning).
> [GitHub] Bump action versions

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
Maybe it's the build cache getting pulled in causing the transient issues.
> [GitHub] Disable Gradle build cache

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
Try to get additional information out of Gradle as to why things are going the way they're going.
> [GitHub] Increase Gradle log level to INFO

- MekHQ/src/mekhq/gui/MekLabTab.java
This adapts The MekLabTab in MHQ to the latest MML changes and resolves compilation errors
> Adaptation to MML changes

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
A method rename in ClientGUI.java was made and was not updated in MekHQ - fixes broken nightly.
> Fix nightly build from a missed method rename in megamek.

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/MHQOptions.java
- MekHQ/src/mekhq/gui/StratconPanel.java
- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
- add MHQOption for stratconHexCoordForeground color
> add MHQOption for stratconHexCoordForeground color

- MekHQ/data/stratconbiomedefinitions/StratconBiomeManifest.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/gui/StratconPanel.java
In no particular order:
-fix missing badlands image
-don't fail to generate scenario when temperature mapping isn't present for facility
-more contrast between revealed/unrevealed hexes
fixes #3741
> stratcon data/graphics fixes

- MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
Superheavy mechs behave sort of like vehicles and large spacecraft when it comes to crew assignment. Fixes #3747
> allow assignment of pilot/gunner to superheavy mech

- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
As the title says, a small adaptation to moving quirks to unit files.
> Moving Quirks to unit files: adapt MHQ to MM changes

- MekHQ/src/mekhq/utilities/MHQXMLUtility.java
- update to use constants
requires https://github.com/MegaMek/megamek/pull/5071
they should be committed at the same time
> MUL parser updates

- MekHQ/src/mekhq/gui/RepairTab.java
- MekHQ/src/mekhq/gui/model/UnitTableModel.java
- in repair bay unit list, show if unit is in repair or salvage mode
> in repair bay unit list show if unit is in repair or salvage mode

- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/BaArmor.java
- MekHQ/src/mekhq/campaign/parts/ProtomekArmor.java
MekHQ part of MegaMek/megamek#5101
> Armor rework, part 1a

- MekHQ/src/mekhq/utilities/MHQXMLUtility.java
This adapts MHQ to MegaMek/megamek#5107
> Adaptation to the clanname field for Meks

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/campaign/finances/Money.java
> #3740 Standardising on C-Bills

- MekHQ/src/mekhq/campaign/market/PartsStore.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- MekHQ/src/mekhq/campaign/parts/ProtomekArmor.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
MekHQ part of MegaMek/megamek#5116
> Armor rework, part 1b

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/nightly-ci.yml
- .github/workflows/nightly-maven-ci.yml
Noticed CI and nightly actions had a number of deprecation notices.
> Bump GitHub action versions

- MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
> No selling units in scenario resolution if campaign disallows selling

- MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- MekHQ/src/mekhq/gui/dialog/QuirksDialog.java
This PR  goes along with MegaMek/megamek#5369. It should be merged with that one to handle dependencies.
> Add action listener for DialogOptionListeners

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
These changes are needed for MekHQ to run under the latest .20 code.  These updates match existing code in MM.
Testing:
- Ran MekHQ unit tests
- Started MekHQ and loaded a campaign, started and finished a mission
> Update to match latest .20 code: Fix MekHQ GameThreads.run

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- save boardType to xml file
- this caused issues with space and low atmosphere scenarios after a save and load.
- add additional checks for when board is space
fixes #4017
> save boardType to xml file

- MekHQ/data/terrainconditionsodds/TerrainConditionsOddsManifest.xml
- MekHQ/src/mekhq/campaign/mission/TerrainConditionsOddsManifest.java
- add glare and solar flare odds
requires https://github.com/MegaMek/megamek/pull/5295
> add glare and solar flare odds

- MekHQ/docs/history.txt
> merge 3928 and 4023

- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/Scenario.java
- MekHQ/src/mekhq/gui/view/ScenarioViewPanel.java
- move modifiedTemperature to AtBScenario
- save and load modifiedTemperature to xml
fixes #4051
> move modifiedTemperature to AtBScenario

- MekHQ/unittests/mekhq/campaign/parts/equipment/EquipmentPartTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/LargeCraftAmmoBinTest.java
- MekHQ/unittests/mekhq/campaign/parts/equipment/MissingLargeCraftAmmoBinTest.java
I believe this will fix the broken tests on Weapon Bays in MekHQ. I am not an expert on tests though, so some one please check my work!
> Attempt to fix broken bay equipment tests

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/codeql-analysis.yml
First attempt to add 0.49.19.1-specific workflows.
> Update workflows for 0.49.19.1 (attempt 1)

- MekHQ/src/mekhq/gui/dialog/EditMapSettingsDialog.java
> MM code adaptation for boards validation

- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/unittests/mekhq/campaign/personnel/education/AcademyTests.java
This fixes the incorrect hyperspace navigation and small arms parsing within academy.java
> Fix Hyperspace Navigation & Small Arms Parsing in Education Module

- MekHQ/src/mekhq/gui/dialog/ChooseRefitDialog.java
Per title.
Tested by running MHQ unit tests, and refitting a unit in MekHQ.
> Replace old MechView instantiation that is breaking MekHQ nightlies

- MekHQ/docs/history.txt
> Updated history.txt with Recent Merges

- MekHQ/docs/history.txt
> Updated history.txt to Include Latest Merges

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/resources/mekhq/resources/Education.properties
- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/unittests/mekhq/campaign/personnel/education/AcademyTests.java
This PR adds the first batch of prestigious academies. Pending Hammer's approval, these are the final values and will replace the placeholder values previously merged.
I also made some minor changes to the academy code:
I updated local academy qualification start dates to match those used by prestigious academies.
I removed 'promotions' as I was not satisfied with their implementation. I plan to review the Ranks System down the road and re-implement it then.
Child graduations no longer use the same graduation text as adults.
Additionally, I removed the 'faction' field, as it was a relic from a previous iteration and is no longer necessary.
> Added Prestigious Academies (A-A)

- MekHQ/docs/history.txt
> Updated history.txt

- MekHQ/docs/history.txt
> Updated History

- MekHQ/data/universe/academies/Prestigious Academies.xml
This PR fixes an NPE caused by the James McKenna University lacking any qualifications.
> Fixed Missing Qualification from James McKenna University

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- Replaced getName method with direct use of campus id for eduAcademySystem (resolves NPE)
- Removed duplicate setting of eduAcademyNameInSet
- Adjusted local academy name generation logic to use campus name, instead of campus ID (visual bug)
> Fixed Campus Name in Education Module

- MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
This PR corrects the Management Skill modifier as that it is now a bonus not a malus.
> Inverted Management Skill Modifier in RetirementDefectionTracker

- MekHQ/data/universe/academies/Prestigious Academies.xml
- Updated tuition fees for a number of academies
- Changed qualification and curriculum requirements for a number of academies - this mostly involved adding or removing Administration-based qualifications. As these were being parsed incorrectly by my academy spreadsheet.
- Added missing faction restrictions for certain academies
- Updated the minimum education level requirement for several academies
- Modified descriptions for some academies
All changes were verified using #4274 to check data had been entered correctly.
> Numerous Corrections to the Prestigious Academies.

- MekHQ/data/universe/academies/Prestigious Academies.xml
As per title. All academies tested using #4274.
> Added Prestigious Academies K-M

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Fixes "unhandled exception" error introduced by adding a new EntitySavingException exception type.
Testing:
- Reran all 3 projects' unit tests.
- Refit units to custom and saved, checking logs.
> Add handling for new save-time exception added by fixes to MML 1537

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
As per title. All academies checked using the override requirements campaign option.
I also fixed a number of academies having the wrong type, construction/destruction date, or wrong base education level.
> Added Prestigious Academies R-T

- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
This PR adds the final thirty or so prestigious academies, as well as fixes a minor bug with the override requirements campaign option.
> Added Prestigious Academies U-W

- .github/workflows/ci.yml
- .github/workflows/nightly-ci.yml
- MekHQ/build.gradle
- MekHQ/sentry.properties
- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/GameThread.java
- MekHQ/src/mekhq/IconPackage.java
- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/MHQOptions.java
- MekHQ/src/mekhq/MHQOptionsChangedEvent.java
- MekHQ/src/mekhq/MHQStaticDirectoryManager.java
- MekHQ/src/mekhq/MekHQ.java
- MekHQ/src/mekhq/NullEntityException.java
- MekHQ/src/mekhq/Utilities.java
- build.gradle
Copyright updates
Some warnings removed
CI Updates
> Sentry Additions

- MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
The payout calculation has been updated in the RetirementDefectionTracker to correctly use the retirement multiplier option for KIA personnel.
I also updated the sole use of `switch` in `RetirementDefectionTracker.java` to use the new j17 enhanced switch format.
> Update Payout Calculation for KIA Personnel

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
This PR introduces three new academies to the Local Academies.xml file: Military Creches, Junior Schools, and Colleges.
Furthermore, it updates a number of incorrect entries in the prestigious academy file.
Closes #4361
> Updated & Corrected Prestigious Academy Information and Added Three New Types of Local Academy

- MekHQ/campaigns/Fist and Falcon/Kewran Wolfhounds, C Company, 3rd Battalion, 25th Arcturan Guards RCT.cpnx
- MekHQ/campaigns/Wolf and Blake/Black Widow Company, Church's Independent Company, Wolf's Dragoons.cpnx
- MekHQ/campaigns/Wolf and Blake/Shadow Hunters, Opacus Venatori, Fifty-second Shadow Division.cpnx
- MekHQ/data/universe/news.xml
> Typos, spelling etc.

- MekHQ/build.gradle
Removed unused variables
Updated dependencies
Added CleanALl task
> Adjustments for Window INI creation

- MekHQ/src/mekhq/campaign/force/Force.java
Added a missing recursion element to ensure the TO&E is read correctly.
> Fixed Formation Level Calculations

- MekHQ/mmconf/campaignPresets/Campaign Operations (StratCon).xml
- MekHQ/mmconf/campaignPresets/Campaign Operations.xml
- MekHQ/mmconf/campaignPresets/Complete Experience.xml
- MekHQ/mmconf/campaignPresets/New Pilot Program.xml
- MekHQ/mmconf/campaignPresets/Tabula Rasa.xml
Updated various settings in the new presets.
SPA adjustments courtesy of @Saklad5
> Corrected New Presets, Added Missing Updated SPA Costs

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- MekHQ/src/mekhq/campaign/personnel/enums/randomEvents/personalities/Intelligence.java
- MekHQ/src/mekhq/gui/enums/PersonnelTabView.java
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTabViewTest.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
Enhanced the `PersonnelTabView` to include new columns for personality characteristics such as aggression, ambition, greed, social, and intelligence. Added getters for these traits and updated sorting and display logic to support the new attributes. Also included a test for personality traits in PersonnelTabView.
> Added Personality Characteristics and Loyalty to Personnel Tab

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
> Added Missing Maintenance Planetary Modifier Text

- MekHQ/src/mekhq/campaign/market/ContractMarket.java
- MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
This adds the ability for Admin/Logistics personnel to reroll salvage terms when negotiating AtB contracts. The plumbing was already in place--I mostly just had to add the UI elements.
> Implement negotiation for salvage terms

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java
Turns out some moron forgot to tell mhq to weekly fresh Reputation. This PR corrects that oversight. >_>
I also went and renamed some xml parsing variables, because if I'm going to be asking other developers to avoid single or two letter variables I should follow my own advice.
> Fixed Weekly Reputation Recalculations

- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
> Removed unused import of LogManager and corrected the import path for Intelligence.

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Simplified the conditionals for DropShip bonus calculation by merging nested checks. Updated tooltip text to clarify DropShip salvage rules.
> Refactored DropShip Bonus Calculation Logic

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
- MekHQ/src/mekhq/campaign/storyarc/storypoint/CreateCharacterStoryPoint.java
- MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java
- MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
- MekHQ/src/mekhq/gui/dialog/NewRecruitDialog.java
Removed duplicate personality generation calls across various classes. Centralized education level assignment and personality generation logic.
> Refactored Personality Generation and Education Level Assignment.

- MekHQ/resources/mekhq/resources/GUI.properties
Updated the title and text of DataLoadingDialog's NullPointerException messages to provide clearer and more general error descriptions. This change aims to make troubleshooting easier by specifying that save loading issues may not be limited to missing academy data.
> Simplified NullPointerException Message in DataLoadingDialog

- MekHQ/src/mekhq/campaign/force/Force.java
Merge of previous fix got overwritten during conflict resolution. Code is identical to previous approved PR.
> Fixed Bad Merge

- MekHQ/src/mekhq/campaign/force/Force.java
Merge of previous fix got overwritten during conflict resolution. Code is identical to previous approved PR.
> Fixed Bad Merge (again)

- MekHQ/src/mekhq/gui/BriefingTab.java
Fix for MHQ side of #4755 : assign a default "IS" faction code to forces with blank or null faction code.
This was seen in a long-running campaign where the initial enemy force was routed, so a new "Mercenary" force was generated.  However, owing either to a load/save issue or some other issue, the new force's faction code was not saved, causing some tests and lookups to raise Null Pointer Errors.
Testing:
- Verified correct function with Op's campaign save.
Close #4755 
Note: this PR can be pulled independently of the MegaMek portion.
> MHQ side of fix for MHQ 4755: NPE when opfor has no faction code

- MekHQ/resources/mekhq/resources/FormationLevel.properties
- MekHQ/src/mekhq/campaign/force/FormationLevel.java
Introduced a new "Army Group" formation level for Inner Sphere forces. Updated the relevant parsing logic and the properties file to support this new level.
> Added Army Group Formation Level

- MekHQ/src/mekhq/campaign/personnel/enums/Phenotype.java
Added compatibility handlers for the phenotypes that hand their names changed by the name change project.
Added JavaDocs for better code documentation and readability.
> Added Post-Name Change Compatibility Handlers, Added JavaDocs to Phenotype.java

- MekHQ/src/mekhq/campaign/personnel/SkillType.java
Updated `generateInstanceFromXML` method to handle legacy skill names for backward compatibility.
> Added Post-Name Change Compatibility Handlers to SkillType.java

- MekHQ/data/universe/academies/Unit Education.xml
Added a new "Adult Apprenticeship" to the in-unit education list. Additionally, updated the tuition fees for "In-House Boot Camp" and "Advanced Technical Training" to zero.
> Added Adult Apprenticeship and Updated Tuition Fees

- MekHQ/mmconf/campaignPresets/Campaign Operations (StratCon).xml
- MekHQ/mmconf/campaignPresets/Campaign Operations.xml
- MekHQ/mmconf/campaignPresets/Complete Experience.xml
- MekHQ/mmconf/campaignPresets/New Pilot Program.xml
- MekHQ/mmconf/campaignPresets/Tabula Rasa.xml
- MekHQ/resources/mekhq/resources/Campaign.properties
- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
With the number of changes in the last batch of merges, it's unsurprising that there were a few things wonky. This corrects the immediately found issues.
It also updates a single string in the simulations relationship function, and updates the campaign option presets.
> Post-Merge Corrections

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
Restored earlier version of xml, incorporating name changes as necessary. The academy xml got accidentally malformed by the name compliance project.
> Fixed Academy XML to Avoid Odd Formating

- MekHQ/src/mekhq/campaign/personnel/SkillPerquisite.java
- MekHQ/src/mekhq/gui/HangarTab.java
Added compatibility handlers for SPAs to replace legacy skill names with their updated versions.
> Added <50.01 Compatibility Handlers to `SkillPerquisite.java`

- MekHQ/src/mekhq/gui/dialog/EditDeploymentDialog.java
Must be merged together with MegaMek/megamek#6068
> Adaptation to MM #6068

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
- correct filter to be ```!getTerrainType().equals("Space")``` was proventing fixed map generation
- allow fixed map when doing a map reroll
> correct issues with fixed map generation

- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
... Only update all frames and windows when the gui scale is actually changed in the MekHQ options
> GUI Scaling fix

- MekHQ/src/mekhq/MekHQ.java
This and the PRs for MML and MM (merge together) fix some remaining gui scaling issues.
- adaptation to MM changes
- default to Darcula
> GUI scaling fixes

- MekHQ/src/mekhq/gui/ForceRenderer.java
Closes #5019 - also cleans up the file a little though I'm not up for a major refactor today
> ForceRenderer - bold unit commanders

- MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
Changed the calculation for `numTracks` to use Math.max, ensuring it is at least 1. This prevents issues that arose from having zero tracks.
> Added Minimum Number of Tracks (1) to StratCon Initialization

- MekHQ/data/scenariotemplates/Intercept Engagement.xml
Raised the destruction or routing requirement from 50% to 75% for scenario completion.
> Fixed Objective Criteria for `Intercept Engagement`

- MekHQ/src/mekhq/campaign/Campaign.java
Children are no longer considered the parents of their parents.
> Corrected Parameter Order in Simulated Relationship History Reports

- MekHQ/src/mekhq/campaign/Campaign.java
Changes the multi-day repair message to specify days remaining instead of always saying "tomorrow". Does similar for the refit messages.
> Better multi-day repair and refit reports.

- MekHQ/data/scenariotemplates/Convoy Escort.xml
- MekHQ/data/scenariotemplates/Convoy Interdiction.xml
- MekHQ/data/scenariotemplates/Convoy Raid.xml
- MekHQ/data/scenariotemplates/Critical Convoy Escort.xml
- MekHQ/data/scenariotemplates/Irregular Force Assault.xml
- MekHQ/data/scenariotemplates/Irregular Force Suppression.xml
Updated the `generationMethod` from 2 (fixed unit count) to 1 (BV) across several scenario templates. This will need to be monitored, but will better ensure these scenarios scale more appropriately with the player force.
> [FG3] Adjusted Generation Method in Some Scenarios

- MekHQ/data/terrainconditionsodds/TerrainConditionsOddsManifest.xml
- MekHQ/src/mekhq/campaign/mission/TerrainConditionsOddsManifest.java
- add lightning storm  odds
- adjust others odds
> update odds add lightning storm and adjust others

- MekHQ/data/stratconfacilities/AlliedSupplyDepot.xml
- MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Changed the support point modifiers gained from Supply Depot facilities from weekly to monthly.
> Refactor Supply Depot SP Modifiers to be Monthly

- MekHQ/resources/mekhq/resources/Personnel.properties
Changed the text and tooltip for the prisoner capture style, I had to go in the code that understand how the words "disable/random/automatic" were applied and what they actually meant gameplaywise, and because of that I think that a name change is important here.
> Changed wording in "Potential Capture Style"

- MekHQ/src/mekhq/campaign/universe/Factions.java
Fixed the faction logging statement to correctly use String.format.
> Updated Faction Loading Log Format

- MekHQ/src/mekhq/campaign/market/contractMarket/ContractAutomation.java
Contract Automation will no longer mothball DropShips, JumpShips, WarShips, or Space Stations.
> Enhanced Mothballing in `ContractAutomation`

- MekHQ/data/scenariotemplates/Irregular Force Assault.xml
- MekHQ/data/scenariotemplates/Irregular Force Suppression.xml
Changed generation methods for Irregular scenarios. This should help reduce the difficulty of both. `Irregular Force Assault` should be roughly as challenging as other normal scenarios; whole `Irregular Force Suppression` should be a much easier experience (by design).
> Updated Force Generation for Irregular Scenarios

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
merge together with MegaMek/megamek#6181
> Rename TroopSpace to InfantryCompartment

- MekHQ/src/mekhq/campaign/report/PersonnelReport.java
Added temp Astechs and Medics to Personnel Report. 
Support Personnel Salaries should  now display correct amount and match finances tab.
closes #5169
> Personnel Report Fix

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
Improved the force generation logging slightly for improved clarity.
> Improved Logging for Force Generation Process.

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java
- MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
- MekHQ/unittests/mekhq/campaign/personnel/marriage/AbstractMarriageTest.java
> Issue 5311: Marriage Announcements Not Appearing in Daily Activity Log

- MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java
> Corrected Calculation of Age Difference When Marrying Personnel

- MekHQ/resources/mekhq/resources/GUI.properties
Shortened button labels to enhance readability and reduce visual clutter.
**New**
**Old**
> Simplified Splash Screen Button Text

- MekHQ/src/mekhq/gui/StratconTab.java
Converted layout from `GridLayout` to `BorderLayout` for better structure. Adjusted component placements and sizes for improved readability and usability. Enhanced display of campaign and objective information with emphasized styles.
In laymen's terms, the StratCon info panel (the one on the right-hand side) is now vertical aligned to the top of the pane, and the pane's width has been reduced, removing a lot of unnecessary negative space. This gives substantially more room for the StratCon strategic map. This room isn't currently utilized by StratCon but is necessary for our 2025 plans.
> Refactored StratCon Tab Layout and Improved UI Design.

- MekHQ/mmconf/log4j2.xml
The console will log everything form the logger if you set an environment variable with `mm.profile=dev`
This way making debuging and developing a bit easier
> feat: env var mm.profile=dev makes log print on console

- MekHQ/src/mekhq/campaign/Campaign.java
Initialized `ignoreSparesUnderQuality` in `campaign.java`. As we act on this during saving if the value is `null` saving breaks and everyone has a bad time.
> Fixed Save Bug

- MekHQ/src/mekhq/campaign/Campaign.java
This PR updates how we add and remove Dependents. The new dependent addition/removal logic predated the 'simulated relationship' system. Unfortunately, they don't play nice together, with relationship dependents eating up the campaign's dependents capacity. This causes dependents not to randomly join the campaign, and for any that do to swiftly leave.
Rather than increasing the dependents capacity, as that likely would obliterate any campaign that doesn't use simulated relationships, I instead opted to update the logic itself. Now, when determining the number of current dependents we ignore any dependents with an active genealogy (i.e. relatives). That means all those spouses and children added by simulated relationships are not considered 'dependents' for the purposes of adding and …
> Adjusted Dependent Addition & Removal Logic

- MekHQ/resources/mekhq/resources/AtBStratCon.properties
- MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
Implemented resource bundle localization for Campaign Management Dialog strings. Improved UI layout with GridBagLayout for better scalability and alignment.
Fixes #5409
> Refactored StratCon Campaign Management Dialog

- MekHQ/src/mekhq/campaign/Campaign.java
While investigating #5369 I stumbled across some improvements that could be made to how we handle personnel when advancing days. There isn't anything particularly fancy here, just cleaning house.
> Refactored Personnel Handling on New Day

- MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
Refactored how we handle divorces (from living or dead spouses). The original code had a number of bugs that would have led to really weird and unintended behavior. Which how everything was laid out I suspect there was a conflict during merging, at some point, which I didn't resolve correctly leading to behavior that wasn't clearly broken - insofar as the user was concerned - in most cases, but under the hood was a bit of a mess.
Fixes #5369
> Fixed Divorce Logic

- MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java
- MekHQ/src/mekhq/gui/StratconPanel.java
This PR fixes an NPE caused when trying to deploy to a scenario in the AO while on an Integrated command contract. As StratCon doesn't expect you to try it throws a bit of a wobbly. This PR puts in some null protection which should resolve that issue moving forward.
Fixes #4430
> Fixed NPE in Caused by Deployment Attempt in Integrated Command

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/GenerateResupplyContents.java
- MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java
- MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
- MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/ResupplyUtilities.java
- MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogItinerary.java
- MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
- MekHQ/src/mekhq/gui/view/MissionViewPanel.java
Improved convoy item allocation by addressing edge cases, randomizing selection, and ensuring efficient distribution of cargo capacity.
Added enhanced logging and insured consistent handling of null cases.
Fixed bug that was causing the size of resupplies to be multiplied based on required forces multiple times.
Fixes #5453
> Refactored Resupply Logic and Streamlined Cargo Calculations.

- MekHQ/data/scenariotemplates/Emergency Convoy Defense - Player - VTOL.xml
Reduced force multipliers from 2.0 to 1.0 for OpFor and Air Cavalry in the VTOL player scenario template. This ensures better balance and aligns with intended difficulty scaling.
Fixes #5464
> Adjusted Force Multipliers in Emergency Convoy Defense - VTOL Scenario Template

- MekHQ/src/mekhq/campaign/unit/Unit.java
Fixes #5467 
Formerly MegaMek/megamek#6288
> Issue 5467: When resetting pilot check campaign settings for edge/SPA properly

- MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogItinerary.java
Fixed a missing resource reference in smuggler dialog.
> Fixed Resupply Smuggler Dialog Formatting

- MekHQ/data/universe/academies/Unit Education.xml
Updated the curriculum for basic battle armor training to include Anti-Mek training.
> Added Missing Anti-Mek Skill to Battle Armor Basic Training In-Unit Education Curriculum

- MekHQ/src/mekhq/campaign/rating/CamOpsReputation/TransportationRating.java
Adjusted capacity and requirement logic for ASF, heavy vehicles, and light vehicles to properly account for spare capacity.
Fixed docking collar requirement and usage comparison conditions.
Fixes #5486
> Fixed Transportation Capacity and Requirement Calculations

- MekHQ/src/mekhq/Utilities.java
We received some feedback that character starting ages were a little high for Elite pilots. Reviewing the numbers I found they were around 10-20 years higher than intended.
I went through and rejigged the numbers and cleaned up the method, including adding more detailed JavaDocs.
> Refactored Pilot Starting Age Calculation

- MekHQ/src/mekhq/Utilities.java
Fixed some edge cases and better refined Clan starting ages.
> Further Adjustments to Starting Ages

- MekHQ/resources/mekhq/resources/Resupply.properties
Corrected a grammatical error in `statusUpdateEnemyStalemate0.text`, removing an incomplete sentence fragment.
Fixes #5534
> Fixed Typo in Resupply Roleplay Event

- MekHQ/resources/mekhq/resources/Education.properties
- MekHQ/src/mekhq/campaign/personnel/education/Academy.java
- MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
Updated logic to ensure accurate identification of failed academy applications by including education level in checks. Added entrance exam information to academy tooltips for better clarity on requirements.
> Fixed Entrance Exam Logic and Added Tooltip Display

- MekHQ/src/mekhq/MekHQ.java
> Log jvm parameters

- MekHQ/data/universe/academies/Unit Education.xml
Corrected Qualification Start Year for NCO Bootcamp and corrected typo in Officer Training Bootcamp
> Update Unit Education.xml

- MekHQ/userdata/data/universe/ranks.xml
Changed the version from `0.50.02-SNAPSHOT` to `0.50.03-SNAPSHOT` in `ranks.xml`. This prevents IDEA nagging us every time we try to push a change.
> Updated Rank Systems Version in `ranks.xml`

- MekHQ/resources/mekhq/resources/Resupply.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/ResupplyUtilities.java
- MekHQ/src/mekhq/gui/baseComponents/AbstractMHQNagDialog.java
- MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogAbandonedConvoy.java
Abandoned convoys were not being processed correctly following the move to use 'Refused Engagement' instead of 'Defeat' when a scenario is ignored.
I also took the opportunity to update the abandoned convoy dialog to the new format.
> Fixed Abandoned Convoys; Updated Abandoned Convoy Dialog

- MekHQ/resources/mekhq/resources/Loot.properties
Replaced "Seized" with "Secured" in the `Loot.properties` file to improve the wording's clarity and tone.
> Improved Loot Good Event Language

- MekHQ/src/mekhq/gui/StratconPanel.java
Revised right-click menu commands to differentiate and refine behavior for managing scenarios and reinforcements. Added checks for scenario states to ensure appropriate UI displays correctly. Previously we updated the menu behavior, however the fall through did not correctly account for situations where a scenario already existed at the location.
Fix #5608
> Corrected StratCon Menu Actions for Scenario and Force Management

- MekHQ/resources/mekhq/resources/AtBStratCon.properties
- MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Revised UI labels to improve clarity and align with the intended frontline deployment context.
> Updated Frontline Deployment Instructions

- MekHQ/data/scenariomodifiers/LiaisonAir.xml
- MekHQ/data/scenariomodifiers/LiaisonGround.xml
> data: spelling typo fix for liaison

- .github/dependabot.yml
This will look for updates to Github actions and put in PRs as needed.
> build: add dependabot for updating Github actions

- MekHQ/data/scenariomodifiers/airBattleModifiers.xml
- MekHQ/data/scenariomodifiers/groundBattleModifiers.xml
- MekHQ/data/scenariomodifiers/modifiermanifest.xml
- Commented out the `EnemyDropShip` and `GroundedEnemyDropShip` modifiers across air, ground, and manifest files.
- These changes reflect user feedback.
> Removed `EnemyDropShip` and `GroundedEnemyDropShip` Modifiers

- MekHQ/src/mekhq/campaign/autoresolve/AtBSetupForces.java
fix error with AtBSetup not implementing isTeamPresent
> fix: missing team present check

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsUtilities.java
- Replaced various placeholder flavor text and quotes to provide more immersive and lore-accurate content.
- Updated tooltips by correcting contractions and ensuring consistent punctuation throughout.
> Replaced a Number of Placeholder Flavor Text & Fixed Encoding Error

- MekHQ/resources/mekhq/resources/Resupply.properties
Some small copy edits/tweaks to the event messages shown when a convoy is in trouble. I've not touched on them all, but just neatened up some language to make it more natural.
FAO @IllianiCBT  - WHEN YOU'RE BACK FROM YOUR HOLIDAY. NOT URGENT.
> Update to convoy message copy

- MekHQ/src/mekhq/campaign/universe/Systems.java
- MekHQ/src/mekhq/gui/InterstellarMapPanel.java
- Separated HPG radius values for A and B stations into constants.
- Adjusted HPG visualization colors for better distinction across ratings.
> Refactored HPG Network Logic and Improved Visualization Clarity

- MekHQ/resources/mekhq/resources/AssignForceToTransport.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/CampaignTransporterMap.java
- MekHQ/src/mekhq/campaign/unit/Unit.java
- MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- MekHQ/src/mekhq/gui/menus/AssignForceToTransportMenu.java
Fixes #5844 
I also implemented a way to unassign all the units from a transport.
> Issue 5844: Units can only be assigned a transport that is in the TOE

- MekHQ/src/mekhq/gui/campaignOptions/contents/MarketsTab.java
- Temporarily removed CamOps contract market. This was unintentionally added back as an option by CO IIC and is not ready for prime time.
> Temporarily Removed CamOps Contract Market

- MekHQ/build.gradle
- Added `jackson-core` and `jackson-dataformat-yaml` dependencies to enable YAML data handling. These changes are necessary to support potential YAML-based features.
> Added Jackson Dependencies for YAML Processing in MekHQ

- MekHQ/resources/mekhq/resources/CampaignHasProblemOnLoad.properties
- MekHQ/resources/mekhq/resources/VocationalExperienceAwardDialog.properties
- MekHQ/src/mekhq/gui/baseComponents/MHQDialogImmersive.java
- MekHQ/src/mekhq/gui/dialog/CampaignHasProblemOnLoad.java
- MekHQ/src/mekhq/gui/dialog/VocationalExperienceAwardDialog.java
- Replaced direct resource bundle usage with `getFormattedTextAt` utility to streamline localization.
- Simplified and improved dialog construction logic, added support for dynamic and flexible panel scaling, and ensured consistent formatting in message handling.
- Updated the look and feel of the dialog based on community and dev feedback.
> Immersively Updated the Immersive Dialog to Be More Immersive

- MekHQ/src/mekhq/gui/campaignOptions/contents/EquipmentAndSuppliesTab.java
- Corrected label addition and adjusted layout constraints for tech, industry, and output modifiers panels.
> Restored Missing Column Labels for Planetary Acquisition

- MekHQ/resources/mekhq/resources/NewsDialog.properties
- MekHQ/src/mekhq/campaign/universe/NewsItem.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/baseComponents/MHQDialogImmersive.java
- MekHQ/src/mekhq/gui/dialog/NewsDialog.java
- Replaced `NewsReportDialog` with the new `NewsDialog` extending `MHQImmersiveDialog`.
- News Network will change based on year and (in the case of the Clans) faction.
Old...
New...
> Implemented `NewsDialog` for Immersive News Display

- MekHQ/src/mekhq/campaign/mission/BotForce.java
- Simplified the BV label in BotForce descriptions for clarity and consistency.
> Renamed 'Fixed BV' to 'BV' in BotForce Scenario Details

- MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java
Add check for injuries that are not permanent before going on leave.
fixes #5932
> 5932 Injury&fatigue

- .gitignore
- MekHQ/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- gradlew
* Updated Gradle to 8.12.1
* Added ignore for user preferences
> Added user prefs files to ignore for build

- MekHQ/userdata/data/universe/ranks.xml
Changed the version from `0.50.03-SNAPSHOT` to `0.50.04-SNAPSHOT` in `ranks.xml`. This prevents IDEA nagging us every time we try to push a change.
> Updated `rankSystems` version to `0.50.04-SNAPSHOT`

- MekHQ/data/scenariotemplates/Intercept the Escapees.xml
- MekHQ/src/mekhq/campaign/mission/enums/ScenarioType.java
- Introduced a new scenario template XML defining the "Intercept the Escapees" scenario.
This scenario will be used by the upcoming prisoner rework.
> Added "Intercept the Escapees" Scenario Template

- MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
Same as MegaMek/megamek#6494, but for HQ
> Cap splashscreen button width

- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java
Corrected `randomDeathMultiplier` to use Double
> Corrected `randomDeathMultiplier` to use Double

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/finances/CurrencyManager.java
- MekHQ/src/mekhq/campaign/finances/Finances.java
- MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java
> Rolled Back Finance Changes

- MekHQ/resources/mekhq/resources/FameAndInfamy.properties
- Corrected `greetingCGBVersion1*` keys to `greetingCGB*`. No greeting text content was changed.
> Fixed Clan Ghost Bear Greeting Keys

- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
- MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
- MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
- Renamed the `addSupportPoints` method to `changeSupportPoints` as calls to this method are not exclusively Additive.
No functionality has been changed.
> Refactored Support Point Modification Method Name

- MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/Fatigue.java
- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Renamed the `increaseFatigue` method to `changeFatigue` as calls to this method are not exclusively Additive.
No functionality has been changed.
> Refactored Fatigue Modification Method Name

- MekHQ/resources/mekhq/resources/Resupply.properties
> fix: typo in cargo, fixes bolding, addresses issue #5996

- MekHQ/src/mekhq/gui/MekLabTab.java
Reverts MegaMek/mekhq#5920
Should not have been merged.
> Revert "MegaMekLab Issue 1703: Allow bays to be added to aerospace fighters"

- MekHQ/build.gradle
Updated Dependencies
Fixed Gradle Warnings
> Added Planetary Compression of files.

- MekHQ/src/mekhq/campaign/personnel/backgrounds/BackgroundsController.java
fix: uses the correct getInstance instead of accessing directly the static map
> fix: uses the correct getInstance instead of accessing directly the static map

- MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
See MegaMek/megameklab#1741 for more info (merge together)
This PR corrects some equipment flag checks
> Pintle turret and flags (MML #1741)

- MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java
- Removed hardcoded convoy assignment.
- Deployed Convoy to Area of Operations _before_ generating the scenario. This allows the scenario to automatically pull in the convoy without extra handling. There is no risk of the convoy spawning extra scenarios in this manner.
Fix #6079
I'm expecting this will make convoy interceptions _significantly_ easier, so that will need to be monitored and addressed accordingly.
> Fixed Incorrect Seed Force in Resupply Interceptions

- MekHQ/resources/mekhq/resources/Resupply.properties
- Updated all single quotes within HTML attributes to use '' format for proper escaping
Fix #6145
> Fixed Incorrect Quotation Escaping In `Resupply` Properties File

- MekHQ/src/mekhq/campaign/Campaign.java
Recently delivery speeds in MekHQ for non-Planetary Acquisitions were brought in line with CO 51's latest times. This made PA much quicker. This optionally makes PA slower to be vaguely in line with non-PA times. 
The option is under Logistics -> Supplies and Acquisition -> Acquisitions & Deliveries -> Delivery Scale. It defaults to "Months" on the Complete Preset, which brings it roughly in line with CO.  Days is how it works before this change. Weeks is in between.
> Adjusted Planetary Acquisitions to use the campaign option for Delivery Scale to make deliveries optionally slower

- MekHQ/src/mekhq/campaign/autoresolve/AtBSetupForces.java
fix: ACAR - automatically change the color of the bot for another color in case the bot force was generated with the same color as the player.
I don't know why it happens, but that does happens sometimes.
- closes #5829
> fix: ACAR - automatically change the color of the bot for another color if there is a collision

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- Added a suppression comment for the "UnusedProperty" inspection to the CampaignOptionsDialog.properties file.
> Added Suppression Of UnusedProperty Inspection Comment

- MekHQ/data/names/callsigns.csv
- Expanded the `callsigns.csv` file by adding 829 new callsign entries.
- New additions include creative, thematic, and diverse names to enhance the variety and options available.
These callsigns were donated by community member 'Tempest56' and all credit goes to them.
This brings us one step closer to the target of 5,000 callsigns. We'll get there one day! :D
All callsigns were vetted by me and I made sure that **The Forbidden Callsign** was not included.
> Added 829 New Callsigns

- MekHQ/data/scenariotemplates/Assassination.xml
- Fixed wording to match objectives
> Corrected Assassination Scenario Briefing

- MekHQ/data/stratconfacilities/AlliedBaseOfOperations.xml
- MekHQ/data/stratconfacilities/AlliedIndustrialFacility.xml
- MekHQ/data/stratconfacilities/HostileBaseOfOperations.xml
- MekHQ/data/stratconfacilities/HostileSpacePort.xml
- AlliedBaseOfOperations.xml: corrected white space
- AlliedIndustrialFacility.xml: restored missing effect
- HostileBaseOfOperations.xml: clarified the addition of commander unit
- HostileSpacePort.xml: corrected spacing in name
> Corrected Multiple Facility Errors

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Extracted neighboring coordinate scan logic into a new `scanNeighboringCoords` method for improved readability and single-responsibility adherence.
- Updated `processForceDeployment` to delegate scanning tasks to `scanNeighboringCoords`.
- Ensured clear separation of logic for fatigue handling, force assignment, and event triggering during force deployments.
Fix #6266
What this fix does is remove the ability for forces to explore neighboring hexes if they're being deployed to a hostile facility or scenario. Logically this makes sense: the force is too busy fighting to scout.
While this fixes the specific issue outlined in the above case it does not resolve the underlying problem which is more of a fundamental issue not suitable for fixing this close to 50.04's launch.
Basically, when we …
> Removed the Ability for Busy Combat Teams to Scout Neighboring Coords

- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Added `reviewBotForceTemplateCompleteness` to ensure all bot forces are correctly mapped to their templates.
- This method checks for missing template mappings and restores them using force and template names.
- Fix addresses rare cases where templates became inconsistent, ensuring data integrity and proper tracking of post-generation bot forces.
Fix #6313
> Fixed Bot Force Template Mapping Issue in AtB Scenarios

- MekHQ/userdata/data/universe/ranks.xml
- Updated the `rankSystems` version attribute in the `ranks.xml` file from `0.50.04-SNAPSHOT` to `0.50.05-SNAPSHOT`.
This just stops IDEA automatically updating the file every time anyone makes an edit.
> Updated Rank Systems Version

- MekHQ/src/mekhq/AtBGameThread.java
- MekHQ/src/mekhq/campaign/autoresolve/AtBSetupForces.java
- MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- MekHQ/src/mekhq/campaign/mission/AtBScenario.java
- MekHQ/src/mekhq/campaign/mission/atb/scenario/ChaseBuiltInScenario.java
- MekHQ/src/mekhq/gui/MekLabTab.java
This is the MHQ part of allowing both jump jets and Mek mechanical jump boosters. It only has a few small adaptations.
Requires Megamek/megamek#6752 and MegaMek/megameklab#1780
> MML #44: Mek jump boosters and jump jets

- MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Updated `StratconRulesManager` to iterate over `allForces` when retrieving forces by ID, instead of directly accessing by key.
Fix #6356
> Fixed Missing Scenarios

- MekHQ/src/mekhq/campaign/Campaign.java
> Removed Turnover Checks While in Transit

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/data/universe/academies/Unit Education.xml
- Updated multiple XML files to include "Administration" in various curricula.
- Changes impact MekTech, AeroTech, BattleArmor, Vessel, and more in Unit Education and Prestigious Academies.
This is the data portion of #6438
> Added Administration Curriculum to Various Tech Qualifications

- MekHQ/src/mekhq/gui/InfirmaryTab.java
- Moved JScrollPane initialization directly after related JList setup to improve initialization flow.
- Fixed Assign/Unassign issues and other weirdness.
Fix #6380
Just a classic case of me butchering some merge conflicts. Nothing too exciting.
> Fixed Infirmary Assign/Unassign Interactions

- MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/OutstandingScenariosNagLogic.java
- Corrected logic to ensure track scenarios are duplicated in the active scenarios list.
> Fixed Incorrect Duplicate Display of Scenarios in Outstanding Scenario Nag

- MekHQ/data/universe/academies/Local Academies.xml
- MekHQ/data/universe/academies/Prestigious Academies.xml
- MekHQ/data/universe/academies/Unit Education.xml
- Added "Administration" to various academy curricula alongside "Doctor" qualifications.
This is the data side of #6436
> Updated Doctor Academy Curricula To Include `Administration`

- MekHQ/src/mekhq/gui/RepairTab.java
- Added `refreshTechsList` method documentation to explain functionality and edge case handling.
- Improved row selection logic to handle table updates more robustly:
- Ensured re-selection of previously selected rows or technicians where valid.
- Safely cleared selection for invalid indices or empty tables.
- Addressed edge cases to prevent invalid index exceptions during table updates.
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4108/?alert_rule_id=13&alert_type=issue&notification_uuid=00eb7ed1-7d13-4041-a653-2195199763fb&project=10&referrer=discord)
> Updated Technician List Refresh Logic in `RepairTab`

- MekHQ/resources/mekhq/resources/Glossary.properties
- Corrected the file path in the Glossary.properties file for the "Prisoner Capacity" documentation link.
> Updated Glossary Documentation Reference for Prisoner Capacity

- MekHQ/resources/mekhq/resources/BirthAnnouncement.properties
- MekHQ/resources/mekhq/resources/WinterHolidayAnnouncement.properties
- MekHQ/src/mekhq/campaign/personnel/lifeEvents/BirthAnnouncement.java
- MekHQ/src/mekhq/campaign/personnel/lifeEvents/WinterHolidayAnnouncement.java
Just a grab bag of minor fixes to the Celebration events, including a progression blocker.
> Celebration Event Fixes

- MekHQ/src/mekhq/campaign/mission/Scenario.java
- Implemented fallback handling for scenarios missing the "team" attribute in bot force stubs (pre-version 50.05 campaigns).
- Added info logs to alert when fallback team values are applied, preserving pre-change behavior.
- Ensured backward compatibility to avoid issues with older campaign files.
Fix #6507
> Added Fallback Handling for Missing Team Attribute in Scenarios

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/parts/Armor.java
- Corrected logic in `Armor.java` to ensure correct handling of capital-scale unit checks and armor quantity decrementing.
- Updated `fixWarehousePart` to no longer use deprecated methods.
Fix #6510
> Fixed NPE In Armor Repair

- .github/workflows/ci.yml
- MekHQ/build.gradle
- build.gradle
Removed more gradle deprecations.
Adjusted CI scripts to run tests separate.
> Cleaned up gradle scripts.

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/Warehouse.java
- MekHQ/src/mekhq/campaign/parts/Part.java
> Issue 6178: [RFE] Add warehouse stock level when salvaging

- MekHQ/src/mekhq/campaign/unit/Unit.java
- Added a check to ensure only non-GM users are prevented from activating non-CI self-crewed units.
> Fixed Inability to GM Activate Self-Crewed Units (such as DropShips)

- MekHQ/resources/mekhq/resources/GUI.properties
- MekHQ/src/mekhq/gui/enums/PersonnelTabView.java
- MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
- Introduced new attributes (Strength, Body, Reflexes, Dexterity, Intelligence, Willpower, and Charisma) to `PersonnelTableModelColumn`.
- Added corresponding getter methods and utility checks for the new attributes.
- Updated `PersonnelTabView` to include a new "Attributes" tab for better categorization and display.
- Enhanced `GUI.properties` with localized text for the newly added attributes and the new "Attributes" tab.
Nothing exciting here, just a way for users to view their Attributes
> Added Attribute Columns to Personnel Table

- MekHQ/src/mekhq/campaign/Quartermaster.java
Fixes #6245 
Moved logic for adding refit kits from `buyPart` to `addPart` to ensure it works when added via GM commands.
> Issue 6245: Moved logic for adding refit kits from to ensure it works when added via GM Commands

- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/Utilities.java
- Skipped models classified as Clan or mixed-tech if the campaign is non-Clan and the date is prior to Tukayyid.
Fix #3964
> Fix #3964: Added Clan Tech Refit Restrictions Before Battle Of Tukayyid

- MekHQ/src/mekhq/campaign/finances/Accountant.java
- Enhanced `Accountant` class to handle null engine scenarios, including logging a debug message and skipping null-engine units during fuel calculations.
> Fixed NPE When Loading Units Without an Engine

- MekHQ/resources/mekhq/resources/CampaignHasProblemOnLoad.properties
- Separated "The MegaMek Team" into its own paragraph for better readability.
> Fixed Formatting Issue in Campaign Load Prompt

- MekHQ/src/mekhq/campaign/finances/enums/TransactionType.java
- Added a compatibility handler for "RETIREMENT" transaction type to map it to "PAYOUT".
> Fixed Retirement Transaction Type Compatibility for Older Versions

- MekHQ/src/mekhq/campaign/mission/enums/AtBMoraleLevel.java
- Updated the AtBMoraleLevel enum to handle "ROUT" morale level, mapping it to the ROUTED state for compatibility.
> Added Support For the "ROUT" Morale Level Used in Older Versions

- MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
- Adjusted method calls to include compatibility handling rather than prematurely exiting for incompatible versions.
Fix #6646
> Fix #6646: Fixed Skill XP Costs Resetting

- MekHQ/src/mekhq/campaign/Campaign.java
Fixes #6651 
Partial maintenance is no longer a thing. Shorthanded only cares about astech minutes on the day-of.
> Issue 6651: Removed Partial Maintenance and fixed Shorthanded Penalty

- MekHQ/src/mekhq/gui/dialog/MHQOptionsDialog.java
Fixes #6672 
New Day Optimize Medical Assignments and MRMS were switching.
> Issue 6672: Corrected swapped new day Optimize Medical Assignments and MRMS

- MekHQ/src/mekhq/gui/CommandCenterTab.java
- MekHQ/src/mekhq/gui/model/ProcurementTableModel.java
While working on #6674 i found and fixed 2 unreported problems.
- Fixed sorting for the "Total Cost" column  in the procurement table
- Fixed cell update for "Total Cost" column if quantity is incremented / decremented
> Fix 2 unreported problems in procurement table

- MekHQ/src/mekhq/gui/campaignOptions/contents/AbilitiesTab.java
- Updated logic to remove specific reliance on hardcoded keywords by leveraging `SkillType` and `SkillSubType` instead.
- Added special handlers for Gunnery/BA and Gunnery/ProtoMek as these two are frequently used as piloting skills for their respective unit types.
In addition to removing our reliance on String Comparison this PR improves our categorization of SPAs so piloting SPAs cannot be mistakenly placed in the Combat SPA category.
> Fixed SPA Grouping Logic in Campaign Options IIC

- MekHQ/data/campaignPresets/1 - New Player Preset.xml
- MekHQ/data/campaignPresets/2 - Veteran Experience Preset.xml
- MekHQ/data/universe/defaultspa.xml
- Fixed `Functional Tail and Mobile Ears (ATOW:Companion)` and `Functional Tail and Mobile Ears (Unofficial)` being compatible, when they shouldn't be.
- Fixed `Ambidextrous (ATOW)` removing `Animal Antipathy (ATOW)`.
- Updated Presets to match these corrections.
> Fixed Two Invalid and Removable SPAs

- MekHQ/resources/mekhq/resources/Campaign.properties
- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/unit/actions/ActivateUnitAction.java
- MekHQ/src/mekhq/campaign/unit/actions/MothballUnitAction.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Fix #6711 
This PR addresses some issues with activating and mothballing self-crewed units. Specifically conventional infantry and DropShips. These units will now correctly mothball and activate.
> Fix #6711: Fixed Conventional Infantry & Large Vessel (DropShip) Mothballing and Activation

- MekHQ/src/mekhq/campaign/unit/Unit.java
- Resolved incorrect calculation of infantry capacity in `Unit.java`.
Fix #4801
> Fix #4801: Fixed Infantry Capacity Calculation in Transport Report

- MekHQ/src/mekhq/campaign/personnel/lifeEvents/BirthAnnouncement.java
- Corrected an issue in `BirthAnnouncement.java` where the dialog suppression setting incorrectly enabled dialogs instead of disabling them.
> Fixed Birth Announcement Dialog Suppression Behavior

- MekHQ/src/mekhq/campaign/market/contractMarket/AbstractContractMarket.java
- Dynamic difficulty was applying to enemy Quality not Skill Level
> Fix: Fixed Dynamic Difficulty Modifiers

- MekHQ/src/mekhq/campaign/Campaign.java
Added visibility for the target numbers and modifiers going into Planetary Acquisition verbose mode.
> Improvement: Made Planetary Acquisition Verbose Mode Even More Verbose

- MekHQ/src/mekhq/campaign/parts/TankLocation.java
Updated functions in TankLocation.java to correct sale price. Location costs now calculate for internal structure / controls. Still needs updates for chassis costs per support vehicles in Tech Manual p280, maybe?
> Fix for Unit Sale Costs being generally incorrect - Mekhq part

- MekHQ/src/mekhq/campaign/personnel/skills/SkillDeprecationTool.java
- MekHQ/unittests/mekhq/campaign/personnel/skills/SkillTypeTest.java
With the amount of new skills that have been recently added I'm really aware of how fragile our skill addition is. It's a lot of manual entry with a fair amount of stuff that can go wrong.
With a mind to making the process more secure I went ahead and added a handful of tests. These tests will run on every skill type and ensure full skill validity.
> Improvement: Added Additional Testing for Skills

- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Just fixes a copy-paste error from the original PR.
> Fix: Minor Fix to Profession Categorization

- MekHQ/src/mekhq/campaign/personnel/Person.java
- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
How else are you going to cook gourmet hotdogs out of the back of your Field Kitchen?
> Fix: Added Missing Art/Cooking Skill as Potential Skill for the Vehicle Crewmember Role

- MekHQ/data/scenariotemplates/Hostile Facility.xml
> Fix: #6957 Fixed Description of Facility Assault Standard Scenario to Make Clear That the Facility Must Be Destroyed

- MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
Fixes issue #7004. Gives buttons in the Purchase Unit dialog more consistent behavior by disabling the Purchase and Add(GM) button until a unit is selected. (Also lots of reformatting, apparently)
> Fixes for issue #7004 - Purchase Unit Dialog Button Behavior

- MekHQ/src/mekhq/MHQConstants.java
- MekHQ/src/mekhq/campaign/finances/CurrencyManager.java
Updated CurrencyManager to remove inline file path and move reference to MHQConstants.
>  Finishing TODO: Remove inline file path

- MekHQ/src/mekhq/campaign/parts/Avionics.java
Updated Avionics part with costs from Conventional Fighter table. Costs based on Tech Manual p238.
>  Finishing TODO: Conventional Fighter avionics parts cost fix

- .github/workflows/ci.yml
- MekHQ/build.gradle
> Fix Gradle warning due to a deprecation

- MekHQ/src/mekhq/campaign/personnel/skills/SkillDeprecationTool.java
- MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
Fixed removal of Scrounge and removed Climbing, as that was also deprecated.
> Fix: Fixed Compatibility Handler for Removal of Scrounge

- MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
- MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
Their hands are too small and they don't have object permanence yet. How are they supposed to fix 'Meks? They can't hold the tools, or even read the manuals.
> Fix: Stopped Babies Breaking Child Labor Laws by Being Born With Jobs

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Removed all 'added since last Milestone' and 'added since last Development' icons.
> Fix: Updated Campaign Options Iconography for 50.07

- MekHQ/src/mekhq/gui/dialog/EditMapSettingsDialog.java
-  rename MinimapPanel
requires 
https://github.com/MegaMek/megamek/pull/7143
> Refactor: rename MinimapPanel

- MekHQ/src/mekhq/campaign/Campaign.java
Fix: stop checking a misc flag against equipment class
> Fix: stop checking a misc flag against equipment class

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/dependency-scan.yml
- .github/workflows/java-doc.yml
- .github/workflows/nightly-ci.yml
- MekHQ/build.gradle
- gradle.properties
> Fix: Adjustments and fixes for CI for OOM issues

- .github/workflows/ci.yml
- .github/workflows/code-coverage.yml
- .github/workflows/dependency-scan.yml
- .github/workflows/java-doc-pr.yml
- .github/workflows/java-doc.yml
Tweaks and adjustments to the CI pipeline
> Fix: Minor tweaks and updates

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Close #7165
`lblFactionStanding.text` -> `lblFactionStandingTab.text`
> Fix: #7165 Fixed Typo in Faction Standing Options Label

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
Close #7179
Inter-Unit -> Intra-Unit
> Fix: #7179 Fixed Typo in Intra-Unit Marriage Campaign Option

- MekHQ/resources/mekhq/resources/PersonnelRole.properties
- MekHQ/src/mekhq/campaign/CampaignOptions.java
- MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java
Close #7197
A member of the ruling class, often raised in privilege and trained in leadership, diplomacy, and military etiquette.
A low-tier offender engaged in theft, smuggling, or violence - someone shaped more by circumstance than strategy.
> Improvement: #7197 Added Noble & Common Criminal Civilian Professions

- MekHQ/src/mekhq/campaign/personnel/Person.java
Close #7142
This addresses an oversight in role assignment that allowed certain invalid roles to be assigned to personnel. While in that neck of the woods I also cleared away some duplicate logic.
- Tested multiple personnel role assignments, both valid and invalid.
> Fix: #7142 Cleaned Up Profession Assignments to Prevent Invalid Assignments

- MekHQ/src/mekhq/campaign/personnel/PronounData.java
- MekHQ/src/mekhq/campaign/personnel/lifeEvents/BirthAnnouncement.java
- MekHQ/src/mekhq/campaign/personnel/lifeEvents/ComingOfAgeAnnouncement.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/PersonalityController.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Aggression.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Ambition.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Greed.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/PersonalityQuirk.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Reasoning.java
- MekHQ/src/mekhq/campaign/randomEvents/personalities/enums/Social.java
This is a pure refactor, no functionality has changed. I needed access to this class functionality outside of the random personality class.
> Improvement: Changed Location of Pronoun Data Class for Ease of Access

- MekHQ/src/mekhq/gui/dialog/CompanyGenerationDialog.java
Just a minor conditional return statement missing. Easily fixed.
> Fix: Fixed Double Welcome to Faction Message for Mercenary Campaigns

- MekHQ/src/mekhq/campaign/universe/Factions.java
> Improvement: Updated Faction Icons for Mercenary Review Board, Mercenary Bonding Authority, Piracy Success Index Factions, and Scorpion Empire

- MekHQ/src/mekhq/campaign/unit/Unit.java
> Don't double-count beast damage divisor

- MekHQ/resources/mekhq/resources/Skill.properties
- MekHQ/src/mekhq/campaign/personnel/skills/Skill.java
- MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This PR enables the visibility of attribute score modifiers in person view and skill tooltips.
> Improvement: Enabled the Display of ATOW Attribute Score Modifiers

- MekHQ/src/mekhq/campaign/randomEvents/prisoners/CapturePrisoners.java
Fix #7326
Fix #7340
The first issue was caused by a missing check to ensure characters considering Bondsref are Clan personnel. The second was caused by an order of operations issue.
> Fix: #7326 #7340 Fixed Non-Clan Personnel Committing Bondsref; Fixed Bondsref & Seppuku Prisoners Being Resurrected

- MekHQ/data/universe/factionhints.xml
#7387 includes a better explanation of the issue than I could provide.
> Fix: #7387 Fixed St. Ive's Compact Alliance Data

- MekHQ/resources/mekhq/resources/FactionStandingUltimatumDialog.properties
- MekHQ/src/mekhq/campaign/universe/factionStanding/FactionAccoladeEvent.java
- MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandingUltimatum.java
- MekHQ/src/mekhq/campaign/universe/factionStanding/GoingRogue.java
- MekHQ/src/mekhq/gui/dialog/factionStanding/FactionStandingUltimatumDialog.java
In a shortsighted decision made during the earlier development of faction standing I failed to consider that we might want more than one ultimatum for any given faction. This PR hooks in the unique ultimatum name to remove that issue.
Also includes the changes from https://github.com/MegaMek/mekhq/pull/7399
> Improvement: Allowed Multiple Ultimatums Per Faction

- MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
`factionStanding.border` -> `factionStandingTab.border`
> Fix: Fixed Faction Standing Missing Flavor Text

- MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandings.java
The Clans were a little too tetchy about mercenary campaigns. This PR gives them a chill pill.
> Improvement: Reduced How Much Clan Factions Hate Pirates

- MekHQ/resources/mekhq/resources/FactionStandings.properties
- MekHQ/src/mekhq/campaign/mission/AtBContract.java
- MekHQ/src/mekhq/campaign/mission/Contract.java
- MekHQ/src/mekhq/campaign/mission/Mission.java
- MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandings.java
- MekHQ/src/mekhq/gui/BriefingTab.java
- MekHQ/src/mekhq/gui/dialog/ContractMarketDialog.java
- MekHQ/src/mekhq/gui/dialog/factionStanding/FactionStandingReport.java
- MekHQ/src/mekhq/gui/dialog/factionStanding/manualMissionDialogs/ManualMissionDialog.java
- MekHQ/src/mekhq/gui/dialog/factionStanding/manualMissionDialogs/SimulateMissionDialog.java
- MekHQ/unittests/mekhq/campaign/universe/factionStanding/FactionStandingsTest.java
Regard gains and losses are multiplied by the duration of the contract (in months) divided by 6 months (minimum of 1).
So a contract that lasts 12 months will modify Regard double that of a contract that lasts 6 months, or less.
> Improvement: Faction Standing Changes Now Increase Based on Contract Duration

- MekHQ/src/mekhq/gui/dialog/CompanyGenerationDialog.java
As per title. Just a copy-paste error.
This was a visual bug only.
> Fix: Fixed Minor Bug Where Clan Faction Welcome Events Were Being Given by Merchants and Not MekWarriors

- MekHQ/build.gradle
Fixes for bad data
Fixes for Too much data in each project.
> Fixes for Build.

- MekHQ/src/mekhq/campaign/stratCon/StratConRulesManager.java
> Fix #7546: Multi-Level Combat Teams Can Now Deploy Leadership Units

- MekHQ/build.gradle
- MekHQ/unittests/mekhq/campaign/personnel/death/RandomDeathTest.java
This fixes a handful of import issues with the RandomDeathTest class.
> Fix: Fixed Random Death Test

- MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
> Fix #7594: Added Missing Event Call When Removing All Roleplay Skills So That Character Changes Are Logged Correctly

- MekHQ/src/mekhq/campaign/Campaign.java
- MekHQ/src/mekhq/campaign/campaignOptions/CampaignOptions.java
- MekHQ/src/mekhq/campaign/campaignOptions/CampaignOptionsMarshaller.java
- MekHQ/src/mekhq/campaign/campaignOptions/CampaignOptionsUnmarshaller.java
- MekHQ/src/mekhq/campaign/universe/RATManager.java
- MekHQ/src/mekhq/gui/CampaignGUI.java
- MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
Fix #7462
This PR removes some remaining Static RAT code that should have been fully retired during the development of CO IIC, but was missed.
I've tested the change by generating multiple Quickstart companies and scenarios. All looks good.
> Fix #7462: Removed Residual Static RAT Code

- MekHQ/src/mekhq/gui/stratCon/StratConScenarioWizard.java
Fix #7627
This PR undoes some changes made during The Great Data Refactor that broke Leadership Units.
> Fix #7627: Stopped Players from Deploying More Leadership Unit BV Than Budget Allows in StratCon
