MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/universe/Atmosphere.java, MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Integrated various planetary conditions (such as gravity, atmosphere, pressure, and temperature) into the campaign's targeting calculations. Improved the Atmosphere class by adding methods to check specific atmospheres and refactoring the parseAtmosphere method using a switch expression.
=> Added CamOps Planetary Condition Modifiers to Maintenance Checks

MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
When personnel give birth while at an academy, their child is added to a list of 'tag alongs' so that mhq knows who is being simulated as 'away from the unit' and doesn't just teleport the baby back to the unit. I included a check to ensure this wasn't done if the mother wasn't attending an academy, however this was done using `isBlank`. I wasn't aware blank xml tags are not included in personnel save data, as they are in other parts of our codebase (campaign options, for example). This caused the check to hit a NPE. Switching to check for `null` instead does the same thing, but prevents the NPE.
=> Fixed Null Check for Education Tag Alongs

MekHQ/src/mekhq/gui/PersonnelTab.java, MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java, MekHQ/src/mekhq/gui/view/PersonViewPanel.java
This PR improves the Person View pane on the Personnel Tab by switching the number of biographic columns from 2 to 1. It also adjusts the Person View width both on the Personnel Tab and Personnel Market. This allows the associated tables to take up the bulk of the screen real estate, while also ensuring all the important information on the Person View is fully visible.
This PR should be particularly useful for users with unusually wide or narrow screens.
=> Updated Person View and Personnel Tab to Better Support Differing Screen Sizes

MekHQ/resources/mekhq/resources/PlanetViewPanel.properties, MekHQ/src/mekhq/campaign/universe/PlanetarySystem.java, MekHQ/src/mekhq/gui/InterstellarMapPanel.java, MekHQ/src/mekhq/gui/view/PlanetViewPanel.java
This PR is another Hammer request: the academies present in a system are now visible in the system information, including their description.
Furthermore, I went ahead and implemented an 'academies' filter, so users can visually spy which systems have non-local, non-homeschool academies.
These changes are also designed to handle custom academy sets, so if users have one or more custom academy sets, those academies will appear in the filter and system description.
As always, I did some light refactoring in the files I edited. Nothing too exciting, just clean up where appropriate.
=> Integrated Academy Information into Interstellar Map Tab

MekHQ/resources/mekhq/resources/CamOpsReputation.properties
Changed mission text placeholders from integer to string format. This ensures the text is displayed correctly for various mission details.
=> Fixed Text Placeholders in CamOpsReputation.properties

MekHQ/mmconf/campaignPresets/Campaign Operations (StratCon).xml, MekHQ/mmconf/campaignPresets/Campaign Operations.xml, MekHQ/mmconf/campaignPresets/Complete Experience.xml, MekHQ/mmconf/campaignPresets/New Pilot Program.xml, MekHQ/resources/META-INF/services/mekhq.module.api.PersonnelMarketMethod, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/market/PersonnelMarket.java, MekHQ/src/mekhq/campaign/market/PersonnelMarketCampaignOps.java
This PR simply renames the Strat Ops personnel market method to "Campaign Ops" which reflects the fact that these rules moved to a different book. I added a check to the XML loader to automatically use Campaign Ops when saves contained the old Strat Ops string so backward compatibility works. 
As a sidenote, I doublechecked the personnel generation code and it matches what is in camops, although it doesn't seem to use the same skill generation method...or at least I couldn't find it. I will keep looking for that and push a separate PR once that's done.
=> Rename strat ops personnel market to campaign ops to reflect rulebook reorganization

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
Updated `Person` class to include method for retrieving permanent injuries.
Modified `Campaign` to retire personnel with permanent injuries instead of sacking them, bypassing contract breaches. Adjusted `RetirementDefectionTracker` to provide the appropriate payout for medically discharged personnel. Medical Discharge occurs if the character resigns while possessing a permanent injury.
Fixed a bug in the payout logic that would cause personnel to always receive a 0 c-bill payout if they were sacked. Now the payout value correctly factors in whether the character is eligible for retirement or medical discharge.
=> Added Support for Handling Medical Discharge

MekHQ/src/mekhq/campaign/personnel/Person.java
Ensured that loyalty change reports are only generated when loyalty modifiers are in use.
=> Removed Loyalty Change Notifications for Campaigns with Loyalty Disabled

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/autoAwards/TimeAwards.java
Updated the `getYearsInService` method in the `Person` class to return a long instead of integer. This ensures accurate representation of service years even for extended durations and refactored related code in `TimeAwards` to take advantage of this method, as it didn't exist when TimeAwards were originally written.
=> Refactored Years of Service Calculation for autoAwards Time Awards

MekHQ/src/mekhq/campaign/CampaignOptions.java
Restored parsing for the `adminXPPeriod` option in the CampaignOptions class. This ensures that the setting is now correctly read and applied from configuration files.
=> Restored adminXPPeriod Option Parsing

MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
The EducationController was incorrectly trying to display hyperlinked titles in the finance table.
=> Fix hyperlink issue in payment text

MekHQ/src/mekhq/campaign/unit/Unit.java
Reorganized the getCommander method to merge all crew members into a single list and determine the commander by comparing ranks in a single iteration. Simplified logic by removing repeated comparisons and ensuring a single pass over all crew members.
This resolves a bug where we were prioritizing `crewmembers` over all other types of crew type. This was caused by the logic chain first checking for the highest ranked `crewmember`, then the highest ranked `gunner`, and so on. This logic chain broke if all personnel have the same rank because at that point nobody outranks the first person parsed, which (if there were `crewmembers` would always be a `crewmember`). My refactoring focused on resolving that bug and removing a lot of the repetition that existed in the original logic chain by …
=> Refactored Unit getCommander() Method

MekHQ/docs/history.txt, MekHQ/src/mekhq/gui/CommandCenterTab.java
This PR changes the Story Arcs objectives panel from a `List()` to a `JList()`, this gives us a lot more formatting options, and means the panel will inherit client theme colors, rather than being a bit of an eyesore on non-light themes.
While this pane was written with Story Arcs in mind, I took the opportunity to get some non-story arc usage out of it. Now it will show an abbreviated version of the campaign finance report and what scenarios have been completed (or are still to be completed).
I've included an example of this below, actual font colors will depend on local MekHQ settings.
=> Adjusted Objectives Pane to Use Client Theme Colors and Added Normal Play Usage

MekHQ/src/mekhq/gui/BriefingTab.java
Changed the `prisonerPrompt` method to use `defectors` instead of `prisoners` within the defectors check. This ensures the correct list is passed to the prompt, preventing text errors when the prompt is displayed.
=> Fixed Copy-Paste Error in End Mission Prisoner Nag

MekHQ/src/mekhq/campaign/personnel/autoAwards/AutoAwardsController.java
Replaced duplicate campaign parameter assignments with `this.campaign` to clearly indicate class member usage. Fixed support for scenario awards as a new case in award processing.
=> Refactored `AutoAwardsController` and Fixed Scenario Awards Support

MekHQ/src/mekhq/campaign/personnel/Person.java
Added methods to enhance Edge trigger processing, improving the handling of disabled Edge triggers.
Replaced LogManager with MMLogger for consistent logging.
=> Improved Edge Trigger Unmarshalling

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Improved the logic for updating force commanders by refactoring the method to streamline the selection process. Used a list of eligible commanders based on units and sub-forces, and enhanced the selection by incorporating a tiebreaker mechanism.
Further, we now track force commander beyond the lance level, ensuring a proper chain of command is displayed throughout the TO&E. To that end force commander is now visible for nodes beyond lance and origin.
I also discovered we were re-calculating force commanders when viewing sub-forces in the side-bar. This meant that changes to force commander were not reflected when viewing sub-forces. Now sub-forces correctly display the current force commander.
Finally, I adjusted font sizes in a couple of places to improve readability.
=> Refactored Force Commander Logic & TOE Information Display

MekHQ/src/mekhq/gui/CommandCenterTab.java
Modified scenario sorting to account for null dates using `nullsFirst` comparator. Ensured scenarios with null dates are excluded from the date difference calculation, preventing potential errors.
=> Added Checks for Scenarios with Null Start Dates within Objectives Panel

MekHQ/data/universe/factions.xml
In-line comments have been added clarifying the source of each set of era modifiers, and each faction's modifiers have been painstakingly reviewed to ensure the fourth printing of Campaign Operations is followed.
Faction data up to the ilClan era has also been added, including successors and corrections end years.
=> Clean up factions file

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Rounded XP costs to nearest integer to improve accuracy and consistency. Corrected handling of zero intelligence scores to avoid division anomalies.
=> Fixed Intelligence XP Cost Calculations and Minor Logic Issues

MekHQ/src/mekhq/campaign/parts/PartInUse.java, MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
Commit a4cc0f9 introduced a bug where several types of parts could no longer be sold. This PR simply reverts it and goes back to looking up the target part by name rather than ID.
I agree with the original comment that it's not ideal to search by strings, but it appears there isn't really a better way to do it with how this dialog is constructed. I think there are some opportunities for refactoring it but I think those should be done in the future rather than now. Let me know what you think.
Closes #4663
=> Revert change to find parts by name when selling from parts in use

MekHQ/src/mekhq/campaign/mission/AtBContract.java
Fix #4664 
The contract's enemy name was always being populated with some default value, which is fine, but it didn't get updated with the actual enemy name when the enemy code was being updated.
=> clear out enemy name if we're changing enemy code

MekHQ/src/mekhq/campaign/force/Force.java
Fix #4666 
Prime example of why I don't really like the stream functionality
=> check for units without operators

MekHQ/resources/mekhq/resources/Mission.properties
closes #4660
There was a typo in the independent command rights tooltip text in the contract market which broke the formatting. This PR adds it and I've confirmed the formatting works as expected.
=> Add missing angle bracket in Independent Command Rights tooltip text

MekHQ/src/mekhq/campaign/rating/CamOpsReputation/OtherModifiers.java
Previously, mission date calculation could throw a NullPointerException if there were no missions. Added a null check to ensure `oldestMissionDate` defaults to the current date if no missions exist. This prevents the exception.
=> Fixed NPE in CamOps Mission Date Calculation

MekHQ/src/mekhq/campaign/market/PersonnelMarketCampaignOps.java
A tester in Discord pointed out that the CamOps personnel market was occasionally generating personnel without a role. I observed that this was happening on rolls of 7, which CamOps page 203 says should be "no personnel available". Instead, the market was generating personnel without any roles which is kind of weird. Note this issue predates the renaming to CamOps--it existed in the StratOps personnel market as well.
=> Update CamOps Personnel Market to Properly Not Generate Personnel on a roll of 7

MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
Replaced the incorrect usage of academy.getName() with `academyNameInSet` to ensure proper reporting of education application status.
=> Fixed Incorrect Variable in Education Failed Application Report.

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/parts/Part.java, MekHQ/src/mekhq/campaign/parts/PodSpace.java, MekHQ/src/mekhq/campaign/work/IPartWork.java
Fix NPE when mass-repairing damaged pod space (only seen when "pay for repairs" is enabled).
Moves some methods up out of Part into IPartWork, which is fine because all Part child classes implement that interface and these methods already.
This allows us to remove the bad cast of IPartWork to Part, which was failing for PodSpace specifically.
Note that there is no canon price for PodSpace, as it is an abstraction we created to manage working on the parts of a unit that will take Pod-mounted hardware once repaired / replaced.
The price of Pod equipment is already built into the Pods, so Pod Space can be free without affecting anything.
Testing:
- Ran OP's campaign and confirmed NPE did not occur, and that Pod Space could be repaired.
Close #4608
=> Fix #4608: Relocate some methods and remove bad Part casting

MekHQ/src/mekhq/campaign/market/PersonnelMarketCampaignOps.java
Per CamOps rules, forces can attempt to recruit new personnel every maintenance/repair cycle, which is defined as 1 day. This PR makes the CamOps personnel market refresh daily. The serialization methods have been removed as it's no longer necessary to store the `daysSinceRolled` value in the XML, and previous and current saves load just fine.
Future refactoring could remove the `removePersonnelForDay()` override since it doesn't actually do anything except return the list that was passed in, but I don't think it's a good idea to mess with the interface at the moment.
@IllianiCBT  Feel free to hold off until 0.50 if you'd rather not introduce this now. Thanks!
=> Refresh camops personnel market daily

MekHQ/data/universe/factions.xml, MekHQ/src/mekhq/gui/InterstellarMapPanel.java
Changed the RGB color values for a number of factions, including Independent, to match official colors. I also updated Capital and Hiring Hall ring colors to make it easier to distinguish one from the other.
=> Updated Map Colors

MekHQ/src/mekhq/gui/model/TechTableModel.java
Resolves RFE #4695
Show current edge as long as edge for support personnel is enabled in the options and the specific tech has the repair failure edge trigger enabled.
=> Add current edge total to the tech information

MekHQ/src/mekhq/campaign/universe/Faction.java
The warning doesn't serve any useful purpose, as factions with fewer era modifiers (usually because they cease to exist) simply default to using 0 for later eras.
=> Remove unnecessary faction era modifier warning

MekHQ/mmconf/campaignPresets/Campaign Operations (StratCon).xml, MekHQ/mmconf/campaignPresets/Campaign Operations.xml, MekHQ/mmconf/campaignPresets/Complete Experience.xml, MekHQ/mmconf/campaignPresets/New Pilot Program.xml, MekHQ/mmconf/campaignPresets/Tabula Rasa.xml
Updated presets to account for recently added campaign options and changes.
Added requirements for Natural Aptitude traits to reduce the likelihood of personnel spawning with those Traits.
Adjusted experience point costs for SPAs for the CamOps based presets, as SPAs have no XP cost under CamOps.
=> Updated Campaign Presets

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java
Changed the skill retrieval method from `getLevel()` to `getTotalSkillLevel()` to ensure skill level plus bonus is retrieved for commanders.
This bug affected things like the speed of deployment when the scenario calls for staggered deployment, the number of scenario re-rolls, the number of hidden units during an ambush scenario, reinforcement speed, and the number of leadership units.
=> Fixed Skill Level Retrieval Method in AtBDynamicScenario

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/unit/Unit.java
Updated the `incrementDaysSinceMaintenance` method to account for time scaling based on active missions, and changed maintenance time tracking from `integer` to `double`. This ensures maintenance frequency matches CamOps.
=> Fixed Maintenance Interval Calculations

MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
Added a minimum size of 1100x500 to CustomizePersonDialog to ensure consistent layout and prevent UI elements from being truncated.
This is the mhq half of #5939
=> Set Minimum Size for CustomizePersonDialog UI element

MekHQ/src/mekhq/campaign/force/Force.java
Simplified recursive depth calculation in `getMaximumDepth` and improved the method `populateFormationLevelsFromOrigin` by combining related logic. Also adjusted the `populateOriginNode` function to return an integer.
Also removed a couple of 'tabs' that somehow snuck in at some point over the past couple of years.
=> Fixed Recursive Node Reader in Force.java

MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/src/mekhq/campaign/parts/TransportBayPart.java, MekHQ/src/mekhq/campaign/personnel/enums/Profession.java, MekHQ/unittests/mekhq/campaign/parts/PartTest.java
Adds an additional anti-null check when getting the Bay name for a Part for a Unit that may not have its Entity set yet.
This info should be corrected later in the campaign loading process anyhow.
NOTE: the save file in #4728 did display missing/destroyed DS bay doors and cubicles on my system following this fix, but I was not able to repro that with a brand new save replicating the TOE layout.  This save may be useful for replicating this bug in the future.
Testing:
- Loaded OP's campaign save
- Added a unit test for the specific failure
Close #4728
=> Fix 4728: Safety getBay, add unit test, turn down logging in one location

MekHQ/src/mekhq/campaign/force/Force.java
Replaced stream processing with a loop to check for null commander units, preventing potential `NullPointerExceptions` during data loading (if, for example, we attempt to build the TO&E before the Unit has fully initialized).
=> Fixed NPE in `getEligibleCommanders`

MekHQ/src/mekhq/campaign/unit/Unit.java
Previously, `daysSinceMaintenance` was incorrectly interpreted as an integer, which lead to all kinds of craziness. Now, it is correctly unmarshalled as a Double.
=> Fixed Unmarshalling of `daysSinceMaintenance`

MekHQ/src/mekhq/campaign/unit/Unit.java
Prevent Rapid unplanned disassembly. Added some `Double.parseDouble` .
Ran the MHQ units tests.
Saved and loaded.
=> Prevent Rapid unplanned disassembly

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Added a utility function to clamp salary values, ensuring they fall within a specified range.
Also increased the maximum salary from 100,000 to 1,000,000,000. This should be more than sufficient for our users.
=> Refactored Salary Editing Logic

MekHQ/src/mekhq/Utilities.java, MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Fixed bug in experience level generation that caused rolls of 2 to result in Ultra-Green personnel.
Replaced direct value checks with a clamped switch case for experience level generation.
Streamlined the campaign options pane by removing unused skill levels and updating labels for clarity.
=> Corrected Experience Generation Logic and Refined Campaign Options GUI

MekHQ/src/mekhq/MekHQ.java, MekHQ/src/mekhq/gui/dialog/EditMapSettingsDialog.java
GameManager in Megamek was refactored into `megamek.server.totalwarfare.TWGameManager` recently, which caused MekHQ to fail to compile. There were only two instances I found that needed to be updated, and all MekHQ unit tests were still passing.
=> Update GameManager package/class to new name

MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
This adds a small amount of information about new personnel in the market refresh report when the CamOps market is being used. I decided to only do this for CamOps as it generates a single unit per day and thus won't flood the report with messages for "higher yield" methods.
This change was in response to player feedback in Discord that it was tedious to check the personnel market every day to see what was available. The intention here is to show the player at a glance the important information (exp level and role, mainly) so they can skip checking the market if they aren't interested.
Here's what the report looks like:
=> Include more information about available personnel in Camops Personnel Market Refresh Report

MekHQ/src/mekhq/campaign/CampaignOptions.java
This fixes a typo related to Mission XP Rewards.
Closes #4790
=> Fix Mission XP Reward Setting

MekHQ/src/mekhq/gui/dialog/nagDialogs/UntreatedPersonnelNagDialog.java, MekHQ/unittests/mekhq/gui/dialog/nagDialogs/UntreatedPersonnelNagDialogTest.java
This fixes the "untreated personnel" nag by having it exclude defectors. Illiani suggested making sure that bondsmen are also excluded, so I added unit tests to cover that as well as other cases. Note I had to make `isUntreatedInjury()` "package-private" instead of fully private in order to test it, but I don't think that should have any impact since only classes in the exact same package can access it. 
Closes #4789
=> Remove untreated personnel nag for prisoner-defectors and add unit tests

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
This adds better guards when generating infantry for transports, to ensure 'large' transporters like the Maxim (I) are limited to a number that is suitable to their capacity.
Fixes #4535.
=> Improved limits on generating infantry for APCs

MekHQ/data/universe/academies/Local Academies.xml, MekHQ/data/universe/academies/Prestigious Academies.xml, MekHQ/data/universe/academies/Unit Education.xml
Standardized spelling of "MechWarrior" and "BattleArmor" across multiple academy entries. This reverted work done by the name consistency project as these names are covered by the 'fluff exception'
=> Corrected terminology in Academy XMLs

MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java, MekHQ/unittests/mekhq/gui/dialog/nagDialogs/UntreatedPersonnelNagDialogTest.java
Corrected the role name from MECHWARRIOR to MEKWARRIOR in unit tests. Fixed the method name from getUnitRatingMod to getAtBUnitRatingMod in campaign tracker.
=> Fix typos in identifiers for MEKWARRIOR and AtBUnitRatingMod

MekHQ/src/mekhq/campaign/personnel/education/Academy.java
Compatibility handlers were added for a number of skills to account for the name change project.
Redundant setter methods were removed to streamline the code in Academy.java.
=> Added Post-Name Change Compatibility Handlers to Academy.java., Removed Redundant Setter Methods

MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
PersonnelMarket.java was not filtering out inactive factions when determining whether a planetary system was a faction capital. This led to situations where personnel would be generated on a planet like Styk before Styk actually became a faction capital in 3058. This PR adds a filter when populating the local variable `factions` and also changes the `c` argument to for this method to `campaign`.
Closes #4871
=> Filter out inactive factions when determining capitals for personnel market generation

MekHQ/src/mekhq/campaign/personnel/death/AbstractDeath.java, MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Replaced stream-based award filtering and sorting with explicit loops for clearer logic. Adjusted image scaling to maintain aspect ratios using `getScaledInstance` instead of `ImageHelpers`. This change enhances code readability and ensures consistent image scaling.
=> Refactored Award Drawing Methods

MekHQ/src/mekhq/campaign/personnel/autoAwards/MiscAwards.java, MekHQ/src/mekhq/campaign/personnel/death/AbstractDeath.java
Moved the 'prisoner of war' type of Misc Award to be issued only at the end of a Mission.
=> Added Mission Check for 'prisonerofwar' Award Eligibility

MekHQ/src/mekhq/campaign/personnel/death/AbstractDeath.java, MekHQ/src/mekhq/gui/StratconTab.java
Extended the message to clarify when no active contract is selected or the contract has not yet started. This provides better feedback to users regarding the state of their campaign.
###Closes #4701
=> Updated StratCon Status Message for Inactive Contracts

MekHQ/src/mekhq/MekHQ.java, MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/BriefingTab.java
Added a new field `hitsPrior` in the `Person` class to capture hits sustained before the last completed scenario. Modified relevant methods and XML serialization/deserialization to handle this new field, ensuring accurate injury tracking. This resolves an issue present in autoAwards where new hits would not be properly tracked whenever Advanced Medical is disabled.
=> Added the Tracking of Hits Obtained Prior to the Completion of a Scenario

MekHQ/src/mekhq/campaign/Campaign.java
Fixed `ConcurrentModificationException` in Personnel Removal Process by streamlining the logic.
I am once again reminded that streams are not my friend.
=> Fixed `ConcurrentModificationException` in Personnel Removal Process

MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
Fixed an issue where NPC personnel had placeholder names at point of creation leading to a disconnect between the name used in descriptions.
The placeholder name is a necessary byproduct of how we generate OpFors, however now we regenerate their description at the point in which is becomes visible to the user, preventing the prior issue.
=> Regenerate Personality Descriptions for NPCs

MekHQ/data/universe/defaultspa.xml, MekHQ/src/mekhq/campaign/parts/Part.java, MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java
Removed all instances of the 'Clan Tech Knowledge' SPA from `PersonnelOptions`, `Part`, and `defaultspa.xml`.
Recently, errata removed the +2 modifier to TNs when IS teams work on Clan-based equipment. This rendered the above SPA no longer relevant.
=> Removed TN Modifier for IS Techs working on Clan Tech, Removed Clan Tech Knowledge SPA and Effects

MekHQ/mmconf/campaignPresets/Complete Experience.xml, MekHQ/mmconf/campaignPresets/New Pilot Program.xml, MekHQ/mmconf/campaignPresets/Tabula Rasa.xml
Modified the 'idleXP' value from 10 to 5 in 'New Pilot Program.xml' and 'Complete Experience.xml`. This is based on QA discussion.
Updated various experience-related attributes in 'Tabula Rasa.xml' that should have been matching the Complete Experience.
=> Reduced Idle XP in Campaign Presets

MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java
The CamOps contract market had a NPE when contracts were GM-added and the modifiers had not previously been populated on a monthly refresh. This PR populates the modifiers if a contract is added and they haven't been initialized.
Closes #4897
=> Generate contract modifiers when adding contracts individually

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Added checks to handle potential null `Person` objects in the `ForceViewPanel` and `Force` classes. This prevents the application from attempting to access methods on a null object and ensures default text is shown when no commander is found.
=> Fixed Two Instances of NPE Related to the TO&E

MekHQ/src/mekhq/campaign/personnel/Person.java
Removed experience level checks from tech personnel checks to streamline the determination of technician roles. This removes the really weird situation where ultra-green techs can't be assigned to units (or, in some cases, repair tasks). Whether they _should_ be assigned is something best left to the player. This was particularly odd, as this is the only role that had the 'must be Green or better' restriction.
=> Simplified Tech Personnel Checks

MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java
Added try-catch blocks to handle differences in data structure names for 'mek', 'protoMek', and technician types to ensure backward compatibility with version <50.01.
=> Added Several <50.01 Compatibility Handlers to CamOps Reputation Report

MekHQ/src/mekhq/campaign/personnel/AwardsFactory.java, MekHQ/src/mekhq/campaign/personnel/Person.java
Restored functionality to process awards from XML in personnel logs. Removed ancient, <0.47.15, compatibility handler from `generateNewFromXML` method.
=> Restored Award Unmarshalling Method Call

MekHQ/src/mekhq/campaign/parts/Cubicle.java, MekHQ/src/mekhq/campaign/parts/MissingCubicle.java
Added a compatibility handler to convert legacy bay type names "MECH" and "PROTOMECH" to their current equivalents "MEK" and "PROTOMEK".
=> Added <50.01 Compatibility BayType Handlers

MekHQ/src/mekhq/campaign/parts/Part.java
Corrected the className string comparison and assignment for `VeeStabiliser` to `VeeStabilizer`.
=> Added <50.01 Compatibility Handler for `VeeStabiliser` Parts

MekHQ/src/mekhq/campaign/mission/AtBContract.java
Accounted for backslash escape sequences in camouflage file paths to ensure compatibility across different operating systems. Added an alternate root directory constant and updated the path sanitization to replace the alternate format correctly.
=> Fixed Random-Camouflage Path Handling for Alternate Directory Format

MekHQ/src/mekhq/campaign/Campaign.java
Added a check to exclude the "clan_tech_knowledge" key from being written to the XML file. This ensures compatibility with versions before 50.01.
=> Added <50.01 Compatibility Handler for Removed Clan Tech Knowledge SPA

MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Moved DropShip Bonus calculation outside of the conditional block for ejected units. This change ensures that the DropShip bonus is consistently applied. Adjusted the existing logic to avoid redundant checks and improve code readability.
Refactored `processGame` to remove single or abbreviated variable names.
=> Refactored DropShip Salvage Handling

MekHQ/resources/mekhq/resources/AtBContract.properties, MekHQ/resources/mekhq/resources/AtBDynamicScenarioFactory.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/universe/fameAndInfamy/BatchallFactions.java
Centralized Batchall faction list and ensured consistent checking throughout the codebase. Improved the reporting mechanism by differentiating between strict, opportunistic, and liberal honor levels, and added more informative logging to the bidding process. Added a fun Easter Egg for non-Clan factions encountering the Clans for the first time prior to the Outreach Summit of January 3051.
=> Refactored Batchall Logic and Enhanced Bidding Report

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java
There was an error when calculating the payment multiplier using the CamOps unit rating method for AtBMonthly contracts, which was caused by incorrectly using the reputation score instead of the reputation modifier for determining this multiplier. This PR does a couple of things:
1. Fixes `getReputationFactor()` to use the camopsUnitRatingMod instead of the reputation score
2. Reverts the change in `AtBMonthlyContractMarket` and uses the `AtBUnitRatingMod` instead
3. Adds a `getCamOpsUnitRatingMod()` method to get the camops unit rating mod and support `getReputationFactor()`
4. Adds docstrings for everything
Closes #4952
=> Fix AtBMonthlyContractMarket payment multiplier

MekHQ/src/mekhq/campaign/universe/PlanetarySystem.java
This PR updates the dynamic hiring hall formula to remove hiring halls for systems owned by the clans. This was due to a discussion in Discord where the consensus was that having hiring halls was inconsistent with clan lore.
=> Remove hiring halls from clan worlds

MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Updated the tooltips in PersonViewPanel to use HTML for option descriptions. This ensures line breaks in descriptions are properly displayed as `<br>` tags, improving readability.
=> Edited Display of Advantage Tooltips in Person View

MekHQ/src/mekhq/gui/enums/PersonnelFilter.java
When doing the big merge the other day, we accidentally used `isVesselCrew`/`isVehicleCrew` instead of `isVesselCrewMember`/`isVehicleCrewMember`
###Closes #4900
=> Fixed Personnel Filter Role Checks to For Vehicle and Vessel Crews

MekHQ/src/mekhq/gui/HangarTab.java
Introduced `FormattedNumberSorter` for the maintenance column.
=> Add Sorter for Maintenance Column in Hangar Tab

MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java, MekHQ/unittests/mekhq/campaign/rating/CamOpsReputation/ReputationControllerTest.java
This PR adds tests for the Reputation Controller class, which is responsible for performing various calculations and creating a final reputation score and reputation modifier.
=> Add ReputationController tests

MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
This fixes the grammar in the CamOps personnel market notification to use "An" for the exp levels starting with a vowel and "A" for the others.
=> Fix a/an grammar in camops personnel market notification

MekHQ/src/mekhq/campaign/Campaign.java
Consolidated code into private methods for better readability and maintainability. Updated `processNewDayPersonnel` to handle all personnel, avoiding potential `ConcurrentModificationExceptions`.
This doesn't just close the below case, but also fixes a number of issues stemming from the fact that we were only checking personnel events for characters with the 'active' personnel status. Characters who have departed the campaign (such as characters who have died, or resigned) are skipped.
=> Refactored Daily Personnel Processing Logic.

MekHQ/src/mekhq/campaign/CurrentLocation.java
A new style of Current Location info line that reads better and gives a little better info.
Pros of new format:
- Shows remaining jumps
- Shows travel time to jump point instead of travel time from planet when outbound
- Supports planets with different names than their system.
- Clarifies that the jumpship is what's being charged
Cons:
- No longer shows jumpship charge unless you're waiting at jumppoint
Wish I could:
- Show total days remaining in trip
Stylistic:
- Doesn't use any italics anymore
=> Better Current Location / Travel Status

MekHQ/resources/mekhq/resources/RetirementDefectionTracker.properties, MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
This PR implements RFE #4946. 
After discussion and code help from @IllianiCBT I've implemented a -1 modifier to the TN, if a person has been promoted in the last 6 months.
In future this should have a campaign option, but that's not done until CO IIC is done.
Tested and observed working in an MHQ test campaign.
=> Implements #4946 - Adds Recent Promotion Modifier to Turnover System

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
This is a very simple hacky fix to StratconRulesManager.java's scenario generation.
Please be aware I don't know how to write or add unit tests, so haven't done any of that here.
I've added a line that, when trying to generate a new scenario on a Monday, as well as Nick's original checks of whether a unit is already deployed and is assigned to a track, also checks if the force is flagged as combat.
I've seen it step over a force that was flagged as non-combat in a very simple test campaign using the debugger so I think this works, but this needs careful testing to make sure.
I've attached a save file to this PR that people can use to test by generating some contracts and then seeing if you ever get 'lance-truck' picked as the seed lance.
It has one combat force and one non-combat force - …
=> Hacky Fix: Makes StratCon Scenario Generation Respect Non-Combat Flag in TO&E

MekHQ/src/mekhq/gui/dialog/PersonnelMarketDialog.java, MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
This fixes the real issue behind #4986: that paid recruitment is even available when camops markets are selected.
It adds camops markets as a reason not to show the paid recruitment controls. It also makes sure paid recruitment is turned if the controls are turned off, though this won't come into effect until the window is opened. 
Added bonus QoL: Since camops markets only have one person at a time, select the first person in the list automatically when opened. One less click and it doesn't really hurt other market types either.
=> Camops Paid Recrutiment Removal

MekHQ/src/mekhq/gui/CampaignGUI.java
=> Better visual distinction for GM mode / overtime toggles

MekHQ/data/universe/factions.xml, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/market/contractMarket/AbstractContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/ContractTerms.java, MekHQ/src/mekhq/campaign/market/contractMarket/DisabledContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/MissionSelector.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java, MekHQ/src/mekhq/campaign/universe/Faction.java, MekHQ/src/mekhq/campaign/universe/enums/HiringHallLevel.java, MekHQ/src/mekhq/gui/BriefingTab.java
Opening this as a draft while I work on the next batch of functionality for the CamOps Contract Market. Any feedback welcome.
=> CamOps Contract Market - Contract Generation

MekHQ/src/mekhq/gui/TOETab.java
Another tiny one but it will save me many many clicks. It makes the force view tab sticky, so if you're viewing a unit and select a different TO&E entry, it stays on unit. Or goes back there when its relevant.
There's probably a better way to do this like rearchitecturing the pane to not be recreated all the time and to just have two subpanels that get populated as needed, but this is the least invasive change I could come up with.
=> Pin/sticky force view tab on TO&E panel

MekHQ/src/mekhq/Utilities.java, MekHQ/src/mekhq/gui/dialog/ChooseRefitDialog.java
Removed old kludges obsoleted by getFullChassis()
Refactoring of retrieveOriginalUnit() to enable
refactoring of populateRefits() that properly throws exceptions.
This fixes the bug that ever since `(Standard)` was purged from model names, those models with now blank names stopped showing up as targets for refits in the GUI.
And if something similar happens again we will get an EntityLoadingException now.
Screenshots from 49.7 (last milestone before the bug) vs 50.0 vs this commit for illustration purposes.
=> Cleanup related to new naming scheme and refactoring, fixes refits to blank model names.

MekHQ/src/mekhq/campaign/mission/AtBContract.java
The random camouflage picker was sometimes picking directories instead of files to use as camo for a group in a generated contract. It also wasn't going into all of the subdirectories, only the first level under the faction, so some files were getting left out. This fixes both of those problems. 
It seems like Camoflauge or AbstractIcon should have some verification that the files you pass them exist, but...
=> Fix #5028 and allow random camo to go into deeper directories

MekHQ/data/scenariomodifiers/HouseOfficerAir.xml, MekHQ/data/scenariomodifiers/HouseOfficerGround.xml
Changed `HouseOfficerAir` and `HouseOfficerGround` XML files to ensure both now correctly contribute to BV and unit count.
=> Corrected Scenario Modifiers for `HouseOfficer` units

MekHQ/src/mekhq/gui/dialog/CustomizeScenarioDialog.java, MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java, MekHQ/src/mekhq/gui/view/ScenarioViewPanel.java
Minor tweak to show which is width and which is height, because we always get confused here and it matters for cross-the-map objectives.
=> Clarify map dimensions in scenario displays

MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml, MekHQ/data/scenariotemplates/Low-Atmosphere DropShip Escort.xml, MekHQ/data/scenariotemplates/Space Blockade Run.xml, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Added a condition to check whether Use DropShips is enabled in AtB Options, before substituting NPC DropShips with Player DropShips.
- Fixed player DropShip substitution in FG3
=> Prevent StratCon from Pulling in Player DropShips, when Option is Disabled

MekHQ/src/mekhq/campaign/CampaignOptions.java
Updated the `getAtBBattleChance` method to return `0` if StratCon is enabled. This removes the need for users to manually set these values to `0` when enabling StratCon.
=> Add Check for StratCon Usage in `getAtBBattleChance` Method

MekHQ/src/mekhq/campaign/mission/AtBContract.java
Properly uses average BV across all Meks instead of random ones.
Corrected ally ratio for House command, best guess magic number for Liaison for now.
This should fix the displayed contract difficulty changing semi-randomly when going back and forth between contracts in the contract market, and generally improve the estimate.
This does not yet estimate the difficulty for Liaison command as accurately as it could, but it's better than what we had before and can be improved later.
@IllianiCBT requested mention
=> Bug fix and improvements for calculateContractDifficulty()

MekHQ/src/mekhq/campaign/parts/TurretLock.java
This makes Turret Locks write to and restore from the save file.
Without this, Turret Locks will always "load" from the save file as quality D items rather than the quality they were when saved, and possibly other problems involving saved work scheduling.
Thanks to @atmafox for notcing that her Turret Locks were maintaining up to quality E and somtimes F repeatedly.
---
It's possible that this is the wrong solution for this problem because Turret Locks are meant to be a meta component. If this is the case, they should not be maintenance items and they should not show up in the part quality report.
=> Fix TurretLock Part not saving

MekHQ/data/universe/academies/Prestigious Academies.xml, MekHQ/data/universe/academies/Unit Education.xml
Changed `isMilitary` and `isPrepSchool` flags to false for Adult Apprenticeship in `Unit Education.xml`. Corrected spelling of "MechWarrior" in `Prestigious Academies.xml`.
=> Fixed `isMilitary` and `isPrepSchool` flags; Corrected Typo.

MekHQ/src/mekhq/campaign/Campaign.java
One-line fix so that it shows the actual amount of armor (points) on order rather than the points of just one unit of armor.
=> Fix to show actual amount of armor on order in repair info

MekHQ/src/mekhq/adapter/LocalDateAdapter.java, MekHQ/src/mekhq/campaign/universe/HiringHallOverride.java, MekHQ/src/mekhq/campaign/universe/PlanetarySystem.java
This adds a static list of hiring halls with dates to systems.xml. The hiringHall node is embedded in the relevant system node. This allows us to override the dynamic hiring hall system for certain worlds like Outreach.
=> Implement Hiring Hall Overrides

MekHQ/src/mekhq/gui/BriefingTab.java
Added calculation and integration of generic battle value in `BriefingTab` when saving entity lists to MUL.
This is hidden in MUL export as GBV is not meant to be user-facing. We include it here as a debugging tool.
=> Added `TotalGenericBattleValue` Tag to MUL Export

MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Standardized the GM hire command naming for consistency and fixed the skill level override logic to skip pre-existing crew members. This prevents unintended skill level changes and ensures correct hiring and configuration of personnel.
=> Fixed Hire Minimum Compliment Commands

MekHQ/src/mekhq/campaign/Kill.java, MekHQ/src/mekhq/campaign/personnel/autoAwards/KillAwards.java
Introduced a unique award identifier in `Kill.java` and updated `KillAwards.java` to use this to filter duplicate kills in multi-crewed units. This ensures accurate kill counts and prevents duplicate rewards.
=> Added Duplicate Kill Checking for Multi-Crewed Units.

MekHQ/data/scenariomodifiers/PrimaryAlliesAir.xml, MekHQ/data/scenariomodifiers/PrimaryAlliesGround.xml
The two primary allies modifiers are a special case that is randomly added to a scenario, based on the contract command level (or contract type)...
...this runs contrary to the modifiers' description which made it seem like mhq was reacting to the size of enemy forces. 
Instead, this modifier would increase the size of the OpFor (by increasing the size of the player-allied force), resulting in the 'overwhelming enemy forces' problem it was claiming to 'solve'.
This PR restores the ability for these modifiers to contribute to BV (that had been accidentally dropped some time around 50.0) and updates the modifier description. While the original description was well intentioned, and technically accurate, it contributed to a lot of confusion over the months whenever Force Generation and …
=> Updated Primary Allies Scenario Modifiers

MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Removed the markdown rendering of the personality description and the word wrapping from the text field. As well as two incorrect uses of `wordWrap`.
=> Fixed Wrapping of Personality Description

MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
Modified the `PersonnelTableModelColumn` to use the effective fatigue value for personnel instead of the raw fatigue.
=> Updated Fatigue Column of Personnel Table to Use Effective Fatigue Value

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/src/mekhq/campaign/Campaign.java
Corrected whitespace and formatting inconsistencies within various methods in the `Campaign` class. Added triggering of `NewDayEvent` at the start of each new day cycle, instead of the end.
Also fixed a couple of minor issues in campaign.java that weren't worth their own PR.
=> Fixed New Day Reporting

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Updated the `generateLance` methods to include the `allowsTanks` parameter to allow us to ensure Vees aren't substituted into environments they cannot survive.
Enhanced logging and fallback mechanisms were also integrated to handle unit generation failures and substitutions more effectively.
=> Improved Force Gen Unit Substitution

MekHQ/src/mekhq/gui/dialog/reportDialogs/PartQualityReportDialog.java
Updated the layout for `PartQualityReportDialog` by calling `pack()` and setting the dialog to modal. Excluded `AmmoBin` parts from report generation and dynamically scaled font sizes using `UIUtil` for improved UI adaptability.
=>     Refined `PartQualityReportDialog` Layout Handling and Exclusions

MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Removed the unnecessary `<html>` tags from tooltip descriptions in `PersonViewPanel`.
=> Fixed SPA Tooltip HTML Wrapping in `PersonViewPanel`

MekHQ/src/mekhq/gui/dialog/nagDialogs/UnableToAffordJumpNagDialog.java, MekHQ/unittests/mekhq/gui/dialog/nagDialogs/UnableToAffordJumpNagDialogTest.java
Prevented the 'UnableToAffordJumpNagDialog' nag from appearing if jump path is empty, or the campaign is in transit to the final planet in the Jump Path.
=> Added Empty Jump Path Check `UnableToAffordJumpNagDialog`

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
Changed the default camouflage directory to "Standard Camouflage" when the faction code is null, ensuring valid directory assignment.
=> Fixed Camouflage Directory Assignment for Null Faction Codes

MekHQ/data/scenariotemplates/Frontline Disruption.xml, MekHQ/data/scenariotemplates/Irregular Force Assault.xml, MekHQ/data/scenariotemplates/Irregular Force Suppression.xml, MekHQ/data/scenariotemplates/Skirmish Disruption.xml, MekHQ/data/scenariotemplates/Tactical Withdrawal.xml
Updated force multipliers in several scenario templates to lower values to ensure more balanced gameplay.
Lowered weight of OpFor in `Irregular Force Assault` from 2-4 to 1-3. Removed the generic OpFor from `Irregular Force Suppression` to make these two scenarios feel more distinctive.
=> More FG3 Scenario Adjustments

MekHQ/src/mekhq/campaign/market/PartsStore.java
PartsStore's generator for miscellaneous EquipmentParts was not using new instances of the part everywhere it needed to. In particular this was causing this to happen:
1. New Hatchet A is generated with Omnipod turned off.
2. Hatchet A is placed in parts list.
3. New Hatchet B is generated with OmniPod turned on.
4. Hatchet B is placed in parts list.
5. Hatchet B is used to generate an empty OmniPod.
6. Empty OmniPod constructor turns off OmniPoddedness on Hatchet B, which propagates back to the one in the parts list.
Which results in two copies of each non-OmniPodded hatchet in the parts store, effectively:
My change adds a Hatchet C used to create the OmniPod, which fixes this:
The same is true for at least Maces if not other misc-type EquipmentParts
=> PartsStore - Fix EquipmentParts and OmniPods - Fixes Hatchets and Maces at least

MekHQ/src/mekhq/campaign/personnel/enums/AwardBonus.java, MekHQ/src/mekhq/gui/model/AutoAwardsTableModel.java
Added logic to include award bonus details like XP and Edge rewards in the award description in the autoAwards award ceremony dialog.
=> Added Award Bonuses to Award Ceremony Dialog

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/storyarc/storypoint/ScenarioStoryPoint.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java, MekHQ/src/mekhq/gui/CampaignGUI.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/dialog/ForceTemplateAssignmentDialog.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Right now, there's this problem:
Fire Support I was deployed via the right click menu in TO&E and Scout I was deployed via the StratCon Map.
Of note is that if you save and load the game, the units would get the deployment flag then anyway.
I consolodated the code for updating unit deployments into Force.SetScenarioID.
Note that this does not add or remove issues regarding TO&E drag and drop that I will document in another issue. (#5084)
=> Fix StratCon vs Normal deployment status of units

MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
Moved date and game year setting to ensure they apply after preset selection. This guarantees the correct initialization of campaign settings.
=> Fixed Preset Picker Date Issues

MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
This increases the size of the Resolve Scenario wizard a bit so you can see all the components horizontally, and makes it stop changing size as much. It also increases the size of the popups for viewing personnel to something useful.
There are still some issues with window placement and size wiggling that I intend to look into but this should increase the UX of these dialogs a little bit at least.
=> ResolveScenarioWizardDialog - Some UX Improvements

MekHQ/resources/mekhq/resources/ResolveScenarioWizardDialog.properties, MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
**Requires #5105**
Adds a very simple button to the Resolve Sceanrio Wizard Dialog. This button checks 'ransom prisoner' for every prisoner who has 'captured' set.
When you have a lot of vehicles and infantry, going through this list and ransoming everyone you don't want can be tiresome. Hence, button.
=> ResolveScenarioWizardDialog - Ransom All Button

MekHQ/src/mekhq/gui/InterstellarMapPanel.java
This PR updates the interstellar map to make the old ISW the default. It makes some substantial optimizations under the hood to ISW to make it less of a resource hog. As well as some general visual changes to that view and renamed it to 'Territory'.
This has a few added benefits. In addition to looking closer to CGL's official maps, the territory won't disappear when the user changes map filters. So you avoid situations like the image below:
Instead you get...
=> Updated Interstellar Map View Defaults & Optimized 'ISW' view

MekHQ/data/scenariomodifiers/EnemyDropship.xml, MekHQ/data/scenariomodifiers/GroundedEnemyDropship.xml
Changed the generation method from 2 to 3 and added `minWeightClass` with a value of 0 in both `GroundedEnemyDropship.xml` and `EnemyDropship.xml`.
This corrects the 'fleet of DropShips' bug (again).
=> Corrected DropShip Scenario Modifier Generation Method

MekHQ/src/mekhq/gui/model/TechTableModel.java
When you're eyeballs deep in multiple days of repair, tasks stretched over days, not sure who's time you've spent  today or yesterday, it's easy to lose track of how much time people are going to have tomorrow after maintenance; this would help with that. 
It's also how we already display tech time on the refit tech selector.
I think this might just be the last change to the tech list for a good while. Probably. :>
=> TechTabelModel - Show Daily Available Time for Techs

MekHQ/data/scenariomodifiers/LiaisonGround.xml, MekHQ/data/scenariotemplates/Decoy Engagement.xml, MekHQ/data/scenariotemplates/Decoy Interception.xml, MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Deep Raid.xml, MekHQ/data/scenariotemplates/DropShip Raid.xml, MekHQ/data/scenariotemplates/Heavy Recon Evasion.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml, MekHQ/data/scenariotemplates/Recon Evasion.xml
- Updated the turn limit on a number of scenarios, some have been made harder, others easier.
- Fixed ground forward observers turning up in aerospace fighters. These would spawn on the ground and the observer would spend the entire battle just driving them about - making airplane noises as they did so, I suspect.
=> FG3 Scenario Improvements

MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/gui/model/UnitTableModel.java, MekHQ/src/mekhq/gui/sorter/UnitTypeSorter.java, MekHQ/src/mekhq/gui/view/UnitViewPanel.java
Omni units have different rules in regards to refits and such that matter in MekHQ more than in MegaMek, so I thought it would be nice to distinguish them a little more clearly.
Omni units sort after non-omni units of the same type.
Unit list filters don't change, e.g. OmniMeks and Meks are both listed under the Mek filter.
Also kills a couple deprecaiton warnings along the way.
=> Label OmniUnits as Omni in the MekHQ UI

MekHQ/src/mekhq/campaign/Campaign.java
Moved `MekHQ.triggerEvent(new NewDayEvent(this))` to the end of `processNewDay` method. This refactor ensures the event trigger occurs after all day-start logic has been processed.
=> Fixed Position of `NewDayEvent` Trigger in `processNewDay`

MekHQ/src/mekhq/utilities/ReportingUtilities.java
Figured I'd break these out of my Refit rework.
For example, `surroundIf("(", maybeText, ")")` will return `"(<maybeText>)"` or `""` depending on the status of `maybeText`
`separateIf(text1, ", ", text2)` will return one of `"<text1>, <text2>"`, `"<text1>"`, `"<text2>"`, or `""` based on the status of the first and last parameters.
They're pretty simple, but can declutter a lot of the simpler cases of things where using a StringBuilder or StringJoiner seems like overkill.
The names are inspired by WinAmp title formatting marcos ^^;.
=> A few text joining functions for ReportingUtilities

MekHQ/src/mekhq/campaign/personnel/education/Academy.java
Adjusted logic to ensure reeducation camps only consider wars involving the campaign faction. This means players can continue brainwashing their prisoners without fear of a pesky little thing like 'interstellar war' getting in the way.
=> Fixed Faction Conflict Checks for Reeducation Camps

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignSummary.java
Field Kitchens will no longer count Prisoners against their limit, unless the Prisoner has a role. Furthermore, support personnel are no longer counted in the campaign summary screen (this was a visual bug only).
=> Refactored Field Kitchen Personnel Count Logic

MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
Added checks to handle scenarios where facilities or objectives could not be placed because all coordinates in a StratCon track were occupied. Issued warnings and errors, and updated the `getUnoccupiedCoords` method to return null when placement is not possible.
It's worth noting that this is not a scenario that is likely to ever come up, because what are the chances we try to place a new scenario down on a track where _every_ hex is occupied? In vanilla StratCon that scenario will never occur because `getUnoccupiedCoords` is only called at the beginning of a contract when a track is effectively empty.
I'm currently working on a secret project that will require me to place events on the StratCon map. I'm planning to use `getUnoccupiedCoords`, as I don't want stacked events, but that …
=> Handled StratCon Scenario Placement Failure when All Coordinates Occupied

MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
Changed minimum number of tracks from 1 to 0 when initializing contracts. This adjustment ensures that the number of tracks properly reflects contracts requiring fewer lances, preventing erroneous excess tracks.
This fixes a misunderstanding in #5091. Seeing a variable called `numTracks` I mistakenly thought it was the number of tracks, instead it's the maximum track index. Mea culpa.
=> Fix Track Calculation in `StratconContractInitializer`

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Moved difficulty multiplier application exclusively to enemy forces. Previously it was being applied to both player and enemy forces. This meant that, if the player was playing with a low difficulty, their allies would have their force budgets slashed.
I also did a couple of minor reporting changes. Nothing of note.
=> [Fg3] Refactored Difficulty Multiplier Application

MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
Previously, loot checkboxes were initialized as unselected. Now, they are set to be selected by default, and loot is added to the campaign only if the scenario's overall status is classified as a victory.
=> Adjusted Scenario Loot Box Behavior

MekHQ/src/mekhq/gui/utilities/JScrollPaneWithSpeed.java
Changed the `JScrollPaneWithSpeed` constructor to take a null argument for the viewport. This was done to ensure proper initialization of the scrolling pane.
This might be negated by some refactoring @WeaverThree is doing, but I had to make the change locally so I figured it was worth pushing.
=> Refactored `JScrollPaneWithSpeed` Constructor

MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java
Added a new helper method to `StratconRulesManager` that allows Classes outside of StratCon to spawn StratCon scenarios. These scenarios can be spawned either on a random or specific Track. Likewise, the scenario template can be either specific or random.
I also extracted some repeated logic into helper methods and consolidated map location imports, seeing that they're being used in a whole bunch of places in this class.
Finally, I adjusted `generateScenariosForTrack` (which my new method is based on) to only place scenarios in unoccupied locations. This should help avoid scenarios being lost under facilities (or visa versa) and is meant to work alongside the changes made in #5141.
=> Added New StratCon Scenario Generation Utility Method

MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
**Includes #5146
Closes #5132**
This is a major UI overhauld of the Resolve Scenario Wizard Dialog. It's now a tabbed dialog instead of being based on CardLayout. Highlights:
- Window will not resize itself while changing between pages
- Tabs are all visible but they're enabled based on the same criteria that the old panel skipped pages by.
- Prev/Next still work. They skip disabled tabs.
- Every page is now formatted the same: centered column of controls flush against the top of the display area, or scrolling if the page is long enough
- Fixed prior issue of text boxes growing but not shrinking.
- Code cleaned up, modularized, documented, and generally spiffied up.
There's one piece I haven't figured out: dynamically updating the objectives list based on selections from units and …
=> ResolveScenarioWizardDialog - Rebuild as a tabbed dialog, improve UI

MekHQ/data/stratconfacilities/AlliedAirBase.xml, MekHQ/data/stratconfacilities/AlliedArtilleryBase.xml, MekHQ/data/stratconfacilities/AlliedBaseOfOperations.xml, MekHQ/data/stratconfacilities/AlliedCommsCenter.xml, MekHQ/data/stratconfacilities/AlliedMekBase.xml, MekHQ/data/stratconfacilities/AlliedTankBase.xml, MekHQ/data/stratconfacilities/HostileAirBase.xml, MekHQ/data/stratconfacilities/HostileArtilleryBase.xml, MekHQ/data/stratconfacilities/HostileBaseOfOperations.xml, MekHQ/data/stratconfacilities/HostileDataCenter.xml, MekHQ/data/stratconfacilities/HostileIndustrialFacility.xml, MekHQ/data/stratconfacilities/HostileMekBase.xml, MekHQ/data/stratconfacilities/HostileOrbitalDefense.xml, MekHQ/data/stratconfacilities/HostileTankBase.xml
Removed unnecessary line breaks in `userDescription` tags.
=> Fixed Line Breaks in StratCon Facility Descriptions

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Removed redundant check for victory points in deployment eligibility. Previously we removed the automatic exchange of CVP to SP when reinforcing a non-Fight Stance'd force. However, this check was missed so would display non-Fight forces even if the player has no SP. Now, those forces will only be visible if the player has SP adding visible value to the Fight stance.
=> Fixed StratCon Reinforcement Deployment Check

MekHQ/src/mekhq/gui/enums/MHQTabType.java
Changes order of the tabs in CampaignGUI, interstellar map is now right beside the command center mostly due to "vibes".
I think a command center should have easy access to a map. Then we have the TO&E, Briefing Room and StratCon, this is the "war room" basically, then we have personnel and hangar. Warehouse moved after the repair bay due to ergonomics, its not so frequent that we "visit" the warehouse, and it has more to do with book keeping most of the time, checking how many tons we have left, if there is anything to sell, etc. Infirmary, Finances, and in the last tab MekLab.
I think that MekLab in the last position is reasonable since it is mostly an empty screen unless you are activelly changing something, and as soo
n as you accept a design it disappears from the mek lab again, so …
=> CampaignGUI Tab reordering

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Added logging to display the force BV multiplier from the scenario template and the computed BV budget after applying the multiplier and any scenario modifiers. This helps in debugging by providing detailed information about how the BV budget is calculated.
=> Added Force BV Multiplier Logging & Adjusted Calculation in `AtBDynamicScenarioFactory`

MekHQ/data/scenariomodifiers/AlliedTraineesAir.xml, MekHQ/data/scenariomodifiers/AlliedTraineesGround.xml, MekHQ/data/scenariomodifiers/LocalGarrisonInfantry.xml, MekHQ/data/scenariotemplates/Irregular Force Assault.xml, MekHQ/data/scenariotemplates/Irregular Force Suppression.xml
Changed infantry generation method in two scenario templates to reduce infantry spam.
Updated text and settings in trainee forces. They are now tied to the same victory conditions as the player force and will now spawn as a full lance/star/level II instead of an arbitrary 3 unit count.
=> [FG3] Updated Infantry Generation Method and Trainee Settings

MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java
Changed the `forceStandardBattleValue` parameter from `false` to `true` to ensure accurate BV display in the Scenario Wizard Lance Renderer. This stops the StratCon force allocation windows from displaying GBV.
=> [FG3] StratCon will No Longer Display GBV when Using FG3

MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
As per title. Customize preset is still available. This functionality was set up to enable easy testing of new features and is feature incomplete without the rest of Campaign Options IIC. Once 50.01 has shipped this option will be re-enabled.
=> Temporarily Disabled Preset Confirm in New Campaign Dialog

MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Removed the CAM_OPS item from the `comboContractMarketMethod` comboBox in `CampaignOptionsPane`. This option is not ready for general use and will be re-enabled once 50.01 has shipped.
@Algebro7 I know you had plans to do this yourself, but I also know you're super busy IRL and I had time, so figured I'd do it.
=> Temporarily Removed CAM_OPS from Contract Market Method ComboBox

MekHQ/src/mekhq/gui/model/PersonnelTableModel.java
When I was last in these parts apparently I didn't set the filter argument to a function correctly and permanent injuries displayed as if they were regular injuries in the list. This fixes that.
=>  Fix Perm. Injury showing as Injury on Personnel tabel

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
Fixes an error in calcluating the number of days left on a refit caused by not discounting time spent by a tech assigned to both do the refit and maintain the mech being refit.
Also marks techs that are doing refits in the personnel column.
=> Show refitting techs and fix refit countdown

MekHQ/src/mekhq/gui/MekLabTab.java
All the prep work was already done, see line 328-331.
Closes #5185 
Closes #846 
That's got to be some kind of record, 6 years for a one line fix.
=> Fix BattleArmor customization/refit overweight check.

MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
This was temporarily disabled, prior to the release of 50.01, as it wasn't ready for public consumption.
=> Re-enabled Confirm Preset Option for New Campaign Preset Picker

MekHQ/src/mekhq/gui/StratconPanel.java
Added a try-catch block to handle errors when fetching a force by its ID in `StratconPanel.java`. This prevents the application from attempting to draw a force on the map if it fails to fetch the force data and logs an error message accordingly.
=> Handled Exception when Fetching Force by ID in `StratconPanel`

MekHQ/data/scenariotemplates/Decoy Engagement.xml, MekHQ/data/scenariotemplates/Decoy Interception.xml, MekHQ/data/scenariotemplates/DropShip Raid.xml, MekHQ/data/scenariotemplates/Heavy Recon Evasion.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml, MekHQ/data/scenariotemplates/Recon Evasion.xml, MekHQ/data/scenariotemplates/Reconnaissance Interdiction.xml
Adjusted the `timeLimitScaleFactor` from 1 to 2 across multiple scenario templates. This change extends scenario time limits.
=> Increase Time Limit Scale Factors in Scenario Templates

MekHQ/data/scenariomodifiers/PiratesIncomingAir.xml, MekHQ/data/scenariomodifiers/PiratesIncomingGround.xml, MekHQ/data/scenariomodifiers/PiratesPresentAir.xml, MekHQ/data/scenariomodifiers/PiratesPresentGround.xml
Lowered the force multiplier from 1.0 to 0.5 for all pirate-related scenario modifiers. This change affects both ground and air scenarios involving pirates to adjust the difficulty balance.
=> Reduced Force Multiplier for Pirate Scenarios

MekHQ/src/mekhq/campaign/personnel/divorce/AbstractDivorce.java
Corrected an error where the departing partner was incorrectly set to the origin partner rather than the spouse. This ensures that the dependent spouse is properly added to the departing partners list.
=> Fix Spouse Dependency Check in Divorce Logic.

MekHQ/src/mekhq/campaign/Campaign.java
Replaced `SITE_FACILITY_MAINTENANCE` with `SITE_FACILITY_BASIC` in the comparison logic for unit site determination. This ensures planetary modifiers are only applied in appropriate circumstances.
=> Corrected Unit Site Comparison Logic

MekHQ/src/mekhq/campaign/Campaign.java
Replaced `getPersonnel` with `getActivePersonnel` in `getCurrentPrisoners` method. This change ensures only active personnel are checked for prisoner status.
=> Refactored `getCurrentPrisoners` to use `getActivePersonnel`

MekHQ/resources/mekhq/resources/CamOpsReputation.properties, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/CommandRating.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/TransportationRating.java
CamOps Reputation now correctly calculates transport rating and command rating.
The CamOps Reputation report dialog has been reformatted to improve usability.
Going from this...
To this...
=> Reputation Error Corrections & Report Reformatting

MekHQ/src/mekhq/campaign/force/FormationLevel.java
Expanded the case matching for the INVALID formation level to include the string "Invalid Formation". This prevents invalid formations from failing to parse.
=> Enhanced INVALID Formation Level Checking

MekHQ/data/scenariomodifiers/FacilityHostileCapture.xml, MekHQ/data/scenariomodifiers/FacilityHostileCaptureNonWin.xml
Reduced the percentage of forces to be preserved for a successful hostile facility capture from 75% to 25%. This brings these modifiers in better alignment with their defense equivalents.
=> Lowered Capture Percentage Requirement to 25%

MekHQ/data/scenariomodifiers/HouseOfficerAir.xml, MekHQ/data/scenariomodifiers/HouseOfficerGround.xml, MekHQ/data/scenariomodifiers/IntegratedAlliesAir.xml, MekHQ/data/scenariomodifiers/IntegratedAlliesGround.xml, MekHQ/src/mekhq/campaign/mission/AtBContract.java
Adjusted the command rights modifiers based on player feedback.
Originally the intent was to roll these modifiers back to their 50.0 values, however that presented a couple of issues. As those modifiers use fixed unit counts we end up in a situation where we have to use magic numbers to guesstimate the power of those units when preparing the contract difficulty estimate. It also fails to scale with the player force, leading to an undesirable scenario where the player might have a tiny force (say, a couple of Warrior VTOL) and the allied princess drops two 100t assault 'meks.
Instead, I've opted to keep things scaled by BV, but adjusted the BV multiplier to reduce the overall size of engagements and to reduce the players' reliance on the performance of their allied Princess (the two chief …
=> Adjusted Command Rights Scenario Modifiers

MekHQ/src/mekhq/campaign/personnel/generator/DefaultSpecialAbilityGenerator.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
Removed hard-coded logic for SPA gain when improving personnel from Regular -> Veteran and Veteran -> Elite.
Legacy AtB has personnel automatically gain SPA when reaching Veteran and Elite ratings. Personnel acquired off the market have a random chance of 0-2 SPAs, plus those guaranteed SPAs.
SPAs cost around 50 xp each. Hitting Elite will cost 170-340 xp (depending on whether it's a one or two skill profession). That means buying an Elite character from the personnel market is the equivalent of getting 320-540+ xp for effectively free.
Furthermore, these hardcoded SPA improvements cause problems for anyone wanting to play using CamOps, as they need to manually remove the hardcoded SPAs prior to adding their own picks.
While the second issue could be resolved by adding a campaign option …
=> Removed Legacy AtB Guaranteed SPAs

MekHQ/docs/Stratcon and Against the Bot/AtB documentation.19_8 (WIP).txt, MekHQ/resources/mekhq/resources/AddFundsDialog.properties, MekHQ/src/mekhq/gui/FinancesTab.java
Changed the label and button text from "Add Funds" to "Add Transaction" across the GUI and documentation. This better reflects the functionality of the feature.
=> Renamed "Add Funds" to "Add Transaction" for Clarity

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/src/mekhq/campaign/Campaign.java
If StratCon is enabled, on the first of each month Admin/Transport personnel will use their Administration skill to generate Support Points.
The creation of a Support Point requires they pass an Administration skill check (with no current modifiers). If passed they create a single Support Point. Support Points created in this manner are capped at 1 per Track. So a contract with 3 Tracks can generate up to 3 additional Support Points each month.
Campaigns with multiple active contracts will make rolls for the oldest contract first. Admin/Transport personnel are only afforded a single roll each month, no matter how many active contracts there are.
=> Added Monthly StratCon Support Points Generation

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
StratCon initialization requires a nonzero requiredLances to generate a nonzero number of tracks, and zero tracks causes a division by zero further along in initialization.
Solves issue #5181.
=> Generate required lances for manual AtB contracts for StratCon init

MekHQ/resources/mekhq/resources/Campaign.properties
Updated text for the Employee Turnover dialog to provide clearer instructions.
Changed "Employee Turnover" to "Continue", "Advance Day Regardless" to "Ignore Check", and "Cancel Advance Day" as "Cancel".
These changes should help remove any possible confusion as to what button should be clicked.
=> Refined Turnover Prompt Dialog Text

MekHQ/userdata/data/universe/ranks.xml
Incremented the rank systems version in ranks.xml from 0.50.1-SNAPSHOT to 0.50.2-SNAPSHOT. This stops IDEA from pestering us to update it any time we make a change in mhq.
=> Update Rank Systems to Version 0.50.2-SNAPSHOT

MekHQ/docs/history.txt, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
Simulated Relationships allowed females to get pregnant and give birth in the same week, letting them have more kids than possible. Characters in simulated relationships with females were unable to procreate, and if they did their children wouldn't be saved. Children from simulated relationships will have a high school education if they're at least 16.
Solves issue #5239
=> Issue 5239 simulated relationship behavior fixes

MekHQ/resources/mekhq/resources/RetirementDefectionTracker.properties, MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java
Corrected the typo in the resource key "recentPromotion" and added a `null` check for the last promotion date before calculating the months difference. This ensures the application does not encounter a silent null pointer exception.
=> Fix Typo and Added `null` check in `RetirementDefectionTracker`

MekHQ/data/scenariotemplates/Low-Atmosphere DropShip Escort.xml, MekHQ/data/scenariotemplates/Space Blockade Run.xml, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/unittests/mekhq/campaign/mission/DynamicScenarioFactoryTest.java
Adjusted the two DropShip Escort scenarios to veer less towards spamming units. This was achieved by marking the DropShips as not contributing towards BV, but then doubling the BV allowance of the OpFor.
Adjusted how aircraft forces are generated. Previously, whenever a planet-owner generated an arial force there was a 50/50 chance they would spawn Conventional Fighters. In addition, the size of Conventional Fighter forces was around 6 units (triple the standard array). When combined with the _very_ low BV2 / GBV cost of Conventional Fighters, this meant when those forces were spawned they disproportionately flooded the OpFor. In many cases 6 Conventional Fighters were still less BV2/GBV than a single Aerospace Fighter. Now Conventional Fighter flights match the size of their Aerospace …
=> [FG3] Updated Aircraft Force Generation, Unit Culling, and Added ProtoMeks

MekHQ/src/mekhq/campaign/parts/MissingCubicle.java
Fixes #4849 
Same fix was used on the MissingBayDoor class.
=> Issue 4849: Replaced Cubicles Persist after Saving & Loading

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
I dont know of any bug in particular that called for this, however when checking the save from the issue #4529 I encountered this error, where it was looking for a specific skill that the person didnt had loaded, so when trying to open the person contextual menu it threw a null pointer exception.
=> fix: adds null check before accessing skill property

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/unit/MothballInfo.java, MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/gui/CampaignGUI.java, MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java, MekHQ/unittests/mekhq/campaign/CampaignTest.java
Because we have the concept of "engineer" inside MM to handle the self-healing properties of large vessels, funcitonalities like "mothball" and "activate" are compromised due to them requiring a tech.
This fix does two things:
- fix #4529, it does that by adding the previous "engineer" to the crew of the mothballed vessel.
- Adds `vessel techs` to the selection of techs in the "select a techie" drop down window when you want to activate a unit.
The later was necessary to deal with a rare but possible situation. If the engineer that originally mothballed the large vessel (present in the mothballInfo object) is not active, or were removed/sacked by any reason then they would not be available to activate the ship, this means that the ship would be locked in a situation that could only be …
=> allows to select a previous engineer or new crew member to activate large vessels

MekHQ/src/mekhq/campaign/parts/Thrusters.java
This allows for both left and right thruster missing parts.
It does not clear excess missing Thrusters, but they won't return once fixed or cleared by the GM.
Fix #4163
=> Fixing bug #4163. This allows the left thruster to be a missing part

MekHQ/src/mekhq/AtBGameThread.java
Fixes #4085 
We don't actually track bay personnel. You can assign units to a dropship, but it doesn't change the nCrew for the ship, which MegaMek assumes will include bay personnel, so when loading a spaceship from MekHQ to MegaMek, it will calculate the current crew by taking nCrew and removing the assumed bay personnel - this is what prevents Spaceships from being moved form MHQ to MM, they will never have enough crew.
When spaceships are loaded from data, the crew includes the bay personnel, so the calculation passes.
=> Issue 4085: MegaMek fails to load Dropship sent from MekHQ

MekHQ/src/mekhq/AtBGameThread.java, MekHQ/src/mekhq/GameThread.java, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Added initiative bonus to campaign and passes it to megaMek's constantInitBonus.
Currently doesn't have bonus/negative ceiling, but can implement something along those lines if needed.  
The initiativeBonusIncrement function takes a boolean-->  true increases by 1, false decrease by one.
closes #4600
In future could tie bonus to fatigue/morale module
=> Add Persistent Initiative Bonus to campaign

MekHQ/src/mekhq/AtBGameThread.java, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/force/StrategicFormation.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java, MekHQ/src/mekhq/campaign/mission/AtBScenario.java, MekHQ/src/mekhq/campaign/mission/CommonObjectiveFactory.java, MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/BreakthroughBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/ChaseBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/ExtractionBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/HideAndSeekBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/HoldTheLineBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/ProbeBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/ReconRaidBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/StandUpBuiltInScenario.java, MekHQ/src/mekhq/campaign/personnel/autoAwards/MiscAwards.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/BriefingTab.java, MekHQ/src/mekhq/gui/ForceRenderer.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java, MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java, MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
**Key Note:** `Lances` are what MHQ called any combat `Force`, i.e. any combat node in your TO&E that contains at least one ground `Unit`. When reading the below any instance of 'lance' is referring to the internal class and _not_ the IS Formation.
To reduce confusion `Lance.java` has been renamed to `StrategicFormation.java`. The relevant methods and classes have also been renamed.
A StratFor is considered to be any combat force in the TO&E that contains at least one ground unit and has no ancestor or descendant nodes which are also StratFors. Players can manually define individual forces to always be considered StratFors, or never considered StratFors. These overrides can be easily removed. Assigning or removing an override is accessed via the TO&E right-click menu.
StratFors are easily …
=> Renamed 'Lances' to 'Strategic Formations', Expanded Functionality

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/unittests/mekhq/campaign/CampaignTest.java
Added initiativeMaxBonus to Campaign  with XML support
added maxBonus check to initiativeIncrementer
added applyInitiativeBonus() to adjust initiativeMax  and  apply appropriate bonus
added initiative tests 
Ref #4600
=> Added initiativeMaxBonus to Campaign 

MekHQ/src/mekhq/AtBGameThread.java, MekHQ/src/mekhq/campaign/force/StrategicFormation.java
Refactored the manner in which we calculate Strategic Formation weights (Heavy, Light, etc). Previously we inherited the old Legacy AtB weight categories which considered any `Force` with a weight greater than 390 to be a Super Heavy force. This older method also failed to properly account for non-IS campaigns.
Now weight categories are correctly tied to unit weight categories, with faction exceptions applied where appropriate.
=> Refactored Strategic Formation Weight Categories

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Updated the morale calculations for scenario rolls and replaced conditional statements with switch cases to enhance code readability. Added detailed logging outputs to track morale checks and associated modifiers for better debugging and monitoring of morale changes.
Adjusted morale-based scenario generation modifiers for StratCon. The goal here is to make the player feel like they are being overrun when at higher morale levels.
=> Refactored Morale Calculations and Logging

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/force/StrategicFormation.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/AtBScenario.java, MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioFactory.java, MekHQ/src/mekhq/campaign/personnel/autoAwards/MiscAwards.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java, MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java, MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
This PR does a bunch of refactoring for the new Strategic Formations system. It bolsters existing methods with a few extra calls and integrates better across MHQ. This includes self-sanitizing methods and a centralized way to review the TO&E to ensure it's always up-to-date. A number of bugs have been resolved and the general user experience has been improved.
=> Refactored Strategic Formations

MekHQ/src/mekhq/gui/dialog/NewAtBContractDialog.java
closes #5149 
Added null checks for Employer, Enemy, and Planet with matching messages.
=> Null checks in manual contract generation

MekHQ/data/forcegenerator/3075.xml
Fixed a syntax issue in the availability line for the 'Enforcer' chassis in the 3075.xml file, separating 'FVC:7' and 'LA:2' with a comma.
=> Corrected Availability Syntax in `3075.xml`

MekHQ/src/mekhq/gui/BriefingTab.java, MekHQ/src/mekhq/gui/dialog/MissionTypeDialog.java
Bad behavior on canceling "Add Mission" was due to single boolean check if mission was contract.  If add mission tab was closed it would default to false and CustomizeMissionDialog frame would be generated.
-- added isMission() check 
Also set briefing tab to remain visible.
Add mission check to AddMission and left BriefTab visible
closes #5060
=> BriefingTab  Fix

MekHQ/data/scenariotemplates/Low-Atmosphere Reinforcements Intercepted.xml, MekHQ/data/scenariotemplates/Reinforcements Intercepted.xml, MekHQ/data/scenariotemplates/Space Reinforcements Intercepted.xml, MekHQ/resources/mekhq/resources/AtBStratCon.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
The previous reinforcement implementation created some balancing concerns. The gameplay loop would be this: scenario spawns, player deploys a lance, the player then reinforces that scenario using Forces in Fight Stance. This is easily done by converting CVP to SP, if necessary. The player will usually out-BV Princess at this point, allowing for a much easier victory. This generates a CVP, making future scenarios easier. So long as the player can maintain CVP above 1 they can infinitely reinforce. The only limitation is the number of Forces available to them. As they are taking less casualties they end up in a victory spiral where past victories ensure future victories. There is a bit more to it than that, but that's the general gist.
Following a handful of discussions on Discord it was …
=> Implemented Advanced StratCon Reinforcements

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java
Modified pickRandomCamo to have "Root" faction that selects from all faction icons and implemented it in Campaign.
closes #5114
=> Campaign now uses pickRandomCamouflage when initialized

MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java, MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
Removed the conversion of victory points to support points and replaced it with a GM function to remove victory points.
At will SP is very powerful, and while recent changes have reduced the effectiveness of SP, it was decided that we should remove at will SP sources.
Players are awarded with extra XP if they get over a certain number of CVP, meaning excess CVP are not wasted.
The primary source of SP is Admin/Transport personnel who generate monthly SP.
=> Refactored CVP Conversion to Removal of CVP.

MekHQ/src/mekhq/campaign/Campaign.java
Adjusted the logic for calculating negotiated support points.
Each month personnel in the Admin/Transport role use their administration skill to generate Support Points. Previously the number of Support Points that could be generated was capped at the number of Sectors assigned to the contract.
This PR changes this so that the maximum number of Support Points that can be generated, per month, is equal to the number of combat forces required by the contract.
Furthermore, for every 4 points a character exceeds their Admin skill check, that character will generate an extra Support Point. This should allow Elite personnel to carry less skilled characters.
=> Adjusted Support Points Negotiation Logic

MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
Updated the force display logic to exclude the origin node name in the Lance Assignment View. This ensures that the force name is displayed without unnecessary origin information.
=> Remove Origin Node Name from Lance Assignment Table

MekHQ/resources/mekhq/resources/ScenarioTableModel.properties, MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
Implemented a new sector column in the `ScenarioTableModel` to display relevant sector information for StratCon scenarios. This changes improves the user interface by ensuring users know which sector they should be looking in, when trying to track down a scenario for deployment purposes.
=> Added Sector Column to `ScenarioTableModel`

MekHQ/src/mekhq/campaign/parts/SVArmor.java
Adjusted the `SVArmor` price calculation to account for armor that doesn't exist at certain tech levels by returning zero cost. This change ensures we don't end up with a value of `Infinity` due to dividing by `0.0` -- the return value of ineligible (or non-existent) `bar` armor (specified elsewhere in the codebase).
=> Fixed `SVArmor` Price Calculation

MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/handler/TOETransferHandler.java
Removed the ability for users to deploy/undeploy forces to/from StratCon scenarios. Both of these are known to cause issues with StratCon. There are quite a few steps for users to take prior to accidentally deploying the wrong force, so in my mind the benefit outweighs the occasional inconvenience.
Removed the ability to unassigned deployed units from transports.
Removed the ability to move units/forces that are currently deployed.
=> Adjusted TO&E Menu Option Availability

MekHQ/data/forcegenerator/2823.xml, MekHQ/data/forcegenerator/3075.xml, MekHQ/data/forcegenerator/3085.xml
Fixed missing commas in the availability data for several unit chassis types across different XML files.
Given the large number of these little buggers I don't doubt there are some still hiding in the recesses of the less popular eras, however with this PR all 'bookmarked' years will now load correctly.
=> Corrected Further XML Availability Formatting Errors

MekHQ/resources/mekhq/resources/Mission.properties, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenario.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java, MekHQ/src/mekhq/gui/StratconPanel.java, MekHQ/src/mekhq/gui/StratconTab.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
This PR updates the StratCon sector display to display a list of sectors, rather than using a drop-down. This makes it easier for users to spot how many sectors they are assigned to, for any given contract.
I also went ahead and expanded the scenario information to include ally (including player) and hostile (including 3rd parties) BV. This should make it easier for users to determine what forces to assign to what scenario without needing to bounce between the AO and Briefing tabs quite as much.
Players currently on Integrated contracts, when updating, will notice a minor visual bug where things don't use the best alignment. It's very minor and doesn't break anything. This bug will not exist for campaigns that pick Integrated contracts _after_ updating.
=> Updated Sector Display & Expanded Scenario Information

MekHQ/resources/mekhq/resources/DateChooser.properties, MekHQ/src/mekhq/gui/dialog/DateChooser.java
Corrected the spelling of "Fourth", from "Forth", in variable lists and properties to ensure accuracy in references to the Fourth Succession War. This change affects both the code's internal logic and user-facing text elements.
=> Fixed Typo in 'Fourth Succession War' Naming

MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/campaign/unit/actions/HirePersonnelUnitAction.java, MekHQ/unittests/mekhq/campaign/unit/UnitPersonTest.java, MekHQ/unittests/mekhq/gui/model/UnitTableModelTest.java
=> Issue 5256: Refactored MekHQ Unit's Gunners to be Set to ensure gunners are unique

MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifier.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Revised the method handling briefing text to eliminate redundant modifier file names from the briefing panel. Also adjusted formatting in `StratconRulesManager` to improve readability now modifier file names have been removed.
=> Simplified Modifier Briefing Text in `AtBScenarioModifier`

MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java, MekHQ/src/mekhq/gui/StratconPanel.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Added HTML tags for bold and italic styles to enhance the clarity of scenario information in the StratCon UI. Removed unused boolean parameter 'html' from the `getInfo` method to simplify its usage.
=> Enhanced Formatting in StratCon Scenario Information

MekHQ/src/mekhq/campaign/Campaign.java
=> Issue 5195: Made completion/finished by day calculation unambiguous

MekHQ/src/mekhq/campaign/personnel/autoAwards/TheatreOfWarAwards.java, MekHQ/src/mekhq/gui/dialog/AutoAwardsDialog.java, MekHQ/src/mekhq/gui/model/AutoAwardsTableModel.java
Reordered parameters in the `processFaction` method call to ensure proper functionality. Fixed call fetching employer faction, to correctly call faction code. Changed log message levels to debug - these were missed when I lowered the logging level of the majority of the internal autoAwards logger messages.
=> Fixed Theatre of War Faction Checks

MekHQ/data/scenariotemplates/Convoy Escort.xml, MekHQ/data/scenariotemplates/Convoy Interdiction.xml, MekHQ/data/scenariotemplates/Convoy Raid.xml, MekHQ/data/scenariotemplates/Critical Convoy Escort.xml, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
As a part of our FG3 push, we included a 'unit substitution' system to try and resolve the old issue of 0 entity forces. This system goes through multiple layers of failure, attempting to substitute failed entities, step-by-step loosening generation restrictions until we find _something_, even if that something isn't quite what we wanted.
At some point prior I included a much simpler system that did the same thing, but worse. That older system simply tried to generate a unit and if it failed it tried again, this time without any role requirements.
Because both of these systems existed at the same time what would happen is we'd try and generate a unit, fail for whatever reason, then abandon all attempts to match role requirements. Essentially bypassing unit substitution entirely. This …
=> Improved Unit Substitution

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/src/mekhq/campaign/Campaign.java
Fixes #5333 
In order to prevent confusion, when hiring personnel we will simulate their relationship history before showing their name. This lets us show their former surname if their name changed upon getting married.
=> Issue 5333: Show Hired personnel's name change

MekHQ/src/mekhq/gui/CampaignGUI.java
Added logic to disable the Advance Day button to prevent multiple activations while the advance day event is still being resolved. Re-enabled the button after the process completes, ensuring proper functionality and avoiding unintended behavior.
=> Disable Advance Day Button While Advance Day is in Progress

MekHQ/src/mekhq/campaign/unit/Unit.java
Fixes #5373 
Fixes #5372 
Fixes #5375 
Improperly added & removed gunners originally. Verified after this fix I can load the original save from the issue correctly. I also verified I can make a new save and that it loads properly.
=> Issue 5373: Fixed fix references not adding gunners

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/AtBScenario.java
Fix to align MHQ calls of TeamLoadOutGenerator functions with their updated argument lists.
Testing:
- Ran all 3 suites' unit tests
- Ran mission vs pirate ASFs
- Manually confirmed Rocket Launcher (Prototype) 10 bomb /RL-P 10 bomb ammo is purchasable in MHQ
NOTE: should be pulled immediately after https://github.com/MegaMek/megamek/pull/6254
=> MHQ part of Fix 6240: era-illegal asf bombs

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Ensured a minimum unit count for objective scaling to avoid overly short time limits in small scenarios. Added logging for missing scale factors, using a default value of 1 as a fallback.
Closes #5348
=> Refactored Objective Time Scaling to Handle Edge Cases.

MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
Updated `maybeShowPopup` to ensure the "Edit Unit" menu item appears only when a valid unit is selected, preventing out of index errors.
I also updated a couple of variable names for improved clarity.
Closes #5350
=> Corrected Briefing Room Unit Editing Menu Condition

MekHQ/src/mekhq/gui/stratcon/TrackForceAssignmentUI.java
Added setModal(true) to enforce modal behavior for the Manage Force Assignment dialog.
Simplified variable declarations and refactored the `actionPerformed` method by replacing the switch statement with an if condition.
Closes #5345
=> Reassigned StratCon Force Assignment Picker as Modal

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
It has long been a point of frustration for players that when scouting a StratCon strategic map, with a force assigned to the scout role, if a random scenario spawns it will spawn on top of the scouts forcing them into often uneven fights. While there is a degree of realism there, it doesn't offer the best play experience.
Now, when scouting, if a random scenario is spawned it will spawn in an empty adjacent empty hex (if possible). Only if all adjacent are occupied (highly unlikely) will the scenario spawn on top of the scout force.
While I recognize there may be some desire for scouts to occasionally fail to evade enemy forces, or to have scout suitable scenarios, I opted for this system as we do not currently categorize scenario templates based on force role suitability. This would be …
=> Scouts, Scout: Refactored StratCon Scenario Deployment to Support Scout Role Behavior

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Adjusted how the new autoLogistics module, added by @Lapras, marshals and unmarshals to/from xml.
Previously, it was converting the PartQuality to string (adjusted based on whether the user had reverse quality names enabled). This is a bit cumbersome and I'm not confident it would properly handle users enabling/disabling that option mid-campaign.
Instead, I've changed it so that it's using the enum value, as this remains consistent no matter what options the user has enabled. QUALITY_A is always QUALITY_A, the only thing that changes is how that's presented to the user.
=> Adjusted Marshaling and Unmarshaling of New AutoLogistics Module

MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java
Replaced dashes with underscores when parsing the `averageExperienceRating` field to prevent issues with invalid characters. Specifically to better handle 'ultra-green' experience ratings.
=> Fixed Experience Rating Parsing to Handle Invalid Character

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
The other day I went ahead and adjusted how scouting forces scout. Namely adjusting things so that they don't have scenarios spawn on top of them, instead having the scenario spawn in an adjacent hex. Unfortunately, I didn't do my due diligence. The way the deployment method is set up it's done in such a way that assumes not only is the hex a scenario spawns in identical to the hex the deployed force is in, but also that the deployed force will be the one fighting it.
This PR goes through and rewrites the method so that is no longer the case.
Closes #5392
=> Updated StratCon Deployment Mechanics

MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Deep Raid.xml, MekHQ/data/scenariotemplates/DropShip Raid.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml
Removed references to "30 turns" in scenario briefings to match the scenario templates, which FG3 changed to have a variable turn limit.
Fixes #5394
=> Corrected Scenario Briefings by Removing Explicit Turn Limits.

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Added a check to skip formations with a reserve role in the `StratconRulesManager`. This ensures that combat teams in reserve cannot be deployed to StratCon hexes. This is beneficial in a few ways: it ensures users are using the role system - which benefits them - and it also reinforces the idea that having a force 'in reserve' exempts it from being processed by StratCon (this is particularly important for Integrated commands).
=> Prevent Reserved Formations from Being Deployed to StratCon

MekHQ/src/mekhq/campaign/Campaign.java
Adjusted the calculation of maximum support points for StratCon campaigns to consider the number of active tracks. Ensured a fallback value of 1 when no tracks are available. I'm not entirely sure why I previously set it at required lances, because that's... ...let's just say 15 Support Points a month is a lot...
=> Capped Negotiated StratCon Support Points at Sector Count

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/gui/adapter/LoanTableMouseAdapter.java
Removed use of the term 'contract breach' in the 'outstanding scenario', and 'defaulting on a loan' nags.
In the latter case this nag was no longer accurate now we only support CamOps Reputation.
In the former case we want users to be empowered to skip scenarios they can't win. Taking a CVP loss is punishment enough. While I do intend to fully implement contract breaches, at this current time we don't track them and adding this messaging is confusing to players.
=> Removed Contract Breach References in Scenario and Loan Events

MekHQ/src/mekhq/campaign/Campaign.java
Added a call to `setMaintenanceMultiplier` for salvaged units. This ensures consistent initialization of maintenance settings for all newly created units.
=> Set Default Maintenance Multiplier for Salvaged Units

MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
In StratCon selecting a scenario with no forces assigned allows you to select a primary force, for that scenario, however if no forces are selected and you press 'commit' the scenario's state is changed as if a force had been committed - meaning all future forces are considered Reinforcements.
This change disables the commit button if no forces have been selected.
This dialog can be exited if users don't want to commit a force, by clicking the exit window button.
=> Disabled Commit Forces Button when No Forces Selected

MekHQ/src/mekhq/campaign/force/Force.java
Removed vestigial call to `updateCommander` when loading forces.
Renamed variables and parameters to improve readability and alignment with current coding standards. I was in that neck of the woods, so might as well.
Fixes #5304
=> Fixed Force Commanders Changing on Load

MekHQ/resources/mekhq/resources/acs-report-messages.properties, MekHQ/src/mekhq/campaign/autoresolve/acar/SimulationContext.java, MekHQ/src/mekhq/campaign/autoresolve/acar/phase/EndPhase.java, MekHQ/src/mekhq/campaign/autoresolve/acar/phase/VictoryPhase.java, MekHQ/src/mekhq/campaign/autoresolve/acar/report/EndPhaseReporter.java, MekHQ/src/mekhq/campaign/autoresolve/acar/report/VictoryPhaseReporter.java, MekHQ/src/mekhq/campaign/unit/damage/DamageApplier.java, MekHQ/src/mekhq/campaign/unit/damage/DamageApplierChooser.java, MekHQ/src/mekhq/campaign/unit/damage/EntityFinalState.java
This makes a couple of changes in ACAR and how it applies damage to entities, it will now only "consolidate" the damage on the entities after the game has ended, instead of doing it whenever they are destroyed and again after the game ends. Now its just a single step.
Also changed one of the reports so it makes more sense.
=> fix: change how damage is applied on ACAR

MekHQ/src/mekhq/campaign/personnel/Person.java
Reordered `PREGNANCY_COMPLICATIONS` and `STUDENT` to ensure intended fall through occurs. This change ensures status changes occur as intended.
=> Fixed Incorrect Ordering in Personnel Status Change Switch

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/icons/enums/OperationalStatus.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceModel.java, MekHQ/src/mekhq/gui/stratcon/ScenarioWizardLanceRenderer.java, MekHQ/src/mekhq/gui/stratcon/ScenarioWizardUnitRenderer.java
Renamed `LayeredForceIconOperationalStatus` to `OperationalStatus` now that enum is no longer only used to determine layered force icons.
Made a number of visual improvements to the StratCon force pickers, so that the user has more upfront information. Previously, users only had access to the force name, combat stance, and BV. I've added operational status and a full force name, so that users with multiple identically named forces can more easily differentiate between them.
Old...
...New...
These changes were extended to the reinforcement dialog...
Fixes #5344
=> Improved StratCon Force Picker & Renamed `LayeredForceIconOperationalStatus` to `OperationalStatus`

MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
Adjusted the JSpinner configuration to set the minimum skill level to 1 instead of 0. This prevents users accidentally locking themselves into an invalid state.
Fixes #5317 - I'm hoping this will retroactively fix any saves affected by this bug, too.
=> Set Minimum Target Skill Level in Mass Training Dialog to 1

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/view/ForceViewPanel.java
@Scoppio inadvertently showed how confusingly similar the terms 'Combat Team' and Combat Force were (specifically 'Non-Combat Force'. The confusion arises from the ability to mark a force to never be considered a Combat Team and declaring them a Non-Combat Force is, on the surface, identical - despite having different use-cases.
This PR changes the term 'Non-Combat' to be 'Support'. All player forces previously labeled as 'Non-Combat Forces' will now be labeled as 'Support Forces', instead. With the advent of Combat Teams and our future plans, 'Support Forces' better matches the purpose of that label than 'Non-Combat'.
=> Updated TO&E to Use "Support" Term instead of "Non-Combat"

MekHQ/src/mekhq/campaign/force/CombatTeam.java
Replaced `getUnits` with `getAllUnits` to include all units (including those in child forces) during the status check. This ensures proper evaluation of Combat Team suitability.
=> Fixed Unit Check in Combat Team Status Evaluation

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
The bug this aims to fix is primary and reinforcement forces swapping about when reloading MekHQ. So forces previously sent to a scenario would end up as the primary force, while the primary force got shunted to reinforcements.
In the first place we had an issue where primary force wasn't being serialized or deserialized. So mhq would, essentially, 'forget' that information when reloading the client.
However, fixing that did not resolve the problem, which lead us to the second issue: when reloading mhq also 'forgets' what Template player forces are assigned to. I did a couple hours' digging and I've concluded that we simply do not save this information. `StratconScenario` inherits from `AtBScenario` which inherits from `Scenario` and it's in `Scenario` that we store what forces have been …
=> Fixed Force Deployment Order Bug

MekHQ/data/scenariotemplates/Heavy Recon Evasion.xml, MekHQ/data/scenariotemplates/Recon Evasion.xml, MekHQ/data/scenariotemplates/Reconnaissance Interdiction.xml
Halved the scenario duration in three scenario templates: Heavy Recon Evasion, Reconnaissance Interdiction, and Recon Evasion. This should make these scenarios feel a little less punishing.
=> Halved Duration of Recon Scenarios

MekHQ/data/scenariomodifiers/AlliedASFAce01.xml, MekHQ/data/scenariomodifiers/AlliedAirSupport.xml, MekHQ/data/scenariomodifiers/AlliedAirSupportBombers.xml, MekHQ/data/scenariomodifiers/AlliedArtyGarrison.xml, MekHQ/data/scenariomodifiers/AlliedArtySupport.xml, MekHQ/data/scenariomodifiers/AlliedCavLance.xml, MekHQ/data/scenariomodifiers/AlliedHorseCav.xml, MekHQ/data/scenariomodifiers/AlliedMekAceCRD.xml, MekHQ/data/scenariomodifiers/AlliedMekAceGLT.xml, MekHQ/data/scenariomodifiers/AlliedMekAceGOL.xml, MekHQ/data/scenariomodifiers/AlliedMekAceOTT.xml, MekHQ/data/scenariomodifiers/AlliedMekAceTBT.xml, MekHQ/data/scenariomodifiers/AlliedMekGarrison.xml, MekHQ/data/scenariomodifiers/AlliedOfficerMek.xml, MekHQ/data/scenariomodifiers/AlliedTraineesAir.xml, MekHQ/data/scenariomodifiers/AlliedTraineesGround.xml, MekHQ/data/scenariomodifiers/AlliedTurrets.xml, MekHQ/data/scenariomodifiers/FacilityAlliedEvac.xml, MekHQ/data/scenariomodifiers/LocalGarrisonInfantry.xml, MekHQ/data/scenariomodifiers/PrimaryAlliesAir.xml, MekHQ/data/scenariomodifiers/PrimaryAlliesGround.xml
We received some feedback on Discord that highlighted a significant problem with how Scenario Modifiers were being handled:
In short, getting an Allied Force modifier would actually make the scenario harder. As for every allied unit added, the OpFor's size would increase. Conversely, whenever the player got an Enemy Force modifier, it would increase the size of the enemy force, by nature of giving the OpFor more units.
No matter what kind of modifier the player got, it would result in a harder scenario.
This PR addresses this by telling MekHQ to ignore random allied force modifiers, when calculating the OpFor's BV allowance. An exception was made for two types of allied force: those added by scenarios (like Allied DropShips) and those added by Command Rights (like Liaison units). For all …
=> Adjusted Scenario Modifiers BV & Unit Count Contribution

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
Introduced a default time limit constant to ensure objectives always have a minimum time limit. This prevents edge cases where objectives could lack a proper time constraint and improves overall scenario reliability. Adjusted related logic to use the constant for consistency.
If we _still_ get null turn limits it means the objective is failing to parse in its' entirety, which will be a thornier problem to resolve, so I'm hoping it's not necessary.
=> Added Further Edge Case Handling for Turn Limit Scenario Objectives

MekHQ/src/mekhq/campaign/force/CombatTeam.java
Replaced `getAllUnits() with `getUnits()` to prevent parent nodes from incorrectly being marked as Combat Teams. Added a comment for clarification of the logic.
=> Fixed Combat Team Eligibility Check by Rolling Back Use of `getAllUnits()`

MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Added removal of child forces when a parent force is deleted, ensuring proper cleanup of associated sub-forces.
Disabled certain menu actions for convoy forces to prevent invalid operations.
=> Fixed Force Removal Bug in TO&E, Fixed Convoy-Support Force Option Bug

MekHQ/data/scenariotemplates/Convoy Escort.xml, MekHQ/data/scenariotemplates/Critical Convoy Escort.xml, MekHQ/data/scenariotemplates/Emergency Convoy Defense.xml
Changed `contributesToBV` and `contributesToUnitCount` to `false` in `Critical Convoy Escort`, `Convoy Escort`, and `Emergency Convoy Defense` (NPC Convoys Only). This ensures these units do not affect battle value calculations or unit counting during scenarios.
This change was suggested by QA.
=> Updated Convoy Scenarios to Exclude BV and Unit Count Contribution for Convoy Units

MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
Previously, the "Undeploy Unit" hangar option was always enabled, regardless of the campaign's StratCon setting. Added logic to disable the menu item when the StratCon option is enabled. This is to remove the likelihood the user will run into a couple of squirrelly bugs related to deploy-undeploy behavior in StratCon.
=> Removed Remaining Instance of Undeploy Functionality when StratCon is Enabled

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
Implemented a new method to verify if parts are instances of `MotiveSystem` and included it in the resupply check logic. This ensures MotiveSystem components are not considered eligible for resupply.
=> Added Motive System Exclusion in Resupply Eligibility

MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Adjusted the spinner array size to account for correct CombatRole enumeration length. This resolved an off-by-one error that caused improper initialization.
Fixes #5461
=> Fixed Legacy AtB Battle Chance Spinner Array Indexing Bug

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
In its original form, the modified loop causes the following exception when the scenario is on any track but the first:
```
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.stratcon.StratconScenario.getPrimaryForceIDs()" because "stratconScenario" is null
at mekhq.campaign.mission.AtBDynamicScenarioFactory.setPlayerDeploymentTurns(AtBDynamicScenarioFactory.java:3652)
at mekhq.gui.BriefingTab.startScenario(BriefingTab.java:908)
```
I'm not sure if warning is the correct action if a primary force isn't found, or if it needs to be an exception.
=> Fix NPE when searching for primary force in Stratcon scenario generation

MekHQ/data/stratconfacilities/AlliedIndustrialFacility.xml, MekHQ/data/stratconfacilities/AlliedSupplyDepot.xml
`AlliedSupplyDepot` was incorrectly using `weeklySPModifier` instead of `monthlySPModifier` preventing monthly SP gain. (this is now addressed as part of #5472)
I also went ahead and added this benefit to `AlliedIndustrialFacility`, as these previously had no functionality.
Fixes #3639
Fixes #4036
=> Fixed Monthly Facility Support Point Gains & Added Functionality to Allied Industrial Facilities

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java
Added a default name "Resupply" for the Loot object in the `PerformResupply` class to improve clarity. This ensures loot from resupply missions is properly labeled, rather than inheriting the default loot name of "None'
=> Added Name for Resupply Loot

MekHQ/src/mekhq/campaign/mission/Scenario.java, MekHQ/src/mekhq/campaign/mission/ScenarioTemplate.java, MekHQ/src/mekhq/campaign/mission/enums/ScenarioType.java
This PR addresses an issue where MekHQ would 'forget' the value of `stratConScenarioType` on load, as well as failing to parse this value from the scenario template.
This was caused by multiple failure points, which this PR corrects.
=> Fixed Marshalling and Unmarshalling of `stratConScenarioType`

MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Added event triggering for all forces after modifying their status to ensure consistent updates. Adjusted the `refreshForceView` call position for better logical flow and UI updates.
This fixes a legacy bug that meant non-combat (support) forces were not being correctly removed from the list of Combat Teams if they were eligible to be a Combat Team _before_ receiving the Support designation.
=> Updated Force Refresh Logic in `TOEMouseAdapter`

MekHQ/src/mekhq/campaign/mission/enums/CombatRole.java, MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java
Updated `CombatRole` and `StratconScenario` to handle pre-50.02 data formats gracefully. Ensured backward compatibility by adding conversion logic and null checks where necessary.
Failure to include this resulted in some rather serious load bugs, so I'm going to be merging this immediately.
=> Added Compatibility Handlers for Legacy Save File Support

MekHQ/data/stratconcontractdefinitions/ExtractionRaid.xml, MekHQ/data/stratconcontractdefinitions/GuerillaWarfare.xml, MekHQ/data/stratconcontractdefinitions/ReconRaid.xml
Replaced various "VIP Capture" scenarios with "VIP Ambush" and other mission types in `ExtractionRaid`, `GuerillaWarfare`, and `ReconRaid` definitions. These scenarios were removed from general rotation, but apparently I forgot to clean them up.
Fixes #5500
=> Update contract scenarios to replace VIP Capture objectives

MekHQ/src/mekhq/campaign/Campaign.java
Removed a duplicated autoAwards trigger in day advance. This would have resulted in not insignificant slowdown when advancing to a new month, especially on very large campaigns. I suspect this was introduced by a bad merge.
While I was there, I also simplified variable usage and improved code readability in day advancement logic by replacing getter/setter calls with direct field access.
=> Fixed Duplicated autoAwards Trigger in New Day

MekHQ/src/mekhq/campaign/parts/AeroSensor.java, MekHQ/src/mekhq/campaign/parts/MissingAeroSensor.java
PR addresses this issue:
https://github.com/MegaMek/mekhq/issues/5480
Aerospace sensors for large spacecraft do not matter depending on tonnage. However small aerospace craft do. The shopping system doesn't take tonnage into account but our AcquisitionWork system did. This adjusts AcquisitionWork and part naming so that spacecraft sensors do not display arbitrary tonnages both internally to the code and externally in the warehouse. This prevents the continuous purchasing through the autologistics system as described in the issue. If there are other parts with this tonnage split within the code, I'd expect that they have the same bug and need to be fixed similarly, but I'm not sure if there are any more.
=> AutoLogistics fix for issue #5480

MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
PR addresses the issue [here](https://github.com/MegaMek/mekhq/issues/5479)
Requested stock values for parts in use were not properly saving on certain checkbox tick/untick or buying singular parts. I wasn't saving changes to the requested stock map during these changes and the refereshOverviewPartsInUse() method would reset their values. I've split the method in two, one that saves the stock map before and then continues, and one that doesn't. this is because we can't save the stock map on initialization or it messes everything up). I've also implemented a function that saves the requested stock for a singular part that has been implemented in refreshOverviewSpecificPart() to prevent singular part purchases in the menu from resetting that part's value.
=> Autologistics Fix for issue #5479

MekHQ/resources/mekhq/resources/AtBStratCon.properties, MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
Moved the logic for support point negotiation to a new `SupportPointNegotiation` class, organizing initial and monthly support point calculations. This improves code modularity, readability, and maintainability while simplifying related methods in `Campaign` and `StratconContractInitializer`.
This also corrects a major bug that was preventing contracts from beginning with a pool of starting Support Points.
=> Refactored Support Point Negotiation into a Dedicated Class; Fixed Initial Support Point Pool Bug

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignSummary.java
Replaced repetitive personnel filtering code with a new helper method `getActiveCombatPersonnel`.
Simplified logic for counting combat-capable and prisoner personnel, when determining Field Kitchen capacity.
Fixes #5517
=> Refactored Personnel Filtering Logic for Field Kitchens...Again

MekHQ/src/mekhq/AtBGameThread.java, MekHQ/src/mekhq/campaign/autoresolve/converter/SetupForces.java, MekHQ/src/mekhq/campaign/mission/AtBScenario.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/enums/CombatRole.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
Renamed 'isScouting' to 'isRecon' across various classes to improve terminology consistency with the 'RECON' combat role. Updated related comments, logic checks, and UI labels to reflect the new naming convention.
Fixed bug with scenarios occasionally spawning off the map when deploying a recon force on a Sector's edge.
Fixes #5519
=> Fixed Recon Scenario Spawn; Fixed Bugs Related to Role Name Changes

MekHQ/src/mekhq/campaign/personnel/education/TrainingCombatTeams.java
Added checks to prevent errors when no skills are available for training. Ensured that training actions are skipped when either educator or trainee skills are missing. This prevents a potential out-of-bounds exception.
We had an OoB reported on Discord, but not issue report logged. This is the only instance I could find that might cause the error. If/when the issue report is filed I can verify the issue is resolved and address it, if it isn't.
=> Fixed Training Logic to Handle Empty Skill Lists

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Added missing check to see whether a force is being deployed as reinforcements when excluding Auxiliaries as deployable forces. This bug prevented Auxiliaries from _ever_ being deployed.
=> Corrected Auxiliary Deployment Restrictions

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
Previously we used the map type of the target scenario when determining the interception scenario map type. So ground maps would have their reinforcements intercepted in a ground map.
Unfortunately, this failed to account for players reinforcing with unit types, for example reinforcing a ground map with ASF. This would result in the ASF being 'intercepted' by ground forces.
This PR corrects this oversight by tying interception scenario map type to the primary unit type of the reinforcing force.
=> Corrected Reinforcement Interception Map Type

MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml
Reduced the weight of artillery units in DropShip defense scenario templates.
Fixes #5535
=> Adjusted Force Role Weighting in DropShip Defense Scenario Templates

MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java, MekHQ/src/mekhq/gui/panes/CampaignOptionsPane.java
Removed the CAM_OPS item from the comboContractMarketMethod comboBox in CampaignOptionsPane. This option is not ready for general use and will be re-enabled once 50.01 has shipped.
Temporarily Disabled Preset Confirm in New Campaign Dialog. Customize preset is still available. This functionality was set up to enable easy testing of new features and is feature incomplete without the rest of Campaign Options IIC. Once 50.01 has shipped this option will be re-enabled.
=> Temporarily Disabled Non-Launch Ready Options

MekHQ/src/mekhq/campaign/mission/Scenario.java, MekHQ/src/mekhq/campaign/mission/enums/ScenarioType.java
Replaced `valueOf` with `parseFromString` in `ScenarioType` to enhance input validation and error handling. Included logging for parsing failures and ensured fallback to `NONE` for invalid inputs.
Fixes #5543
=> Refactored `ScenarioType` Parsing Logic

MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
Removed the entire `setUserPreferences` method, along with associated imports.
Storing preferences caused a lot of fragility with this system. It was very easy for a user to accidentally brick their Mass Training dialog by moving between different campaigns if those campaigns had different skill set ups. For example, if Campaign A had Piloting/Mek cap out at 8, while B had it cap out at 10. Moving from B to A could prevent the Mass Training dialog being used entirely if the user had their target level set to 9 or 10.
User preferences, in this instance, just stored the last known configuration for the Mass Training dialog. Given how few options there are - and the fact that it doesn't appear to have stored configurations on a per-skill basis - I opted to remove preferences entirely.
Fixes …
=> Remove User Preferences Handling from `BatchXPDialog`

MekHQ/src/mekhq/campaign/personnel/education/EducationController.java, MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java, MekHQ/src/mekhq/campaign/storyarc/storypoint/CreateCharacterStoryPoint.java, MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java
Following a Discord report that personnel were not spawning with education higher than `High School` I took the opportunity to review how we initialize education when spawning characters. I replaced duplicated logic with a centralized method and incorporated Intelligence (for players using random personalities). Now characters will more reliably spawn with education levels that better reflect their experience level.
=> Refactored Initial Education Logic

MekHQ/src/mekhq/campaign/market/contractMarket/AbstractContractMarket.java
Updated rating calculations to use distinct, modular methods for determining skill and quality modifiers based on factions, contract types, and historical context. Introduced clear, reusable logic for faction, contract type, and historical period modifiers. Documented all new methods with detailed JavaDocs for better maintainability and clarity.
It was highlighted on Discord that Clan OpFors frequently spawned with Green rating which didn't really match their MO. Looking through the modifiers I found that we weren't really factoring in a handful of variables and that Clan OpFors had an undesirably large chance of being Green - with the right modifiers.
After a thorough rebalancing of modifiers I also implemented clamping specific to the Clan faction. Clan factions will never spawn as the …
=> Refactored Ally and Enemy Rating Calculations for Contracts

MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
Fixed a new day blocker bug in the command center report created when negotiating new support points. We were incorrectly pulling the wrong report, and were firing the report even when there were no active contracts.
=> Fixed Support Point Negotiation Report

MekHQ/data/universe/academies/Unit Education.xml
Added three new in-house training academies: NCO Bootcamp, Warrant Officer Bootcamp, and Officer Bootcamp. These were conspicuous in their absence.
=> Added Missing in-House Bootcamps for NCOs, Warrant Officers, and Officers

MekHQ/src/mekhq/gui/dialog/nagDialogs/DeploymentShortfallNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/EndContractNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechTimeNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientMedicsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InvalidFactionNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NoCommanderNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/OutstandingScenariosNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/PregnantCombatantNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/PrisonersNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UnableToAffordExpensesNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UnableToAffordJumpNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UnableToAffordLoanPaymentNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UnmaintainedUnitsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UnresolvedStratConContactsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UntreatedPersonnelNagDialog.java
We ran into an issue where nag dialogs were tanking new day perform. This was caused by a few factors, but predominantly due to the number of JDialogs we were creating on new day. This PR updates the nags and nag controller so that we only initialize a nag JDialog if we intend to use it.
=> Refactored Nag Dialog Checks to Improve Performance

MekHQ/src/mekhq/campaign/unit/CargoStatistics.java
What it says in the title. Some spare parts in this particular warehouse have a "NaN" tonnage value ("0-shot inferno rounds"? lol), which was causing the total cargo tonnage to go to NaN, which prevented game loading.
Fix #5572
=> don't attempt to sum NaN tonnage equipment

MekHQ/src/mekhq/MekHQ.java
Replaced direct theme retrieval from preferences with `selectedTheme`. This ensures that the look and feel updates correctly based on the current theme selection.
Fix #5188, #5410
=> Corrected GUI Theme Retrieval to Use `selectedTheme`

MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
Added a null check for `StratconCampaignState` in `ScenarioTableModel` to prevent potential null pointer exceptions. This ensures more robust handling of scenarios without an associated campaign state.
Fix #5584
=> Fixed NPE in `ScenarioTableModel`

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
AtB Bonus Events could sometimes trigger a resupply, which created a lot of confusion as users would end a month; get their normal resupply, then get a second seemingly out of nowhere.
Now only post-scenario bonus events can trigger a resupply. Normal, monthly, events give 1 SP instead.
Also expended a few other options so that if users had certain settings enabled they would still get a bonus.
=> Adjusted AtB Bonus Events

MekHQ/src/mekhq/MekHQ.java
Replaced the default value for the selected UI theme with an empty string. This ensures we replace it with Dracula further down the pipeline. This is also the reason why prior attempts to set a default theme didn't work correctly. We were looking for an empty string, instead of a default value.
Fix #5609
=> Corrected Default Theme to Empty String

MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
Previously, the distance label was added for all contract types, which was incorrect as non-AtB Contracts do not track system. This change ensures it is only displayed for AtB contracts.
=> Restrict Distance Label to AtB Contracts Only

MekHQ/src/mekhq/MekHQ.java, MekHQ/src/mekhq/campaign/handler/PostScenarioDialogHandler.java
Replaced `AtBScenario` references with the generic `Scenario` class to enhance code flexibility and maintainability. Updated relevant method signatures and calls to align with the new parameter type. Simplified and cleaned up related code.
Fix #5615
=> Refactored `PostScenarioDialogHandler` to use Generic `Scenario`

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/src/mekhq/campaign/Campaign.java
Two really small changes here that fix two things that are just some dumb mistakes I made.
1) The weekly stock update text was surrounded by quotations, these have been removed
2) adding to the 'bought' local variable on the stockUpPartsInUse function has been properly nested, it was previously reporting every part, regardless of if it was being bought, as a kind of part that was understocked.
=> Autologistics Reporting fixes

MekHQ/data/stratconfacilities/AlliedDataCenter.xml, MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java, MekHQ/src/mekhq/gui/StratconPanel.java
Replaced the "track reveal" mechanic with a new "scan range" system, allowing facilities and units to extend the area they can reveal. Updated all relevant classes, methods, and XML definitions to reflect this change.
This change was made to reduce the effectiveness of Allied Data Centers. In prior versions the presence of a single Data Center completely removed the scouting stage from a contract for an entire Sector.
Now for each Allied Data Center present in the Sector the player's scan range will be increased by 1. This means, with a single Data Center the sight range of Patrol Forces will be increased from 1 to 2. While other combat roles will have their sight range increased from 0 to 1. The effectiveness of Allied Data centers stack. So a Patrol force, supported by two Data Centers, …
=> Updated StratCon Data Center to Increase Scan Range Instead of Sector Reveal

MekHQ/src/mekhq/gui/FinancesTab.java
=> feat: add sortable columns in the finance tab, addresses issue #4876

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/GenerateResupplyContents.java
Resupplies were incorrectly using sell value for both resupply cost and resupply evaluation. This made it seem like resupplies were a much worse value proposition than they actually are.
=> Fixed Value Display in Resupplies

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/ResupplyUtilities.java
Integral value cast to double and then passed to Math.ceil This code converts an integral value (e.g., int or long) to a double precision floating point number and then passing the result to the Math.ceil() function, which rounds a double to the next higher integer value. This operation should always be a no-op, since converting an integer to a double should give a number with no fractional part. It is likely that the operation that generated the value to be passed to Math.ceil was intended to be performed using double precision floating point arithmetic.
Bug kind and pattern: ICAST - ICAST_INT_CAST_TO_DOUBLE_PASSED_TO_CEIL
Found via [SpotBugs](https://spotbugs.readthedocs.io/en/stable/index.html)
=> bug: address potential int and double issue from SpotBugs

MekHQ/src/mekhq/campaign/market/PartsStore.java
Do not use floating-point variables as loop counters
Using floating-point variables should not be used as loop counters, as they are not precise, which may result in incorrect loops. A loop counter is a variable that is changed with each iteration and controls when the loop should terminate. It is decreased or increased by a fixed amount each iteration.
See rule NUM09-J.
Bug kind and pattern: FL - FL_FLOATS_AS_LOOP_COUNTERS
Found via [SpotBugs](https://spotbugs.readthedocs.io/en/stable/index.html)
Also has a few other cleanups like consistency with doubles (don't use `f`) and an unneeded conditional check for modulus.
=> fix: don't use floats in for loops

MekHQ/resources/mekhq/resources/MekLabTab.properties, MekHQ/src/mekhq/gui/MekLabTab.java
This PR aims to add the ability to save a prospective refit configuration from the MekLab tab within MekHQ, per RFE #5604 
Testing:
- Created several refit configs, saved them, and then applied them via the Hangar menu.
Close #5604 
NOTE: tests will continue failing until [this](https://github.com/MegaMek/megameklab/pull/1678) MML PR is merged.
=> RFE 5604: save refit config from MHQ MekLab tab

MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java, MekHQ/src/mekhq/campaign/stratcon/StratconTrackState.java, MekHQ/src/mekhq/gui/StratconPanel.java
Restored the `revealTrack` property in facilities and integrated it into the StratCon logic to determine visibility. Restored drawing and visibility checks accordingly to account for facilities that enable track-wide reveals.
This ensures we have two facility modifiers relating to hex reveal: Scan Range (which increases line of sight), and Reveal Track (which reveals the whole Sector). The latter is not currently used by any Facilities, but might be useful for player custom facilities.
=> Restored Logic for Facilities to Reveal StratCon Tracks

MekHQ/src/mekhq/gui/BriefingTab.java
Previously, the auto-resolve button was always enabled based on the `canStartGame` flag. This change ensures it is only enabled if the scenario is an `AtBScenario`. Running ACAR on a non-AtB Scenario results in Class Cast Errors.
Posting this PR as a suggested edit, assuming Luana hasn't got plans to expand ACAR to non-AtB Scenarios. If she does, then this can act as a temporary solution until her edits go live.
=> Enable Auto-Resolve Button Conditionally for AtB Scenarios

MekHQ/data/scenariomodifiers/LiaisonGround.xml, MekHQ/resources/mekhq/resources/ContractMarketDialog.properties, MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
Could someone please double-check the "Command Rights" text?
Helps with user-experience (UX) and usability.
=> feat: adds some helpful tooltips for contracts

MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Previously, `selectionCountLabel` retained a negative font color even when selections were valid. This update resets the font color to its default state to ensure proper visual feedback for users.
Fix #5662
=> Restore Default Font Color when Leadership Selection Valid

MekHQ/data/scenariomodifiers/airBattleModifiers.xml, MekHQ/data/scenariomodifiers/groundBattleModifiers.xml, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Removed hardcoded chance for 'primary allies air' and 'primary allies ground' to be attached to a scenario.
- Added these modifiers to the standard array of modifiers that can spawn for air/ground scenarios.
Previously users were unhappy that these scenario modifiers artificially increased the size of scenarios, so it was decided to remove the BV contribution of these modifiers. Then, much later, players voice concern that other 'good' modifiers were actually making a scenario harder. So the contribution of those modifiers were also removed. Each removal was sound in isolation, however when combined it results in as much as a 50% chance (per scenario) for the scenario to become unbalanced as the result of these two modifiers, as these were hardcoded so could always spawn. By adding …
=> Removed Hardcoded Primary Ally Modifier Chances

MekHQ/src/mekhq/campaign/unit/Unit.java
- Included Refrigerated, and Insulated cargo bays in the capacity calculation.
- Updated coverage for misc capacity by using `Mounted` rather than string comparison. This should make it a lot more durable to change. This should fix #5648, however as that appears to be a localization issue I cannot be certain.
- Updated calculations to better account for damaged and location destruction.
=> Expanded and Fixed Cargo Capacity Logic

MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java
- Increased the range of potential special unit roles from 2 to 6, adding CIVILIAN and CARGO roles.
- A special unit still has a 1:2 chance of being Artillery.
=> Expand Special Unit Generation in AtB Unit Market

MekHQ/resources/mekhq/resources/Resupply.properties, MekHQ/src/mekhq/campaign/market/procurement/Procurement.java, MekHQ/src/mekhq/campaign/mission/Loot.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/GenerateResupplyContents.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/ResupplyUtilities.java, MekHQ/src/mekhq/gui/view/MissionViewPanel.java
**Code**
- Fixed weight calculations for armor and ammo.
- Ammo is now delivered in 1t blocks, not 5t. Armor is still 5t.
- Fixed warehouse parsing so that items have their weight correctly reduced based on items already in the warehouse. This particularly affects ammo, which were previously always being considered as having 0 rounds spare.
- Corrected early exit for Routed morale that would previously delivery convoys twice.
**GUI**
- Corrected typo in Resupply briefing.
- Adjusted estimated cargo requirements to incorporate a minimum of 6t (as a resupply cannot normally be less than the sum of a single ammo and armor block).
- Added indicator to Briefing Room that resupply weight may exceed estimate.
Fix #5668, #5640
=> Multiple Resupply Bug Fixes

MekHQ/src/mekhq/campaign/event/PersonCrewAssignmentEvent.java, MekHQ/src/mekhq/campaign/unit/Unit.java
- Updated `PersonCrewAssignmentEvent` to update the commander data of any associated forces.
- Replaced instances of single letter variables in affected methods.
Fix #5681
=> Refactored Crew Assignment Event Handling

MekHQ/resources/mekhq/resources/ContractViewPanel.properties, MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java, MekHQ/src/mekhq/gui/view/MissionViewPanel.java
- Changed the special handler that causes some contract types to start at 'Routed' to only apply to Garrison contracts. Rather than all Garrison-_type_ contracts.
- Updated 'Peaceful' morale level to include clearer tooltips.
- Added the ability for reinforcements on Garrison-Type contracts to arrive with morale between Stalemate and Overwhelming.
- Added the possibility for reinforcements on Garrison-type contracts to arrive with a substantially spiked scenario chance, representing a more substantial attack.
- Added early contract end to Riot Duty contracts. Once the riots have been quelled these contracts will end, rather than essentially becoming Garrison Duty contracts by another name.
Fix #5689
=> Added Potential Difficulty Spikes to Garrison-Type Contracts

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
- Stopped scenarios regenerating when reinforcements were applied.
- Stopped Patrol forces failing to generate scenarios if they land on top of an enemy facility
- Cleaned up some leftover code from prior to 50.02
- Ensured scenario objective time limits are recalculated when recalculating objectives
Fix #5636, #5697, #5603
=> Fixed Multiple StratCon Bugs

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Scenario generation was treated artillery formations as if they did not use weight classes, resulting in generation failing due to an illegal weight class of -1.
- Changed artillery formations to now be treated like any other formation, allowing for unit substitution in instances where generation fails.
- Changed generation failure messaging to cite weight class integer, not name. This means that if we ever try passing an illegal weight class we will be able to see exactly what was passed, rather than getting an `IllegalArgumentException`
Fix #5694
=> Corrected Weight Class Initialization of Artillery Units

MekHQ/src/mekhq/campaign/Campaign.java
- Replaced "replay" with "repay" in the text describing payment overages during a contract.
Fix #5688
=> Fixed Typo in Payment Overages Message

MekHQ/src/mekhq/campaign/market/PersonnelMarket.java
- Simplified and modularized personnel market logic by adding a dedicated report generation method and improving clarity in personnel filtering conditions.
- Changed 'is capital' check to use the same logic as the Interstellar map. This is both cheaper and more reliable than the previous method.
- Corrected absence of 'is on planet' check. This was always intended, but got removed/forgotten at some point.
Fix #5705
=> Refactored Personnel Market Generation & Fixed Capital/Hiring Hall Checks

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Added missing isDeployed check to `getAvailableForceIDs` (first overload).
- Removed isDeployed check from `getAvailableForceIDs` (second overload). This will prevent Patrol forces from being over-emphasized as seed forces.
- Moved isDeployed check to 'generate weekly scenarios' so that only Integrated contracts care if a force has already been deployed. For all other contract command rights we're just using this information for the purposes of seeding the scenario, so whether the force is deployed or not is irrelevant.
=> Corrected Available Force Check

MekHQ/resources/mekhq/resources/AtBStratCon.properties, MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
- Added a soft cap to Support Points, where Administrators will not add new Support Points (during weekly generation) if Support Points already meet or exceed the number of required forces for the Contract. We received feedback that Support Points were a bit generous, under the current implementation, because the user could just stockpile them indefinitely.
=> Added a Soft Cap to Support Point Generation

MekHQ/src/mekhq/campaign/Campaign.java
- Replaced getLocalDate() with currentDay for consistency and clarity in date handling logic.
- Fixed maternity leave eligibility check to check if maternity leave due date is _after_ the current date and not equal.
This bug was caused by us only checking whether a character is eligible for Maternity Leave once a week, combined with us only checking whether that specific Monday is equal to 20 weeks prior to birth date. Essentially, unless a character was due to give birth on a Monday they would never go on maternity leave.
Fix #5570
=> Fixed Maternity Leave Date Handling

MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
fix: compilation error due to a function being set as static but acessing instance data
=> fix: compilation error due to a function being set as static but acessing instance data

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
- Restricted Clan items to only appear in Resupplies if the employing faction is Clan or the resupply is after the Battle of Tukayyid.
- Restricted Clan items to only appear in Resupplies if the purchase of Clan parts is enabled in Campaign Options
- Restricted Inner Sphere items to only appear in Resupplies if the purchase of Inner Sphere parts is enabled in Campaign Options.
Fix #5746
=> Added Clan and Inner Sphere Resupply Restrictions

MekHQ/src/mekhq/campaign/personnel/education/EducationController.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
- Simplified and clarified tag-along logic for dependents during education journeys.
- Refactored child processing, accounted for active spouses as dependents, and streamlined status checks.
Fix #5766
Fix #5769
=> Refactored Education Tag-Along Logic

MekHQ/src/mekhq/campaign/force/CombatTeam.java
- Adjusted validations to prevent assigning combat team status to convoy forces and non-combat forces.
Fix #5760
=> Fixed Combat Team Status Logic for Convoy and Support Forces

MekHQ/resources/mekhq/resources/ScenarioTableModel.properties, MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
- Revised the scenario table model to append Stratcon coordinates to the track display name when available.
- Also updated the column header text from "Sector" to "Grid Reference" now that it's showing the full grid reference and not just sector
This was suggested by @Scoppio and will help debugging ghost scenarios.
=> Update Sector Display in Briefing Room to Show Full Grid Reference

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Reduced track width and height by one to account for zero-based indexing in coordinate calculations.
Fix #5779
=> Adjust Bounds Calculation in `getUnoccupiedAdjacentCoords`

MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
- Adjusted logic to ensure objective translations and scaling occur only when a Primary Force is assigned. This prevents improper processing of scenario objectives.
Fix #5779
=> Corrected Objective Calculations when Assigning Forces to StratCon Scenarios

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java, MekHQ/unittests/mekhq/campaign/personnel/procreation/AbstractProcreationTest.java
- Moved maternity leave handler into procreation weekly activity.
- Cleared up the handling of going _on_ or returning _from_ maternity leave.
Fix #5714 (tentative)
=> Fixed Maternity Leave... yet again

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
- Set `forceCommanderID` to `null` when no eligible commanders exist, ensuring valid leadership.
- Updated force commander assignment during campaign load to prevent invalid leadership issues.
- Added `overrideForceCommanderID` to XML read/write methods for better persistence.
Fix #5716
=> Fixed Force Commander Handling and Improve XML Persistence.

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Added support for calculating and storing routed payouts when AtB contracts end due to the enemy being routed.
- Updated XML serialization and deserialization to include routed payout data.
When the enemy is routed, for non-Garrison Type contracts, we change the contract end date. This resulted in players being shortchanged payouts. This PR adds tracking so that we know how much the player was due at the pre-rout contract conclusion. Then, when making a contract conclusion payout we ignore the calculated value and use the pre-stored value (where relevant). This allows us to shorten the contract, due to rout early finish, without truncating the users' payout.
Fix #5727
=> Fixed Routed Contracts Resulting in Truncated Payouts

MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
- Replaced the use of `negotiatedSupportPoints` with `maxSupportPoints` to ensure the correct value is displayed in messages. 
Fix #5726
=> Fix Support Point Acquisition Visual Bug

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Removed redundant `Person` parameter in `canPerformRole`.
- Removed 'must be Green' expertise requirement from Tech roles -- I could have sworn I removed this before, but apparently not. So, removing it here. This ensures these roles are treated like all others, none of which require minimum expertise.
- Fixed a very long standing bug where, when assigning personnel to roles, we only checked the eligibility of the first selected character and then assumed all other characters' eligibility matched theirs. Now we correctly check the eligibility of all selected characters.
- Added sanitizers to ensure all personnel are eligible for their assigned roles, on load, and unassigning them if they're not.
Fix #5740, Fix #5580
=> Fixed Role Eligibility Checks and Ensured Proper Role Assignment

MekHQ/src/mekhq/campaign/personnel/generator/AbstractPersonnelGenerator.java
- Updated the birthday generation logic to ensure accurate age calculation based on experience level and affiliation.
- Constrained random date selection to always occur on or before the current campaign date.
This should address an edge case where under specific circumstances characters could generate with an age 1 year younger than intended.
=> Corrected Birthday Generation for Personnel

MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/OutstandingScenariosNagLogic.java
- Added a null date check to prevent further processing of scenarios with null dates (such as uninitialized scenarios in StratCon).
Fix #5770
=> Added `null` Protection to `OutstandingScenariosNagLogic` for Outstanding Scenario Nags

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/atb/scenario/BaseAttackBuiltInScenario.java, MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java, MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
- Replaced `getRequiredLanceRole` with `getRequiredCombatRole` across the code to better align naming with functionality.
- Swapped 'Maneuver' and 'Frontline' combat role requirements to better match their current implementation.
- This change will affect both StratCon and AtB campaigns.
=> Updated Contract Role Requirements

MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java, MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
Fixes #5777 
Fixed both the menus for assigning people to units to support QuadMeks/Vees better.
=> Issue 5777: QuadMeks (and QuadVees) that use Gunner & Pilot can be crewed

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/src/mekhq/campaign/Campaign.java
- Added logic to deduct Combat Victory Points (CVPs) for unmet StratCon deployment requirements.
- Updated user feedback to include a report for this specific breach scenario.
This CVP loss will only occur if the user begins a week with fewer than required assigned Combat Teams.
Fix #5750
=> Added Contract Breach CVP Penalties to StratCon Contracts

MekHQ/src/mekhq/campaign/Campaign.java
=> MegaMek Issue 6416: Ghostbusting - Reset isDestroyed for entities when returning to MekHQ

MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Replaced explicit `Math` method calls with static imports for consistency and readability.
- Added morale spike logic during contract extensions to adjust difficulty dynamically, aligning with narrative intent.
Fix #5801
=> Added Enemy Morale Spike to Justify Contract Extension Clause

MekHQ/src/mekhq/gui/StratconPanel.java
- Replaced deployment date check with a `coordsRevealed` flag. This ensures proper control over when scenario info is displayed.
Fix #5800
=> Corrected Scenario info Visibility Logic in `StratconPanel`

MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java
- Modified hostile and allied BV display to handle cases where both values are zero by showing "UNKNOWN."
Previously these would show as `0` which, while correct, gave the impression of a bug where there was none.
=> Refactored BV Display Logic in `StratconScenario.java`

MekHQ/src/mekhq/campaign/mission/Loot.java
- Implemented null protection for units and parts to address a known issue in the deprecated Legacy AtB.
As Legacy AtB is deprecated, and the special scenarios that have this issue have been removed from StratCon, I opted not to resolve the root cause of this bug, but to add `null` protections so the writing process would gracefully fail in the event the bug was triggered.
Fix #5745
=> Added `null` Protection to Loot Saving

MekHQ/src/mekhq/AtBGameThread.java, MekHQ/src/mekhq/gui/dialog/AutoResolveBehaviorSettingsDialog.java
```java
// Commands should be sent in this format:
// <botName>: <command> : <arguments>
StringTokenizer tokenizer = new StringTokenizer(chatEvent.getMessage(), ":");
```
Princess ACAR makes an AI with the template `%s:AI`... so... if I send a message for the AI to flee, it is going to send:
`player:ai: fl : 4` it will receive it as `player, ai, fl, 4` and respond with "nah... I dont know what that means.
This changes the name of the bot from `%s:AI` to `%s@AI`
=> fix: due to how things work the ai player cant have : in its name

MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/InsufficientAstechTimeNagLogic.java
Fixes #5724
Implemented a proper method for checking if a unit is being actively maintained. The "isUnmaintained()" method should not be used for these purposes, such an approach gives incorrect results for units that do not require maintenance - for example, mothballed Mechs.
=> [Issue 5724] Fix astech time calculations for units that do not require maintenance

MekHQ/src/mekhq/campaign/utilities/CampaignTransportUtilities.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Fixes #5818 
This fixes a bug with the new MekHQ transporters. 
@UlyssesSockdrawer on Discord observed that infantry **squads** were unable to load into a 3 ton infantry compartment, and that when right-clicking on a "force" it was improperly showing unassign from transport (& it didn't work).
- Infantry loaded into a compartment will use the correct weight
- Right clicking a force has the correct assign/unassign transport options
=> Issue 5818: Fixed assigning/unassigning transports from TOE at the Force level & infantry compartments use the correct weight for infantry squads

MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- Reversed the comparison operator to correctly determine if a character flunked based on the pass rate. This ensures the education evaluation uses the intended logic for pass/fail decisions.
Fix #5761
=> Fixed Incorrect Pass/Fail Logic in Initial Education Evaluation

MekHQ/src/mekhq/gui/StratconPanel.java
- Adjusted condition to ensure uncloaked scenarios are properly handled. Scenario info is now displayed if coordinates are revealed, the scenario is not cloaked, or the GM has revealed it.
Fix #5826
=> Fixed Scenario Info Display for Uncloaked Scenarios

MekHQ/src/mekhq/gui/baseComponents/MHQDialogImmersive.java, MekHQ/src/mekhq/gui/dialog/CampaignHasProblemOnLoad.java
- Replaced the minimal constructor for `MHQDialogImmersive` with the full constructor to simplify code maintenance and reduce redundancy.
This was causing a major bug that prevented saves from prior to 50.03 being loaded at all.
=> Corrected `MHQDialogImmersive` Constructor Usage

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/market/contractMarket/ContractAutomation.java, MekHQ/src/mekhq/campaign/personnel/education/EducationController.java
- Expanded unit removal to also remove the unit from the list of automatically mothballed units.
- Added `null` checks to ensure compatibility with <50.03 saves. This will self-sanitize the first time the campaign is saved in 50.03
Fix #5831
=> Added `null` Protection for Units Involved in Automated Mothballing

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/personnel/education/TrainingCombatTeams.java, MekHQ/src/mekhq/gui/ForceRenderer.java
Fixes #5836 
A CombatForce should have its commander updated when its force's commander is updated. In addition, to fix broken saves, we'll refresh the CombatForce's commander when doing training.
=> Issue 5836: Combat Force commanders should be updated when a Force's Commander is updated.

MekHQ/src/mekhq/campaign/CampaignOptions.java
- Modified the isUseAtB method to return true if useStratCon is enabled.
This change was made a little while ago, but got overwritten at some point (probably by CO IIC). I checked `getAtBBattleChance` which had a similar change to account for StratCon and that change hasn't been overwritten.
Fix #5841
=> Corrected `isUseAtB` to account for `useStratCon`

MekHQ/src/mekhq/campaign/personnel/education/EducationController.java, MekHQ/src/mekhq/campaign/universe/StarUtil.java
- Implemented a method to estimate a star's radius using luminosity and temperature based on the Stefan-Boltzmann law. - Added a utility function to calculate the spectral type number by combining the spectral class and subclass.
These are leftovers from an aborted attempt to more realistically (visually) model solar systems within mhq. As I can see these methods being useful in the future, I opted to push them as a utility change.
=> Added Methods for Star Radius Estimation and Spectral Type Parsing

MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Added a cleanup step to remove invalid characters before parsing, ensuring robust handling of input and preventing potential crashes or incorrect values. Previously, non-numeric characters in routedPayout caused parsing errors.
=> Fixed Parsing of `routedPayout` to Handle Non-Numeric Characters

MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
- Replaced `JTextArea` with `JEditorPane` for `txtRewards` to support HTML rendering.
Fix #5840
=> Refactored Loot Preview to Use `JEditorPane` not `JTextArea`

MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java
Fixes #5810 
In some cases the assignment of variables for "usePeacetimeCost" was mixed up with "showPeacetimeCost". As a result, the checkbox for using peacetime costs in the settings was effectively overriden by the checkbox for logging peacetime costs.
Users whose campaigns were affected by the bug would need to turn on the peacetime costs after the fix, since their campaign settings are currently saved as having that feature disabled (and not displayed that way).
=> [Issue 5810] Fix peacetime operating cost settings

LICENSE.txt
Per the README, the license is GPLv3.  This adds the file which appeared to be missing.
=> chore: add GPLv3 license file

MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Fixes #5828 
It looks like this bug also impacts turrets, so this should also let the player claim kills on turrets.
=> Issue 5828: Kill Credits for killed but not totally destroyed turrets & dropships

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java, MekHQ/src/mekhq/gui/campaignOptions/contents/AbilitiesTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/EquipmentAndSuppliesTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/MarketsTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/RulesetsTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/SkillsTab.java
- Updated the logic for handling AtB and StratCon compatibility, ensuring proper selection behavior.
- Fixed disallowing Clan parts usage from IS sources, fixing a duplicate line.
- Corrected and completed financial year duration configuration in the finances tab.
Fix #5860
=> Fixed Loading & Saving of Some Campaign Options

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/gui/campaignOptions/contents/RelationshipsTab.java
- Updated tooltips for random clan and prisoner death to correctly describe their functions.
- Fixed the spinner tooltip for random new dependent marriages.
Fix #5862
Fix #5857
=> Fixed Incorrect Tooltips

MekHQ/src/mekhq/campaign/personnel/Person.java
- Eliminated a logger statement in the `removeUnusedEdgeTriggers` method as it served no functional purpose. This helps reduce unnecessary log noise.
This was added while debugging edge triggers back in 50.01 and I accidentally forgot to remove it afterwards.
=> Remove Unnecessary Edge Trigger Logging

MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- Triggered an `OrganizationChangedEvent` for each remaining force following the removal of any forces. This prevents a visual bug where forces seemingly remain post-removal.
Fix #5817
=> Fixed Force Updates after Removal in `TOEMouseAdapter`

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Implemented a feature allowing GMs to add random special abilities (SPA) to selected personnel via the right-click personnel menu.
Fix #5718
=> Added GM Option to Assign Random SPAs

MekHQ/src/mekhq/gui/CampaignGUI.java
- Removed the window size initialization code implemented by #5812 as this was causing mhq to open in a window rather than maximized. This does not affect any of the other functionality or changes implemented in #5812.
Discussed with Luana and she advised to just remove it rather than exploring other options.
=> Rolled Back Window Size Setting

MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Adjusted the logic for Internal Dissension events to account for StratCon-enabled campaigns.
- Added a support point penalty if StratCon is active, while maintaining the original behavior for non-StratCon campaigns.
This ensures _all_ AtB Special Scenarios will not spawn for StratCon enabled campaigns.
=> Replaced Internal Dissension Events in StratCon

MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Simplified morale roll outcomes by consolidating default cases.
- Updated contract type checks to better handle Relief Duty contracts.
- Ensured only Garrison Duty contracts changed the OpFor faction when ending a rout. This will stop Rebel OpFors suddenly turning into Clan OpFors on Security Duty and similar contracts.
Fix #5885
=> Corrected Morale Logic and Contract Type Checks

MekHQ/data/images/hexes/minimap/cyberpunk.theme, MekHQ/data/images/hexes/minimap/darkula.theme, MekHQ/data/images/hexes/minimap/defaultminimap.theme, MekHQ/data/images/hexes/minimap/dreamy colors.theme, MekHQ/data/images/hexes/minimap/earth and grass.theme, MekHQ/data/images/hexes/minimap/gbc green.theme, MekHQ/data/images/hexes/minimap/noctis.theme, MekHQ/data/images/hexes/minimap/non-boolean.theme, MekHQ/data/images/hexes/minimap/phosphor green.theme, MekHQ/data/images/hexes/minimap/pink lemonade.theme, MekHQ/data/images/hexes/minimap/pink world.theme, MekHQ/data/images/hexes/minimap/rebirth.theme, MekHQ/data/images/hexes/minimap/red amaranth.theme, MekHQ/data/images/hexes/minimap/shades of green.theme, MekHQ/data/images/hexes/minimap/solarized.theme, MekHQ/data/images/hexes/minimap/synthwave.theme, MekHQ/data/images/hexes/minimap/wood cabin.theme, MekHQ/data/images/hexes/minimap/zone of battle.theme
Just a bunch of minimaps, the same found on MM, but on MekHQ so it does not explode when you play MM from it.
=> feat: missing minimaps for MekHQ

MekHQ/src/mekhq/Utilities.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/education/EducationController.java, MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java, MekHQ/unittests/mekhq/campaign/personnel/marriage/AbstractMarriageTest.java, MekHQ/unittests/mekhq/campaign/personnel/procreation/AbstractProcreationTest.java
- Updated methods and test cases to consistently use `isChild` with an 18-year-old threshold override where required.
- Clarified project policies on age restrictions for marriage, procreation, and academy-related events.
- Improved readability and maintainability of `canMarry` and 'canProcreate'.
- Rewrote `canMarry` and `canProcreate` Unit Tests
Mid-2024 we settled on a policy of 18+ for marriage, procreation, and roles. This was to cut back on the child soldier problem that had been in mhq since ages were introduced. There were other reasons, but that's the main one. Since then, we've received feedback to reduce the strictness specifically for Roles, given how many 16 year old pilots and such there are in the lore.
After discussing it with Hammer we opted to update the policy so that …
=> Refactored Age Checks; Updated Unit Tests for Procreation and Marriage

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Edge purchases were not correctly factoring in cost modifiers when deducting xp. They do now.
Fix #5883
=> Corrected Edge Cost Calculations

MekHQ/resources/mekhq/resources/AtBDynamicScenarioFactory.properties, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Enhanced logging for bidding and force budget adjustments, including Clan-specific handling and Batchall refusal messages.
- Ensured proper fallback handling for empty forces and set fixed entity lists for generated forces.
- Fixed verbose bidding so that the first two units wouldn't be on the same line.
- Adjusted Clan force generation so that we don't cull units, prior to bidding. This ensures we're not, effectively, double handling everything for minimal benefit. This also has the added benefit of making refusing a Batchall even deadlier (and consequently more rewarding for the brave and foolhardy both).
- Fixed Clan force generation so that units bid away are actually removed from the force.
#5882
So it turned out the Clans were bidding away units, and then fielding them anyway. …
=> Fixed Clan Bidding

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Adjusted pay multiplier for required lances to better handle both large and small campaigns. Previously we were overcompensating large campaigns.
- Adjusted pay multiplier for difficulty.
- Adjusted how required lances and difficulty multipliers were applied to the overall base pay multiplier so that we're less likely to spike contract pay.
- Added clearer JavaDocs to `calculateContractDifficulty` so developers are aware it can, on occasion, return a value outside of the expected 1-10 bounds. Fix #5898
These changes ensure required lances and difficulty (if FG3 is enabled) properly impact contract pay.
=> Fixed Negative Contract Base Pay

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Ensured generated units have at least 1 walk movement point, preventing immobile units like trailers from being selected.
Fix #5886
=> Added Movement Filter to Entity Generation Logic

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Introduced a helper method to handle weight class bypass logic based on specific mission roles, ensuring better unit generation outcomes in constrained scenarios.
- Replaced fully qualified `MissionRole` enum references with direct imports to simplify code and improve readability.
Fix #5823
=> Added Weight Bypass Based on Role

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
- Fixed the generated number of Combat Teams to be applied to the follow up contract and _not_ the contract just concluded.
- Fixed the generated base pay multiplier to be applied to the follow up contract and _not_ the contract just concluded.
- Adjusted the order of operations to match `generateAtBContract` to fix Renegotiate bug. I don't quite know _why_ this fixed it, but matching the order between the two methods _did_. So, progress...?
- Added JavaDocs to `addFollowup`
Fix #5811
=> Fixed Multiple Follow-up Contract Bugs

MekHQ/src/mekhq/campaign/parts/PartInUse.java, MekHQ/src/mekhq/campaign/parts/equipment/HeatSink.java
Fixes #5799 
IS and Clan Double Heat Sinks have the exact same name, how confusing! This adds "details" to Double Heat Sinks (only) that is the heat sink's tech base (Clan or IS). 
I also found commas in the parts in use was broken - it would cut off details in parenthesis after the first comma. I tweaked it some to hopefully work how the the last dev wanted.
=> Issue 5799: Differentiating between IS & Clan DHS & unbreaking commas in Parts in use

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Enhanced `AtBContract` bonus unit generation with a fallback mechanism to retry creation if the initial attempt fails.
- Improved error handling in `getTankEntity` by checking for null roles and logging more informative messages.
Fix #5910
=> Added Fallback for AtB Bonus Unit Creation.

MekHQ/data/scenariotemplates/Emergency Convoy Defense - Player - VTOL.xml, MekHQ/data/scenariotemplates/Emergency Convoy Defense - Player.xml
- Moved the `ANTI_AIRCRAFT` force role from the `Emergency Convoy Defense - Player` template to the `Emergency Convoy Defense - Player - VTOL` template. This ensures alignment of role assignments with the intended scenario design.
=> Fixed Unit Role configuration in Resupply Scenario Templates

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
- Reorganized the employer multiplier logic to match CamOps.
- Fixed a bug where we were using the full Reputation Rating and _not_ Reputation _Modifier_.
- Refactored difficulty modifier by ensuring calculations only occur for positive difficulty values. This likely wouldn't have changed anything, but it's cleaner so better.
Fix #5934
=> Fixed Contract Multiplier Again

MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java
- Replaced the use of a reversible quality naming option with a fixed label naming behavior.
Fix #5921
=> Fixed Used Parts Multiplier Labels to Ignore Quality Reversal in Finances Tab

MekHQ/src/mekhq/gui/model/UnitTableModel.java
Previously, infantry units did not specifically track soldier assignments and requirements. This update introduces logic to account for soldiers needed and assigned, ensuring accurate reporting for infantry units in the personnel report. Other behaviors remain unchanged.
Fix #5917
=> Added Soldier Requirements Handling in `UnitTableModel`

MekHQ/src/mekhq/campaign/Quartermaster.java
- Removed a call to `setBrandNew(false)` when adding parts to the campaign. This boolean already initializes as `false`, so including it here just meant we were overwriting any instance where we set brand new to `true`.
=> Fixed Overwriting of 'Brand New' Part State

MekHQ/resources/mekhq/resources/PartsReportDialog.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
closes #5685 
The more robust default percentage levels have already been implemented, this just adds another button to reset your requested stock levels to the default. The method here is really simple,  we just clear the requested stock map and then update our overview table with the cleared stock map.
=> [RFE Completion]: Ability to reset AutoLogistics requested stock levels to their defaults

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- Updated tooltip text for Vocational XP to specify that 'Relief Duty' contracts are excluded from the doubled XP exclusion. Previously the tooltip stated that all contracts ending in 'Duty' were excluded from granting double xp awards.
This was a visual bug only.
=> Clarify Vocational XP Tooltip

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java, MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
- Reworked part handling to remove redundant preparation steps and optimize collection and weighting logic for resupply operations.
- Improved part eligibility checks for better efficiency and maintainability.
Overall, this should see a decent jump in the usefulness of Resupply drops, as well as improve performance. It also has the added benefit of using the preexisting system used by the parts in use dialog. Which means any improvements and fixes made to that will be passed onto the Resupply module. Using the systems in that dialog was my original intent, but wasn't logical at the time as that dialog was in a state of flux.
=> Refactored Part Handling in Resupply Module

MekHQ/src/mekhq/campaign/unit/Unit.java
- Replaced a greater-than check with a non-equal check to handle edge cases where internal structure values might be negative (for example, if the Mounted object is in the body location.
Fix #5951
=> Fixed Cargo Capacity Calculation in For Cargo Items in Body

MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/unittests/mekhq/campaign/unit/GetCargoCapacityTest.java
- Updated the cargo capacity logic to better account for destroyed locations and excluded unusable equipment.
- Introduced comprehensive unit tests to validate calculations across various scenarios, ensuring correctness and robustness.
=> Further Improvements to Cargo Container Checks; added Unit Tests

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/universe/Faction.java, MekHQ/src/mekhq/campaign/universe/enums/HonorRating.java
- Replaced hardcoded honor rating logic with an `HonorRating` enum for better readability and maintainability.
- Moved honor rating computation to the `Faction` class, simplifying related code in `AtBDynamicScenarioFactory`.
=> Converted Honor Rating into an Enum

MekHQ/src/mekhq/campaign/mission/BotForceRandomizer.java, MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java
- Replaced `TaharqaSkillGenerator` with `ModifiedConstantSkillGenerator` in `AtBScenarioModifierApplicator` and `BotForceRandomizer`.
This ensures consistency with updated skill generation logic used elsewhere in MekHQ. I updated our generation methods back in 2024, but apparently missed these two instances.
=> Use `ModifiedConstantSkillGenerator` for Skill Generation

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/ScenarioForceTemplate.java
- Implemented a 'None' option in `ForceGenerationMethod` to allow bot forces where no units are generated, enabling more flexible scenario templates.
- Adjusted `AtBDynamicScenarioFactory` to account for this method in force generation logic.
This resolves a situation where we need to have all objective-significant Bot Forces generated when the scenario is created. However, if we want the Bot Force to have specific units and not random ones, we then need to remove the already generated ones. By using this method, we're able to generate an empty force during scenario creation which can then be populated later.
This will be used by the upcoming prisoner rework.
=> Added 'None' Generation Method to `ScenarioForceTemplate`

MekHQ/resources/mekhq/resources/AssignForceToTransport.properties, MekHQ/resources/mekhq/resources/AtBStratCon.properties, MekHQ/src/mekhq/campaign/utilities/CampaignTransportUtilities.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Fixes #5845 
- In the Scenario Setup Wizard, there is a dropdown for Transport Type
- When a unit is selected from the leadership bonus unit list, if the transport type is not none, it'll check the unit's transport & transported units for the corresponding campaign transport type: If they're also eligible leadership units, let's mark them as selected too.
=> Issue 5845: In Stratcon scenario wizard, leadership units consider transport assignments

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Fixes #5980 
After getting all forces we need to update their commanders. I moved this to happen later in the campaign xml parsing. 
Before, when getting eligible commanders it would get incorrect Unit commanders - it was attempting to determine a `Unit`'s commander before the `Personnel` were initialized. The ranks were all null, so it would wind up the last person (who was often a driver). 
Now, it will update commanders after everyone has been initialized with their ranks.
Related to #5729
=> Issue 5980: Improved commander updating logic

MekHQ/src/mekhq/CampaignPreset.java
Reported on Discord, not in GitHub yet.
It isn't possible to load presets made after 50.03-snapshot (like 50.03), but it is possible to load presets made before 50.03-snapshot, like 50.02.
I fixed the check so 50.03-snapshot and 50.03 presets work, and campaign preset versions older than 50.02 (50.01, 50.02-snapshot) won't work.
=> Fixed backwards "last compatible version" check

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/unittests/mekhq/campaign/force/ForceTest.java
- Refactored the `getAllUnits` method by restructuring conditional logic and initializing `allUnits` at the declaration point, improving code clarity.
- Added comprehensive unit tests to validate the method's behavior across various scenarios, to prevent regression.
Fix #5995
=> Refactored `getAllUnits` to Simplify Logic and Added Unit Tests

MekHQ/src/mekhq/campaign/randomEvents/GrayMonday.java, MekHQ/src/mekhq/gui/dialog/randomEvents/GrayMondayDialog.java
Changed event logic to activate on day 3 after Gray Monday instead of day 2. This ensures consistency in timing for dialog display and related contract interactions.
=> Adjusted Gray Monday Employer Dialog to Trigger on the Correct Day

MekHQ/src/mekhq/campaign/unit/Unit.java
- Introduced a new `isBattleArmor` method to determine if the associated entity is classified as battle armor.
=> Added Shortcut Method to Check if a Unit is Battle Armor

MekHQ/src/mekhq/gui/StratconPanel.java
Fixes #6009 
- I believe this was fixed by #6003 
- There were some issues with #6003's implementation that were found while investigating this issue that were fixed:
- If the scenario was null when assigning the initial forces it wouldn't show the leadership bonus units screen
- If a deployment was comitted the next deployment would not properly clear its deployment if the user didn't commit to that deployment.
=> Issue 6009: Improve Stratcon deployment logic to ensure units aren't deployed twice

MekHQ/src/mekhq/gui/StratconPanel.java
Fixes #6018 
This used to work because the `RCLICK_COMMAND_MANAGE_FORCES` case intentionally fell through to the `RCLICK_COMMAND_MANAGE_SCENARIO` case. When I removed that this bug was exposed.
=> Issue 6018: Manage Scenario will now use manage scenario and not manage forces

MekHQ/src/mekhq/campaign/parts/PodSpace.java
Fixes #5784 
Another "Ghost" bug? It's pretty ghostly I think. 
When using the "Pod Space" salvage for a busted location it would also remove "Missing Parts", so when the location is replaced there will be no option to repair the equipment that was a "Missing Part" at the time of the salvage task. This could be worked around be reloading after salvaging. 
This fixes that by:
1. Not removing "Missing Parts" when salvaging via Pod Space. 
2. Don't count "Missing Parts" as something that needs fixed (otherwise the repair pod space task would always show for missing limbs - this is why when salvaging parts it would show twice, first time would remove initial missing parts and present parts, 2nd salvage would remove the originally-present-now-missing-parts.)
=> Issue 5784: Better handling for missing parts when replacing parts via "Pod Space"

MekHQ/src/mekhq/campaign/Campaign.java
- Deprecated the original `getActivePersonnel` method to enforce explicit behavior regarding prisoner inclusion.
- Introduced an replacement method `getActivePersonnel(boolean)` to allow greater control and clarity when filtering active personnel.
This approach reduces ambiguity and potential bugs in personnel filtering.
=> Refactored Active Personnel Retrieval Logic

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/resources/mekhq/resources/RandomDependents.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/RandomDependents.java, MekHQ/unittests/mekhq/campaign/personnel/RandomDependentsTest.java
- Extracted random dependent management logic from `Campaign` into a new `RandomDependents` class for better modularity and maintainability.
- Added unit tests for `RandomDependents` to ensure functionality and moved related properties to a dedicated resource file.
=> Refactored Random Dependents Removal-Addition into a Seperate Class

MekHQ/src/mekhq/campaign/finances/Finances.java, MekHQ/src/mekhq/gui/adapter/FinanceTableMouseAdapter.java
My MekHQ was running slow - taking over 10 seconds to process a new day for a thicc Battalion while off contract. IntelliJ's profiler suggested that `Finances::getBalance` was taking a lot of time, so it's now cached. 
Before caching:
After caching:
=> Cache finances balance

MekHQ/src/mekhq/campaign/universe/StarUtil.java
Windows wasn't able to compile the javadocs - it didn't like the special character used for the exponents. I switched it to use a ^ instead so windows is able to compile the javadocs.
=> Javadoc error in StarUtil from superscript

MekHQ/data/storyarcs/young_wolves/storyArc.xml, MekHQ/src/mekhq/campaign/storyarc/storypoint/CreateCharacterStoryPoint.java
Fixes #6025 
The main problem was how the phenotype and role enums were loaded, so I just needed to make a quick change to the XML code for the story arc. However, the phenotype bonuses were also not registering, so I had to make some changes to the underlying code to ensure that those phenotype changes would be picked up in the future.
=> Issue 6025: Young Wolves Storyarc doesn't correctly assign main character or Tobias to the Mechwarrior Trueborn Caste

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/Contract.java, MekHQ/unittests/mekhq/campaign/mission/AtBContractTest.java, MekHQ/unittests/mekhq/campaign/mission/ContractTest.java
This is a pretty simple change--to prepare for further work on cleaning up the Contract APIs, I've refactored `getSharesPercent()` to simply be overridden by AtBContract rather than defining a new public function that "shouldn't be called" according to the old docstrings. This removes the hard dependency on AtBContract in Contract as it's no longer necessary to check what kind of object it is.
I've also added a couple of basic tests to verify that the existing functionality has not changed.
=> Refactor shares percent to be polymorphic

MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
fixes #5814 
Non Stratcon users currently getting an indexOut of bounds when attempting to use mekLab.   This due to using enums ordinal index when setting up tabs.  Changed the meklab index check to use last index instead of MEK_LAB.ordinal.
Could also swap Stratcon and MekLab enums but that didn't look right.  
Tried leaving Statcon tab there but setting it to not visible but for some reason it was always visible.
=> CHange meklab check to last index check

MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java, MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java
When comparing if two BattleArmor parts are the same it will strip (Sqd#) from the model. The price for each part is already the same regardless of part size, so now `Elemental[Flamer](Sqd5)` can be used to replace a missing `Elemental[Flamer](Sqd4)`.
=> Enhancement - Allow Battle Armor suits from different squad sizes to be used as replacements

MekHQ/src/mekhq/gui/baseComponents/JScrollablePanel.java, MekHQ/src/mekhq/gui/view/UnitViewPanel.java
Fixes #6065. The simple solution to this was to make `UnitViewPanel` a `JScrollablePanel`. The class was marked as deprecated, but I think that is inaccurate as we still use it for all of our view panels (e.g. PersonViewPanel, ScenarioViewPanel), and the suggested replacement (`AbstractMHQScrollablePanel`) does not work for any of these view panels, as it requires things in its constructor that these view panels don't have access to. Therefore, I have removed the deprecated tag. Long live `JScrollablePanel`.
=> Fix Issue #6065: Unit History in UnitViewPanel does not wrap.

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java, MekHQ/src/mekhq/campaign/mission/enums/AtBEventType.java
This simply moves the hardcoded ATB Event Type constants from static variables to an enum. This supports further refactoring work on AtBContract by reducing the number of public variables that other classes need to call, therefore simplifying the public interface. My understanding was also that there was an initiative to try and use enums instead of static ints throughout the codebase.
=> Extract AtB Event Types to enum

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/unittests/mekhq/campaign/mission/AtBContractTest.java
This PR starts a larger effort  for increasing test coverage of the AtBContract and Contract classes. Specifically, this adds tests for the `calculateContractDifficulty()` method to ensure the calculations don't break during later refactoring. (_Note: tests for additional methods have been added while waiting for a review_)
A couple of internal helper functions needed to be changed from `static private` to non-static/package private to enable mocking. I've also attempted to begin transitioning to not using `Campaign` objects as an argument to reduce coupling, in this case by adding new versions of two functions and marking the old ones deprecated. I've covered both the new and old ones with unit tests to make sure the behavior doesn't change between versions.
Regarding the new methods …
=> Add Tests for calculateContractDifficulty()

MekHQ/src/mekhq/campaign/parts/BattleArmorSuit.java, MekHQ/src/mekhq/campaign/parts/MissingBattleArmorSuit.java, MekHQ/src/mekhq/campaign/parts/utilities/BattleArmorSuitUtility.java
This uses some values from the suit's entity to determine if two parts are the same.
If for whatever reason we can't find the suit's entity then it'll fallback to using the original comparison method. 
If it can find the entity, then instead of comparing model name it'll compare the per-suit BV and the weapon types the entity has.
=> Enhancement - A further enhancement for BA Suit swappability in MekHQ

MekHQ/mmconf/campaignPresets/CampaignOperations.xml, MekHQ/mmconf/campaignPresets/CampaignOperationsStratCon.xml, MekHQ/mmconf/campaignPresets/NewPilotProgram.xml, MekHQ/mmconf/campaignPresets/TheCompleteExperience.xml, MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/CombatRecordRating.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java
- Introduced options to clamp reputation-based pay, reduce mission performance score impact, and apply a cutoff for old missions in reputation calculations.
These changes aim to prevent excessive reputation inflation, particularly in long-running campaigns.
The issue of **Rampant Reputation** emerged in version 50.03 when we fixed a bug that had been preventing contract pay from correctly factoring in Reputation. This fix led to an extreme spike in contract pay—so significant that it was initially mistaken for a new bug. However, after investigation, we confirmed that the system was functioning according to **Rules as Written** and that the issue stemmed from the adaptation of **CamOps** mechanics into **MekHQ**.  
CamOps was designed for in-person groups who typically play only a few …
=> Added Reputation Sanity Options to Campaign Settings

MekHQ/src/mekhq/campaign/randomEvents/RandomEventLibraries.java, MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonEscapeScenario.java
- Updated the DIRECTORY constant to use backslashes, ensuring compatibility with Windows systems.
This resolves potential issues with file paths being incorrectly interpreted.
Fix #6081
=> Fixed File Path Separator for `RandomEventLibraries` on Windows

MekHQ/build.gradle
Fixes #6090 
Fix suggested by @rjhancock on Discord, thanks!
This was verified by assembling the distribution via buildAllPackages. Before the fix, it was crashing as the bug describes. After this fix, it is able to launch properly.
=> Issue 6090: Updated Gradle build for MekHQ to include new randomEvents directory

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Increased reinforcement arrival scale to ~~40~~ 25 (from 15).
- Reduced base leadership budget to 500 (from 1,000) for better balancing.
- Refactored skill modifier logic to no longer factor in ally skill. This allowed users to indirectly double-dip and resulted in unintentionally low target numbers.
We received a lot of feedback following the launch of the new reinforcement and leadership system. Rather than rushing into quick fixes, we wanted to let the dust settle to fully understand the pain points and implement meaningful improvements instead of reactionary changes.  
One of the biggest concerns was that the reduced arrival times made lighter units nearly obsolete. The difference between reinforcing with a light unit versus an assault was too small to justify deploying anything but …
=> Adjusted Reinforcement Arrival Time Scaling, Target Number, and Leadership Budget Logic

MekHQ/campaigns/Fist and Falcon/Binary Bravo, 1st Falcon Strikers.cpnx, MekHQ/campaigns/Fist and Falcon/Kewran Wolfhounds, C Company, 3rd Battalion, 25th Arcturan Guards RCT.cpnx, MekHQ/campaigns/Sword and Dragon/Fox's Teeth, McKinnon's Company, Vausur's Battalion, Seventh Crucis Lancers RCT.cpnx, MekHQ/campaigns/Sword and Dragon/Sorenson Sabres, Jisatsu Company, Otomo, formerly Third Company, Tarwater's Battalion, Fifth Sword of Light.cpnx, MekHQ/campaigns/Wolf and Blake/Black Widow Company, Church's Independent Company, Wolf's Dragoons.cpnx, MekHQ/campaigns/Wolf and Blake/Shadow Hunters, Opacus Venatori, Fifty-second Shadow Division.cpnx, MekHQ/mmconf/campaignPresets/CampaignOperations.xml, MekHQ/mmconf/campaignPresets/CampaignOperationsStratCon.xml, MekHQ/mmconf/campaignPresets/NewPilotProgram.xml, MekHQ/mmconf/campaignPresets/TheCompleteExperience.xml, MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/personnel/generator/RandomPortraitGenerator.java, MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java
Implements #4364
When the option "Allow Duplicate Portraits" is enabled, random portrait generator ignores existing personnel and feels okay with potentially using the same portrait. Defaults to true.
=> [RFE 4364] Add campaign option to allow duplicate portraits

MekHQ/src/mekhq/campaign/personnel/RandomDependents.java
I got a NPE in my nightly save. 
`genealogy.isDependent`'s return `Person` is tagged as `@Nullable`.  This will handle that. 
Child above shouldn't need it, if someone doesn't have children it'll return an empty list.
=> Null Check for Random Dependents

MekHQ/data/universe/academies/Unit Education.xml
- Changed "In-House NCO Bootcamp" type from "Basic Training" to "NCO Academy."
- Removed "Basic Training" type from "In-House Warrant Officer Bootcamp."
- Removed "Basic Training" type from "In-House Officer Bootcamp."
Fix #6069
Unit education is generally less formal and hands-on than found in actual education institutions. The quality of officer training offered in-unit is drastically lower than that offered by a formal education. Meanwhile, Basic Training and the NCO Bootcamp offer a comparative (albeit lower quality) education to their formal counterparts.
That is why Basic Training and NCO Bootcamp award Awards, while Warrant Officer and Officer Bootcamps do not.
See also the length of in-unit officer bootcamps (70 days) vs. formal officer schooling (300 days).
=> Updated Academy Training Types in `Unit Education.xml`

MekHQ/resources/mekhq/resources/PrisonerEvents.properties
- Fixed incorrect glossary link references for "Fatigue" by changing `GLOSSARY:Fatigue` to `GLOSSARY:FATIGUE`.
=> Corrected Glossary Links For Fatigue

MekHQ/src/mekhq/campaign/randomEvents/prisoners/CapturePrisoners.java
- Corrected prisoner status check to ensure it specifically checks for death instead of absence from personnel.
- Updated `processPrisoner` call to properly handle the `addingToCapturePersonnel` parameter with a `false` value when appropriate.
- Improved logic clarity for handling prisoner death scenarios during Bondsref processing.
Fix #6094
This was a classic whoopsie caused by refactoring just prior to release. Basically we had a check that shortcutted prisoner capture if the prisoner performed Bondsref. However, the conditional was checking whether the character was in the campaign or not, because Bondsrefing NPC prisoners were just removed. However, the refactoring changed this so that they were just not added to the campaign. However, this meant they were never present _in_ the …
=> Fixed Prisoner Capture And Processing Logic

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java, MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java, MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java, MekHQ/src/mekhq/utilities/EntityUtilities.java
- Added `isUnsupportedUnitType` utility method to check unsupported units based on type.
- Updated `DataLoadingDialog.java` to unassign crews instead of selling unsupported units like Gun Emplacements.
- Removed GUI properties related to unsupported unit sale notifications.
- Integrated `isUnsupportedUnitType` in `AssignUnitToPersonMenu.java` to block the crewing of unsupported units.
- Integrated `isUnsupportedUnitType` in `MekHQUnitSelectorDialog.java` to block the purchase of unsupported units.
Fix #6089
After internal discussions, we decided the best approach is to allow the salvage of Gun Emplacements (and any other unit types that may be declared unsupported in the future) while preventing them from being purchased or crewed. This ensures that players cannot _use_ unsupported units …
=> Refactored Unsupported Unit Handling

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/enums/AtBContractType.java
- Replaced explicit `AtBEventType` references with static imports for cleaner and more concise code.
- Streamlined switch cases in `AtBContractType` by adopting concise return statements.
- Introduced `isUseStratCon` variable in `AtBContract` to reduce repetitive calls to campaign options.
- Adjusted scenario logic to selectively assign special event scenarios based on `isUseStratCon`.
- Improved readability and maintainability by simplifying conditional structures.
Fix #6088
I'm not sure if this is due to a regression or if I just missed these scenario calls, but I’m really hoping this will finally put an end to the old legacy scenarios.
=> Simplified Enum References And Removed Legacy Scenarios

MekHQ/src/mekhq/campaign/personnel/education/TrainingCombatTeams.java
- Introduced a constant `FATIGUE_GAIN` to represent the fatigue increase during training.
- Updated training logic to apply fatigue gain to trainees if the fatigue system is enabled in campaign options.
Fix #6078
This is our first attempt at rebalancing Training Combat Teams following the rework. I anticipate further adjustments will be needed, but I want to proceed gradually. The next step will be adding scenarios with a chance to spawn where the OpFor attacks the training force.
=>  Added Fatigue Gain Mechanism for Training Combat Teams

MekHQ/src/mekhq/campaign/RandomOriginOptions.java, MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java
- Added a null check for `getSpecifiedPlanet()` in the condition to avoid potential `NullPointerException`.
- Ensured a fallback to the first available planet if no planet is selected from the dropdown.
- Prevented potential crashes caused by null values when setting the specified planet.
This issue was highlighted in the comments of #6067. Without knowing the exact source of the NPE, it's difficult to determine where to add null protection. However, since the only new functionality comes from CO IIC, it made sense that the issue originated there, so I added protection accordingly.
=> Fixed `NullPointerException` In `RandomizeAroundSpecifiedPlanet`

MekHQ/resources/mekhq/resources/ScenarioTableModel.properties, MekHQ/src/mekhq/campaign/mission/AtBScenario.java, MekHQ/src/mekhq/gui/BriefingTab.java, MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
- Updated `AtBScenario.getStratconScenario` to take `AtBContract` and `AtBScenario` as parameters for improved clarity and separation of responsibilities.
- Refactored `ScenarioTableModel` rendering logic for StratCon scenarios, simplifying status and turning point display.
- Enhanced string formatting to incorporate localized "Turning Point" text from resources.
- Adjusted StratCon scenario coordinate and track name determination for better null handling and accuracy.
- Updated `ScenarioTableModel.properties` to include a new key for "Turning Point" localization.
Fix #6063
I moved the Turning Point helper to the status column, making it easier to add other helpers if we introduce additional scenario types in the future. This also eliminates any ambiguity in the display.
=> Refactored StratCon Scenario Retrieval And Table Rendering

MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
- Updated condition to correctly assess maternity leave activation relative to the due date.
- Adjusted logic to check if due date minus 20 weeks is before today, improving accuracy.
Fix #6107
=> Fixed Maternity Leave Activation Logic

MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java, MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java, MekHQ/src/mekhq/gui/dialog/ResolveScenarioWizardDialog.java
**Dependent on MegaMek/megamek#6643 - do not merge until that has been merged.**
Fixes #3655 
Trailers no longer require crew in MekHQ (if appropriate - if a trailer has weapons or an engine it'll need crew). Trailers with no crew can be added to the TOE now. Trailers with no crew are no longer listed as crippled in the hangar. Trailers with no crew can be sent to MegaMek correctly, and work as expected in the `ResolveScenarioWizardDialog.java` (no creating a new "No Commander" person, no assigning kills to unmanned trailers, no NPEs!).
=> MekHQ Issue 3655: Fix vehicle crew requirements for trailers 

MekHQ/src/mekhq/campaign/Quartermaster.java, MekHQ/src/mekhq/campaign/parts/AmmoStorage.java, MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java, MekHQ/src/mekhq/campaign/parts/equipment/BattleArmorAmmoBin.java, MekHQ/unittests/mekhq/campaign/parts/equipment/BattleArmorAmmoBinTest.java
Fixes #6112 
- Battle Armor Ammo is now purchased by the ton (50 for SRM ammo) instead of per shot per trooper (1 for SRM ammo) - for reference an Elemental point needs 10 SRM rounds to fully rearm.
- Ammo lookup will consider other qualities of ammo.
- Battle Armor ammo properly partially reloads now - Before this fix I was managing to get _3_ SRM rounds per trooper on an Elemental which isn't right.
- Battle Armor ammo loading now gets ammo in `getNumTrooper()` size batches. An BA unit must have the same ammo in all units, otherwise if even one BA unit has more ammo than the rest then they all have that ammo - I was generating 4 free SRM shots by reloading 6 SRM shots and then reloading the game - and then my elemental is fully armed.
=> Issue 6112: Fix BA Ammo Issues

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/randomEvents/prisoners/EventEffectsManager.java, MekHQ/src/mekhq/gui/view/PersonViewPanel.java, MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/EventEffectsManagerTest.java
- Enhanced fatigue display by showing differences between raw and effective fatigue for better clarity.
- Fixed incorrect parameter in `getActivePersonnel` call in `EventEffectsManager`, ensuring prisoners personnel are excluded for the POISON event.
- Adjusted target selection logic in `EventEffectsManager` to include all potential targets instead of a fraction.
- Updated unit tests to reflect these changes, improving test coverage and fixing assertion logic.
Fix #6121
=>  Improved Effective Fatigue Handling and Fixed Target Selection in POISON Event Effects

MekHQ/src/mekhq/campaign/mission/ScenarioObjectiveProcessor.java
- Updated `effectMultiplier` calculation to scale based on 10 qualifying units to improve balance in resupply rewards.
- Added clarifying comment to explain the updated scaling logic.
=> Adjusted Resupply Scaling Logic

MekHQ/src/mekhq/gui/CommandCenterTab.java
- Simplified code by eliminating unnecessary handling of non-current scenario statuses.
- Removed code path that displayed overall victory or negative statuses for non-current scenarios, as they were not required.
Fix #6119
This change ensures that only current scenarios are displayed in the Command Center. This means that for players with one, or more, subcontracts they don't have to scroll past potentially tens of scenarios to see the upcoming scenarios for their subcontracts.
=> Removed Non-Current Scenario Status Handling In `CommandCenterTab.java`

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java
- Updated `AtbMonthlyContractMarket` and `CamOpsContractMarket` to restrict generating new contract offers if the player has an active contract (AtB or otherwise).
- Ensured MekHQ's limitation of supporting only one main contract (apart from subcontracts) is enforced.
=>  Prevented New Contract Offers When an Active Contract Exists

MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/ContractTerms.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java
- Changed `reputationFactor` data type from `int` to `double` in multiple classes for improved precision.
- Updated `ContractTerms` constructor and `addUnitReputationModifiers` to work with `double` values, including proper flooring and clamping.
- Modified `calculatePaymentMultiplier` in `CamOpsContractMarket` to utilize the new `double` type for `reputationFactor`.
- Adjusted `getReputationFactor` in `ReputationController` to return a `double` for consistency with related changes.
Fix #6117
Because Reputation Factor was being stored as an integer it was effectively flooring the value. That meant that any value between 0 and 1 (but less than 1) would be stored as 0. Essentially meaning the user would get a zero base pay. Rules as Written the minimal value is 0.5. However, other parts of …
=> Refactored `ReputationFactor` To Use `Double` Instead Of `Integer`

MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
- Updated `PersonnelTableModelColumn.java` to display the calculated age based on the campaign's local date.
- Ensured the age value is returned as a String for proper display.
Fix #6113
=> Added Age Calculation In Personnel Table Column

MekHQ/data/scenariotemplates/Base Defense.xml, MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Deep Raid.xml, MekHQ/data/scenariotemplates/DropShip Raid.xml, MekHQ/data/scenariotemplates/Hostile Facility.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml
- Updated `arrivalTurn` for multiple scenario templates:
- Changed from `0` to `1` in some templates to ensure proper reinforcement timing.
- Changed to `-3` in specific cases (e.g., "Deep Raid Defense") for unique deployment scenarios.
- Enhanced `Isolated DropShip Defense` details:
- Expanded briefing for better mission clarity and narrative immersion.
- Restored and revised scenario objectives for better alignment with mission success criteria.
- Modified objectives logic for "Isolated DropShip Defense" to improve gameplay balance:
- Added clear success and failure conditions.
- Adjusted victory/defeat point scaling for better impact.
Fix #6111
=>  Adjusted Scenario Templates for Arrival Turn and Objectives

MekHQ/src/mekhq/campaign/finances/Accountant.java
- Refactored `getForceValue` method to remove reliance on a `CampaignOptions` object. Updated it with modern method calls and improved the layout for ease of human parsing.
- Refactored `getContractBase` to improve readability.
- Changed the `getAllUnits` call to only return units in 'STANDARD' forces. This will exclude any force with a non-combat assignment.
- Refactored the `Accountant` class to use a Java record for simplicity and immutability.
- Replaced getter methods with direct record accessor usage (`campaign()`).
Fix #6027
By including only combat forces we better align with CamOps RAW, which specifically references 'combat units', which would exclude forces assigned to non-combat formations. At that point they cease to be combat units.
Also, seeing that `Accountant.java` was …
=> Refactored Campaign Force Value Calculation

MekHQ/src/mekhq/campaign/Campaign.java
- Modified `Campaign` class to count only fully crewed units when processing forces for the purposes of determining if there is a deployment deficit.
- Replaced direct counting of units with a validation check using `isFullyCrewed()`.
- Added a check to include only salvage units in the unit count logic.
- Enhanced safety by ensuring null units are skipped during iteration.
Fix #6002
This change means that when determining whether there is enough units in a Combat Team, to count towards the requirements of a contract, we no longer count units that are not fully crewed. This means that the employer is only counting units that are combat operational, i.e. fully crewed and not marked as salvage.
=> Updated Unit Count Logic When Determining if There is a Force Deployment Deficit

MekHQ/resources/mekhq/resources/GrayMonday.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/finances/Loan.java, MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/campaign/market/contractMarket/CamOpsContractMarket.java, MekHQ/src/mekhq/campaign/market/unitMarket/AtBMonthlyUnitMarket.java, MekHQ/src/mekhq/campaign/randomEvents/GrayMonday.java, MekHQ/src/mekhq/gui/dialog/NewLoanDialog.java
- Corrected a typo in the event message text ("contro" to "control") within the GrayMonday.properties file.
- Added `calculateContract` and set salvage percentage to 100% in Gray Monday contract logic.
- Removed unnecessary HTML tags in Gray Monday event messages to improve formatting.
- Updated text in event messages to no longer say that the player won't be paid, but that the pay will be very low.
- Updated `isGrayMonday` method to accept `LocalDate` and simulation flag directly, improving flexibility and reusability.
- Adjusted all `isGrayMonday` calls across the codebase to use the new parameters.
- Enhanced loan generation logic to incorporate Gray Monday event conditions, allowing for predatory loans.
- Improved documentation for `isGrayMonday` and loan-related methods to describe …
=> Fixed Multiple Gray Monday Bugs

MekHQ/src/mekhq/campaign/randomEvents/prisoners/CapturePrisoners.java
- Changed the resource bundle from `DefectionOffer` to `PrisonerEvents` in the `handlePostCapture` method.
Fix #6143
=> Updated Resource Bundle Reference In `CapturePrisoners`

MekHQ/src/mekhq/campaign/personnel/RandomDependents.java
- Corrected the order of operations in the `processMonthlyRemovalAndAddition` method.
- Moved the random dependent removal logic to occur after dependent addition, ensuring proper sequence.
- Updated comments and documentation to reflect the corrected method behavior.
Fix #6146
=>  Swapped Order Of Dependent Removal And Addition Logic

MekHQ/data/universe/academies/Prestigious Academies.xml
- Added "New Avalon Institute of Science" and its revised version for 3079, detailing their history, qualifications, and curriculums. This data was provided by @LadyAdia.
- Added data for the reopening of the War Academy of Mars.
Prior to the ilClan Era, the last we heard about the War Academy of Mars was that it had been destroyed and there were no plans to have it reopened. However, we now know that that it reopened _at some point_ only to be destroyed (again) by Clan Jade Falcon during the opening salvos of the Battle for Terra (3151). We were unable to find a canon source for the re-opening year, so after discussing the situation with @HammerGS we opted to go with 3135.
=> Added New Academies To Prestigious Academies Dataset

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java, MekHQ/src/mekhq/gui/stratcon/TrackForceAssignmentUI.java
- Renamed `getAvailableForceIDs` to `getAvailableForceIDsForManualDeployment` for better clarity and specificity.
- Updated all method calls and references to use the new method name.
=> Renamed Method For Improved Clarity

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/src/mekhq/gui/CampaignGUI.java
- Added `NO_ASSIGNED_SCENARIO` as a new constant in the `Force` class.
- Replaced `-1` for unassigned scenario ID with the new `NO_ASSIGNED_SCENARIO` constant across relevant files.
- Updated all references and logic checks to use these new constants.
- Replaced `-1` for a couple of unassigned force IDs with the `FORCE_NONE`. This is far from exhaustive, the couple changed were just those I stumbled over while addressing Scenario ID.
=>  Replaced Magic Numbers With Constants For Scenario IDs

MekHQ/src/mekhq/campaign/personnel/Skill.java, MekHQ/src/mekhq/gui/dialog/CreateCharacterDialog.java, MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- Introduced `COUNT_UP_MAX_VALUE` and `COUNT_DOWN_MIN_VALUE` constants in `Skill` to define boundaries for skill values.
- Updated `Skill` methods to use `min` and `max` functions to enforce these boundaries when calculating skill values.
- Refactored `CreateCharacterDialog` and `CustomizePersonDialog` to utilize the new boundary constants and methods for consistent skill value calculations.
- Improved clarity of variable names in relevant methods for better readability and maintainability.
On this edition of 'Illiani Hates Fun', I decided to go ahead and clamp skills to a logical upper bound. While I do recognize that some players rather enjoy their -8/-8 übermensch, having skills fall below the expected minimum of 0/0 has previously been a problem (and will almost certainly be again). …
=>  Enforced Skill Value Boundaries

MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsDialog.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java, MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
- Introduced a new `STARTUP_ABRIDGED` mode to `CampaignOptionsDialogMode` enum.
- Updated `CampaignOptionsDialog` logic to handle the new mode, including button behaviors and campaign option application logic.
- Adjusted tab creation in `CampaignOptionsPane` to exclude tabs for `STARTUP_ABRIDGED` mode.
- Modified `DataLoadingDialog` to use `STARTUP_ABRIDGED` for specific workflows instead of `ABRIDGED`.
- Refactored related portions of `GeneralTab` to ensure proper initialization for the new mode and cleanup of redundant checks.
Fix #5639
I want to start by mentioning that this was a planned change prior to Raoz posting their issue report (so sling any grumps at me, not them). Basically time traveling causes a number of issues with the underlying simulation - in particular galaxy …
=> Disabled Time Traveling in Campaign Options; Fixed Campaign Options Start Up in Abridged Mode

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Ensured options like "Free," "Execute," and "Jettison" are correctly displayed only for NPC Prisoners.
- Fixed the condition to display "Ransom Friendly" option for PC Prisoners, and only for GM.
Fix #6144
=> Refactored Prisoner Context Menu Behavior

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/gui/campaignOptions/contents/MarketsTab.java
- Introduced a new campaign option: "Deliver Units Mothballed".
- Units purchased from the unit market will now arrive in a mothballed state if enabled.
- Updated `Unit` logic to reflect the mothballed delivery state.
- Units marked as mothballed but still in transit will display as "In transit (`n` days)".
- Enhanced `CampaignOptions` to handle the new `mothballUnitMarketDeliveries` flag.
- Added appropriate getter, setter, and XML persistence updates.
- UI changes:
- Added a checkbox in the Markets Tab of the campaign options dialog for enabling "Deliver Units Mothballed".
- Updated tooltips and labels to describe the new functionality.
Fix #5734
=> Added Mothball Option for Unit Market Deliveries

MekHQ/src/mekhq/AtBGameThread.java
Stops PACAR from starting the game before the player has a chance to setup the scenario, game rules and units in the way they want when running with the legacy Client GUI.
- closes #6059 (it lists as an RFE, but after reflection, the behavior was wrong and should not be starting the game automatically, so I am treating as a bug instead)
=> fix: PACAR auto-start only when using CommanderGUI

MekHQ/resources/mekhq/resources/PartsTableModel.properties, MekHQ/src/mekhq/campaign/parts/Part.java, MekHQ/src/mekhq/gui/model/PartsTableModel.java
- Removed italicized formatting of brand-new parts in the Name column for a cleaner presentation.
- Introduced a new resource bundle (`PartsTableModel.properties`) to centralize localization strings for `PartsTableModel`.
- Replaced hardcoded column names with calls to `getFormattedTextAt` to dynamically fetch localized strings from the resource bundle
- Removed redundant hardcoded strings to improve maintainability and support for additional localization in the future.
- Simplified and modernized `getColumnName` logic using the `switch` expression.
- Appended "(Brand New)" and "(Used)" to the Quality column for improved clarity and visibility of part status.
This should cut back on the number of contacts we get from users asking what the italic name in their warehouse means.
=>  Updated `PartsTableModel.java` To Better Indicate Brand-New Status in Quality Column

MekHQ/resources/mekhq/resources/Resupply.properties
- Replaced placeholders `{0}` with `{1}` in all `statusUpdateIntercepted` properties to ensure consistency.
- No changes to the core content or logic, only syntax refinement.
Fix #6166
=> Corrected Resupply Interception Placeholder Syntax

MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
- Refactored `btnGMRemoveSP` action listener to directly call `removeSP`, removing unnecessary `dispose()` call.
- Updated `removeSP` method to use `changeSupportPoints()` for modifying support points instead of directly setting them.
- Adjusted condition to allow removal of support points when greater than 0, instead of 1.
=> Corrected Support Points Removal Logic

MekHQ/resources/mekhq/resources/RandomDependents.properties, MekHQ/src/mekhq/campaign/personnel/RandomDependents.java, MekHQ/unittests/mekhq/campaign/personnel/RandomDependentsTest.java
- Renamed `getActiveNonDependents` to `prepareData` to better reflect its functionality.
- Refactored `RandomDependents` class to use boolean fields (`isUseRandomDependentAddition` and `isUseRandomDependentRemoval`) instead of accessing campaign options directly multiple times.
- Rewrote `prepareData` to initialize `activeDependents` directly and ensure reuse across the class.
- Updated logic in `dependentsRollForRemoval` to remove dependents directly from `activeDependents` after processing, eliminating redundant reassignment.
- Cleaned up and improved readability of dependent addition and removal logic by leveraging class fields.
- Simplified test cases to align with the refactored `prepareData` method and ensure accuracy.
- Refined resource bundle formatting logic for dependent …
=> Updated `RandomDependents.java`: Fixed Reporting & Optimized

MekHQ/resources/mekhq/resources/CampaignGUI.properties, MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java, MekHQ/src/mekhq/gui/dialog/MekHQUnitSelectorDialog.java, MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java, MekHQ/src/mekhq/utilities/EntityUtilities.java
Relates to #6123 
Drones are currently not supported by MekHQ. This change prevents the player from acquiring them.
=> Issue 6123: Mark drones as unsupported in MHQ.

MekHQ/src/mekhq/gui/dialog/PartsReportDialog.java
Fixes #6180 
Parts in Use dialog will now consistently use `getSellableQuantity()` for determining how many parts it can sell.
=> Issue 6180: Fix Parts in Use Dialog selling wrong number of parts

MekHQ/src/mekhq/campaign/randomEvents/prisoners/CapturePrisoners.java
- Updated `CapturePrisoners` constructor and `processPrisoner` method to accept nullable `Faction` parameters, ensuring null-safety.
- Defaulted null `searchingFaction` to the "MERC" faction in the constructor, utilizing `Factions.getInstance()`.
- Adjusted logic to handle potential null `Faction` values, including checks for `isClan`, `isPirate`, and `isMercenary`.
- Added `@Nullable` annotations to promote clarity and reduce potential null pointer exceptions.
=> Added `null` Protection During Prisoner Capture to Avoid Lockup in Non-AtB Campaigns

MekHQ/resources/mekhq/resources/PrisonerEvents.properties
- Suppressed "UnusedMessageFormatParameter" inspection for the entire file.
- Suppressed "UnusedProperty" inspection for the entire file.
This just suppresses these warnings, so that it's easier to spot if there are actual issues at play.
The former is irrelevant because of how i18n works - you no longer need to have placeholders in the right order, or always include every placeholder.
The latter is irrelevant because we dynamically build the reference key, rather than direct referencing. So IDEA thinks the entries aren't being used.
=> Added Suppress Inspection Annotations To `PrisonerEvents.properties`

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
- Refactored `calculateReinforcementTargetNumber` method by removing unused parameters: `Campaign`, `StratconScenario`, and `StratconCampaignState`.
- Replaced facility-based modifier calculation with an enemy morale-based modifier for better balancing.
- Updated call to `calculateReinforcementTargetNumber` in `StratconScenarioWizard` to match the new method signature.
This was a change I actually thought I made the other week. It stops player reinforcements from becoming progressively easier (to the point of being nonsensically easy) as a contract progresses and the player captures more facilities.
The facility modifier was the primary cause being so many negative target numbers, with reinforcements.
The intention of the facility modifier was to reflect the OpFors control of a sector. …
=> Updated Reinforcement Target Calculation Logic

MekHQ/src/mekhq/gui/campaignOptions/SelectPresetDialog.java, MekHQ/src/mekhq/gui/campaignOptions/components/CampaignOptionsHeaderPanel.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java
- Replaced manual image scaling logic with `scaleImageIconToWidth` utility function.
- Simplified and cleaned up code in `SelectPresetDialog`, `GeneralTab`, and `CampaignOptionsHeaderPanel` by leveraging the utility.
Fix #5975
Basically, this was caused by image-size hitting 0. At which point the scaling broke because you can't have a 0 dimension in an object. The naughty bit of code actually predated the image utility and never got updated (whoops).
=> Fixed Image Scaling Stopping Campaign Options IIC from Launching

MekHQ/src/mekhq/gui/campaignOptions/contents/SkillsTab.java
- Changed `storedTargetNumber` and `storedValuesSpinners` from `double` to `integer` to ensure consistent and precise data type usage.
- Updated relevant casting in the `copyButton`'s action listener to handle integer values.
- Ensured alignment with integer input expectations from UI elements like `spnTargetNumber` and `spinners`.
Fix #5978
This bug was caused by us incorrectly storing (and passing around) skill costs as a double instead of an integer. Normally I would say that probably made sense at the time, but I'm not convinced that decision _ever_ made sense, so it's been fixed.
If only all of CO IIC's bugs could be this simple...
=> Fixed Copy-Pasting of Skill Values in Campaign Options IIC

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- Updated the label for the "Kills" option to remove "(Deprecated)".
- No functional changes made, only a text adjustment in the properties file.
Fix #5969
=> Removed Deprecated Label From Kill XP Awards in Campaign Options IIC

MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/MarketsTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/PersonnelTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/RelationshipsTab.java
- Corrected the mapping of `chkUseTactics` and `options.setUseTactics` in `PersonnelTab` to align with `isUseTactics` instead of `isUseTaxes`.
- Resolved incorrect option mapping for random clan personnel and prisoner marriages/divorces in `RelationshipsTab`.
- Fixed incorrect connection of personnel and unit market report refresh options in `MarketsTab`.
- Rearranged and corrected the `comboFaction` initialization order in `GeneralTab` for proper functionality.
- Removed redundant salary-related options initialization in `PersonnelTab` to improve clarity and avoid duplication.
Fix #6185
This just fixes a handful of instances where we weren't loading or saving options correctly. Thankfully, none of these were critical options, but they're fixed now. I'm marking this as 'critical' because …
=> Fixed Incorrect Loading/Saving of Options in Campaign Options IIC

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/gui/campaignOptions/contents/RulesetsTab.java
- Corrected tooltip strings by adding missing periods for consistency across labels.
- Fixed spacing in warning messages to align with formatting standards.
- Updated `RulesetsTab` to format tooltip strings dynamically using `String.format`.
Fix #6181
=> Fixed Tooltips and Formatting in Campaign Options IIC

MekHQ/src/mekhq/gui/campaignOptions/contents/RulesetsTab.java
- Added a `JLabel` instance for `MinimapTheme` to properly initialize the minimap theme selector's label.
- Ensured `lblMinimapTheme` is a class-level variable instead of a local variable for better management.
- Adjusted grid width and layout configuration for consistent component alignment in the UI.
- Removed redundant `gridx` increment to streamline layout logic.
From...
To...
=> Corrected AutoResolve Campaign Option Layout

MekHQ/src/mekhq/campaign/parts/Part.java
- Changed `brandNew` serialization to always save its value, regardless of its state, rather than omitting it when `false`.
- Fixed deserialization of `brandNew` by replacing `equalsIgnoreCase("true")` with `Boolean.parseBoolean(trimmedText)`.
We’re aiming for **50.04** to be a milestone, so I want to implement this change in **50.04** to prepare for [#6168](#) (which will be merged in **50.05**).  
Currently, due to legacy decisions, a part’s **‘Brand New’** status defaults to `true` and is only saved if the status is explicitly set to `false`.  
In [#6168](#), we plan to change the default **‘Brand New’** status to `false`, since parts are more often used than brand new.  
This change creates an issue:  
- Parts whose brand new status was never stored were previously assumed to be brand …
=> Updated Part Saving to Always Save 'Brand New' Status

MekHQ/src/mekhq/campaign/mission/AtBContract.java
- Changed delivery time from 0 days to 1 day when adding new units to the campaign via AtB bonus rolls.
- Ensures compatibility with the 'mothball' campaign option by allowing time for unit addition to process.
- Adds realism by simulating the time needed for the unit to arrive in the hangar.
Fix #6184 
This was the final component of #6184 that hadn't been implemented.
=> AtB Bonus Roll Units Now Take 1 Day to Arrive

MekHQ/data/universe/defaultspa.xml
- Restored 12 missing SPAs to `defaultspa.xml`.
- Adjusted XP costs and requirements to match current standard.
Fix #5968
Without these entries being added to the relevant file players have to save their presets in 50.0**2** to gain access to the missing SPAs. As a result I've flagged this a critical, as while there _is_ a workaround it's not something we want players needing to do, if 50.04 is to be a Milestone release.
=> Added Missing SPAs to Campaign Options IIC

MekHQ/src/mekhq/gui/campaignOptions/contents/AbilitiesTab.java
- Replaced single-ability map with a comprehensive map of all abilities during SPA editing.
- Introduced a temporary map to include all abilities from `allAbilityInfo`.
Fix #5960
This has been marked as 'critical' as without the fix players are completely unable to assign prerequisite, incompatible, or automatically removed SPAs without editing their save or preset files.
=> Fixed SPA Editing in Campaign Options IIC

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java
- Implemented the addition of the "Clan Pilot Training" ability to applicable Clan personnel based on faction and role criteria.
- Updated `DefaultPersonnelGenerator` to assign the ability during personnel generation if eligibility conditions are met.
- Modified `AtBDynamicScenarioFactory` to ensure generated Clan unit pilots receive the ability when enabled in campaign options.
Fix #403
If the SPA is disabled in Campaign Options Clan personnel will not be assigned it.
=> Added Automatic Assignment of 'Clan Pilot Training' SPA to Clan Personnel

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
- Added a minimum weight constraint (`CARGO_MINIMUM_WEIGHT`) for resupply cargo tonnage calculations.
- Updated the cargo tonnage computation to use the `max` function, ensuring it adheres to the minimum weight threshold.
- Included the `Math.max` static import to support the new calculation logic.
This prevents a bug where convoy size can become 0t.
=> Adjusted Resupply Tonnage Calculation to Enforce a Minimum Weight of 1 Ton

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Added a check to skip scenarios with a deployment time extending beyond the contract's end date.
- Logged a message when such scenarios are skipped for better debugging and tracing.
Fix #2724
This has been a pet peeve for a long time and I don't know why I didn't address this when I implemented less predictable scenario spawning. I'm marking this as a bug, because scenarios spawning after the end of the contract wasn't intended.
=> Skipped Scenarios After Contract End Date

MekHQ/src/mekhq/gui/campaignOptions/contents/SkillsTab.java
- Removed the unnecessary sorting of the skill list in `SkillsTab.java` by eliminating the unused `allSkills` array and the `sort(allSkills)` call.
So, it turns out when we read in skills we do so in the order they were saved. Which means if some innocent developer who has never done a single crime happens to sort the skills alphabetically in a campaign options rewrite... suddenly all skills everywhere are sorted alphabetically. Which, after over a decade of non-alphabetical skill sorting, was just _wrong_.
It looked wrong, it felt wrong, and it made some people (understandably) very upset. This fixes it. I'm sure the innocent developer who made that mistake is very sorry.
=> Fixed Incorrect Alphabetical Sorting of Skills

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/RandomSkillPreferences.java, MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java, MekHQ/src/mekhq/gui/campaignOptions/contents/AdvancementTab.java
- Updated "Tactics" skill to "Command Skills", encompassing Leadership, Strategy, and Tactics.
- Renamed variables, methods, XML tags, labels, and UI components from `Tactics` to `CommandSkills` to reflect the broader scope.
- Added generation for additional leadership skills: Leadership and Strategy, alongside Tactics.
- Maintained backward compatibility with `<50.04` XML files by handling legacy "tacticsMod" tags.
- Adjusted tooltips and UI descriptions to align with the updated functionality.
This was added by user request and is something we should have done last year, however I wasn't aware that this isn't already include Strategy and Leadership. Now it does. Go us! :D
=> Rebranded 'Tactics Skills' Campaign Options to 'Command Skills'; Expanded Coverage to Include Leadership and Strategy

MekHQ/src/mekhq/gui/campaignOptions/contents/AdvancementTab.java
- Updated spinner value ranges in the `AdvancementTab` to a minimum of 0 and a maximum of 100 (previously -10 to 10).
- Affected spinners include:
- `ArtilleryChance`
- `AntiMekChance`
- `SecondarySkillChance`
These were a casualty of a classic copy-paste error. Marking as 'High' as this prevents users from properly setting up these values.
=> Fixed Artillery, Anti-Mek, and Secondary Skill Spinner Min and Max Values in Campaign Options IIC

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
Fixes the issue where saved enemy forces would not load with SPAs they had at campaign save time.
There may also be some other issues, such as Edge settings reverting to defaults for enemy crews, etc. that were also caused by this behaviour.
Simply put, we rely on the RPG_PILOT_ADVANTAGES game option to decide whether to load SPAs when loading units' crews from the campaign save.
At the same time, the `\<gameOptions\>` block comes after every other block in the save file, and if unread, we get a default value of `false` for RPG_PILOT_ADVANTAGES.
By moving the Campaign and Game Options loading into the first of three loops over the campaign save file, we can ensure that all options are properly populated prior to loading any parts that depend on those options, without spending noticeably …
=> Fix MHQ 3175: load Campaign Options and Game Options before everything else

MekHQ/src/mekhq/CampaignPreset.java, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java
- Introduced `updateCampaignOptionsFromGameOptions` and `updateGameOptionsFromCampaignOptions` methods in `CampaignOptions` for clearer bidirectional synchronization between game and campaign options.  
- Deprecated `applyContinuousToCampaign` in `CampaignPreset` as it is no longer in use, following the arrival of CO IIC.
- Replaced the previous `updateCampaignOptionsFromGameOptions` logic in `Campaign` with a call to the new encapsulated method in `CampaignOptions`.
Marking this as **high** because we really need this in 50.04. I’m genuinely surprised it’s taken this long for it to cause major problems.  
When the user updates MegaMek's options, some choices (such as tech level) are propagated back into Campaign Options. This makes sense — if the user selects "use edge" in MegaMek’s …
=> Corrected One-Way Sync Between MegaMek and Campaign Options

MekHQ/resources/mekhq/resources/NewLoanDialog.properties, MekHQ/src/mekhq/campaign/finances/Loan.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/AverageExperienceRating.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java, MekHQ/src/mekhq/gui/dialog/NewLoanDialog.java, MekHQ/unittests/mekhq/campaign/rating/CamOpsReputation/ReputationControllerTest.java
- Removed the `getAtBModifier` method and its references, replacing its logic with `SkillLevel.ordinal()` for streamlined reputation functionality.
- Updated the loan duration calculation to clamp ratings within a bounded range, matching skill level ordinals for better alignment.
- Adjusted predatory loan settings with Gray Monday scenario-specific behaviors in the loan dialog, including disabling sliders and showing unique labels.
There were a couple of bugs with Gray Monday loans that I wanted to close off. Chief among them players could avoid having to accept the predatory loan by just changing the sliders a little bit. So I disabled those sliders during Gray Monday. Now if players want to take out loans to survive the year of chaos they need to accept some pretty stern rates.
While …
=> Fixed Gray Monday Loans; Improved AtB Modifier Handling

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Implemented logic to set command bonus for crew if either Tactics initiative bonus option is enabled in campaign settings.
So, to be clear, I still think having Tactics apply a direct modifier to initiative is a tad silly and breaks the initiative economics of the game entirely wide open. It is, however, a very popular mechanic and while we don't support ATOW it is undeniably raw within ATOW.
So, if you can't beat them join them: Princess now gets an initiative modifier based on her skill rating. This uses the skill randomization settings for Command Skills that the user has set up in Campaign Options. So crews commanded by Princess have the same chance of getting 'Tactics' as any normal character hired from the Personnel Market. Princess' tactics skill will also be influenced by the …
=> Added Initiative Bonuses from Tactics to Princess Units

MekHQ/resources/mekhq/resources/GrayMonday.properties
- Corrected a missing escape character for an apostrophe in the GrayMonday.properties file.
=> Fixed Typographical Error in GrayMonday Properties

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/personnel/PersonUtility.java, MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java, MekHQ/src/mekhq/gui/dialog/HireBulkPersonnelDialog.java
- Centralized skill override logic by refactoring `overrideSkills` to handle admin and role-specific conditions consistently.
- Introduced a new `addSkillsAndRandomize` method to consolidate skill addition with optional randomization for better reusability.
- Implemented a new `randomizeSkills` method to adjust skill levels based on dice rolls within defined constraints.
- Simplified skill level assignments using `SkillLevel` enum ordinals to improve clarity and reduce redundancy.
- Refactored Ronin generation and unit table logic to utilize the updated `overrideSkills` API, incorporating random skill preferences cleanly.
Requires https://github.com/MegaMek/megamek/pull/6703
This adds functionality I thought was already included, but apparently wasn’t.
Currently, players can GM Generate …
=> Refactored Skill Overrides; Added Randomization Logic; Added AeroSpace Ronin

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/universe/RandomFactionGenerator.java
- Updated conditional logic to consistently exclude the ROS faction after the FORTRESS_REPUBLIC date.
- Added error handling in `AtBDynamicScenarioFactory`:
- Logged an error and set a fallback faction if the faction code is blank.
- Logged an error and aborted force generation if the faction is null.
I stumbled onto this completely by accident. But basically, ROS isn't a valid employer or enemy once the Wall goes up. However, there was a single missed instance where the Republic _could_ still be chosen as an enemy. However, because it wasn't valid the faction would be `null` resulting in a bunch of unfortunate weirdness.
While investigating this I also added some null faction protection to force generation.
Marking this as 'high' as this issue is most prevalent in ilClan, the current …
=> Fixed Enemy Picker Logic And Added Faction Validation

MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/PrisonersNagLogic.java, MekHQ/unittests/mekhq/gui/dialog/nagDialogs/nagLogic/PrisonersNagLogicTest.java
- Corrected the logic in `PrisonersNagLogic.hasPrisoners` to ensure accurate handling of active contract and prisoner status.
- Updated unit tests in `PrisonersNagLogicTest` to reflect the corrected behavior and ensure proper validation.
Fix #6276
=> Fixed Logic In Prisoner Nag And Updated Unit Tests

MekHQ/src/mekhq/AtBGameThread.java
Fixes bug where opfor units might deploy with "any" deployment zone instead of the zone specified for their owner's force in the scenario.
Testing:
- Ran all three projects' unit tests
- Started various scenarios and confirmed units were set to the correct deployment zones and actually deployed there.
Close #6267
=> Fix 6267: Set each entity starting position explicitly

MekHQ/src/mekhq/campaign/unit/Unit.java
During investigations into issues passing the Commander's Tactics score to MegaMek as an Initiative bonus, we discovered that this option is only used if the Campaign Options _also_ have SPA, Edge, or Implant options enabled.
This PR moves the Tactics options check outside of this larger block, simplifies some of the logic, and replaces some redundant code.
A force's Commander will now have their Command Bonus set to 0 by default, then modified by their Tactics score (if applicable and Commander Initiative is enabled).
There are plans to massively overhaul Initiative bonus code and calculations for 0.50.05, so I tried to keep this change very localized.
Testing:
- Started new scenarios using CO with Tactics, using various Campaign Option settings.
=> Uncouple Tactics-based Commander Init setting from SPA, Edge, and Implant options

MekHQ/resources/mekhq/resources/ReplacementLimbDialog.properties, MekHQ/src/mekhq/campaign/mod/am/InjuryTypes.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/src/mekhq/gui/dialog/ReplacementLimbDialog.java
- Updated the minimum Doctor skill level required for 'Replacement Limb Types 3, 4, and 5' from to total 5+.
- Adjusted related logic in `PersonnelTableMouseAdapter` to use the `getFinalSkillValue` method for accurate skill evaluation.
- Refactored `ReplacementLimbDialog` to dynamically inject the new skill level requirement into the message description.
- Adjusted the message text in `ReplacementLimbDialog.properties` to make the skill level requirement configurable.
=> Increased Minimum Skill Requirement For Replacement Limb Procedures to Match RAW

MekHQ/src/mekhq/gui/adapter/UnitTableMouseAdapter.java
- Prevented `NullPointerException` by adding a check for null or blank input when setting the quality level.
- Ensures the method exits early if the user provides invalid input.
Fix Sentry `bbf5a2e3b53b4d488bb199996c7759a1`
=> Added Handling for When Unit Quality is Manually Set to Empty or `null` Quality

MekHQ/src/mekhq/gui/campaignOptions/contents/TurnoverAndRetentionTab.java
- Implemented the `setFieldKitchenIgnoreNonCombatants` method in `TurnoverAndRetentionTab.java` to allow toggling whether field kitchens ignore non-combatants.
=> Fixed Field Kitchen Ignore Non-Combatants Option

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
- Consolidated skill level imports for cleaner code and to avoid fully qualified calls.
- Replaced `getEmployerCode()` and employer code string checks with `getEmployerFaction()` and `Faction` object methods for clarity and consistency.
- Added `getEmployerNegotiatorModifier` method to calculate negotiation modifiers based on employer faction type, incorporating new logic for faction-specific negotiation difficulty.
- Adjusted contract negotiation logic to include the newly calculated negotiation modifiers across relevant clauses (command, salvage, support, transport).
This was added by QA request. In short, all it does is add some negative modifiers to the contract clause rolls to simulate counter negotiations from the employer. While this doesn't move things in a strictly RAW direction, …
=> Added Employer Modifiers to Contract Negotiations

MekHQ/src/mekhq/gui/stratcon/CampaignManagementDialog.java
- Changed `btnRemoveCVP` and `btnGMRemoveSP` to enable based on `gmMode` instead of point counts.
- Ensured consistency in button enabling logic for GM mode in the Campaign Management Dialog.
This just ensures these options are only usable if GM Mode is enabled, while also allowing GMs to take CVP and SP into negative, should they wish.
=> Disabled Remove CVP and Remove SP Options if GM Mode is Disabled; Allowed GMs to Take SP and CVP into Negative

MekHQ/src/mekhq/campaign/stratcon/SupportPointNegotiation.java
- Introduced a local variable to store current support points for improved readability.
- Updated the condition in the `while` loop to account for both negotiated and current support points.
Basically if support points were 1+ below cap the player's Admin personnel would generate support points up to the current amount + the cap. Essentially allowing the player to negotiate above the intended soft cap, so long as they ended each week with at least 1 SP below the soft cap.
This likely contributed significantly to the sense that players had 'infinite' SP.
I've marked this as 'high' because improving the SP economics is a particular pain point in 50.03 and I've been working hard  to see it in a more stable state in 50.04.
=> Fixed Support Point Generation Soft Cap

MekHQ/src/mekhq/campaign/parts/MissingPart.java
Fixes one of the issues in #6302 - Refit will now properly consider items reserved for refit planning.
=> Issue 6302: Refit will now properly consider different qualities as "used for refit planning"

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/Scenario.java, MekHQ/src/mekhq/campaign/stratcon/StratconScenario.java, MekHQ/src/mekhq/gui/BriefingTab.java
- Updated `setDeploymentTurnsForReinforcements` to include campaign and scenario context.
- Improved handling of transported units by creating and utilizing player transport relationships in scenarios.
- Refined logic for skipping transported units during deployment turn calculations.
- Introduced `addPlayerTransportRelationships` in `StratconScenario` to manage transport linkages directly within the campaign.
- Ensured proper initialization of player transport linkages in `Scenario` class.
This fixes an issue where mounted units (such as infantry) were being considered unmounted, because Transport ID wasn't set at that point. It appears this value is only set once the unit is loaded into MegaMek. I fixed this by hooking into Player Transport Linkages. This fix will not likely address …
=> Fixed Deployment Turn Calculation For Mounted Reinforcements

MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerRansomEventDialog.java
- Changed the resource bundle path from `mekhq.resources.PrisonerRansomEvent` to `mekhq.resources.PrisonerEvents` to correct or align with the proper resource file.
- Will resolve potential issues with missing references in prisoner ransom event dialogs.
=> Corrected Resource Bundle Reference In `PrisonerRansomEventDialog`

MekHQ/src/mekhq/campaign/force/Force.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/ResupplyUtilities.java, MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonEscapeScenario.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java, MekHQ/src/mekhq/gui/BriefingTab.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogInterception.java, MekHQ/src/mekhq/utilities/EntityUtilities.java
- Moved VTOL and aerial force utility methods from `ResupplyUtilities` to the `Force` class for better cohesion and encapsulation.
- Replaced `Campaign` references with `Hangar` in force resolution methods to improve decoupling and maintainability.
- Simplified deployment logic and aerial/VTOL determination logic in relevant classes by centralizing functionality in `Force`.
- Updated force sorting logic to improve handling of map types, including better differentiation for airborne and aerospace forces.
- Enhanced error handling to log missing force entries when accessing by ID.
Fix #6315
This does three things:
- It moves the various 'does this force contain x' utility methods out of resupplies and into force, so they're more accessible. It also tidies them up a bit so they're more …
=> Fixed MekHQ Throwing Meks into Low Altitude Scenarios

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Added a `break` statement to stop unnecessary iterations after finding the correct force template.
- Improved performance and prevented potential overwrites by halting further template checks once a match is found.
The correction added in #6317 works perfectly fine, but paranoia called me to double-check everything before launch and I spotted that I missed an opportunity for an early exit. It's not needed, the size of the array we're looping through is tiny, but if it's worth doing, it's doing properly. Or however the saying goes.
=> Added Early Exit for Objective Determination Self-Correction Loop

MekHQ/resources/mekhq/resources/RandomDependents.properties, MekHQ/src/mekhq/campaign/personnel/RandomDependents.java
- Removed dynamic role assignment for dependents, defaulting to "Dependent" in join force reports.
- Updated resource properties to reflect the simplified role reporting.
- Streamlined code by eliminating unnecessary role variable.
Fix #6329
=> Corrected Dependent Arrival Reporting

MekHQ/src/mekhq/campaign/stratcon/StratconFacility.java, MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Added `isOwnerAlliedToPlayer` method in `StratconFacility` to determine if the facility owner is allied with the player.
- Updated `StratconRulesManager` to properly skip scanning only when facilities are owned by non-allied entities.
Fix #6337
=> Deploying to an Allied Facility No Longer Blocks Scanning

MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Corrected the logic to properly determine if there are prisoners (`isEmpty` to `!isEmpty`).
- Ensured the `PrisonersNagDialog` is displayed when there are current prisoners in an active contract.
Fix #6336
During development we had a weird situation where this dialog was triggering when prisoners weren't present. We went ahead and fixed the issue, and it was concluded to have just been faulty logic. Which, it turns out, was correct. Just not in the way we thought. This is now _definitely_ fixed. For realties this time.... I hope.
=> Fixed Prisoners Check Logic in NagController

MekHQ/data/scenariomodifiers/AlliedAirGarrison.xml
- Changed `<syncDeploymentType>` from "None" to "Opposite" to adjust deployment behavior.
- Added `<syncedForceName>` with value "Player" to specify the linked force for synchronization.
Fix #6343
So this was working as intended, but I absolutely see the issues raised by OP. In particular, due to the size of the ground map, ASF starting in the center are liable to just fly off board on turn 1, making deploying them there somewhat redundant. Now they deploy opposite the player, ready to bomb their deployment zone. As Blake intended.
=> Updated Allied Air Garrison Spawn Location

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/gui/panels/StartupScreenPanel.java
- allow setting MekHQ Options from splash screen
- so that you can set the user folder without having to load a campaign when upgrading to a new version
=> allow setting MekHQ Options from splash screen

MekHQ/data/scenariotemplates/Annihilation.xml, MekHQ/data/scenariotemplates/Assassination.xml, MekHQ/data/scenariotemplates/Base Defense.xml, MekHQ/data/scenariotemplates/Chasing a Rumor.xml, MekHQ/data/scenariotemplates/Covert Strike.xml, MekHQ/data/scenariotemplates/Decoy Engagement.xml, MekHQ/data/scenariotemplates/Decoy Interception.xml, MekHQ/data/scenariotemplates/Engagement.xml, MekHQ/data/scenariotemplates/Frontier Assassination.xml, MekHQ/data/scenariotemplates/Frontline Engagement.xml, MekHQ/data/scenariotemplates/Heavy Recon Evasion.xml, MekHQ/data/scenariotemplates/Low-Atmosphere Air Intercept.xml, MekHQ/data/scenariotemplates/Low-Atmosphere Reinforcements Intercepted.xml, MekHQ/data/scenariotemplates/Minor Engagement.xml, MekHQ/data/scenariotemplates/Pivotal Battle.xml, MekHQ/data/scenariotemplates/Recon Evasion.xml, MekHQ/data/scenariotemplates/Reconnaissance Interdiction.xml, MekHQ/data/scenariotemplates/Reinforcements Intercepted.xml, MekHQ/data/scenariotemplates/Space Aerospace Intercept.xml, MekHQ/data/scenariotemplates/Space Reinforcements Intercepted.xml, MekHQ/data/scenariotemplates/VIP Ambush.xml, MekHQ/data/scenariotemplates/VIP Defense.xml
- Cleaned up scenario template XML files to remove `<deploymentZone>0</deploymentZone>` entries.
- Affected 22 scenario templates to ensure consistent deployment zone configuration.
This change stops player forces from getting the 'any' deployment zone. Now they will always be deployed to one of the edge zones (including 'any edge'), or 'center'
=> Removed Player Deployment Zone "ANY" From Scenario Templates

MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/PrisonersNagLogic.java, MekHQ/unittests/mekhq/gui/dialog/nagDialogs/nagLogic/PrisonersNagLogicTest.java
- Corrected logic in `PrisonersNagLogic.hasPrisoners` to properly handle cases with and without active contracts.
- Updated related unit tests in `PrisonersNagLogicTest` to align with the corrected logic.
This basically undoes the 'fix' that was implemented in 50.04's dev cycle that ultimately led us to the constant nagging bug in release. Between this and the logic fix I added yesterday this nag should be working as intended.
What a mess...
=> Fixed Logic Error In Prisoners Nag Yet Again

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java, MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java
- Added date and faction retrieval methods (`getDate` and `getFaction`) to `GeneralTab`.
- Updated `BiographyTab` to accept `GeneralTab` as a parameter for accessing campaign configurations.
- Replaced direct `campaign` date and faction references in `BiographyTab` with `GeneralTab` methods to ensure we're fetching the right data.
- Updated tooltip and label in Campaign Options to include a warning about faction-specific system toggling.
- Improved default behavior for `SpecifiedPlanet` when no selection is made by setting it to Terra.
Purely out of force of habit I made the mistake of fetching faction and date information from `campaign`, however this becomes an issue if CO IIC is being triggered during campaign creation, as it would cause CO IIC to pull the default values from the …
=> Updated Date and Faction Handling in Campaign Options IIC

MekHQ/src/mekhq/gui/view/ForceViewPanel.java
- Corrected the method used to calculate the Battle Value in the `ForceViewPanel` to replace redundant per-unit BV calculations with a single call to `force.getTotalBV()`.
- Updated BV calculation in the unit summary to account for C3.
Fix #6351
The original issue report stated that the deploy force dialog displayed the wrong BV, in fact it was actually force view. Force view wasn't factoring in C3, now it does.
=> Updated BV Display in TO&E to Account for C3

MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/UntreatedPersonnelNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/nagLogic/UntreatedPersonnelNagLogic.java, MekHQ/unittests/mekhq/gui/dialog/nagDialogs/nagLogic/UntreatedPersonnelNagLogicTest.java
- Integrated a check to determine if patients exceed available doctor capacity when automatic medical assignment optimization is enabled.
- Updated unit tests to cover scenarios for doctor capacity and optimized assignment logic.
Fix #6353
Nags are triggered prior to the new day action - so the player can interrupt new day advancement. However autoInfirmary runs _after_ the new day processes have started. This means the infirmary nag will trigger, to advise the player they have untended patients, but then the whole situation will be solved automatically if the player proceeds.
Now, if the player has autoInfirmary enabled they will only get the infirmary nag if the total number of patients exceeds the total capacity of the campaign's doctors.
**Note:** this nag still will **not** trigger …
=> Updated Untreated Injuries Nag Dialog to Account for AutoInfirmary

MekHQ/resources/mekhq/resources/PrisonerEvents.properties, MekHQ/src/mekhq/gui/baseComponents/MHQDialogImmersive.java, MekHQ/src/mekhq/gui/dialog/MercenaryAuctionDialog.java, MekHQ/src/mekhq/gui/dialog/MissionEndPrisonerDialog.java
- Enhanced `MHQDialogImmersive` to define a default button option when dialog is closed or canceled.
- Adjusted the order of buttons in `MercenaryAuctionDialog` and `MissionEndPrisonerDialog` to align with this new functionality.
- Updated `PrisonerEvents.properties` to clarify 'cancel dialog' results.
Previously we disallowed users from canceling Immersive Dialogs. That made sense, from a developmental standpoint, but it created a poor play experience. I've gone through and confirmed all existing Immersive Dialogs will have expected behavior when the dialog is canceled. With this feature in place my next move will be to replace the nag dialogs with Immersive Dialogs.
=> Improved Immersive Dialog Behavior

MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
- Moved "Change Force Type" menu initialization outside of AtB conditional block.
Fix #6355
=> Fixed Force Type Changing Being Unavailable in Non-StratCon, Non-AtB Campaigns

MekHQ/resources/mekhq/resources/Fatigue.properties
- Replaced `%s` placeholders with internationalization placeholders (`{0}`, `{1}`, `{2}`).
Fix #6357
=> Fixed Fatigue Status Report Update Messages

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/resources/mekhq/resources/Glossary.properties, MekHQ/resources/mekhq/resources/NagDialogs.properties, MekHQ/src/mekhq/gui/dialog/nagDialogs/AdminStrainNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Refactored `AdminStrainNagDialog` to use `ImmersiveDialogSimple` for a more modular and customizable dialog implementation.
- Replaced `AbstractMHQNagDialog` inheritance with a standalone class implementation to streamline functionality.
- Updated `NagController` to account for `AdminStrainNagDialog`'s restructuring, specifically replacing `wasAdvanceDayCanceled()` with `shouldCancelAdvanceDay()`.
=> Updated Admin Strain Nag to Use Immersive Dialog

MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogCore.java
- Ensured that scroll panes in immersive dialogs start scrolled to the top by adding a `SwingUtilities.invokeLater` call.
=> Fixed Scroll Pane Starting Position In Immersive Dialogs

MekHQ/src/mekhq/gui/dialog/GlossaryDialog.java
- Ensured the GlossaryDialog's scroll pane defaults to the top position on load.
- Corrected `handleImmersiveHyperlinkClick` to use the correct reference (`this` instead of `parent`).
Regarding the second point, basically if a user clicks on a hyperlink inside a glossary dialog it should trigger a second dialog to appear, fading away the previous until the current is discarded. However, I was incorrectly hooking into 'parent' and not the current glossary dialog. This meant when consecutive dialogs were opened the _original_ dialog was rendered visible/hidden, causing MekHQ to lock-up entirely.
=> Fixed MekHQ Lockup Caused by Consecutive Glossary Dialogs; Fixed Scroll Pane Start Position in Glossary Dialogs

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/resources/mekhq/resources/NagDialogs.properties, MekHQ/src/mekhq/gui/dialog/nagDialogs/AdminStrainNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/DeploymentShortfallNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Refactored `DeploymentShortfallNagDialog` to utilize `ImmersiveDialogSimple` for improved modularity and customization.
- Replaced inheritance from `AbstractMHQNagDialog` with a standalone class to simplify and streamline the implementation.
- Updated NagController logic to replace `wasAdvanceDayCanceled()` with `shouldCancelAdvanceDay()` to reflect the updated behavior.
=> Updated Deployment Shortfall Nag To Use Immersive Dialog

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/resources/mekhq/resources/NagDialogs.properties, MekHQ/src/mekhq/gui/dialog/nagDialogs/EndContractNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Refactored `EndContractNagDialog` to utilize `ImmersiveDialogSimple` for improved modularity and customization.
- Replaced inheritance from `AbstractMHQNagDialog` with a standalone class to simplify and streamline the implementation.
- Updated NagController logic to replace `wasAdvanceDayCanceled()` with `shouldCancelAdvanceDay()` to reflect the updated behavior.
=> Updated Contract End Nag To Use Immersive Dialog

MekHQ/src/mekhq/gui/dialog/GlossaryDialog.java
- Increased `CENTER_WIDTH` from 400 to 800 for improved usability and readability.
- Increased `CENTER_HEIGHT` from 300 to 400 for better display of glossary content.
Some of the glossary entries are quite large, so I opted to increase the dialog size to better accommodate them.
=> Adjusted Glossary Dialog Dimensions

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/resources/mekhq/resources/NagDialogs.properties, MekHQ/src/mekhq/gui/dialog/nagDialogs/AdminStrainNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/DeploymentShortfallNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Refactored `InsufficientAstechsNagDialog` to utilize `ImmersiveDialogSimple` for improved modularity and customization.
- Replaced inheritance from `AbstractMHQNagDialog` with a standalone class to simplify and streamline the implementation.
- Updated NagController logic to replace `wasAdvanceDayCanceled()` with `shouldCancelAdvanceDay()` to reflect the updated behavior.
=> Updated Insufficient Astechs Nag To Use Immersive Dialog

MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/resources/mekhq/resources/NagDialogs.properties, MekHQ/src/mekhq/gui/dialog/nagDialogs/DeploymentShortfallNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/EndContractNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InvalidFactionNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Refactored `InvalidFactionNagDialog` to utilize `ImmersiveDialogSimple` for improved modularity and customization.
- Replaced inheritance from `AbstractMHQNagDialog` with a standalone class to simplify and streamline the implementation.
- Updated NagController logic to replace `wasAdvanceDayCanceled()` with `shouldCancelAdvanceDay()` to reflect the updated behavior.
=> Updated Invalid Faction Nag To Use Immersive Dialog

MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogNag.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/AdminStrainNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/DeploymentShortfallNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/EndContractNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechTimeNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientAstechsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InsufficientMedicsNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/InvalidFactionNagDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java
- Consolidated the common nag dialog logic into a newly created `ImmersiveDialogNag` base class to reduce code duplication.
- Updated `AdminStrainNagDialog`, `EndContractNagDialog`, and `InsufficientAstechsNagDialog` to extend `ImmersiveDialogNag`.
Nothing super fancy here, just some consolidation of code so we don't have so much duplication.
=> Created `ImmersiveDialogNag` Base Class; Rolled Out Base Class to Previously Edited Nags

MekHQ/src/mekhq/gui/baseComponents/AbstractMHQNagDialog.java
- Added `@Deprecated` annotation to `AbstractMHQNagDialog`, specifying version `0.50.05` and indicating it is marked for removal.
=> Marked `AbstractMHQNagDialog` as Deprecated

MekHQ/src/mekhq/MekHQ.java
I've added some null safeties and error triggers to a specific section of scenario resolution. Something is breaking at that point, and I really need more data to know why. Once the below Sentry error is resolved these safeties can probably be removed.
https://sentry.tapenvy.us/organizations/tapenvyus/issues/4069/?alert_rule_id=13&alert_type=issue&notification_uuid=d2dad6b9-c01e-47ad-873b-a48f7a4c10e0&project=10&referrer=discord
I've marked this case as 'high', but in absence of user made error reports it's hard to know the extent of the problem.
=> Added Null Checks To Prevent Potential Runtime Exceptions During Scenario Resolution

MekHQ/data/universe/academies/Local Academies.xml, MekHQ/data/universe/academies/Prestigious Academies.xml, MekHQ/data/universe/academies/Unit Education.xml
- Updated various academy curricula to replace the "Scrounge" skill with "Negotiation" or removed it where appropriate.
Scrounge was deprecated in #6430, so it doesn't make sense to have Academies issue it.
=> Replaced Scrounge With Negotiation or Removed It Across Academy Curricula

MekHQ/src/mekhq/campaign/mission/enums/CombatRole.java, MekHQ/src/mekhq/gui/view/LanceAssignmentView.java
- Introduced `isCombatRole` method in `CombatRole` enum to classify roles as combat-related (FRONTLINE, MANEUVER, PATROL).
- Updated deployment eligibility logic in `LanceAssignmentView` to account for Cadre Duty contracts and suitable role classification (`isTraining` or `isCombatRole`).
Fix #6434
=> Corrected Briefing Room Combat Team Counter

MekHQ/src/mekhq/campaign/handler/PostScenarioDialogHandler.java
- Added a try-catch block around `MekHQ.triggerEvent` to handle exceptions during scenario resolution.
- Introduced logging using `MMLogger` to capture detailed error messages and stack traces.
- Added an error dialog to inform the user of critical issues and prompt them to report the problem.
A part of the investigation into Sentry report: https://sentry.tapenvy.us/organizations/tapenvyus/issues/4078/?alert_rule_id=13&alert_type=issue&notification_uuid=17ad74c9-582d-4287-8a72-ea9e897dca1e&project=10&referrer=discord
=> Added Error Handling to Scenario Resolution in `PostScenarioDialogHandler`

MekHQ/src/mekhq/campaign/unit/AbstractTransportedUnitsSummary.java, MekHQ/src/mekhq/campaign/unit/ShipTransportedUnitsSummary.java, MekHQ/src/mekhq/campaign/unit/TacticalTransportedUnitsSummary.java, MekHQ/src/mekhq/campaign/unit/TowTransportedUnitsSummary.java
Fixes #6399
It was saving the correct `TransporterType` it just wasn't utilized when recalculating the transport's space. Now it will attempt to load entities into the correct `TransporterType`/class of `Transporter`.
=> Issue 6399: Load Entity in Specific Transporter when Recalculating Free Space

MekHQ/src/mekhq/gui/dialog/CreateCharacterDialog.java, MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- Added the `clamp` utility function to ensure skill levels and bonuses are constrained within valid ranges.
- Updated `CustomizePersonDialog` and `CreateCharacterDialog` to use `clamp` for correcting invalid skill values modified by users.
- Prevented issues with JSpinner components caused by out-of-range skill values.
- Ensured consistent application of min/max constraints for skills (level: 0-10, bonus: -8 to 8).
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4086/?alert_rule_id=13&alert_type=issue&notification_uuid=305fb781-7f05-4e38-b178-39be985aabb9&project=10&referrer=discord)
=> Fixed Skill Value Out-Of-Range Errors in Dialogs

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Introduced helper methods `getCampaign()` and `getCampaignOptions()` to streamline campaign data access.
- Replaced multiple instances of `gui.getCampaign()` and `gui.getCampaign().getCampaignOptions()` with new helper methods for improved readability and maintainability.
- Updated references throughout the various command cases to use the new helper methods consistently.
This PR replaces 164 instances of `gui.getCampaign()` with the `getCampaign()` helper.
And 45 instances of `gui.getCampaign().getCampaignOptions()` with the `getCampaignOptions()` helper.
=>  Added Helper Methods to `PersonnelTableMouseAdapter` for Cleaner `Campaign` Access

MekHQ/src/mekhq/campaign/randomEvents/GrayMonday.java
- Corrected the date comparison logic in `GrayMonday.java` to use `today.isBefore()` instead of `EVENT_DATE_GRAY_MONDAY.isBefore()`.
Now Gray Monday's effects will actually end, rather than continuing into perpetuity. _Mea culpa_.
=> Fixed "Every Monday is a Gray Monday" Bug

MekHQ/src/mekhq/campaign/Campaign.java
#6161 was not drastic enough. It should be two-month minimum for PA deliveries. This drags delivery times out even further for Planetary Acquisitions.
=> Make planetary acquisitions even slower to be in line with RAW

MekHQ/data/universe/planetary_systems/canon_systems/FellWind.yml, MekHQ/data/universe/planetary_systems/canon_systems/GloryCei.yml, MekHQ/data/universe/planetary_systems/canon_systems/Graystone.yml, MekHQ/data/universe/planetary_systems/canon_systems/Hallelujah.yml, MekHQ/data/universe/planetary_systems/canon_systems/Holdout.yml, MekHQ/data/universe/planetary_systems/canon_systems/Khanquest.yml, MekHQ/data/universe/planetary_systems/canon_systems/Matteo.yml, MekHQ/data/universe/planetary_systems/canon_systems/Winston.yml
SUCS made some changes to their numeric ids when they added planets from the Aurigan sourcebook. Its just a very few at the end of [this document](https://docs.google.com/spreadsheets/d/17GFFFp1sGvSYcs8DBryleQGvqgppX8EZ8MuF6Oq3or8/edit?usp=sharing), but we need to change them to be inline with SUCS.
=> Correct SUCS id on a few planets

MekHQ/resources/mekhq/resources/GUI.properties
- Deleted remaining unused Nag Dialog-related strings from `GUI.properties`, including titles and button texts.
=> Removed Unused Nag Dialog Strings From GUI Properties

MekHQ/src/mekhq/campaign/mod/am/InjuryTypes.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
- Added a new injury type: `Postpartum Recovery` to the Advanced Medical sub-system for tracking postpartum recovery effects.
- Implemented postpartum effects on mothers, including the addition of recovery-related modifiers (e.g., Gunnery and Piloting penalties) and potential internal bleeding risks.
- Updated the `birth` method in `AbstractProcreation` to apply postpartum effects based on campaign options.
- Registered the `Postpartum Recovery` injury type in the `InjuryTypes` class.
This is meant to accompany #6482 (though doesn't require it) and adds a 10-day recovery period after a character give birth (if AM is enabled), or inflicts a single _Hit_ (if AM is disabled). This accounts for postpartum recovery and should help reduce the impression that a character is fighting fit the …
=> Added Postpartum Recovery Injury Type And Effects

MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Isolated DropShip Defense.xml
- Eliminated redundant roles such as `MISSILE_ARTILLERY` and `MIXED_ARTILLERY`.
This was a consequence of me misunderstanding how the `ARTILLERY`, `MISSILE_ARTILLERY`, and `MIXED_ARTILLERY` roles were configured.
Switching up the roles should help reduce the spam of specific artillery units when these scenarios are generated.
=> Removed Redundant Artillery Role Entries in Scenario Templates

MekHQ/src/mekhq/gui/RepairTab.java
- Added `@Nullable` annotation to indicate the method can return null.
- Replaced assertions with proper null checks for `techTable` and `techsModel`.
- Logged errors for uninitialized `techTable` and `techsModel` to improve debugging.
- Ensured the method gracefully handles cases where no row is selected.
=> Updated `RepairTab` to Improve Handling of `null` States in `getSelectedTech`

MekHQ/src/mekhq/gui/RepairTab.java
- Replaced repeated `getCampaign().getCampaignOptions()` calls with direct `getCampaignOptions()` to streamline code readability.
=> Simplified Campaign Options Access In `RepairTab`

MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/gui/baseComponents/AbstractMHQNagDialog.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogCore.java, MekHQ/src/mekhq/gui/campaignOptions/SelectPresetDialog.java, MekHQ/src/mekhq/gui/campaignOptions/components/CampaignOptionsHeaderPanel.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java, MekHQ/src/mekhq/gui/dialog/ContractAutomationDialog.java, MekHQ/src/mekhq/gui/dialog/NewsDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/GrayMondayDialog.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogAbandonedConvoy.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogContractStart.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogInterception.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogItinerary.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogPlayerConvoyOption.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogResupplyFocus.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogRoleplayEvent.java, MekHQ/src/mekhq/gui/dialog/resupplyAndCaches/DialogSwindled.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java, MekHQ/src/mekhq/utilities/ImageUtilities.java
- Replaced usage of `scaleImageIconToWidth` with the new `scaleImageIcon` method across multiple classes.
- Marked `scaleImageIconToWidth` as deprecated with a warning to use `scaleImageIcon`.
- Ensured all affected image scaling operations now account for GUI scaling factors and maintain aspect ratios.
This just replaces the image scaling utility with something that's a bit more feature complete and safer to use.
=> Replaced Old Image Scaling Method with New

MekHQ/src/mekhq/campaign/CurrentLocation.java, MekHQ/src/mekhq/campaign/personnel/SkillDeprecationTool.java, MekHQ/src/mekhq/campaign/personnel/lifeEvents/BirthAnnouncement.java, MekHQ/src/mekhq/campaign/personnel/lifeEvents/ComingOfAgeAnnouncement.java, MekHQ/src/mekhq/campaign/randomEvents/MercenaryAuction.java, MekHQ/src/mekhq/campaign/randomEvents/RoninOffer.java, MekHQ/src/mekhq/gui/CampaignGUI.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogCore.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogNag.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogSimple.java, MekHQ/src/mekhq/gui/dialog/CampaignHasProblemOnLoad.java, MekHQ/src/mekhq/gui/dialog/DefectionOffer.java, MekHQ/src/mekhq/gui/dialog/MercenaryAuctionDialog.java, MekHQ/src/mekhq/gui/dialog/MissionEndPrisonerDefectorDialog.java, MekHQ/src/mekhq/gui/dialog/MissionEndPrisonerDialog.java, MekHQ/src/mekhq/gui/dialog/NewsDialog.java, MekHQ/src/mekhq/gui/dialog/ReplacementLimbDialog.java, MekHQ/src/mekhq/gui/dialog/VocationalExperienceAwardDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/GrayMondayDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerEscapeeScenarioDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerEventDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerEventResultsDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerRansomEventDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerWarningDialog.java, MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerWarningResultsDialog.java
- Refactored `ImmersiveDialogCore` to include an optional `ImageIcon` parameter for enhanced visual support in dialogs.
- Modified `createCenterBox` method to display the image above the message if provided.
- Updated all constructors of immersive dialog classes to handle the new `ImageIcon` parameter (defaulting to null where not applicable).
- Improved documentation for dialog-related classes to reflect the changes and clarify parameter purposes.
- Rearranged imports for consistency across impacted files.
Requires #6494
This expands what we can do with immersive dialogs in a cool new direction, making it effortless to add images to the dialog. The below is just an example, using the ACAR splash image.
=> Added Support for Optional Image Icons in Immersive Dialogs

MekHQ/src/mekhq/campaign/randomEvents/MercenaryAuction.java
- Corrected the minimum bid logic by removing its dependency on support points, ensuring it now scales accurately with the required combat teams.
- Adjusted the final bid computation to account for the updated minimum bid calculation.
Marking this as 'high' as it prevented use of this system.
=> Fixed Minimum Bid Calculation in Mercenary Auction

MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsDialog.java
- Removed the `triggerStartUpDialogs` method, simplifying the startup process.
- Integrated the `StratCon` notice logic directly into the campaign options check, streamlining dialog triggering.
_Somehow_ this was managing to try and initialize _before_ campaign was initialized. Which is bonkers, but I'm guessing there is some legacy decisions in the dialog causing issues.
=> Removed Company Generator on Start Up

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
- Removed `getUnofficialMultiplier` method and its associated logic for adjusting contract pay.
This was causing some serious chug due to the need to recalculate contract difficulty.
=> Removed Unofficial Multiplier From Contract Pay Calculation

MekHQ/src/mekhq/campaign/parts/equipment/EquipmentPart.java, MekHQ/src/mekhq/campaign/parts/equipment/MissingEquipmentPart.java
Fix #6515
Fix #6516
Basically, some parts have their value dynamically determined based on the tonnage of the unit they're being attached to. In those cases we were comparing sticker price -- basically the base price with no quality modifiers and so on. However, when a part is classified as 'missing' - for example, when it get blown to smithereens, or is scrapped - it has it's price fixed at 0 C-Bills.
CGL ruled that variable priced items could not be fitted to units of tonnage other than the tonnage they were designed for. A 35-ton 'Mek couldn't use a Lance designed for a 40-ton 'Mek, for example, even though the actual weight of the lance is identical for both.
Originally, we got around this issue by comparing the sticker price of each item. Which ultimately then led us to the problem I …
=> Allow Dynamically Priced Parts to be Replaced in Repair Bay

MekHQ/src/mekhq/campaign/parts/AmmoStorage.java, MekHQ/src/mekhq/campaign/parts/equipment/AmmoBin.java, MekHQ/unittests/mekhq/campaign/parts/equipment/AmmoBinTest.java
In MekHQ, `AmmoBin::isSamePartType` does not properly recognize AC ammo as being the same part type. Two AC/5 ammo bins, for example. This led to any refit in MHQ for a unit that had AC ammo would show as needing changed in the refit even if nothing was changed. 
In the below screenshots, nothing was changed for this unit. I right clicked the unit in the Hangar and selected customize > customize in mek lab. I made no changes to the unit before taking the screenshots.
Before Fix:
After Fix:
=> Fixes Compatibility for AC Ammo in MHQ

MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/unittests/mekhq/campaign/unit/UnitPersonTest.java
Fixes #6481 
For history.txt:
```+ Fix #6481: Soldiers getting "stuck" to previous unit```
If a person was a tech for a unit, it would stop processing. It is possible for a person to be both a tech and crew - for infantry, the leader fills that role. That was the issue here - the unit's leader was also the tech. When removing personnel from the unit, it would remove the leader from the vehicle's tech and then stop, leaving the unit to still have that person as a crew.
=> Issue 6481: Personnel that are both the tech and crew for a unit will now be properly removed from both

MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogCore.java, MekHQ/src/mekhq/utilities/ImageUtilities.java
- Replaced `new Dimension` calls with `scaleForGUI` to improve scalability.
- Enhanced `scaleImageIcon` to use high-quality rendering with `Graphics2D` for better image scaling.
- Adjusted image-related dimensions and padding for improved GUI rendering.
This just makes the image scaler player nicer with our relatively small portraits, allowing us to have larger portraits (such as in Immersive Dialogs) without them appearing pixelated.
While I was there I also went and updated Immersive Dialog to remove some awkward scaling.
=> Improved Image Scaling Utility; Improved Portrait Display in Immersive Dialogs

MekHQ/resources/mekhq/resources/SkillAttribute.properties, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/skills/Attributes.java, MekHQ/src/mekhq/campaign/personnel/skills/enums/SkillAttribute.java, MekHQ/unittests/mekhq/campaign/personnel/skills/AttributesTest.java, MekHQ/unittests/mekhq/campaign/personnel/skills/enums/SkillAttributeTest.java
- Introduced localized label, short name, and description retrieval methods in `SkillAttribute`.
- Implemented `Attributes` in `Person` to track character attribute scores with getter, setter, and modifier methods.
- Updated XML read/write functionality in `Person` to handle `Attributes` persistence.
- Added comprehensive unit tests for `SkillAttribute` and `Attributes` classes to ensure new methods' correctness.
This PR doesn't really do much on its' own and is more setup for future stuff. Essentially all it does is process and store a character's Attribute scores. There is no way to access, or influence these. Characters just get assigned the default of `5` in every attribute, which is stored and loaded alongside the rest of their stats.
Of special note, mhq handles Edge very …
=> Added ATOW Attribute Tracking and Utility Methods

MekHQ/src/mekhq/campaign/parts/Part.java
Improved the display for in stock parts when salvaging: 
Relates to #6178 and #6527
=> Issue 6178: [RFE] Improved Display for in stock parts while salvaging

MekHQ/src/mekhq/campaign/parts/MissingEnginePart.java, MekHQ/src/mekhq/campaign/parts/PartInUse.java
Engines with the same rating but different unit tonnages cost different and are not interchangeable. This updates the parts in use table to reflect that. Prior to this change it only showed engine tonnage for Clan engines. It now shows & differentiates for IS engines too. 
An engine's actual tonnage doesn't matter when differentiating two engines, it's the unit's tonnage that matters.
=> Show engine tonnage in parts-in-use table

MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java, MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java
Fixes #6548 
On the Personnel table, Age was recently updated to show a person's Age instead of birthday. However, the sort wasn't changed. Unfortunately, the sort won't work properly without the full birthday, otherwise people of the same age-year won't be sorted within their age. 
To fix this I set Age back to having a date as a cell value and updated the Mass Personnel Training (`BatchXPDialoig`) to use `getDisplayValue` from the `PersonnelTableModelColumn`.
=> Issue 6548: PersonnelTableModelColumn's cell value should be a date to allow proper sorting

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogCore.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogNag.java, MekHQ/src/mekhq/gui/baseComponents/immersiveDialogs/ImmersiveDialogSimple.java
- Replaced fallback campaign faction icons with proper handling of speaker portraits.
- Improved image scaling for speaker portraits to maintain quality.
- Added fallback setting to use campaign faction or custom icon if the speaker has a default portrait.
=> Fixed Campaign Portrait Fallback; Updated Immersive Dialog Visuals

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java, MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/PrisonerEventManagerTest.java
Fix for #6560 
- prevent temporaryPrisonerCapacity from going below MINIMUM_TEMPORARY_CAPACITY
negative values should not be possible at all, but with 0% it would still be 
impossible to contain the prisoners with any number of additional forces.
- MINIMUM_TEMPORARY_CAPACITY = 25 (25% normal prisoner capacity) 
is an arbitrary number. I tried to balance being able to recover from an bad event
and being to easy to recove. This value should be subject to further testing
- Changed the formular for degreeOfChange so that a lower value for temporaryPrisonerCapacity
is not slower degrading than a higher temporaryPrisonerCapacity
- Updated the UnitTest to reflect the changes in degreeOfChange
=> Issue 6560: Fix for negative temporary prisoner capacity

MekHQ/resources/mekhq/resources/MarginOfSuccess.properties, MekHQ/resources/mekhq/resources/SkillCheckUtility.properties, MekHQ/src/mekhq/campaign/personnel/skills/Attributes.java, MekHQ/src/mekhq/campaign/personnel/skills/Skill.java, MekHQ/src/mekhq/campaign/personnel/skills/SkillCheckUtility.java, MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java, MekHQ/src/mekhq/campaign/personnel/skills/enums/MarginOfSuccess.java, MekHQ/src/mekhq/gui/dialog/CreateCharacterDialog.java, MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java, MekHQ/unittests/mekhq/campaign/personnel/skills/SkillCheckUtilityTest.java
Under our current implementation to perform a skill check a developer needs to perform the following actions:
- Check whether the character even has the skill. Failing to do this will result in an NPE.
- Determine what the final target number is, manually adding modifiers as necessary.
- Make the actual roll.
- Manually check whether the check was passed or failed. If necessary, add handler code so we can factor in Margins of Success.
- Determine whether Edge is used and if so, manually factor that in.
Speaking from extensive experience, this is a right pain in the bum and fraught with easy to make mistakes. Not checking whether the character _has_ the skill being the biggest.
All of this becomes exacerbated as characters become increasingly more complex. With interactions between ATOW …
=> Added Dedicated Skill Check Class Utility

MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
- Updated skill cost array initialization to use explicit values and provide clearer structure.
- Replaced incorrect `S_ART_DANCING` references with appropriate constants for corresponding art skills.
=> Corrected Art Skill Type Names

MekHQ/src/mekhq/campaign/parts/Refit.java
- Changed `oldUnitBays` and `newUnitBays` from immutable lists to mutable ArrayLists.
Because these lists were immutable we'd run into errors any time a user tried to refit them.
I'm marking this as 'high' because it completely prevents the refitting of affected units. I'm surprised we didn't have any issue reports.
=> Fixed Refitting Units With Bays

MekHQ/src/mekhq/campaign/personnel/Person.java
When resetting a tech's time, this was causing Large Vessel Crewmembers to not be considered a tech, which is incorrect.
=> When restoring techs time, Large Vessel Crews should be considered techs.

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/universe/UnitGeneratorParameters.java
- Introduced `validateOffBoardCapabilities` method to ensure forces have necessary artillery for off-board deployment, defaulting to on-board deployment if not.
- Enhanced `null` safety checks and logging in unit generation methods to prevent potential `NullPointerExceptions`.
- Fixed `UnitGeneratorParameters` to implement `Cloneable`.
- Added `toString` method to `UnitGeneratorParameters` for clearer logging in the event of an error.
Fix #6596
So this is a bit of a mixed bundle. _Chiefly_ it adds validation to NPC force generation so that we're not trying to deploy non-artillery units off-board.
During the course of adding that I stumbled across a NPE produced by `UnitGeneratorParameters` that led down a whole rabbit hole. The conclusion of which found that we weren't implementing …
=> Fix #6596: Added Off-Board Deployment Validation and Improved Generation Safety

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/resources/mekhq/resources/DiscretionarySpending.properties, MekHQ/resources/mekhq/resources/Finances.properties, MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/finances/enums/TransactionType.java, MekHQ/src/mekhq/campaign/personnel/DiscretionarySpending.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java
- Implemented a discretionary spending system using the "Wealth" trait, with rules inspired by A Time of War: Companion.
- Added configuration option to enable monthly wealth reinvestment via Campaign Options.
- Introduced "Extreme Expenditure" action for personnel, affecting wealth, loyalty, and generating reports.
- Expanded finances logic and resources to include "Wealth" as a new transaction type.
- Integrated spending calculations and options into the campaign process and GUI.OnWealth.tooltip` property to clarify fund reinvestment by campaign commanders.
- Removed extraneous whitespace from `DiscretionarySpending.properties`.
This implements a system inspired by the Discretionary spending rules in ATOW: Companion. Optionally, each month the campaign commander will reinvest their …
=> Added Discretionary Spending System Based on Wealth Trait

MekHQ/src/mekhq/gui/CommandCenterTab.java
- Modified the condition to show facility capacities to include checks for prisoner capture style settings.
- Removed redundant fatigue-specific logic for setting the facility report.
=>  Fixed Facility Capacities Display Logic In Command Center Tab

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/campaign/RandomSkillPreferences.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/generator/AbstractSkillGenerator.java, MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java, MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/src/mekhq/gui/campaignOptions/contents/AdvancementTab.java
- Introduced a new option to randomize traits during character creation, including Connections, Reputation, Wealth, and Unlucky scores.
- Updated `CampaignOptionsDialog.properties` with labels and tooltips for the new setting.
- Extended `RandomSkillPreferences` to support `randomizeTraits` with default settings and XML integration.
- Modified personnel generators to calculate and assign random trait values when the option is enabled.
- Added methods to the `Person` class for modifying traits with proper clamping to ensure values remain within defined limits.
- Updated `AdvancementTab` to include a checkbox for enabling or disabling the new randomization feature.
This is the last of the random character creation features needed to finish off Traits and Attributes. While I was working on …
=> Added Randomize Traits Option For Character Creation

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/gui/view/PersonViewPanel.java
- Replaced calls to `getEdge()` with `getAdjustedEdge()` to account for the "unlucky" trait in edge calculations.
- Updated `PersonViewPanel` to display adjusted edge values in the GUI.
- Modified the `resetCurrentEdge` method to reset based on the adjusted edge value.
- Incorporated safeguarded adjustments (e.g., ensuring edge values are non-negative) in calculations.
- Improved method documentation for `getEdge()` and `getAdjustedEdge()` to clarify usage and behavior.
When I first implemented Unlucky I modified the `getEdge` method. That was a poor call, as it meant we could no longer view Edge score without incorporating Unlucky. So I went back and moved Unlucky out of `getEdge` and created `getAdjustedEdge` which _does_ include Unlucky.
I then went through and updated relevant calls …
=> Refactored Edge Handling to Use Adjusted Edge Values

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
- Updated the condition in `StratconRulesManager` to include a check for the `bypassRoleRestrictions` flag when determining if suitable forces are empty.
- Prevented unintended infinite fallback to `getAvailableForceIDs` in the event no suitable forces exist, even with restrictions relaxed.
- Added detailed logging to indicate when no suitable combat teams are found. So we don't have to guess what happened if we get player reports that no scenarios are spawning.
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4224/?alert_rule_id=13&alert_type=issue&notification_uuid=7d506ef2-4432-4f64-93db-5fe078ff5a2a&project=10&referrer=discord)
=> Fixed Infinite Loop in `getAvailableForceIDs` (Sentry)

MekHQ/src/mekhq/campaign/stratcon/StratconCampaignState.java, MekHQ/src/mekhq/campaign/stratcon/StratconContractInitializer.java
- Refactored logic to extract reusable helper methods `getScenarioOdds` and `getDeploymentTime`, improving code clarity and maintainability.
- Introduced fallback mechanism to guarantee a minimum of one track in StratCon Areas of Operation, preventing cases where zero tracks are generated.
- Added `getTrackCount` method in `StratconCampaignState` to replace direct use of `getTracks().size()`.
- Corrected potential division by zero errors when distributing track objects by ensuring a valid track count.
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4226/?alert_rule_id=13&alert_type=issue&notification_uuid=5a293163-89b8-4422-8d28-bec81b1ed0bd&project=10&referrer=discord)
=> Ensured StratCon Campaigns Always Generate At Least One Track (Sentry)

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/procreation/AbstractProcreation.java
- Replaced `isActive` check with the new `isBusy` method in maternity leave eligibility logic.
- Added `isBusy` method in `Person` class to determine personnel activity based on status, unit assignments, and tasks.
- Includes checks for self-crewed units, technicians, unit deployments, and various task states (mothballing, refitting, repairing).
Fix #6545
=> Fix #6545: Prevented Self-Crewed Unit Crew from Going on Maternity Leave Mid-Refit, Mid-Repair, or Mid-Mothballing

MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
- Removed code that prevented players from salvaging turrets, specifically gun emplacements.
Fix #6544
This was leftover code from 50.03 when we first prevented the player from acquiring gun emplacements, prior to us implementing the Unsupported Unit class.
=> Fix #6544: Restored Ability to Salvage Turrets

MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/menus/AssignUnitToTechMenu.java
- Refactored `doMaintenance` logic so that maintenance time is only deducted on the day maintenance takes place - to match current errata.
- Added failure reporting when a tech lacks sufficient minutes for maintenance, with a localized message update.
- Revised `Person.getDailyAvailableTechTime` to exclude maintenance time.
- Updated `AssignUnitToTechMenu` to display available minutes for tech assignment using recalculated logic.
Fix #4828
Fix #6476 
This PR does two things: one, it changes maintenance time deductions to match current errata which states that maintenance time is only deducted on the day in which the maintenance takes place. This will be a game changer, I suspect.
Second, when assigning a character to a unit you now see the amount of minutes they have available (minus time …
=> Fix #4828, #6476: Updated Maintenance Handling and Tech Assignment Display

MekHQ/src/mekhq/gui/MapTab.java
- Added a missing method call preventing the planet view panel from updating when a system was selected via the 'Find Planet' box.
Fix #6449
=> Fix #6449: Fixed Find Planet and Planet View Panel Interaction

MekHQ/src/mekhq/gui/dialog/RetirementDefectionDialog.java
- Characters breaking contract no longer forfeit ownership of their original units, if the original unit is still present in the campaign.
Fix #6439
=> Fix #6439: Fixed Turnover Unit Assignment for Characters Breaking Contract

MekHQ/src/mekhq/campaign/randomEvents/prisoners/CapturePrisoners.java
- Logged the `sarTargetNumber` details to make it easier to investigate user reports, in the event capture rate does not match expectations.
This came about during the investigation of #6416. While that investigation showed nothing was wrong, I figured it would be helpful to log what the actual TN is, so that if this comes up again it's a lot easier to check.
=> Added Prisoner Capture Target Number to Logs

MekHQ/src/mekhq/campaign/unit/Unit.java
- Updated gunnery skill limit checks across multiple methods to correctly use a minimum (technically maximum) value of 8 instead of 7.
Fix #6409
MegaMek has a hard limit on gunnery and piloting not being higher (worse) than 8, however previously gunnery had been set to 7. Presumably because 7/8 is Ultra-Green in normal Battletech. However, users are entirely capable of editing their skill TN to be lower than this.
8 is the hard limit, though, any higher (worse) and MegaMek starts getting ornery.
=> Fix #6409: Corrected Crew Gunnery Skill Limits From 7 to 8

MekHQ/src/mekhq/campaign/unit/Unit.java
- Replaced hardcoded time calculations with the `TECH_WORK_DAY`.
- Added singular/plural handling for "day" in the refit status message.
=> Fixed 24-hour Work Day in Refit Display

MekHQ/src/mekhq/campaign/randomEvents/MercenaryAuction.java
- Introduced `DECLINE_AUCTION_OPTION`.
- Added an early return for the decline auction option, avoiding unnecessary processing.
- Fixed bug where declining the auction made a bid, while bidding canceled the auction.
Marking this as 'medium' as it was deducting SP.
=> Fixed Mercenary Auction Decline Auction Option

MekHQ/src/mekhq/gui/campaignOptions/components/CampaignOptionsHeaderPanel.java
- Applied a black tint to the Campaign Options Header Panel image using `addTintToImageIcon`.
=> Added Tint To Campaign Options Tab Images

MekHQ/src/mekhq/campaign/mission/Scenario.java, MekHQ/src/mekhq/gui/BriefingTab.java
- Updated `getAllUnits` calls to use `false` instead of `true` for filtering unit lists.
Fix #6616
=> Fix #6616: Fixed Convoys Not Deploying to Scenarios

MekHQ/src/mekhq/MHQConstants.java, MekHQ/src/mekhq/campaign/market/unitMarket/AbstractUnitMarket.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
- Added a new constant `BATTLE_OF_TUKAYYID`.
- Updated unit generation logic to restrict Clan technology in non-Clan forces before Tukayyid.
Fix #6618
Me and Hammer determined last year that Tukayyid would be the cut-off point after which the Houses started relaxing their tendency to hoard Clantech. Generally speaking, prior to this date you would occasionally see units in the Clan Invasion theatre rocking the odd bit of Clantech, however these unique situations are not something we can easily model so it's better to just bar non-Clan factions from accessing Clantech prior to the watershed.
=> Fix #6618: Implemented Pre-Tukayyid Clan Tech Restrictions to Force Generation

MekHQ/src/mekhq/campaign/mission/Scenario.java
- Adjusted logic to apply fallback team value only for scenarios with a current status. Stops it spamming up `mekhq.log`
=> Adjusted Missing Team Fallback Logging

MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/personnel/enums/RandomMarriageMethod.java, MekHQ/unittests/mekhq/campaign/personnel/enums/RandomMarriageMethodTest.java
- Implemented a `fromString` method in `RandomMarriageMethod` for parsing string input into the corresponding enum value.
- Supports matching by enum constant, case-insensitive alias, or ordinal value.
- Defaults to `NONE` for unrecognized input.
- Logs a warning when an unknown method is encountered.
- Updated `CampaignOptions` to use `fromString` for safer parsing of `randomMarriageMethod`.
Fixes a log error when loading old campaigns with `RandomMarriageMethod` set to a value that no longer exists.
=> Implemented Graceful Failure when Loading Random Marriage Settings from Older Versions

MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/personnel/enums/RandomProcreationMethod.java, MekHQ/unittests/mekhq/campaign/personnel/enums/RandomProcreationMethodTest.java
- Implemented a `fromString` method in `RandomProcreationMethod` for parsing string input into the corresponding enum value.
- Supports matching by enum constant, case-insensitive alias, or ordinal value.
- Defaults to `NONE` for unrecognized input.
- Logs a warning when an unknown method is encountered.
- Updated `CampaignOptions` to use `fromString` for safer parsing of `randomProcreationMethod`.
Fixes a log error when loading old campaigns with `RandomProcreationMethod ` set to a value that no longer exists.
=> Implemented Graceful Failure when Loading Random Procreation Settings from Older Versions

MekHQ/src/mekhq/campaign/force/CombatTeam.java
- Removed reflection-based `Class.forName` usage in `generateInstanceFromXML` for `CombatTeam` creation.
- Replaced with direct instantiation of `CombatTeam` to remove runtime errors.
This just fixes the loading of combat teams in campaigns that predate Combat Teams as a _thing_. The failure didn't actually cause any problems, but it did throw up all over the log so with us hoping 50.05 will make Milestone I figured it was worth tidying up.
=> Fixed Error On Loading Campaign That Predates Combat Teams

MekHQ/data/universe/planetary_systems/canon_systems/MariussTears.yml
- Updated the initial name of the planet from "Marius's Tears" to "Herculaneum."
- Added historical event in 3048 where the planet's name changes back to "Marius's Tears."
Fix #1460
=> Fix #1460: Corrected Naming of the Planet Herculaneum/Marius's Tears

MekHQ/src/mekhq/campaign/finances/Accountant.java, MekHQ/src/mekhq/campaign/unit/Unit.java
- Replaced `getFuelCost()` with a new `getFuelCost(int hydrogenProduction)` method to account for hydrogen production offsets.
- Units not in the TO&E no longer incur monthly fuel costs (they're not in use)
Fix #2183
Fix #3819
Fix #4788
We don't currently track hydrogen stockpiles and it would be a pain to implement, so instead we assume all non-mothballed fusion engine having units are producing hydrogen in their spare time. This is done at the rates listed in SO.
While there will be times when a unit is unavailable, without stockpile tracking there is no way for the user to benefit from stocking up before a contract. So we employ a bit of handwavium and run under the assumption that the player stockpiled enough to mitigate fusion engines being at times unavailable.
=> Fix #2183, #3819, #4788: Corrected Hydrogen-Based Fuel Cost Calculation

MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/personnel/enums/RandomDivorceMethod.java, MekHQ/unittests/mekhq/campaign/personnel/enums/RandomDivorceMethodTest.java
- Implemented a `fromString` method in `RandomDivorceMethod` for parsing string input into the corresponding enum value.
- Supports matching by enum constant, case-insensitive alias, or ordinal value.
- Defaults to `NONE` for unrecognized input.
- Logs a warning when an unknown method is encountered.
- Updated `CampaignOptions` to use `fromString` for safer parsing of `RandomDivorceMethod`.
Fixes a log error when loading old campaigns with `RandomDivorceMethod ` set to a value that no longer exists.
=> Implemented Graceful Failure when Loading Random Divorce Settings from Older Versions

MekHQ/src/mekhq/campaign/personnel/lifeEvents/CommandersDayAnnouncement.java
- Replaced direct `ImageIcon` instantiation with a scaled version using `ImageUtilities.scaleImageIcon`.
=> Fixed Commander's Day Dialog To Scale Banner Image Properly

MekHQ/resources/mekhq/resources/BirthAnnouncement.properties, MekHQ/src/mekhq/campaign/personnel/lifeEvents/BirthAnnouncement.java
- Updated `SUPPRESS_DIALOG_RESPONSE_INDEX` constant value from `3` to `2` to align with the expected dialog behavior.
- Corrected `CampaignOptions` logic to properly set `ShowLifeEventDialogBirths` to `true` when the suppression option is selected.
- Adjusted pronoun placeholders in `BirthAnnouncement.properties` to use the correct variable for improved message clarity.
=> Fixed Incorrect Constants and Pronoun Placement in BirthAnnouncement

MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/unit/Unit.java
- Resolved potential null pointer exception when accessing `Refit` in `Person`'s tech assignment logic by adding a null check.
- Updated `Unit#getRefit()` method to explicitly indicate the possibility of a nullable return with `@Nullable` annotation.
Maternity leave once again bites me in the butt.
=> Fixed Null Pointer Issue in Refit Handling

MekHQ/src/mekhq/gui/adapter/TOEMouseAdapter.java
Unassign Towed Units from Tractor / Unassign Force from Tractor was always showing instead of only showing when needed. This fixes that. It was using the incorrect "units", it should be using "unitsInForces".
=> Fix what units are passed to detach trailer/tractor so it only shows when needed

MekHQ/data/universe/defaultspa.xml
- Fixed missing `]]` closing tags in the description of `tech_internal_specialist` ability.
- Standardized capitalization for "Unofficial" in ability display names.
=> A Couple of SPA XML Fixes

MekHQ/src/mekhq/gui/campaignOptions/contents/SkillsTab.java
- Replaced hardcoded rows with a dynamic calculation based on skill panel size.
This fixes a bug where each skills tab could only display a maximum of 20 skills.
=> Fixed Skill Panel Layout Calculation in Campaign Options IIC

.gitignore, MekHQ/src/mekhq/gui/BriefingTab.java
- Fixed an NPE caused by having StratCon enabled, but where the current `Mission` is not a StratCon-enabled `AtBContract`.
Fix: [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4359/?alert_rule_id=13&alert_type=issue&notification_uuid=264e9440-951e-4e95-8812-ea438e97309a&project=10&referrer=discord)
=> Fixed an NPE During Contract Resolution (Sentry)

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/GenerateResupplyContents.java
- Stopped the employer depot crew from counting every ton of ammunition as five tons. Where did the other 4 tons go? Well, where else do you think the Smugglers get their wares?
Fix #6668
The Resupply module went through a _lot_ of revisions during development, as we sought to 'get it right'. During an early build ammunition was delivered in batches of five tons. So every time you go LRMs, for example, you would get five tons of LRMs.
However, we received feedback that this didn't feel great, so instead we moved ammunition to be delivered in patches of 1 ton.
Unfortunately, I missed a single instance where the old 5 tons was being used. Meaning ammunition was being treated as if it weighed 5x as much as was actually delivered.
=> Fix #6668: Fixed Creative Accounting for Ammunition in Resupplies

MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
- It appears 50.05 picked up a brief bug where the three command skills (Strategy, Command, and Leadership) started counting down, not up. This corrects that.
=> Fixed Command Skills Counting Down not Up

MekHQ/src/mekhq/campaign/force/CombatTeam.java, MekHQ/src/mekhq/campaign/force/Force.java
- Updated several methods and variables to explicitly acknowledge that commander-related UUIDs can be null.
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4375/?alert_rule_id=13&alert_type=issue&notification_uuid=d9e5f9cb-b1dd-438e-a7b4-b4fd34dc8b54&project=10&referrer=discord)
=> Fixed NPE in `updateCommander` (Sentry)

MekHQ/src/mekhq/campaign/CampaignOptions.java
- Refactored `CampaignOptions` to use `SkillLevel.parseFromString()` instead of `SkillLevel.valueOf()` for `skillLevel` parsing.
=> Improved SkillLevel Parsing from Older Campaigns

MekHQ/resources/mekhq/resources/Personnel.properties, MekHQ/src/mekhq/campaign/personnel/Person.java
- Added detailed in-game warnings to notify users when a person is found ineligible for their primary or secondary role.
=> Made 'Invalid Profession' Errors More Visible With Advance for Older Campaigns

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/gui/BriefingTab.java
This fix implements a long-standing request from the Turrets team to avoid reconfiguring the ammo of pre-configured turret / gun emplacement units.
This will prevent uneven play experiences and keep the turret BV stable.
Players are still free to reconfigure / auto-configure turret munitions within MegaMek if desired.
Testing:
- Confirmed turrets are skipped when even when ammo auto-configuration is enabled.
- Confirmed other units get auto-configured as usual.
=> Skip Turrets / Gun Emplacements when auto-configuring NPC ammo loadouts

MekHQ/src/mekhq/campaign/personnel/autoAwards/KillAwards.java
Fixes #6700 
Incorrect check was done before trying to retrieve a value from a map.
```
if (!visitedForces.contains(currentNode.getId())) {
if (forceCredits.contains(currentNode.getId())) {
kills.addAll(killData.get(currentNode.getId()));
}
```
We are checking the `killData` map, so we need to make sure the force is valid key in the `killData` map not the `forceCredits` map. This was throwing a caught exception (line 205-206) that was adding only the base formation's kills.
```
if (!visitedForces.contains(currentNode.getId())) {
if (killData.containsKey(currentNode.getId())) {
kills.addAll(killData.get(currentNode.getId()));
}
```
=> Issue 6700: Fixed Formation-level kill awards

MekHQ/resources/mekhq/resources/SkillCheckUtility.properties, MekHQ/src/mekhq/campaign/personnel/skills/Attributes.java, MekHQ/src/mekhq/campaign/personnel/skills/SkillCheckUtility.java, MekHQ/src/mekhq/gui/dialog/SkillCheckDialog.java, MekHQ/unittests/mekhq/campaign/personnel/skills/SkillCheckUtilityTest.java
Without going into the nitty gritty there were a few places where we were calculating target number incorrectly. This PR addresses this, while also moving the class to use `TargetRoll` which I should have done in the first place as it allows for much better modifier tracking.
=> Refactored Centralized Skill Check Class to Use `TargetRoll`; Fixed Multiple Bugs

MekHQ/src/mekhq/campaign/personnel/skills/SkillCheckUtility.java
- Corrected the handling of `targetNumber` by calling `.getValue()` rather than displaying the raw `TargetRoll` string.
=> Fixed Target Number Display in Skill Check Utility

MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
- Raised the compatibility version check from `0.50.05` to `0.50.06` in `SkillType.java`.
Fix #6717
This fixes an issue caused by the recent version changes. The check was previously checking for saves prior to 50.05 - which would have caught any save not saved in 50.05 (specifically including Nightlies). However, with the version changes nightlies return as being from 50.05, causing the compatibility fixes to not fire. This essentially prevented any save from a nightly prior to the skill changes from being updated to the current version.
Thankfully, the only stuff covered by the compatibility handler was internal data. Had this affected user-facing stuff, it would have been unfixable. As resetting the skill in this manner will be occurring every time a save is loaded prior to 50.06, …
=> Fix #6717: Fixed Skill Compatibility Version Check

MekHQ/src/mekhq/campaign/unit/MothballInfo.java, MekHQ/src/mekhq/campaign/unit/Unit.java
> somehow Palpatine has returned
> If there's any day for discussing this  ...
Fixes #6720 
Personnel info was being stored in `MothballInfo`. Enough that we could return removed Personnel from it. Let's prevent ghosts from even inhabiting this place and replace `Person` with `UUID` in `MothballInfo`.
=> Issue #6720: Ghostbusting in `MothballInfo` so Personnel Don't Return

MekHQ/src/mekhq/campaign/randomEvents/prisoners/PrisonerEventManager.java
- Reversed the conditional to properly detect prisoners *without* a doctor (`== null`).
=> Fixed Prisoner Capacity of Injured Prisoners

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
- Resolved potential `NullPointerException` by adding a null check for `Force` objects during BV calculation within `AtBDynamicScenarioFactory`.
- Added detailed logging to capture BV contributions for individual forces.
=> Added Seed Force to Log During Scenario Generation

MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
- Stopped skill type compatibility handler spamming the log whenever a save is loaded.
=> Remove Redundant Logging in SkillType Updates

MekHQ/src/mekhq/campaign/unit/HangarStatistics.java
- Added a `continue` statement to properly skip further processing for mothballed units in `HangarStatistics`.
Fix #3624
Fix #4039
=> Fix #3624, #4039: Fixed Transport Report Counting Mothballed Units as Occupying Bays

MekHQ/src/mekhq/campaign/unit/MothballInfo.java
Fix #6718
- Prevented inactive techs from being reassigned to units when activating a unit from a mothballed state.
=> Fix #6718: Ensured Only Active Techs are Reassigned When Activating Units from a Mothballed State

MekHQ/src/mekhq/campaign/parts/Refit.java, MekHQ/src/mekhq/utilities/ReportingUtilities.java
- Update the error message in `Refit.java` to include bold HTML tags for better visual emphasis when a refit kit is not found.
- Correct JavaDoc reference formatting for `CLOSING_SPAN_TAG` in `ReportingUtilities.java`.
Fix #6701
=> Fix #6701: Added Colorblind Assistance to Refit Not Found Text

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java, MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
- More consistently use the Negotiation skill for negotiations.
- The most senior Admin characters in each roll (Command, Logistics, and Transport) are used, not necessarily the best per skills. This brings negotiation in line with other systems while also giving the player more control and predictability over who makes the rolls.
- Reduced the number of negotiation rerolls to 1 (rather than 1 per rank in Negotiation). This matches RAW.
- Labeled the renegotiation buttons with who is negotiating
Fix #1914 (by providing the player a way to directly influence who performs the negotiations)
These changes mark another step down in the power of the player and further slow progression by reducing the frequency of 'perfect' contracts. Now choosing to negotiate is a gamble, rather than players …
=> Fix #1914 : Refactored Contract Terms Negotiations to Be Closer to RAW

MekHQ/src/mekhq/gui/panes/UnitMarketPane.java
This fixes a bug reported on discord by TravisTgr
I did not find a related Issue on the tracker.
The main changes are in 
Line   64: import of mekhq.gui.sorter.FormattedNumberSorter
Line 332: setting the FormattedNumberSorter on COL_PRICE
the rest is automatic line formatig
=> Fix sorting the units in the Unit Market by price

MekHQ/src/mekhq/gui/adapter/PartsTableMouseAdapter.java
- While in GM mode users can 'add n parts' in addition to the ability to remove n parts added earlier in 50.05.
- Ammo is increased by n shots. Armor is increased by n points, other parts are just increased by n.
Fix #3963
=> Fix #3963: Added the Ability to GM Increase the Number of Each Part in the Warehouse.

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/personnel/generator/AbstractPersonnelGenerator.java, MekHQ/src/mekhq/campaign/personnel/generator/DefaultPersonnelGenerator.java, MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java, MekHQ/unittests/mekhq/campaign/personnel/marriage/AbstractMarriageTest.java
The logic used to generate a character's gender was faulty, resulting in characters being generated with incorrect genders.
This was highlighted by a user who wanted to disable same-sex marriage, but found same-sex marriages were still occurring.
While I was addressing this I also did some like refactoring of marriage gender generation and clarified the language used for the marriage chance campaign options. As those were a source of frequent confusion.
=> Fixed Gender Generation

MekHQ/src/mekhq/campaign/parts/Refit.java, MekHQ/src/mekhq/campaign/unit/Unit.java
An `Entity` needs to be in a game to copy its C3. If it's not a `Game`, let's not copy its C3 network. Fortunately, when refitting, we can still restore the C3 info later once the new entity is added to the game. Neat!
=> Issue #6753: Check if `Game` is null when replacing a Unit's Entity & Transfer C3 During Refit if Possible

MekHQ/data/scenariotemplates/Breakthrough.xml, MekHQ/data/scenariotemplates/Convoy Escort.xml, MekHQ/data/scenariotemplates/Convoy Interdiction.xml, MekHQ/data/scenariotemplates/Convoy Raid.xml, MekHQ/data/scenariotemplates/Critical Convoy Escort.xml, MekHQ/data/scenariotemplates/Diversion Engagement.xml, MekHQ/data/scenariotemplates/Emergency Convoy Defense - Player - Low-Atmosphere.xml, MekHQ/data/scenariotemplates/Emergency Convoy Defense - Player - VTOL.xml, MekHQ/data/scenariotemplates/Emergency Convoy Defense - Player.xml, MekHQ/data/scenariotemplates/Emergency Convoy Defense.xml, MekHQ/data/scenariotemplates/Frontline Breakthrough.xml, MekHQ/data/scenariotemplates/Frontline Disruption.xml, MekHQ/data/scenariotemplates/Intercept Engagement.xml, MekHQ/data/scenariotemplates/Interception Defense.xml, MekHQ/data/scenariotemplates/Low-Atmosphere DropShip Assault.xml, MekHQ/data/scenariotemplates/Low-Atmosphere DropShip Escort.xml, MekHQ/data/scenariotemplates/Picket Line Breakthrough.xml, MekHQ/data/scenariotemplates/Space Blockade Run.xml, MekHQ/data/scenariotemplates/Space DropShip Intercept.xml, MekHQ/data/scenariotemplates/Tactical Withdrawal.xml
- Corrected destination edge to use static for 'opposite' and not 'north' board edge.
Fix #6750
=> Fix #6750: Corrected Destination Edges

MekHQ/src/mekhq/gui/dialog/MassMothballDialog.java
- Increased maximum height from 100px to 400px.
- Set a new minimum height of 150px (previously not defined).
Fix #4780
=> Fix #4780: Added Minimum Height to Tech List in Mass Mothball

MekHQ/src/mekhq/gui/dialog/randomEvents/prisonerDialogs/PrisonerRansomEventDialog.java
- Adjusted dialog to modal to ensure the dialog is resolved before we check for user response.
Fix #6758
=> Fix #6758: Fixed Ransom Events Not Ransoming Prisoners

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
- Updated the label `lblUnitMarketTab.text` in `CampaignOptionsDialog.properties` to include an additional Unicode character (`\u2318`).
=> Added Missing 'Has Documentation' Icon to Unit Market Options in Campaign Options IIC

MekHQ/src/mekhq/campaign/randomEvents/prisoners/CapturePrisoners.java
- Added a check to ensure defection logic is only applied to prisoners with valid prisoner status.
Clan campaigns do not use 'defections' they take Bondsmen, instead.
=> Fixed Defection Logic for Prisoners

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
- Resolved an issue where adopting a child with existing parents triggered a `ConcurrentModificationException` by creating a new list and iterating through that instead of the raw genealogy object.
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4577/events/529935dd7a414abf802548522e7b1bb3/)
=> Fixed Exception When Adopting Child with Existing Parents (Sentry)

MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java, MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
- Refactored logic to always process age effect updates for all personnel when closing campaign options.
- Ensured age modifiers for skills are only applied when the "Use Age Effects" campaign option is enabled.
=> Fixed Aging Effects Applying Even When Disabled

MekHQ/userdata/data/universe/ranks.xml
- Updated the XML version in `ranks.xml` from `0.50.05` to `0.50.06`.
- This stops IDEA whining at us every PR.
=> Updated Rank System XML Version to 0.50.06

MekHQ/src/mekhq/gui/CampaignGUI.java
- `DayEndingEvent`: Blocks day progression based on campaign conditions (e.g., overdue loans, faction issues, etc.).
- `LocationChangedEvent`: Refreshes campaign location data.
- `MissionEvent`: Updates part availability post-mission.
- `PersonEvent`: Recalculates AtB parts availability for logistics role changes.
- `NewDayEvent`: Refreshes multiple UI elements and data at the start of a new day.
- Other events: Adjust UI and schedule updates for funds, parts availability, and pools (e.g., astechs, medics, loans, transactions).
These methods are not directly evoked they're evoked as part of an event bus. The @Subscribe tag means they're evoked whenever the event they're registered to fires.
So when the end day event occurs both handleDayEnding and handleNewDay fire (alongside a bunch of …
=> Restored Event Handlers for Campaign State Management

MekHQ/src/mekhq/gui/view/ContractSummaryPanel.java
- Removed restrictions for government forces when determining command clause reroll eligibility.
Fix #6771
=> Fix #6771: Loosened Government Force Command Rights Re-Roll Restrictions

MekHQ/src/mekhq/campaign/mission/AtBContract.java
Fix #6778
When the enemy routs all held prisoners are meant to be ransomed or released. However, we were only triggering those events if there were _no_ prisoners, not when there _were_ prisoners.
=> Fix #6778: Prisoners Are Now Correctly Released When Enemy Routs

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
Fix #6785
As per rules as written contract negotiation uses the Negotiation skill of the negotiator. However, we were not verifying that the negotiator _had_ the Negotiation skill before performing the check, resulting in an error.
=> Fix #6785: Fixed NPE on New Contract when Negotiator Lacks Negotiation Skill

MekHQ/src/mekhq/campaign/personnel/Person.java
Fix #6800
As part of the splitting up of the personal log we included code that would filter previous log entries into the new log types.
Unfortunately, a missed clause meant that some log entries were being filtered out but not added to another log.
This happened because during testing I used 'real data,' that is actual player saves, rather than 'constructed data,' a save I made up specifically to test. Due to the age of the campaigns I was testing, it wasn't immediately clear these log entries had been lost due to the number of log entries I was checking.
=> Fix: Stopped Certain Personal Log Entries being Deleted on Load

MekHQ/src/mekhq/campaign/randomEvents/MercenaryAuction.java
We were incorrectly adding the total bid success chance to the players available Support Points instead of deducting the support points spent.
=> Fix: Stopped Mercenary Auctions Gifting a Hundred Support Points (No Really)

MekHQ/src/mekhq/Utilities.java, MekHQ/src/mekhq/campaign/personnel/Person.java
Fix [Sentry Report A](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4610/events/8879ee6b92fa453586fa405c00629436/), [Sentry Report B](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4610/events/8879ee6b92fa453586fa405c00629436/)
As part of CamOps Reputation we need to test whether a character has a Bloodname. By all accounts bloodname should initialize as a blank string, however Sentry reports show it can also be null. So we need to test for null state.
=> Fix: Fixed Error When Attempting to Fetch Bloodname for Characters Without a Bloodname

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
Fix #6799
When adopting a child we remove their previous (presumably dead) parents. However, this run into an issue previously thought fixed where we were trying to remove parents while also processing those parents at the same time.
=> Fix: Fixed Error when Adopting Child With Existing Parents

MekHQ/src/mekhq/gui/HangarTab.java, MekHQ/src/mekhq/gui/model/UnitTableModel.java
Fix #6798
This fixes an issue where only the unit 'Status' view option was checking whether maintenance should be displayed.
=> Fix: Fixed Visual Bug Causing Next Maintenance to Always be Displayed in the Hangar

MekHQ/src/mekhq/gui/view/ForceViewPanel.java
Fix #6794
We previously received feedback from a user that C3 was not being factored into BV calculations in the TO&E tab. We then went in and fixed this, however that caused the every C3 equipped unit needing to read the ammo loadout of every unit in the TO&E any time the TO&E was interacted with. This resulted in a lock-up for large campaigns.
=> Fix: Significantly Improved TO&E Reading Speed by Removing C3 Calculations

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/parts/Refit.java
Fixes #6790 
Fixes #6791 
Regarding the change to `Campaign::reloadGameEntities`: This prevents `addEntity` from generating a `GameEntityNewEvent` and setting the initial BV. This is unnecessary as these units were already added to the game and we're just reloading them. This includes when returning from scenarios, the other place `reloadGameEntities` is used. 
When calculating the BV of C3 it will clear C3 connections if they aren't valid, so this prevents networks from being broken as the entities are re-added to the game.
=> Issue #6790: Prevent NPE from C3 when Refitting

MekHQ/data/scenariotemplates/Deep Raid Defense.xml, MekHQ/data/scenariotemplates/Deep Raid.xml, MekHQ/data/scenariotemplates/VIP Ambush.xml, MekHQ/data/scenariotemplates/deprecatedTemplates/Skirmish Disruption.xml
This removes the arrival time delay for several scenarios. The addition of the arrival time deplay made sense of paper, less so in practice.
I also removed an errant reinforcement force that didn't need to be in the scenario.
=> Fix: Fixed Arrival Time in Several Scenario Templates

MekHQ/data/universe/defaultspa.xml
Fix #6817
For some reason exceptional attribute charisma was set up in code, but not included in the spa file. Most likely this was a copy-paste error.
=> Fix: Added Missing Exceptional Attribute Charisma SPA

MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsAbilityInfo.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java, MekHQ/src/mekhq/gui/campaignOptions/contents/AbilitiesTab.java, MekHQ/src/mekhq/utilities/spaUtilities/enums/AbilityCategory.java, MekHQ/src/mekhq/utilities/spaUtilities/enums/AbilityInfo.java
I'm about to move some logic out of `AbilitiesTab.java` connected to the categorization of SPAs. This will allow that logic to be used anywhere, not just campaign options. However, to do that I needed to move the enum values out of `CampaignOptionsAbilityInfo.java`. I was advised to make a PR that just did the move and renaming, and then to follow up with the logic changes.
=> PR: Moved SPA Info in Preparation for Future Changes

MekHQ/resources/mekhq/resources/ContractAutomation.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/src/mekhq/campaign/market/contractMarket/ContractAutomation.java
During a recent user stream it was noted that units failed to unmothball upon arriving at the contract. I investigated, and the most likely cause was us storing units instead of unit IDs. If, for some reason, a unit changed they would no longer match what was stored. While this shouldn't happen I went ahead and switched to storing unit IDs - which are both unique and will never change.
=> Improvement: Improved Robustness of Automatic Unmothballing in Contract Automation

MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java
This fixes an exception that would occur when a player tried to view an already resolved scenario while having Blind Drop or True Blind Drop enabled.
Restarting the client fixes the issue in 50.05
=> Fix: Fixed Exception When Viewing Past-Scenarios While Blind Drop or True Blind Drop is Enabled

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
This PR just switches any instances of the 'Added since the last Development release' added during the 50.05 dev cycle with  the 'Added since the last <b>Milestone</b> release' icon.
=> Improvement: Updated Campaign Options Iconography for 50.06

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/unittests/mekhq/campaign/CampaignTest.java
Fixes #6775 
`Campaign.getDefaultStockPercent(Part)` should now handle  `AmmoStorage` parts with `CampaignOptions::getAutoLogisticsAmmunition` instead of `CampaignOptions::getAutoLogisticsOther`
=> Fix: #6775 AutoLogistics properly considers `AmmoStorage` as ammo and not other 

MekHQ/src/mekhq/gui/model/ScenarioTableModel.java
If the player attempted to sort their list of scenarios by status, while there was a mix of refused scenarios and fought scenarios, they would be hit with a ClassCastException. That exception would persist across saves.
=> Fix: Fixed Exception When Sorting Scenario List by Status While There is a Mix of Refused and Fought Engagements

MekHQ/src/mekhq/gui/dialog/DataLoadingDialog.java
The alphabetical sorting of skills is a bit of a double-edged sword. Veteran players hate it because they're used to how things are, newer players love it because it makes finding individual skills easier.
Previously we removed this functionality, but honestly I don't think we should have. With the new changes coming for the Person Pane having skills sorted alphabetical makes more sense than ever. It also means that we, as developers, don't need to maintain an unspoken order whenever new skills are added - and we've added quite a few.
=> Improvement: Added Alphabetical Sorting of Skills

MekHQ/src/mekhq/campaign/Campaign.java
The calculateCostPerJump function was a mess and not working correctly for small unit counts. I refactored a lot of the variable names to make them clear and consistent across the function, and corrected some of the logic to bring it in line with what it says its supposed to be doing.
A larger redesign of the dropship system should be considered to bring all of this in line with book rules from FM:Mercs and CamOps. Dropship lease costs should be deducted 'per day' for the whole trip, and collar costs should be 'per jump' as per CamOps. There are also additional 'collar idle fees' to have a jumpship idle around waiting for you to finish. Availability of Dropship rentals should also be considered.
=> calculateCostPerJump variable cleanup, reformatting, logic corrections.

MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
A vital call to the Interest/Sports and Training skills accidentally got nixed during the recent addition of new skills. This fixes them.
=> Fix: Fixed Missing Interest/Sports & Training Skills

MekHQ/src/mekhq/campaign/personnel/skills/SkillType.java
Two skills were calling the wrong setup method resulting in campaign options failing to save.
This is another notch in the stick of 'skills need to be enums'
=> Fix: Fixed Exception During Campaign Preset Saving Caused by Two Wrongly Setup Skills

MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java, MekHQ/src/mekhq/gui/CampaignGUI.java
Mac taskbar doesn't accept html formatted text, it turns out...
=> Fix: Fixed Mac Displaying Profession Descriptions Incorrectly in Taskbar

MekHQ/src/mekhq/campaign/personnel/enums/PersonnelRole.java, MekHQ/src/mekhq/gui/CampaignGUI.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/unittests/mekhq/campaign/personnel/enums/PersonnelRoleTest.java
Profession labels were always using IS terms. Now they don't. For example the BA trooper profession will show as Elemental.
=> Fix: Added Clan Labels and Descriptions to Profession Descriptions and Labels

MekHQ/src/mekhq/campaign/parts/Armor.java
Fixes issue #175. Updates armor part with correct times for capital scale ships per Master Repair Table in StratOps p183.
=> Fix for Capital Ship Armor Repair Time

MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java
We were missing the commander's address from convoy roleplay events. Now we're not.
=> Fix: Added Missing Commander Address from Convoy Roleplay Events

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/personnel/marriage/AbstractMarriage.java
Fix #6954
Now it is possible to disable your personnel from marrying extra-unit by setting intra-unit chance to 1. Also, civilians won't materialize out of the aether while in transit.
=> Fix: Stopped New Civilians Spawning While Not On Planet via Marriage; #6954 Fixed Inability to Disable New Civilians via Marriage

MekHQ/data/universe/defaultspa.xml
It was uncorrected citing Combat Sense, instead. Now it isn't.
=> Fix: Corrected Command Paralysis description

MekHQ/src/mekhq/gui/BriefingTab.java
If a mission (Mission, Contract, or AtBContract) is deleted or completed while there are outstanding scenarios _and_ those scenarios had forces assigned to them; those forces would become permanently deployed.
Deleting the force would release the units.
Marking this as critical, as it's a real pain if it happens and isn't something we want in our Milestone candidate. However, this bug has likely been around for a few years, demonstrating that the chance of it occurring is relatively low.
=> Fix: Prevented Forces from Being Locked in a Permanently Deployed State Following Mission Completion or Removal

MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java, MekHQ/src/mekhq/gui/menus/AssignUnitToPersonMenu.java
Fixes #6967 
It was by sheer luck that their one Mek worked - it was a Quad Mek, so that's why the dual-cockpit worked. Anyway, this logic seems to work great. Tested with normal cockpits, dual cockpits, and cockpit command consoles. All work as expected now.
=> Fix: #6967 Crew can be assigned to dual cockpits

MekHQ/src/mekhq/campaign/personnel/Person.java
Fix #6948
This was caused by an inverted conditional, one of the classic blunders.
=> Fix: #6948 Fixed Artillery Skill Only Being Factored into a Character's Experience Level when Use Artillery Skill is Disabled

MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Apparently the section that displays what profession/s a character has got removed during my rework of the Person View panel. This restores it.
=> Fix: Restored Missing Character Profession in Person View

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties
=> Fix: Added Missing Campaign Options Iconography to New Weapons Restock Percentage Option; Changed Color of Iconography to Stand Out

MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/unit/Unit.java
Fix #6998
Related Issue https://github.com/MegaMek/megamek/issues/7054
The initiative bonus from Tactics, when that campaign option was enabled, was incorrectly using the skill target number as a modifier and _not_ the combined skill levels, bonus, and aging modifiers.
I also fixed a bug where Tactics was not being applied to the unit if Individual Initiative Tactics Modifiers was enabled.
Finally I fixed a third bug where Commander Initiative wasn't being enabled in MegaMek when the above mentioned option was enabled.
There is a forth related bug, but that's a wholly MegaMek issue and is being handled by Sleet. But basically if individual initiative was enabled we are still using the highest initiative from all units under a player's control _not_ just the modifiers from the specific …
=> Fix: #6998 Fixed Tactics Bonus to No Longer Use the Tactic Number as a Bonus

MekHQ/src/mekhq/gui/HangarTab.java, MekHQ/src/mekhq/gui/model/UnitTableModel.java
Fix #6996
The use of individual characters for mothballed units was breaking sorting. Now it isn't. I also added in natural language sorting so that it would sort more cleanly.
=> Fix: #6996 Fixed Sorting of Next Maintenance Column in Hangar

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignTransporterMap.java, MekHQ/src/mekhq/campaign/parts/Refit.java, MekHQ/src/mekhq/campaign/unit/AbstractTransportedUnitsSummary.java, MekHQ/src/mekhq/campaign/unit/Unit.java, MekHQ/src/mekhq/campaign/unit/actions/RestoreUnitAction.java, MekHQ/src/mekhq/gui/menus/AssignForceToShipTransportMenu.java, MekHQ/src/mekhq/gui/menus/AssignForceToTacticalTransportMenu.java, MekHQ/src/mekhq/gui/menus/AssignForceToTransportMenu.java
Fixes #7012 
After a refit it was improperly updating the transport capacity. It was also not removing `TransporterType`s that the unit no longer had. I added some nullable tags as well.
=> Fix: #7012 Properly update capacities when changing Transporters via refit

MekHQ/src/mekhq/campaign/personnel/skills/Skill.java
At some point the polarity was switched and I didn't update the modifiers accordingly. This corrects that oversight.
Marking this as Critical as it affects every SPA and Trait that influences Skill target numbers
=> Fix: Fixed Positive SPAs & Traits Applying Penalty to Skills not Benefit (And Negative SPAs & Traits Applying Bonus not Penalty)

MekHQ/src/mekhq/gui/StratconPanel.java, MekHQ/src/mekhq/gui/stratcon/StratconScenarioWizard.java
Fix #7007
When a player deploys to a hidden scenario we generate the scenario, including the BV budget of forces assigned to that scenario. However, if the player cancels deployment - at that moment - the budget was getting set to 0 because we were not correctly resetting the scenario. This was due to the conditional that checked for the deployment being canceled was not functioning fully. However, as the force didn't get deployed it gave the impression that it _was_ fully functional.
We fixed this by added a new variable to the deployment wizard that explicitly states whether the deployment was canceled. If that event comes to pass the scenario is reset fully. However, the originally generated force is not, preventing the 0 BV bug.
The cancel deployment bug is a hacky solution to a UX …
=> Fix: #7007 Fixed Cancel Deployment Producing Scenario with 0 BV Budget

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/src/mekhq/gui/utilities/StaticChecks.java
Added checks to ensure characters are both Active and Free (or Bondsman) before Extreme Expenditure can be used on them.
=> Fix: Prevented Unscrupulous from Performing Extreme Expenditure on Prisoners to Rob Them of Their Wealth Trait

MekHQ/src/mekhq/gui/campaignOptions/components/CampaignOptionsHeaderPanel.java
We were missing the html tags from a handful of tab headers. Now we're not.
=> Fix: Fixed Formatting Error in Title of Some Campaign Options Tabs

MekHQ/src/mekhq/campaign/personnel/Person.java
Experience level calculations for professions (green, regular, etc) were not correctly factoring in modifiers to that skill. This would have been something fixed by the 50.07 change to attribute scores, but might as well be corrected now as it's more obvious following my update to experience level calculations.
=> Fix: Fixed Skill Modifiers Not Being Factored into Profession Experience Level

MekHQ/src/mekhq/campaign/force/CombatTeam.java
We were factoring in the 'Player Vehicles Weigh 50%' Legacy AtB option, even when StratCon is enabled. Now that option is only used if StratCon is disabled.
This is a visual bug only.
=> Fix: Fixed Weight Calculation Visual Bug in StratCon Campaigns

MekHQ/src/mekhq/gui/view/MissionViewPanel.java
The panel in the briefing room that shows the belligerents wasn't center aligned. Now it is.
=> Improvement: Center Aligned Belligerents Panel

MekHQ/src/mekhq/service/mrms/MRMSService.java
Fix #7025
We were running into comparison errors when comparing techs because we were using mixed comparison methods. Comparing both by experience level, and then if experience levels were equal by XP OR skill level (if Elite). Then finally available time.
This creates several issues:
- This assumes that a character with greater XP is more skilled than a character with less. However this fails to account for characters with dual professions.
- We were not checking whether a character was Elite, but if they had level 4 in the appropriate skill. However level 4 in a skill does not necessarily mean a character is Elite (depending on campaign options).
- The 'Elite' comparison also doesn't account for anything that might be influencing that skill (modifying the skill level, such as SPAs). 
- …
=> Fix: #7025 Fixed Mass Repair Dialog Throwing Exception When Run From Warehouse

MekHQ/build.gradle
This ensures the default JVM options are generated with the Launch4j start up scripts for macOS/Linux systems.
=> Adjusted default JVM options

MekHQ/src/mekhq/campaign/personnel/Person.java
Fix [Sentry Report](https://sentry.tapenvy.us/organizations/tapenvyus/issues/4912/events/073f9cb31b5f4bd384d6fb3a83f739f9/)
If the player deleted one of a character's education tagalongs they'd be hit with an exception when we attempted to update the status of a tagalong when setting the character to a non-Student status.
=> Fix: (Sentry) Fixed Exception When Processing Education Tagalongs if Tagalong Has Exited the Campaign

MekHQ/src/mekhq/campaign/personnel/education/Academy.java
Fix #7026
We were accidentally including an explicit 'XP' append as well as an implicit. Now we're just using the implicit.
=> Fix: #7026 Fixed 'XP' Appearing Twice in Academy Tooltips

MekHQ/src/mekhq/campaign/Campaign.java
We weren't checking whether celebration announcements were enabled when triggering Commander's Day.
=> Fix: Fixed Commander's Day Suppression

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java, MekHQ/src/mekhq/campaign/personnel/death/RandomDeath.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java
Random death is initialized when the campaign is initialized, however it relies on campaign options. The default death multiplier is 0.
All of this combined to make death chance 0. Which is somewhat less than intended.
Now we correctly reinitialize random death both when the campaign is loaded and when campaign options is exited.
=> Fix: Stopped Random Death Not Randomly Causing People to Die

MekHQ/src/mekhq/campaign/parts/Avionics.java
Recent changes to `Avionics#getStickerPrice` prevent existing campaign saves from being loaded if that campaign has a unit that uses Avionics. Or, if the campaign has an Avionics part in their warehouse.
This is because `unit` is `null` both during loading and while a part is loose in the warehouse.
Added null protection to the method which resolves the issue.
=> Fixed: Fixed Exception During Avionics Evaluation

MekHQ/src/mekhq/campaign/stratcon/StratconRulesManager.java
A small polarity error in target number calculations.
=> Fix: Stopped Higher Administration Skill Making Reinforcement Attempts Harder

MekHQ/src/mekhq/campaign/Campaign.java
This was accidentally missed out of the attribute score rollout PR.
=> Fix: Fix Skill Fetching in Find Best in Role Comparison

MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/campaign/finances/enums/FinancialYearDuration.java
Misleading JavaDocs resulted in a method being erroneously removed. This PR restores it.
=> Fix: Restored Loading of Financial Year Duration Campaign Option

MekHQ/data/universe/academies/Prestigious Academies.xml
There were descriptions that needed to use the new style guide 'MekWarrior' and 'OmniMek' terms. Additionally, some skills had to be updated to match the current skill names, or a crash could result.
=> Corrected some typos and updated skills to match current entries.

MekHQ/src/mekhq/gui/CampaignGUI.java
This PR simply adds the Enhanced Tabs of MML to MHQ. Nothing fancy but allows tabs reordering and docking/undocking.
Undocking can be done in two ways: 
- dragging the tab out of the tabbed bar
- right click on the tab
To be evaluated (future PRs):
a) use of a custom panel factory when undocking a tab to create a new tab container (this allows grouping)
b) save/load of tab order and, potentially, tabs state (docked/undocked, position, size, instanced multi-panels, etc...)
=> Simple drop-in of the new tabs

MekHQ/src/mekhq/campaign/Campaign.java
Fixes an NPE when:
1. the MekHQ option "Temporarily Retain Daily Log History" is enabled, and
2. all in-memory events are some time in the past, and
3. a new event (such as a contract) is added to the event log, such that
4. The span between all old events' dates and the new event's projected date is > 120 days.
This causes the in-memory log cache to be trimmed, which we _were_ doing in an unsafe fashion.
This patch replaces the unsafe method with a safe `while iterator.hasNext() / iterator.remove()` loop.
FOR DISCUSSION:
1. Why is the in-memory log populated from a campaign file's saved events?  It should probably be left empty.
2. Why does the in-memory log cache even exist?
Testing:
- Confirmed original save now works correctly when adding contracts …
=> Fix to prevent NPE when trimming in-memory Event Log for date range

MekHQ/src/mekhq/utilities/ScenarioUtils.java
Fixes the breaking bug where scenarios could not load into MegaMek from MekHQ with auto-generated maps.
Root cause was the way that `setMapSize()` resets the `selectedBoardsVector` to (X * Y) null entries, instead of leaving it cleared.
Testing:
- Ran OP's campaign scenario and confirmed map now loads.
Close #7141
=> Fix incorrect boardsSelectedVector breaks passing scenario maps from MekHQ to MegaMek

MekHQ/src/mekhq/campaign/parts/Availability.java, MekHQ/src/mekhq/campaign/parts/MissingPart.java
Add safety checks around some availability calls that led to the NPE in #7138.
Also allowed Idea to convert the switch/case block in `getAvailabilityModifier()` to new style.
It looks like the bug was actually fixed by updates in MegaMek code sometime in the last couple weeks but I have not found the exact commit.
Testing:
- Ran repro with OP's campaign save to check correctness
Close #7138
=> Refactor: Add safeties around failure points

MekHQ/src/mekhq/campaign/Campaign.java
I was working on my own fork and spotted a place in Campaign.java that had a hard coded value and didn't use the provide contast this changes from that value to use the constant, no other changes. I've tested locally and it works no issues.
=> Update Campaign.java to use Constant for Astech Team Size

MekHQ/src/mekhq/campaign/utilities/TestableCampaign.java, MekHQ/unittests/mekhq/campaign/randomEvents/prisoners/CapturePrisonersTest.java, MekHQ/unittests/mekhq/campaign/utilities/TestableCampaignTest.java
We've long had an issue of over dependency on the `Campaign` class. This makes it difficult to test with real objects, as the path to setting up a testable Campaign object is not necessarily clear.
This has historically resulted in two consequences: we stop testing as soon as we hit something that requires campaign. Or, we mock campaign and then discover (very quickly) just how entwined many of our core systems are _to_ campaign and how mocking isn't always sufficient to cover all needs.
That last point is the bigger problem, as it results in us being in an awkward situation where to test certain actions we have to mock half of the functionality implemented in campaign and several of the subsystems linked to it. Speaking from experience, this gets messy fast. The more effort something …
=> Improvement: Added Helper Method to Make Testing Real Campaign Objects Easy

MekHQ/resources/mekhq/resources/PersonnelReport.properties, MekHQ/src/mekhq/campaign/report/PersonnelReport.java
Replaces [PR#7158](https://github.com/MegaMek/mekhq/pull/7158) with a better attempt at i18n support. Answers RFE https://github.com/MegaMek/mekhq/issues/7045
current report
new report no secondary personnel
with some secondary personnel
=> Personnel report rework for addition of secondary roles

MekHQ/build.gradle
Adjust build scripts to first sync the license files to the build area then copy to the staging area.
=> Fix: Adjusted to sync then copy the license files.

MekHQ/data/scenariotemplates/Close Air Support.xml, MekHQ/data/scenariotemplates/Convoy Escort.xml, MekHQ/data/scenariotemplates/Critical Convoy Escort.xml
Close #7151
`destroy or route` -> `destroy or rout`
=> Fix: #7151 Fixed Typos in Convoy Escort Scenarios

MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java
Close #7072
There isn't a lot to say about this, I just needed to increase the number of placeholder lines to stop the panel from jumping about.
=> Fix: #7072 Corrected Tooltip Panel Size in Finance Tab

MekHQ/resources/mekhq/resources/ContractViewPanel.properties
Close #7074
`bottom left corner` -> `bottom right corner`
=> Fix: #7074 Corrected Typo in Briefing Room Tutorial Panel

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsUtilities.java, MekHQ/src/mekhq/gui/campaignOptions/contents/PersonnelTab.java
Close #7196
This adds two new campaign options. The first is a set chance that a random Civilian will generate with the 'Dependent' profession (as opposed to the catch-all 'Professional' profession). The second is the chance that the Civilian will generate with a random civilian profession.
=> Improvement: #7196 Improved Civilian Generation to Include Better Control Over Random Profession Selection

MekHQ/src/mekhq/campaign/unit/MothballInfo.java
Close #7185
Now, when activating a unit, if the unit is a part of a force that is currently marked as 'deployed' the unit is not returned to that force.
- Tested that units would not be restored to their original force if that force is currently deployed to the AO (both deployed to a scenario and not).
- Tested that units _would_ be restored to their original force if that force is _not_ currently deployed to the AO.
=> Fix: #7185 Fixed Mothballed Units Teleporting to Already Deployed Forces

MekHQ/resources/mekhq/resources/Aggression.properties
=> Fix: Fixed Typo in Recruiter Notes for Aggression Variant 1 Personality Trait

MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Close #7166
This was a real brainteaser. Basically we were updating Person View at the moment when the directional key was pressed, which happened to occur _before_ the internal list of selected personnel was updated. This caused the selection to 'lag' one step behind the actual selected character. However, that selection was correct internally. Meaning that this was only a visual bug. It was weird, but it's fixed now.
=> Fix: #7166 Fixed Displayed Applicant in New Personnel Market Lagging Behind Selection When Using Directional Keys

MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Close #7156
The golden hello functionality was working, however when the personnel market was opened it was being reset to 'off'. Now it properly remembers its last state between open-close instances.
=> Fix: #7156 Fixed Golden Hello in New Personnel Market Not Remembering Last Setting

MekHQ/src/mekhq/campaign/universe/Faction.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java, MekHQ/testresources/data/universe/factions/CBS_test.yml, MekHQ/testresources/data/universe/factions/CLAN_TAG.yml, MekHQ/testresources/data/universe/factions/CS_test.yml, MekHQ/testresources/data/universe/factions/IS_TAG.yml, MekHQ/testresources/data/universe/factions/LA_test.yml, MekHQ/testresources/data/universe/factions/MH_test.yml, MekHQ/unittests/mekhq/campaign/force/CombatTeamTest.java
**Requires the related MM PR.**
Fixes #7237 
- fixes a silly error with retrieving start and end dates from factions2
- fixes an error in the campaign options general tab where the factions list was not consistently updated when the date was set (when starting a new campaign, the faction list was shown for 3051 while the date was shown as 3151)
- changes the combatteam test to load test factions instead of using real factions/constructing fake factions. This removes the need for setting tags and I removed the setTags() method from Faction2 (which makes it again immutable as it should remain if possible). An alternative would have been to mock the test factions, I guess, but loading test factions is closer to reality and simpler to manage.
- adds a bunch of test factions in testresources. …
=> Factions fixes

MekHQ/src/mekhq/campaign/universe/Faction.java, MekHQ/src/mekhq/campaign/universe/factionStanding/FactionStandings.java, MekHQ/src/mekhq/gui/dialog/factionStanding/gmToolsDialog/FactionSelectionDialog.java, MekHQ/src/mekhq/gui/dialog/factionStanding/manualMissionDialogs/SimulateMissionDialog.java
This PR adds a new faction tag `AGGREGATE` that is used to flag that a faction is not a singular entity but an aggregate of different independent factions.
The example I used in the code was the pirate faction. This represents not a singular monolithic pirate organization, but an _aggregate_ of numerous pirate bands.
This was introduced to simplify Faction Standing so that we can easily exclude aggregate factions from Faction Standing tracking.
=> Improvement: Added Aggregate Faction Tag

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/universe/factionStanding/BatchallFactions.java
This PR deprecates the no-longer needed `BatchallFactions.java` class. That functionality has been superseded by @SJuliez new faction and the Faction Standing code
=> Improvement: Depreciated BatchallFactions.java

MekHQ/src/mekhq/campaign/universe/Faction.java
This PR allows us to store information about a faction's leaders in their YAML entry. It doesn't do anything on its own, but I opted to include the data separately as it's liable to be fairly hefty. Below is an excerpt from a completed YAML entry:
=> Improvement: Added Faction Leadership Tracking to Faction Overhaul

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java, MekHQ/src/mekhq/campaign/personnel/lifeEvents/ComingOfAgeAnnouncement.java, MekHQ/src/mekhq/campaign/personnel/lifeEvents/CommandersDayAnnouncement.java, MekHQ/src/mekhq/campaign/personnel/lifeEvents/FreedomDayAnnouncement.java, MekHQ/src/mekhq/campaign/personnel/lifeEvents/NewYearsDayAnnouncement.java, MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java, MekHQ/src/mekhq/campaign/rating/CamOpsReputation/ReputationController.java, MekHQ/src/mekhq/gui/campaignOptions/contents/GeneralTab.java, MekHQ/src/mekhq/gui/dialog/GMToolsDialog.java, MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java, MekHQ/src/mekhq/gui/dialog/nagDialogs/NagController.java, MekHQ/src/mekhq/gui/view/ForceViewPanel.java, MekHQ/unittests/mekhq/campaign/rating/CamOpsReputation/ReputationControllerTest.java
This effectively replaces the older `getFlaggedCommander()` getter, that just fetched the flagged commander or returned `null` with a version that more robust version. I added this because of the increased reliance on the flagged commander in modern mhq. However, we know that not all players bother with the commander flag. This PR allows us to more reliably fetch a commander figure in those campaigns. For campaigns that do use the commander flag nothing will have changed.
I also added a 'second second in command' method, mainly for use in the in-dev Faction Standing system but I also figured it'd be useful elsewhere.
=> Improvement: Added Improved Ability to Fetch Commander from Campaign; Added Ability to Fetch Second in Command

MekHQ/data/universe/factions/MBA.yml, MekHQ/data/universe/factions/MG.yml, MekHQ/data/universe/factions/MRB.yml, MekHQ/data/universe/factions/MRBC.yml
This PR adds four new factions: the Mercenary Guild, the Mercenary Review Board, the Mercenary Review & Bonding Commission, and the Mercenary Bonding Authority.
These factions are not playable, but are designed to be used in MekHQ's Faction Standing system
=> Improvement: Added The MG, MRB, MRBC, and MBA Factions for Use in Faction Standing

MekHQ/data/universe/factions/MG.yml
=> Fix: Fixed Start Year of the Mercenary's Guild

MekHQ/src/mekhq/campaign/Campaign.java
Earlier in the 50.07 dev cycle I introduced some logic to allow pirate campaigns to start on any playable faction's capital. The intent was for this to introduce a degree of randomness to a play start. However, I really wasn't happy with the code and it didn't really work as I intended.
So I went ahead and updated the logic, improved it for robustness and extended the random start logic to mercenary campaigns.
The logic is thus:
- If the campaign isn't mercenary or pirate start on the relevant faction capital
- If the campaign is mercenary, start on the mercenary capital 33% of the time, otherwise start on a random playable faction's capital (excluding Clan factions and those in the Deep Periphery). No weighting.
- If the campaign is pirate, start in the Tortuga Dominions capital 33% of …
=> Improvement: Updated Faction Starting Location Logic for Mercenary and Pirate Campaigns

MekHQ/src/mekhq/campaign/Campaign.java
I noticed that in a recent [commit](https://github.com/MegaMek/mekhq/commit/925dd6acfcab6187649d73817e0a4a67816de41d), multiple variables were renamed in a similar fashion:
- `Person p` -> `Person person` (2 renames in the previous commit)
- `LogEntry e` -> `LogEntry logEntry` (also 2 renames in the previous commit)
Here's a patch to make those changes consistent with the rest of the file!
=> followup: Rename variables `p` and `e` to verbose names

MekHQ/src/mekhq/campaign/universe/factionStanding/GoingRogue.java, MekHQ/src/mekhq/gui/dialog/factionStanding/factionJudgment/FactionJudgmentNewsArticle.java
Fix #7310
This PR overloads the `FactionJudgmentNewsArticle` class constructor to allow us to input new faction data, rather than relying on the censuring faction. This ensures that the correct faction is displayed during defection events.
=> Fix: #7310 Fixed Defection News Articles Showing Wrong Faction

MekHQ/src/mekhq/campaign/personnel/enums/Profession.java
Fix #7309
This PR stops Civilian Professions from using MekWarrior ranks by adjusting the default rank system from MekWarrior to Civilian and then updating the switch statement that determines rank label category.
=> Fix: #7309Fixed Civilian Professions Using MekWarrior Ranks Instead of Civilian

MekHQ/src/mekhq/campaign/unit/Unit.java
Fix #7271
This PR fixes hydrogen discounts for large and small craft. We had a calculation for fuel usage that was incorrectly shortcutting hydrogen usage calculations. This meant that we were only discounting the hydrogen usage of fighters (aerospace or conventional). While large craft never had their hydrogen costs deducted by hydrogen production.
=> Fix: #7271 Fixed Hydrogen Costs of Large and Small Craft

MekHQ/src/mekhq/gui/menus/AssignPersonToUnitMenu.java
This PR corrects a copy-paste error from all the way back in 2021 that incorrectly added crew members to the pilot menu, instead of the crew member menu.
This was only a visual error.
=> Fix: Fixed Crewmember Assignment Incorrectly Showing as Pilot Assignment

MekHQ/resources/mekhq/resources/AgingMilestone.properties, MekHQ/resources/mekhq/resources/Campaign.properties, MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/skills/Aging.java, MekHQ/src/mekhq/campaign/personnel/skills/enums/AgingMilestone.java, MekHQ/src/mekhq/campaign/personnel/turnoverAndRetention/RetirementDefectionTracker.java, MekHQ/unittests/mekhq/campaign/personnel/skills/enums/AgingMilestoneTest.java
Fix #7261
Fix #7318
Fix #7319
Fix #7320
This PR improves the birthday reports to highlight when characters are eligible to attend specific education tiers (junior school, and high school) - if education is enabled. When they 'come of age' (in case that life event is disabled). When they hit retirement age - if turnover is enabled). And when they reach specific aging effects Milestones - if aging effects are enabled.
It also adjusts the 'always announce 18th birthdays' option to now read 'always announce child birthdays'.
=> Improvement: #7261 Expanded Age Notifications to Include Important Milestones

MekHQ/src/mekhq/gui/campaignOptions/contents/SkillsTab.java
Fix #7112
This PR adds the ability for users to define Heroic and Legendary skill milestones in campaign options.
=> Fix: #7112 Added Missing Heroic & Legendary Skill Milestones

MekHQ/src/mekhq/campaign/personnel/skills/Aging.java, MekHQ/src/mekhq/campaign/personnel/skills/enums/AgingMilestone.java
Fix #7087 
This issue was caused by a missing divisor. I also fixed a typo in Charisma penalty for very old characters.
=> Fix: #7087 Fixed Reputation Modifiers from Aging Being Incorrectly Multiplied by 150

MekHQ/src/mekhq/campaign/mission/AtBContract.java
Fix #7328
This was an error introduced when we moved from combat teams to combat elements.
=> Fix: #7328 Fixed Ronin and Mercenary Auction Events Incorrectly Scaling Off Required Elements, not Required Combat Teams

MekHQ/src/mekhq/campaign/personnel/generator/DefaultSkillGenerator.java
The artillery skill was listed as a possible secondary skill even if artillery use was disabled. This PR explicitly removes the skill in those cases.
=> Fix: Stopped Personnel From Entering Play with Artillery Skills if Artillery is Disabled

MekHQ/resources/mekhq/resources/AttributeCheckUtility.properties, MekHQ/resources/mekhq/resources/GUI.properties, MekHQ/resources/mekhq/resources/SkillCheckDialog.properties, MekHQ/src/mekhq/campaign/personnel/skills/AttributeCheckUtility.java, MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java, MekHQ/src/mekhq/gui/dialog/AttributeCheckDialog.java
Fix #7360
This PR creates a spin-off from the skill check utility and dialog, one that allows users and developers to make single-attribute and double-attribute checks.
=> Feature: #7360 Added the Ability to Perform Single-Attribute and Double-Attribute ATOW Attribute Checks

MekHQ/resources/mekhq/resources/CampaignOptionsDialog.properties, MekHQ/src/mekhq/campaign/CampaignOptions.java, MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsPane.java, MekHQ/src/mekhq/gui/campaignOptions/contents/AdvancementTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/BiographyTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/FinancesTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/MarketsTab.java, MekHQ/src/mekhq/gui/campaignOptions/contents/SystemsTab.java
With the recent push for more ATOW content - and our future plans - it made sense to move the existing ATOW options to their own tab and also to prep for additional options.
While I was doing this I also stumbled across two bugs:
- The color of the 'new option' iconography for Campaign Options was the wrong color
- The new personnel market wasn't hooked up to the tooltip panel.
=> Improvement: Added A Time of War Tab to Campaign Options

MekHQ/resources/mekhq/resources/FactionStandings.properties, MekHQ/src/mekhq/gui/dialog/factionStanding/manualMissionDialogs/SimulateMissionDialog.java
If, while manually resolving a non-AtB Contract, both the employer and enemy were untracked factions the player would be stuck in a loop of constantly being told the update was invalid.
Now we have a skip button.
=> Fix: Fixed Soft-Lock in Faction Standings When Both Employer and Enemy Are Untracked Factions

MekHQ/data/universe/defaultspa.xml, MekHQ/resources/mekhq/resources/Personnel.properties, MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/campaign/personnel/PersonnelOptions.java, MekHQ/src/mekhq/gui/dialog/CustomizePersonDialog.java
This PR adds 5 levels of Dark Secret SPA (Trivial, Significant, Major, Severe, and Extreme).
For each level the mechanics are identical. Every three months 2d6 is rolled to determine whether the secret is revealed. The TN is normally 10, but is increased to 12 if the character also possesses the Alternate ID SPA.
If the roll is equal or higher than the TN, the character's secret is revealed and they suffer the Reputation and Connections penalties outlined in ATOW pg 112.
The reveal state of a Dark Secret can be toggled in Edit Person.
When a Dark Secret is revealed a daily report message is posed, adjusted based on the severity of the Dark Secret.
=> Feature: Added Dark Secret SPA (ATOW)

MekHQ/src/mekhq/gui/CampaignGUI.java
I don't know when these checks were removed, nor do I know the why. But now they're back.
=> Fix: Fixed GM and Overtime Buttons Not Being Selected on Load

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java, MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java, MekHQ/src/mekhq/campaign/mission/AtBScenario.java, MekHQ/src/mekhq/campaign/mission/Scenario.java, MekHQ/src/mekhq/campaign/mission/ScenarioDeploymentLimit.java, MekHQ/src/mekhq/campaign/mission/atb/AtBScenarioModifierApplicator.java, MekHQ/src/mekhq/campaign/universe/generators/companyGenerators/AbstractCompanyGenerator.java, MekHQ/src/mekhq/gui/BriefingTab.java, MekHQ/src/mekhq/gui/model/ScenarioTableModel.java, MekHQ/src/mekhq/gui/utilities/StaticChecks.java, MekHQ/src/mekhq/gui/view/AtBScenarioViewPanel.java, MekHQ/src/mekhq/gui/view/ScenarioViewPanel.java, MekHQ/unittests/mekhq/campaign/force/ForceTest.java
Fix #7338
Across the codebase we use a method called `getAllUnits` to fetch all units in a given force. However, in numerous cases we were explicitly requesting to only include units in combat forces.
This means that if a force passed into the method isn't a combat force - for example, a convoy - those units were not being always factored into several locations. Most noticeably the scenario resolution dialog. This PR addresses that.
=> Fix: #7338 Fixed Numerous Instances Where We Were Requesting all Units & Only Retrieving Those Units in Combat Forces

MekHQ/src/mekhq/campaign/campaignOptions/CampaignOptionsUnmarshaller.java
https://github.com/MegaMek/mekhq/pull/7423 made some headway in reducing the heft of loading and unloading campaign options, however we're still seeing the unmarshalling method causing our automated tests to run out of memory.
In this PR I I went ahead and moved unmarshalling of specific entries to no longer use a truly massive chain of if-else statements, and instead moved it to using a far more economical (and aesthetically pleasing) switch statement.
I also removed the swathes of legacy parsers that were cluttering up the backend of the parser. Given our push to only support milestone -> milestone compatibility (and mid-milestone dev releases) I don't think we need to include compatibility handlers from v49.03 and earlier.
Finally, I replaced uses of `Integer.parseInt` and …
=> Improvement: Further Optimized Campaign Options Loading

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/io/CampaignXmlParser.java
This was a request from @HammerGS.
All this PR does is keep a log of what versions a campaign was saved into, preserved in the campaign save.
This allows developers, at a glance, see how old a campaign is when debugging.
Nothing is done with this information, it is purely for ease of reference.
I should add that this function will not have any memory prior to the campaign being saved in 50.07, the screenshot is for illustration purposes only.
=> Improvement: Added Version History to Campaign Save

MekHQ/src/mekhq/CampaignPreset.java
This just makes it slightly easier for developers to declare presets from a mid-Milestone cycle incompatible.
=> Improvement: Minor Adjustment to Preset Incompatibility Checker

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/AtBContract.java
Fix #7430
We were incorrectly returning true for a single clause in the morale message checker.
This was a visual bug only.
=> Fix: #7430 Fixed Incorrect Morale Messages While on Garrison Contracts

MekHQ/src/mekhq/campaign/Campaign.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/PerformResupply.java, MekHQ/src/mekhq/campaign/mission/resupplyAndCaches/Resupply.java
Pirate campaigns are always meant to receive smuggler events (or no resupply). Instead they were being prompted for normal resupplies.
=> Fix: Fixed Resupplies Not Triggering Smuggler Events for Pirate Campaigns

MekHQ/src/mekhq/campaign/universe/Faction.java
If a Clan does not have an honor entry it's meant to fallback to Strict/Opportunistic based on the current game year (and some RNG). However, if the faction doesn't have an honor entry the code that is meant to handle the fallback never gets triggered, resulting in the Clan having an honor rating of None.
This had massive repercussions for the Clan bidding system, as it caused the Clan to have a bidding budget of 0 BV2. That caused the Clan to bid away their entire force, running into another bug (solved elsewhere) that would then cause the Clan to rebid their entire force - the one they just bid away.
This issue also impacted prisoners, though to a lesser extent.
=> Fix: Fixed Clans Incorrectly Being Considered Honor:None by Default

MekHQ/src/mekhq/campaign/mission/AtBDynamicScenarioFactory.java
This PR fixes several critical force generation bugs:
- Clan forces no longer respond to situations where they bid away their entire force, by deploying their entire force.
- Clan forces no longer bid using the _much_ cheaper GBV when they should be using BV2. This will result in substantially fairer feeling Clan fights.
- Allied forces (such as Integrated forces, or some scenario modifiers) no longer increase the enemy's BV budget by their total BV2, instead of GBV. This is most noticeable on higher veterancy allies, especially Elite allies.
- Fixed a bunch of IDE complaints about Logger entries
=> Fix: Stopped the Clans Cheating at Batchalls (Yet Again) and Other Critical Force Generation Fixes

MekHQ/src/mekhq/gui/campaignOptions/CampaignOptionsDialog.java
See https://github.com/MegaMek/mekhq/pull/7331 for the background.
This PR closes off another potential avenue for this issue to occur. It also deprecates the original `applyPreset` method that assumed startup use. Now developers must explicitly state whether the preset application is occurring during startup. This will prevent the issue from reoccurring in future.
=> Fix: Fixed Using Campaign Updater Causing all Personnel to be Treated as 'Ancients' for the Purposes of Aging Effects

MekHQ/resources/mekhq/resources/Ranks.properties, MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
The default ranks file is resaved whenever mhq launches into a campaign. However, the file was resaving without the new legal statement forcing developers to manually add it each time.
This PR corrects that.
=> Fix: Default Rank File Now Correctly Resaves with Legal Statement

MekHQ/src/mekhq/campaign/market/contractMarket/AtbMonthlyContractMarket.java
Fix #7552
During the recent refactor a change was made to an AtB Contract Generation method so that it accepted String (faction code) instead of the full Faction class. However, the source of the Faction (which we use to fetch the code) is Nullable. No null safety was included, resulting in an NPE and contract creation failure in the event RandomFactionGenerator returned a null value (returning a null value here is working as programmed).
=> Fix #7552: Fixed Contract Generation on New Campaign

MekHQ/src/mekhq/campaign/CampaignController.java
Fix #7551
During the recent refactor the newDay call in CampaignController was deleted. This PR restores it, as its' absence was preventing campaigns from advancing day.
=> Fix #7551: Restored Ability to Advance Campaign Day

MekHQ/src/mekhq/campaign/personnel/ranks/Ranks.java
This PR addresses the issue of rank systems initialization resulting in an early exit of all processes should ranks fail to load. For example, if loading rank systems in the headless-dateless GitHub test environment.
=> Fix: Addressed Rank System Loading Failure

MekHQ/src/mekhq/campaign/personnel/education/Academy.java
Fix #7590
Removes unnecessary hardcoded 'XP' String that got left in at some point in ancient history.
=> Fix #7590: Corrected Errant 'XP' Label in Education Academy Curriculum Tooltips

MekHQ/src/mekhq/campaign/ResolveScenarioTracker.java
Fix #7535
For years we have had reports from users of the scenario resolution dialog missing units or simply not triggering, after the player has dictated field control.
Thanks to #7535 I was able to identify what I believe to be the root cause. Under certain circumstances an entity can generate with an eternal ID of `-1` (no ID). Most of the scenario resolution code has explicit checks (around 60-ish) that confirm the id isn't `-1` before proceeding.
Most, not all. The author of #7535 ran into a circumstance where they had a unit with a `-1` ID as the only unit in the OpFor. This meant that scenario resolution completely failed, but was helpful enough to throw-up an error in the log. This error is silent. That is to say a player receiving the error would never notice, unless they …
=> Fix #7535: Fixed Scenario Resolution Unit Tracking Causing Scenario Resolution Dialog to Not Trigger

MekHQ/src/mekhq/campaign/personnel/enums/education/EducationLevel.java, MekHQ/src/mekhq/gui/enums/PersonnelTableModelColumn.java, MekHQ/src/mekhq/gui/sorter/EducationLevelSorter.java, MekHQ/unittests/mekhq/gui/enums/PersonnelTableModelColumnTest.java
Fix #7529
Now when the Education column is sorted it will sort Early Childhood -> High School -> College -> Post Graduate -> Doctorate
=> Fix #7529: Fixed Education Sorting in Personnel Tab to Order Based on Education Level and Not Alphabetically.

MekHQ/src/mekhq/gui/dialog/BatchXPDialog.java
Fix #7483
Changed the minimum skill level from 1 to 0.
=> Fix #7483: Allowed Mass Training Dialog to Give Characters New Skills, Not Just Improve Existing Skills

MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Fix #7471
This was caused by a scheduling issue where we were trying to select the new applicant before it had been added to the table.
=> Fix #7471: Fixed NPE When GM Adding Applicant to Empty Personnel Market

MekHQ/src/mekhq/gui/dialog/markets/personnelMarket/PersonnelMarketDialog.java
Fix #7616
Golden Hello is meant to be one years' salary, however I failed to account for salary multipliers. As all characters are hired without rank they actually have a x0.5 salary rank multiplier.
This PR updates the calculation used to account for this, effectively giving new hires a x1.0 salary rank multiplier.
=> Fix #7616: Corrected Golden Hello Hiring to Account for Rank 0 Salary Multipliers

MekHQ/src/mekhq/gui/dialog/glossary/NewGlossaryDialog.java
This PR just adds letter headers to break up the 'wall of hyperlinks' issue the Glossary previously had. These headers are created dynamically and therefore will require no developer intervention.
=> Improvement: Added Letter Headers to Glossary Entries

MekHQ/resources/mekhq/resources/PersonViewPanel.properties, MekHQ/src/mekhq/campaign/personnel/Person.java, MekHQ/src/mekhq/gui/view/PersonViewPanel.java
Fix #7650
Permanent injuries were not visible due to an incorrectly falsified boolean param. Once restored I realized that the injury panel hadn't received the same love and care that the rest of Person View had received during the recent rework. So I went ahead and updated it visually:
=> Fix #7650: Restored Ability to View Permanent Injuries in Personnel Tab Character Sheet; Improved Visual Clarity of Injuries

MekHQ/src/mekhq/campaign/unit/Unit.java
There’s a long-standing and infamous bug in MHQ, often called the “ghost 'Mek” or “haunted 'Mek” bug. If you’ve played MHQ for any length of time, you’ve probably run into it: you deploy your forces to a scenario, and one unit ends up placed far away from the rest—seemingly at random. This happens because the unit is retaining deployment data from a previous scenario.
It was dubbed the “ghost 'Mek” bug because it usually affected 'Meks that had been destroyed via cockpit destruction—almost as if they were haunted by the memories of past violence.
Thanks to some solid teamwork, we think we’ve finally identified and resolved the root cause—hopefully for good.
Here’s what was happening:
MHQ has a method that resets crew and unit data. It’s called in various situations, but most importantly, …
=> Fix: Refactored Post-Scenario Unit Resetting Potentially Fixing the Infamous 'Ghost Meks' Bug

MekHQ/build.gradle
Fix #7637
We were adding a `log` directory when building the project, when we should have been added `logs`. This resulted in players ending up with both a `/log` and `logs` directory.
Insofar as I can tell this bug is benign, but if we don't fix it I can guarantee we will see people asking about it throughout 07's lifecycle. :D
=> Fix #7637: Added Missing 's' to /logs in Build Directory Construction

MekHQ/src/mekhq/gui/adapter/PersonnelTableMouseAdapter.java
During the data overhaul the ability to manually add new performance log entries was incorrectly removed. This PR restores it.
=> Fix: Restored Performance Log Entry Adding
